### PR TITLE
rbd: setup encryption if rbdVol exits during CreateVol

### LINKED ISSUE #3402: Crashes during CreateVolume: Pods failing with "unexpected encryption status"
# Describe the bug

With RBD block encrypted volumes, interrupting CreateVolume leads with high likelihood to broken volumes / RBD images.
Broken in the sense that encryption metadata is in an invalid state and Ceph CSI is unable to attach the volume.
Pods will get stuck in ContainerCreating as a result.

# Environment details

-   Image/version of Ceph CSI driver: Saw this on 3.5.1 and current devel (+ RBD fscrypt patches) (logs below from that)
-   Kubernetes cluster version: Probably many. Reproduced last on 1.23.8 minikube 1.26.1
-   Ceph cluster version: Pacific, current main branch

# Steps to reproduce

1.  Create RBD block encrypted storage class
2.  Create rbd-csiplugin-provisioner deployment where the csi-rbdplugin container has a memory resource limit that is likely to invoke the OOM killer (ex: 128Mi)
3.  Create ~10 PVCs and pods
4.  rbd-csiplugin-provisioner likely to OOM while in CreateVolume
5.  Most pods will end up in state ContainerCreating with FailedMount "rbd image &#x2026; found mounted with unexpected encryption status"

Tools and configs I used are in <https://github.com/irq0/dev-ceph-csi-fscrypt-config>
In my minikube setup I can reproduce with close to 100% probability. 

# Actual results

Pods in state ContainerCreating with warning:

    Warning  FailedMount             3m52s (x19 over 26m)  kubelet                  MountVolume.MountDevice failed for volume "pvc-d1d79e84-3d25-4 │
    fd5-9cd3-0f57331fa47d" : rpc error: code = Internal desc = rbd image replicapool/csi-vol-b945bb0d-ed93-40ce-bb4d-32df69cbef71 found mounted with │
    unexpected encryption status   

# Expected behavior

Successful volume creation, even when the provider crashes.

# Logs

This follows image b60b8ccc-776e-4343-993f-1e2a3669595a along:

## csi-rbdplugin-provisioner first CreateVolume request

    [pod/csi-rbdplugin-provisioner-75dd4f948c-2l56f/csi-rbdplugin] 2022-09-22T10:30:23.435162195Z I0922 10:30:23.434774       1 utils.go:195] ID: 71 Req
    -ID: pvc-e691b358-31c1-43a9-8ffd-da499eded20e GRPC call: /csi.v1.Controller/CreateVolume
    
    [pod/csi-rbdplugin-provisioner-75dd4f948c-2l56f/csi-rbdplugin] 2022-09-22T10:30:23.435183954Z I0922 10:30:23.434942       1 utils.go:206] ID: 71 Req
    -ID: pvc-e691b358-31c1-43a9-8ffd-da499eded20e GRPC request: {"capacity_range":{"required_bytes":104857600},"name":"pvc-e691b358-31c1-43a9-8ffd-da499
    eded20e","parameters":{"clusterID":"rook-ceph","csi.storage.k8s.io/pv/name":"pvc-e691b358-31c1-43a9-8ffd-da499eded20e","csi.storage.k8s.io/pvc/name"
    :"pvc-bomb-4879-2","csi.storage.k8s.io/pvc/namespace":"irq0","encrypted":"true","encryptionKMSID":"user-ns-secrets-metadata","encryptionKMSType":"me
    tadata","encryptionType":"block","imageFeatures":"layering","imageFormat":"2","pool":"replicapool","secretName":"cephfs-storage-encryption-secret","
    secretNamespace":"irq0"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}}]}
    
    [pod/csi-rbdplugin-provisioner-75dd4f948c-2l56f/csi-rbdplugin] 2022-09-22T10:30:23.435194494Z I0922 10:30:23.435033       1 rbd_util.go:1308] ID: 71
     Req-ID: pvc-e691b358-31c1-43a9-8ffd-da499eded20e setting disableInUseChecks: false image features: [layering] mounter: rbd
    
    [pod/csi-rbdplugin-provisioner-75dd4f948c-2l56f/csi-rbdplugin] 2022-09-22T10:30:23.501732087Z I0922 10:30:23.500929       1 omap.go:88] ID: 71 Req-I
    D: pvc-e691b358-31c1-43a9-8ffd-da499eded20e got omap values: (pool="replicapool", namespace="", name="csi.volumes.default"): map[]
    
    [pod/csi-rbdplugin-provisioner-75dd4f948c-2l56f/csi-rbdplugin] 2022-09-22T10:30:23.612007908Z I0922 10:30:23.611620       1 omap.go:158] ID: 71 Req-ID: pvc-e691b358-31c1-43a9-8ffd-da499eded20e set omap keys (pool="replicapool", namespace="", name="csi.volumes.default"): map[csi.volume.pvc-e691b358-31c1-43a9-8ffd-da499eded20e:b60b8ccc-776e-4343-993f-1e2a3669595a])
    
    [pod/csi-rbdplugin-provisioner-75dd4f948c-2l56f/csi-rbdplugin] 2022-09-22T10:30:23.656886202Z I0922 10:30:23.656455       1 omap.go:158] ID: 71 Req-ID: pvc-e691b358-31c1-43a9-8ffd-da499eded20e set omap keys (pool="replicapool", namespace="", name="csi.volume.b60b8ccc-776e-4343-993f-1e2a3669595a"
    ): map[csi.imagename:csi-vol-b60b8ccc-776e-4343-993f-1e2a3669595a csi.volname:pvc-e691b358-31c1-43a9-8ffd-da499eded20e csi.volume.encryptKMS:user-ns-secrets-metadata csi.volume.encryptionType:block csi.volume.owner:irq0])
    
    [pod/csi-rbdplugin-provisioner-75dd4f948c-2l56f/csi-rbdplugin] 2022-09-22T10:30:23.656896461Z I0922 10:30:23.656491       1 rbd_journal.go:490] ID: 71 Req-ID: pvc-e691b358-31c1-43a9-8ffd-da499eded20e generated Volume ID (0001-0009-rook-ceph-0000000000000001-b60b8ccc-776e-4343-993f-1e2a3669595a) 
    and image name (csi-vol-b60b8ccc-776e-4343-993f-1e2a3669595a) for request name (pvc-e691b358-31c1-43a9-8ffd-da499eded20e)
    
    [pod/csi-rbdplugin-provisioner-75dd4f948c-2l56f/csi-rbdplugin] 2022-09-22T10:30:23.657051487Z I0922 10:30:23.656557       1 rbd_util.go:423] ID: 71 Req-ID: pvc-e691b358-31c1-43a9-8ffd-da499eded20e rbd: create replicapool/csi-vol-b60b8ccc-776e-4343-993f-1e2a3669595a size 100M (features: [layering
    ]) using mon 10.105.203.132:6789,10.105.203.132:3300
    
    [pod/csi-rbdplugin-provisioner-75dd4f948c-2l56f/csi-rbdplugin] 2022-09-22T10:30:23.657054247Z I0922 10:30:23.656627       1 rbd_util.go:1555] ID: 71 Req-ID: pvc-e691b358-31c1-43a9-8ffd-da499eded20e setting image options on replicapool/csi-vol-b60b8ccc-776e-4343-993f-1e2a3669595a
    
    # No indication in my logs that ID 71 returns

## csi-rbdplugin-provisioner crashes

    [pod/csi-rbdplugin-provisioner-75dd4f948c-2l56f/csi-resizer] 2022-09-22T10:30:23.772794991Z E0922 10:30:23.771960       1 connection.go:132] Lost co
    nnection to unix:///csi/csi-provisioner.sock.
    [pod/csi-rbdplugin-provisioner-75dd4f948c-2l56f/csi-snapshotter] 2022-09-22T10:30:23.773338465Z E0922 10:30:23.773083       1 connection.go:132] Los
    t connection to unix:///csi/csi-provisioner.sock.
    [pod/csi-rbdplugin-provisioner-75dd4f948c-2l56f/csi-snapshotter] 2022-09-22T10:30:23.773363124Z F0922 10:30:23.773170       1 connection.go:87] Lost
     connection to CSI driver, exiting
    [pod/csi-rbdplugin-provisioner-75dd4f948c-2l56f/csi-resizer] 2022-09-22T10:30:23.772829329Z F0922 10:30:23.772074       1 connection.go:87] Lost connection to CSI driver, exiting
    [pod/csi-rbdplugin-provisioner-75dd4f948c-2l56f/csi-attacher] 2022-09-22T10:30:23.773577248Z E0922 10:30:23.773180       1 connection.go:132] Lost connection to unix:///csi/csi-provisioner.sock.
    [pod/csi-rbdplugin-provisioner-75dd4f948c-2l56f/csi-attacher] 2022-09-22T10:30:23.773598498Z F0922 10:30:23.773255       1 connection.go:87] Lost connection to CSI driver, exiting

## Crashes / OOM Events

    [Thu Sep 22 10:30:23 2022] Memory cgroup out of memory: Killed process 44062 (cephcsi) total-vm:3891476kB, anon-rss:127084kB, file-rss:58728kB, shmem-rss:0kB, UID:0 pgtables:932kB oom_score_adj:994
    [Thu Sep 22 10:30:46 2022] Memory cgroup out of memory: Killed process 61167 (cephcsi) total-vm:3874400kB, anon-rss:127612kB, file-rss:58640kB, shmem-rss:0kB, UID:0 pgtables:948kB oom_score_adj:994
    [Thu Sep 22 10:31:27 2022] Memory cgroup out of memory: Killed process 62192 (cephcsi) total-vm:3957276kB, anon-rss:127096kB, file-rss:58740kB, shmem-rss:0kB, UID:0 pgtables:980kB oom_score_adj:994

## csi-rbdplugin-provisioner restart and second CreateVolume

    [pod/csi-rbdplugin-provisioner-75dd4f948c-2l56f/csi-rbdplugin] 2022-09-22T10:31:24.190129537Z I0922 10:31:24.185936       1 utils.go:195] ID: 25 Req-ID: pvc-e691b358-31c1-43a9-8ffd-da499eded20e GRPC call: /csi.v1.Controller/CreateVolume
    
    [pod/csi-rbdplugin-provisioner-75dd4f948c-2l56f/csi-rbdplugin] 2022-09-22T10:31:24.190257743Z I0922 10:31:24.186948       1 utils.go:206] ID: 25 Req-ID: pvc-e691b358-31c1-43a9-8ffd-da499eded20e GRPC request: {"capacity_range":{"required_bytes":104857600},"name":"pvc-e691b358-31c1-43a9-8ffd-da499eded20e","parameters":{"clusterID":"rook-ceph","csi.storage.k8s.io/pv/name":"pvc-e691b358-31c1-43a9-8ffd-da499eded20e","csi.storage.k8s.io/pvc/name":"pvc-bomb-4879-2","csi.storage.k8s.io/pvc/namespace":"irq0","encrypted":"true","encryptionKMSID":"user-ns-secrets-metadata","encryptionKMSType":"metadata","encryptionType":"block","imageFeatures":"layering","imageFormat":"2","pool":"replicapool","secretName":"cephfs-storage-encryption-secret","secretNamespace":"irq0"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}}]}
    
    [pod/csi-rbdplugin-provisioner-75dd4f948c-2l56f/csi-rbdplugin] 2022-09-22T10:31:24.190317421Z I0922 10:31:24.187358       1 rbd_util.go:1308] ID: 25 Req-ID: pvc-e691b358-31c1-43a9-8ffd-da499eded20e setting disableInUseChecks: false image features: [layering] mounter: rbd
    
    [pod/csi-rbdplugin-provisioner-75dd4f948c-2l56f/csi-rbdplugin] 2022-09-22T10:31:24.356612037Z I0922 10:31:24.355969       1 omap.go:88] ID: 25 Req-ID: pvc-e691b358-31c1-43a9-8ffd-da499eded20e got omap values: (pool="replicapool", namespace="", name="csi.volumes.default"): map[csi.volume.pvc-e691b358-31c1-43a9-8ffd-da499eded20e:b60b8ccc-776e-4343-993f-1e2a3669595a]
    
    [pod/csi-rbdplugin-provisioner-75dd4f948c-2l56f/csi-rbdplugin] 2022-09-22T10:31:24.364283491Z I0922 10:31:24.363399       1 omap.go:88] ID: 25 Req-ID: pvc-e691b358-31c1-43a9-8ffd-da499eded20e got omap values: (pool="replicapool", namespace="", name="csi.volume.b60b8ccc-776e-4343-993f-1e2a3669595a"): map[csi.imageid:151a3e041142 csi.imagename:csi-vol-b60b8ccc-776e-4343-993f-1e2a3669595a csi.volname:pvc-e691b358-31c1-43a9-8ffd-da499eded20e csi.volume.encryptKMS:user-ns-secrets-metadata csi.volume.encryptionType:block csi.volume.owner:irq0]
    
    [pod/csi-rbdplugin-provisioner-75dd4f948c-2l56f/csi-rbdplugin] 2022-09-22T10:31:24.437017450Z I0922 10:31:24.436520       1 rbd_journal.go:345] ID: 25 Req-ID: pvc-e691b358-31c1-43a9-8ffd-da499eded20e found existing volume (0001-0009-rook-ceph-0000000000000001-b60b8ccc-776e-4343-993f-1e2a3669595a
    ) with image name (csi-vol-b60b8ccc-776e-4343-993f-1e2a3669595a) for request (pvc-e691b358-31c1-43a9-8ffd-da499eded20e)
    
    [pod/csi-rbdplugin-provisioner-75dd4f948c-2l56f/csi-rbdplugin] 2022-09-22T10:31:24.437901675Z I0922 10:31:24.437024       1 utils.go:212] ID: 25 Req-ID: pvc-e691b358-31c1-43a9-8ffd-da499eded20e GRPC response: {"volume":{"capacity_bytes":104857600,"volume_context":{"clusterID":"rook-ceph","encryp
    ted":"true","encryptionKMSID":"user-ns-secrets-metadata","encryptionKMSType":"metadata","encryptionType":"block","imageFeatures":"layering","imageFormat":"2","imageName":"csi-vol-b60b8ccc-776e-4343-993f-1e2a3669595a","journalPool":"replicapool","pool":"replicapool","secretName":"cephfs-storage-encryption-secret","secretNamespace":"irq0"},"volume_id":"0001-0009-rook-ceph-0000000000000001-b60b8ccc-776e-4343-993f-1e2a3669595a"}}

## rbdplugin NodeStageVolume unexpected encryption status

    [pod/csi-rbdplugin-zxxqw/csi-rbdplugin] 2022-09-22T10:31:40.625211126Z I0922 10:31:40.624357   20745 utils.go:195] ID: 1324 Req-ID: 0001-0009-rook-ceph-0000000000000001-b60b8ccc-776e-4343-993f-1e2a3669595a GRPC call: /csi.v1.Node/NodeStageVolume
    [pod/csi-rbdplugin-zxxqw/csi-rbdplugin] 2022-09-22T10:31:40.625335302Z I0922 10:31:40.624847   20745 utils.go:206] ID: 1324 Req-ID: 0001-0009-rook-ceph-0000000000000001-b60b8ccc-776e-4343-993f-1e2a3669595a GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-e691b358-31c1-43a9-8ffd-da499eded20e/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":7}},"volume_context":{"clusterID":"rook-ceph","encrypted":"true","encryptionKMSID":"user-ns-secrets-metadata","encryptionKMSType":"metadata","encryptionType":"block","imageFeatures":"layering","imageFormat":"2","imageName":"csi-vol-b60b8ccc-776e-4343-993f-1e2a3669595a","journalPool":"replicapool","pool":"replicapool","secretName":"cephfs-storage-encryption-secret","secretNamespace":"irq0","storage.kubernetes.io/csiProvisionerIdentity":"1663842664262-8081-rbd.csi.ceph.com"},"volume_id":"0001-0009-rook-ceph-0000000000000001-b60b8ccc-776e-4343-993f-1e2a3669595a"}
    [pod/csi-rbdplugin-zxxqw/csi-rbdplugin] 2022-09-22T10:31:40.626030652Z I0922 10:31:40.625647   20745 rbd_util.go:1308] ID: 1324 Req-ID: 0001-0009-rook-ceph-0000000000000001-b60b8ccc-776e-4343-993f-1e2a3669595a setting disableInUseChecks: false image features: [layering] mounter: rbd
    [pod/csi-rbdplugin-zxxqw/csi-rbdplugin] 2022-09-22T10:31:40.631305326Z I0922 10:31:40.630967   20745 omap.go:88] ID: 1324 Req-ID: 0001-0009-rook-ceph-0000000000000001-b60b8ccc-776e-4343-993f-1e2a3669595a got omap values: (pool="replicapool", namespace="", name="csi.volume.b60b8ccc-776e-4343-993f-1e2a3669595a"): map[csi.imageid:151a3e041142 csi.imagename:csi-vol-b60b8ccc-776e-4343-993f-1e2a3669595a csi.volname:pvc-e691b358-31c1-43a9-8ffd-da499eded20e csi.volume.encryptKMS:user-ns-secrets-metadata csi.volume.encryptionType:block csi.volume.owner:irq0]
    [pod/csi-rbdplugin-zxxqw/csi-rbdplugin] 2022-09-22T10:31:40.715172282Z I0922 10:31:40.714957   20745 rbd_util.go:352] ID: 1324 Req-ID: 0001-0009-rook-ceph-0000000000000001-b60b8ccc-776e-4343-993f-1e2a3669595a checking for ImageFeatures: [layering]
    [pod/csi-rbdplugin-zxxqw/csi-rbdplugin] 2022-09-22T10:31:40.793816462Z I0922 10:31:40.793618   20745 cephcmds.go:105] ID: 1324 Req-ID: 0001-0009-rook-ceph-0000000000000001-b60b8ccc-776e-4343-993f-1e2a3669595a command succeeded: rbd [device list --format=json --device-type krbd]
    [pod/csi-rbdplugin-zxxqw/csi-rbdplugin] 2022-09-22T10:31:40.837838219Z I0922 10:31:40.837636   20745 rbd_attach.go:420] ID: 1324 Req-ID: 0001-0009-rook-ceph-0000000000000001-b60b8ccc-776e-4343-993f-1e2a3669595a rbd: map mon 10.105.203.132:6789,10.105.203.132:3300
    [pod/csi-rbdplugin-zxxqw/csi-rbdplugin] 2022-09-22T10:31:40.918487370Z I0922 10:31:40.918356   20745 cephcmds.go:105] ID: 1324 Req-ID: 0001-0009-rook-ceph-0000000000000001-b60b8ccc-776e-4343-993f-1e2a3669595a command succeeded: rbd [--id admin -m 10.105.203.132:6789,10.105.203.132:3300 --keyfile=***stripped*** map replicapool/csi-vol-b60b8ccc-776e-4343-993f-1e2a3669595a --device-type krbd --options noudev]
    [pod/csi-rbdplugin-zxxqw/csi-rbdplugin] 2022-09-22T10:31:40.918517219Z I0922 10:31:40.918412   20745 nodeserver.go:415] ID: 1324 Req-ID: 0001-0009-rook-ceph-0000000000000001-b60b8ccc-776e-4343-993f-1e2a3669595a rbd image: replicapool/csi-vol-b60b8ccc-776e-4343-993f-1e2a3669595a was successfully mapped at /dev/rbd0
    [pod/csi-rbdplugin-zxxqw/csi-rbdplugin] 2022-09-22T10:31:41.072878006Z I0922 10:31:41.072773   20745 encryption.go:87] ID: 1324 Req-ID: 0001-0009-rook-ceph-0000000000000001-b60b8ccc-776e-4343-993f-1e2a3669595a image replicapool/csi-vol-b60b8ccc-776e-4343-993f-1e2a3669595a encrypted state metadata reports ""
    [pod/csi-rbdplugin-zxxqw/csi-rbdplugin] 2022-09-22T10:31:41.130138100Z I0922 10:31:41.129862   20745 cephcmds.go:105] ID: 1324 Req-ID: 0001-0009-rook-ceph-0000000000000001-b60b8ccc-776e-4343-993f-1e2a3669595a command succeeded: rbd [unmap /dev/rbd0 --device-type krbd --options noudev]
    [pod/csi-rbdplugin-zxxqw/csi-rbdplugin] 2022-09-22T10:31:41.130195878Z E0922 10:31:41.129953   20745 utils.go:210] ID: 1324 Req-ID: 0001-0009-rook-ceph-0000000000000001-b60b8ccc-776e-4343-993f-1e2a3669595a GRPC error: rpc error: code = Internal desc = rbd image replicapool/csi-vol-b60b8ccc-776e-4343-993f-1e2a3669595a found mounted with unexpected encryption status

### PR DESCRIPTION
**Pull request by Rakshith-R**
This commit adds code to setup encryption on a rbdVol being repaired in a followup CreateVolume request. This is fixes a bug wherein encryption metadata may not have been set in previous request due to container restart.

Fixes: #3402

Signed-off-by: Rakshith R <rar@redhat.com>

### CODE REVIEW

**Comment by Rakshith-R** [comment]
This pr is ready for review. 
It successfully sets up encryption whenever previous requests fail before doing so.

refer:
https://github.com/ceph/ceph-csi/issues/3472#issuecomment-1303291476

**Review by nixpanic — APPROVED** [review]
I think this looks good. Can you explain how you tested/verified this?

**Comment by Rakshith-R** [comment]
> I think this looks good. Can you explain how you tested/verified this?

Without the fix, Prov would get OOMKilled during set metadata step for DEK and encryption Status, and provisioning would get completed in a followup req with empty encryption status like seen in the issue linked. 


With fix, provision tries to setupencryption again in subsequent req leading to repeated OOMkills but raising mem limit leads to provisioning of PVC which can be successfully.

File: internal/rbd/controllerserver.go [hunk 1]
```diff
@@ -508,6 +508,15 @@ func (cs *ControllerServer) repairExistingVolume(ctx context.Context, req *csi.C
 
 			return nil, err
 		}
+
+	default:
+		// setup encryption again to make sure everything is in place.
```
Comment (Madhu-1) [inline internal/rbd/controllerserver.go:513]: Question:
* This is only for PVC. What about the PVC Clone and PVC Snapshot?
* What about the fileEncryption?

Comment (Rakshith-R) [reply internal/rbd/controllerserver.go:513]: > Question:
> 
> * This is only for PVC. What about the PVC Clone and PVC Snapshot?
 
For clone
https://github.com/ceph/ceph-csi/blob/07e9dede2cb10ceaa055b9b2486f688edf9008d6/internal/rbd/rbd_journal.go#L337
For snapshot, just few ones above to copy encryption config 


> * What about the fileEncryption?

This pr handles for block encryption,  
We can handle the same for file encryption in another pr.
@irq0 can you please take a look at this?

Comment (Madhu-1) [reply internal/rbd/controllerserver.go:513]: Open an issue so that we dont forget it?

**Review by Madhu-1 — APPROVED** [review]
