### PR TITLE
cephfs: Fix cephfs PVC sizing

### LINKED ISSUE #4179: CephFS PVC creation fails provision for few sizes
# Describe the bug #

When provisioning the CephFS PVC, for some sizes it would fail to provision volumes with the expected size. For example 101M, 500M, 504M etc.

# Steps to reproduce #

1. Deploy CephFS plugin
2. Create a storage class
3. Create a PVC with size 500M

# Actual results #

$ kubectl get pvc
NAME                 STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS    AGE
csi-cephfs-pvc       Bound     pvc-449021d8-d94f-49f8-bf18-d11c16bd25c1   1Gi        RWX            csi-cephfs-sc   3h7m
csi-cephfs-pvc-500   Pending                                                                        csi-cephfs-sc   2s

# Expected behavior #

PVC creation should succeed and get bound to a PV.

# Logs #

I1009 18:13:43.980418       1 controller.go:1366] provision "default/csi-cephfs-pvc-500" class "csi-cephfs-sc": started
I1009 18:13:43.980519       1 event.go:298] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"csi-cephfs-pvc-500", UID:"e8111a6b-c658-4405-bc06-c7419a2ee5be", APIVersion:"v1", ResourceVersion:"18754", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/csi-cephfs-pvc-500"
W1009 18:13:44.061025       1 controller.go:934] Retrying syncing claim "e8111a6b-c658-4405-bc06-c7419a2ee5be", failure 3
E1009 18:13:44.061051       1 controller.go:957] error syncing claim "e8111a6b-c658-4405-bc06-c7419a2ee5be": failed to provision volume with StorageClass "csi-cephfs-sc": created volume capacity 499122176 less than requested capacity 500000000
I1009 18:13:44.061123       1 event.go:298] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"csi-cephfs-pvc-500", UID:"e8111a6b-c658-4405-bc06-c7419a2ee5be", APIVersion:"v1", ResourceVersion:"18754", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "csi-cephfs-sc": created volume capacity 499122176 less than requested capacity 500000000

### PR DESCRIPTION
**Pull request by karthik-us**
Issue:
The RoundOffCephFSVolSize() function omits the fractional part when calculating the size for cephfs volumes, leading to the created volume capacity to be lesser than the requested volume capacity.

Fix:
Consider the fractional part during the size calculation so the rounded off volume size will be greater than or equal to the requested volume size.

Fixes: #4179

### CODE REVIEW

**Review by nixpanic — COMMENTED** [review]
I think the change looks good.

Would it make sense to add an e2e test with a value that caused the failure?

File: internal/util/util.go [hunk 1]
```diff
@@ -67,9 +67,9 @@ func RoundOffCephFSVolSize(bytes int64) int64 {
 		return 4 * helpers.MiB
 	}
 
-	bytes /= helpers.MiB
+	floatbytes := float64(bytes) / helpers.MiB
```
Comment (Madhu-1) [inline internal/util/util.go]: bytesInFloat sounds better? as @nixpanic suggested please add a E2E test for this one.

Comment (karthik-us) [reply internal/util/util.go]: Done.

File: e2e/cephfs.go [hunk 2]
```diff
@@ -2426,6 +2427,35 @@ var _ = Describe(cephfsType, func() {
 				validateOmapCount(f, 0, cephfsType, metadataPool, volumesType)
 			})
 
+			By("Test 500MB PVC creation and check for PV and PVC binding", func() {
+				size := "500M"
+				err := createCephfsStorageClass(f.ClientSet, f, true, nil)
```
Comment (riya-singhal31) [inline e2e/cephfs.go]: This should be skipped, SC is already created [here](https://github.com/ceph/ceph-csi/pull/4180/files#diff-6602b119e7e19f3938fc55c0cb9ad7f35f517ff5f74eac45efc952969dcf4317L2224)

Comment (karthik-us) [reply e2e/cephfs.go]: Done.

**Review by riya-singhal31 — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio queue

**Comment by nixpanic** [comment]
> /test ci/centos/mini-e2e-helm/k8s-1.28

This CI job seemed to be missing. Started it again to get a status report and have this PR merged.
