### PR TITLE
build: Fix helm chart pushing

### LINKED ISSUE #2006: Failed to push helm charts from Travis  CI
```bash
+'[' devel '!=' devel ']'
+mkdir -p /tmp/tmp.HbfoiegV48/csi-charts/docs/rbd
+cp -R ./charts/ceph-csi-rbd /tmp/tmp.HbfoiegV48/csi-charts/docs/rbd
+pushd /tmp/tmp.HbfoiegV48/csi-charts/docs/rbd
+helm init --client-only
Error: unknown command "init" for "helm"
Did you mean this?
	lint
Run 'helm --help' for usage.
```

Helm charts are not getting pushed due to the invalid `helm init` command which is not available in helm v3.x. Failed builds list https://travis-ci.org/github/ceph/ceph-csi/builds

### PR DESCRIPTION
**Pull request by Madhu-1**
Removed helm init commands as helm v3.x does not have the `init` command see https://github.com/helm/helm/issues/6996 and also install the helm from the version specified in the build.env

resolves https://github.com/ceph/ceph-csi/issues/2006

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
skipping e2e as the change is in deploy.sh which will get executed when the PR is merged.

File: deploy.sh [hunk 1]
```diff
@@ -28,7 +28,6 @@ push_helm_charts() {
 	mkdir -p "$CHARTDIR/csi-charts/docs/$PACKAGE"
 	cp -R "./charts/ceph-csi-$PACKAGE" "$CHARTDIR/csi-charts/docs/$PACKAGE"
 	pushd "$CHARTDIR/csi-charts/docs/$PACKAGE" >/dev/null
-	helm init --client-only
```
Comment (humblec) [inline deploy.sh:31]: Just wondering is there a replacement for above option in helm3

Comment (Madhu-1) [reply deploy.sh:31]: please check https://github.com/helm/helm/issues/6996#issuecomment-555010868

**Review by nixpanic — APPROVED** [review]

**Review by humblec — APPROVED** [review]

**Comment by humblec** [comment]
@Madhu-1 good to backport this to 3.3 branch too.

**Comment by Madhu-1** [comment]
> @Madhu-1 good to backport this to 3.3 branch too.

Doing it

**Comment by Madhu-1** [comment]
@mergifyio backport release-v3.2
