### PR TITLE
rbd: added rbd info to validateRBDImageCount func

### LINKED ISSUE #4547: Log RBD info and RBD status in E2E validateRBDImageCount function in case of failure
> > /retest ci/centos/mini-e2e/k8s-1.29
> 
> spurious failure, the [logs](https://jenkins-ceph-csi.apps.ocp.cloud.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.29/detail/mini-e2e_k8s-1.29/165/pipeline) show that an image was not cleaned up (yet?):
> 
> ```
> [FAILED] backend images not matching kubernetes resource count,image count 1 kubernetes resource count 0
> ```

i think we need to update the validation function to print `rbd info` and `rbd status` of each images to get more clarity what happened. it looks like the image is opened by someone but not closed? not sure who

_Originally posted by @Madhu-1 in https://github.com/ceph/ceph-csi/issues/4499#issuecomment-2039243502_

### PR DESCRIPTION
**Pull request by OdedViner**
# Describe what this PR does #
Added rbd info and rbd status on Failure message

```
bash-5.1$ rbd info --pool=replicapool csi-vol-2b6574ee-9c6f-4a3b-9a96-09060763f7a7
rbd image 'csi-vol-2b6574ee-9c6f-4a3b-9a96-09060763f7a7':
	size 1 GiB in 256 objects
	order 22 (4 MiB objects)
	snapshot_count: 0
	id: 1102e70da18f
	block_name_prefix: rbd_data.1102e70da18f
	format: 2
	features: layering
	op_features: 
	flags: 
	create_timestamp: Thu Oct 31 13:26:32 2024
	access_timestamp: Thu Oct 31 13:26:32 2024
	modify_timestamp: Thu Oct 31 13:26:32 2024
```

```
bash-5.1$ rbd status --pool=replicapool csi-vol-2b6574ee-9c6f-4a3b-9a96-09060763f7a7
Watchers: none
```

## Is there anything that requires special attention ##

Do you have any questions?

Is the change backward compatible?

Are there concerns around backward compatibility?

Provide any external context for the change, if any.

For example:

* Kubernetes links that explain why the change is required
* CSI spec related changes/catch-up that necessitates this patch
* golang related practices that necessitates this change

## Related issues ##

Mention any github issues relevant to this PR. Adding below line
will help to auto close the issue once the PR is merged.

Fixes: #4547 
## Future concerns ##

List items that are not part of the PR and do not impact it's
functionality, but are work items that can be taken up subsequently.

**Checklist:**

* [ ] **Commit Message Formatting**: Commit titles and messages follow
  guidelines in the [developer
  guide](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#commit-messages).
* [ ] Reviewed the developer guide on [Submitting a Pull
  Request](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#development-workflow)
* [ ] [Pending release
  notes](https://github.com/ceph/ceph-csi/blob/devel/PendingReleaseNotes.md)
  updated with breaking and/or notable changes for the next major release.
* [ ] Documentation has been updated, if necessary.
* [ ] Unit tests have been added, if necessary.
* [ ] Integration tests have been added, if necessary.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

* `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)

</details>

### CODE REVIEW

File: e2e/rbd.go [hunk 1]
```diff
@@ -189,12 +189,26 @@ func validateRBDImageCount(f *framework.Framework, count int, pool string) {
...
+			if err != nil {
+				return
+			}
+			// Collecting image details for printing
+			imageDetails = append(imageDetails, fmt.Sprintf("Pool Name: %s, Image Name: %s, Img Info: %v, Img Status: %v", pool, image, imgInfo, imgStatus))
+		}
 		framework.Failf(
 			"backend images not matching kubernetes resource count,image count %d kubernetes resource count %d"+
-				"\nbackend image Info:\n %v",
+				"\nbackend image Info:\n %v\n images information and status%v",
```
Comment (nixpanic) [inline e2e/rbd.go]: `status%v` could use a space befor the `%v`

File: e2e/rbd_helper.go [hunk 2]
```diff
@@ -1094,6 +1104,31 @@ func getImageInfo(f *framework.Framework, imageName, poolName string) (imageInfo
...
+		rookNamespace)
+	if err != nil {
+		return imgStatus, fmt.Errorf("failed to get rbd status: %w", err)
+	}
+	if stdErr != "" {
+		return imgStatus, fmt.Errorf("failed to get rbd status: %v", stdErr)
+	}
+	err = json.Unmarshal([]byte(stdOut), &imgStatus)
+	if err != nil {
+		return imgStatus, fmt.Errorf("unmarshal failed: %w. raw buffer response: %s",
```
Comment (nixpanic) [inline e2e/rbd_helper.go]: don't return the buffer in the error message, as that may get printed many more times when callers log the error. Instead, use `framework.Logf()` to report details like this.

File: e2e/rbd_helper.go [hunk 3]
```diff
@@ -1094,6 +1104,31 @@ func getImageInfo(f *framework.Framework, imageName, poolName string) (imageInfo
...
+func getImageStatus(f *framework.Framework, imageName, poolName string) (imageStatus, error) {
+	// rbd --format=json status [image-spec | snap-spec]
+	var imgStatus imageStatus
+
+	stdOut, stdErr, err := execCommandInToolBoxPod(
+		f,
+		fmt.Sprintf("rbd status %s %s --format json", rbdOptions(poolName), imageName),
+		rookNamespace)
+	if err != nil {
+		return imgStatus, fmt.Errorf("failed to get rbd status: %w", err)
```
Comment (nixpanic) [inline e2e/rbd_helper.go]: It helps to give this `err != nil` and the below `stdErr != ""` errors a slightly different message. When something goes wrong, it can be identified more precisely if the error message is unique.

**Review by nixpanic — CHANGES_REQUESTED** [review]

File: e2e/rbd.go [hunk 4]
```diff
@@ -189,12 +189,26 @@ func validateRBDImageCount(f *framework.Framework, count int, pool string) {
...
+			imgInfo, err := getImageInfo(f, image, pool)
+			if err != nil {
+				return
+			}
+			imgStatus, err := getImageStatus(f, image, pool)
+			if err != nil {
+				return
+			}
+			// Collecting image details for printing
+			imageDetails = append(imageDetails, fmt.Sprintf("Pool Name: %s, Image Name: %s, Img Info: %v, Img Status: %v", pool, image, imgInfo, imgStatus))
```
Comment (nixpanic) [inline e2e/rbd.go]: golangci-lint complains that this line is too log: https://github.com/ceph/ceph-csi/actions/runs/11613610012/job/32379913964?pr=4938#step:3:820

File: e2e/rbd_helper.go (hunk 3 above)
Comment (OdedViner) [reply e2e/rbd_helper.go]: done

File: e2e/rbd_helper.go (hunk 2 above)
Comment (OdedViner) [reply e2e/rbd_helper.go]: done

File: e2e/rbd.go (hunk 1 above)
Comment (OdedViner) [reply e2e/rbd.go]: done

File: e2e/rbd.go (hunk 4 above)
Comment (OdedViner) [reply e2e/rbd.go]: done

File: e2e/rbd.go [hunk 5]
```diff
@@ -189,12 +189,26 @@ func validateRBDImageCount(f *framework.Framework, count int, pool string) {
 		framework.Failf("failed to list rbd images: %v", err)
 	}
 	if len(imageList) != count {
+		var imageDetails []string // To collect details for all images
+		for _, image := range imageList {
+			imgInfo, err := getImageInfo(f, image, pool)
+			if err != nil {
+				return
```
Comment (Madhu-1) [inline e2e/rbd.go]: we need to log error and continue as this is for debuggin

File: e2e/rbd.go [hunk 6]
```diff
@@ -189,12 +189,26 @@ func validateRBDImageCount(f *framework.Framework, count int, pool string) {
...
+			}
+			imgStatus, err := getImageStatus(f, image, pool)
+			if err != nil {
+				return
```
Comment (Madhu-1) [inline e2e/rbd.go]: we need to log error and continue as this is for debugging

File: e2e/rbd.go (hunk 5 above)
Comment (OdedViner) [reply e2e/rbd.go]: done

File: e2e/rbd.go (hunk 6 above)
Comment (OdedViner) [reply e2e/rbd.go]: done

File: e2e/rbd.go [hunk 7]
```diff
@@ -475,7 +490,7 @@ var _ = Describe("RBD", func() {
 					framework.Failf("failed to create PVC: %v", err)
 				}
 				// validate created backend rbd images
-				validateRBDImageCount(f, 1, defaultRBDPool)
+				validateRBDImageCount(f, 11, defaultRBDPool)
```
Comment (iPraveenParihar) [inline e2e/rbd.go]: this is by mistake?

File: e2e/rbd_helper.go [hunk 8]
```diff
@@ -1094,6 +1104,30 @@ func getImageInfo(f *framework.Framework, imageName, poolName string) (imageInfo
...
+		rookNamespace)
+	if err != nil {
+		return imgStatus, fmt.Errorf("error retrieving rbd status: %w", err)
+	}
+	if stdErr != "" {
+		return imgStatus, fmt.Errorf("failed to get rbd status: %v", stdErr)
+	}
+	err = json.Unmarshal([]byte(stdOut), &imgStatus)
+	if err != nil {
+		framework.Logf("unmarshal failed: %w. raw buffer response: %s", err, stdOut)
```
Comment (iPraveenParihar) [inline e2e/rbd_helper.go]:
```suggestion
		return imgStatus, fmt.Errorf("unmarshal failed: %w. raw buffer response: %s", err, stdOut)
```

File: e2e/rbd.go (hunk 7 above)
Comment (Madhu-1) [reply e2e/rbd.go]: i think this is only for testing, to test how the log looks like

Comment (OdedViner) [reply e2e/rbd.go]: correct. only for testing

File: e2e/rbd_helper.go (hunk 8 above)
Comment (OdedViner) [reply e2e/rbd_helper.go]: done

File: e2e/rbd_helper.go (hunk 2 above)
Comment (OdedViner) [reply e2e/rbd_helper.go]:
```
e2e/rbd_helper.go:1125:3: k8s.io/kubernetes/test/e2e/framework.Logf does not support error-wrapping directive %w
```
Failed to run container: https://url.corp.redhat.com/cc13cdb

**Comment by OdedViner** [comment]
Output from failure job: https://url.corp.redhat.com/e9aa53d

```
[38;5;9m[FAILED] backend images not matching kubernetes resource count,image count 1 kubernetes resource count 11
  backend image Info:
   [csi-vol-d2bb1f89-26f7-4c37-a22d-d72f9a7aa30b]
   images information and status Pool: replicapool, Image: csi-vol-d2bb1f89-26f7-4c37-a22d-d72f9a7aa30b, Info: {csi-vol-d2bb1f89-26f7-4c37-a22d-d72f9a7aa30b 0 0 4194304}, Status: {  0 false 0 }[0m
  [38;5;9mIn [1m[It][0m[38;5;9m at: [1m/go/src/github.com/ceph/ceph-csi/e2e/rbd.go:206[0m [38;5;243m@ 11/04/24 13:29:22.803[0m
```

@Madhu-1 @nixpanic Is this the desired output? When I ran it manually I got the following results:
```
bash-5.1$ rbd info --pool=replicapool csi-vol-2b6574ee-9c6f-4a3b-9a96-09060763f7a7
rbd image 'csi-vol-2b6574ee-9c6f-4a3b-9a96-09060763f7a7':
	size 1 GiB in 256 objects
	order 22 (4 MiB objects)
	snapshot_count: 0
	id: 1102e70da18f
	block_name_prefix: rbd_data.1102e70da18f
	format: 2
	features: layering
	op_features: 
	flags: 
	create_timestamp: Thu Oct 31 13:26:32 2024
	access_timestamp: Thu Oct 31 13:26:32 2024
	modify_timestamp: Thu Oct 31 13:26:32 2024
bash-5.1$ rbd status --pool=replicapool csi-vol-2b6574ee-9c6f-4a3b-9a96-09060763f7a7
Watchers: none
```

**Comment by Madhu-1** [comment]
> Output from failure job: https://url.corp.redhat.com/e9aa53d
> 
> ```
> [38;5;9m[FAILED] backend images not matching kubernetes resource count,image count 1 kubernetes resource count 11
>   backend image Info:
>    [csi-vol-d2bb1f89-26f7-4c37-a22d-d72f9a7aa30b]
>    images information and status Pool: replicapool, Image: csi-vol-d2bb1f89-26f7-4c37-a22d-d72f9a7aa30b, Info: {csi-vol-d2bb1f89-26f7-4c37-a22d-d72f9a7aa30b 0 0 4194304}, Status: {  0 false 0 }�[0m
>   �[38;5;9mIn �[1m[It]�[0m�[38;5;9m at: �[1m/go/src/github.com/ceph/ceph-csi/e2e/rbd.go:206�[0m �[38;5;243m@ 11/04/24 13:29:22.803�[0m
> ```
> 
> @Madhu-1 @nixpanic Is this the desired output? When I ran it manually I got the following results:
> 
> ```
> bash-5.1$ rbd info --pool=replicapool csi-vol-2b6574ee-9c6f-4a3b-9a96-09060763f7a7
> rbd image 'csi-vol-2b6574ee-9c6f-4a3b-9a96-09060763f7a7':
> 	size 1 GiB in 256 objects
> 	order 22 (4 MiB objects)
> 	snapshot_count: 0
> 	id: 1102e70da18f
> 	block_name_prefix: rbd_data.1102e70da18f
> 	format: 2
> 	features: layering
> 	op_features: 
> 	flags: 
> 	create_timestamp: Thu Oct 31 13:26:32 2024
> 	access_timestamp: Thu Oct 31 13:26:32 2024
> 	modify_timestamp: Thu Oct 31 13:26:32 2024
> bash-5.1$ rbd status --pool=replicapool csi-vol-2b6574ee-9c6f-4a3b-9a96-09060763f7a7
> Watchers: none
> ```

How about if we just return the stdout and log it, i think it will be useful for debugging instead of unmarshal output. i tlooks like the above logs is not much helpful, @nixpanic WDYT?

File: e2e/rbd_helper.go (hunk 2 above)
Comment (nixpanic) [reply e2e/rbd_helper.go]: `framework.Logf()` does not support `%w` for logging errors. Use `%v` while logging, but when `%w` with `fmt.Errorf()` or `errors.New()`.

**Comment by nixpanic** [comment]
> How about if we just return the stdout and log it, i think it will be useful for debugging instead of unmarshal output. i tlooks like the above logs is not much helpful, @nixpanic WDYT?

Logging stdout is sufficient for me too. It may also be easier to find the right timestamp/location of errors when the logs contain pretty unique words like `block_name_prefix`.

**Comment by OdedViner** [comment]
> > Output from failure job: https://url.corp.redhat.com/e9aa53d
> > ```
> > [38;5;9m[FAILED] backend images not matching kubernetes resource count,image count 1 kubernetes resource count 11
> >   backend image Info:
> >    [csi-vol-d2bb1f89-26f7-4c37-a22d-d72f9a7aa30b]
> >    images information and status Pool: replicapool, Image: csi-vol-d2bb1f89-26f7-4c37-a22d-d72f9a7aa30b, Info: {csi-vol-d2bb1f89-26f7-4c37-a22d-d72f9a7aa30b 0 0 4194304}, Status: {  0 false 0 }�[0m
> >   �[38;5;9mIn �[1m[It]�[0m�[38;5;9m at: �[1m/go/src/github.com/ceph/ceph-csi/e2e/rbd.go:206�[0m �[38;5;243m@ 11/04/24 13:29:22.803�[0m
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @Madhu-1 @nixpanic Is this the desired output? When I ran it manually I got the following results:
> > ```
> > bash-5.1$ rbd info --pool=replicapool csi-vol-2b6574ee-9c6f-4a3b-9a96-09060763f7a7
> > rbd image 'csi-vol-2b6574ee-9c6f-4a3b-9a96-09060763f7a7':
> > 	size 1 GiB in 256 objects
> > 	order 22 (4 MiB objects)
> > 	snapshot_count: 0
> > 	id: 1102e70da18f
> > 	block_name_prefix: rbd_data.1102e70da18f
> > 	format: 2
> > 	features: layering
> > 	op_features: 
> > 	flags: 
> > 	create_timestamp: Thu Oct 31 13:26:32 2024
> > 	access_timestamp: Thu Oct 31 13:26:32 2024
> > 	modify_timestamp: Thu Oct 31 13:26:32 2024
> > bash-5.1$ rbd status --pool=replicapool csi-vol-2b6574ee-9c6f-4a3b-9a96-09060763f7a7
> > Watchers: none
> > ```
> 
> How about if we just return the stdout and log it, i think it will be useful for debugging instead of unmarshal output. i tlooks like the above logs is not much helpful, @nixpanic WDYT?

I return `imageInfo, string, error` because `validateStripe` function

**Comment by Madhu-1** [comment]
> Info: {csi-vol-d2bb1f89-26f7-4c37-a22d-d72f9a7aa30b 0 0 4194304}, Status: {  0 false 0 }

`Info: {csi-vol-d2bb1f89-26f7-4c37-a22d-d72f9a7aa30b 0 0 4194304}, Status: {  0 false 0 }` This should log both key and value from the struct without it its difficult to understand and debug it.

It would be good if we just return the stdout and log the stdout in the logs that helps for debugging, actual struct is missing few details.

**Comment by OdedViner** [comment]
> `Info: {csi-vol-d2bb1f89-26f7-4c37-a22d-d72f9a7aa30b 0 0 4194304}, Status: { 0 false 0 }` This should log both key and value from the struct without it its difficult to understand and debug it.
> 
> It would be good if we just return the stdout and log the stdout in the logs that helps for debugging, actual struct is missing few details.



> images not matching kubernete



> > Info: {csi-vol-d2bb1f89-26f7-4c37-a22d-d72f9a7aa30b 0 0 4194304}, Status: {  0 false 0 }
> 
> `Info: {csi-vol-d2bb1f89-26f7-4c37-a22d-d72f9a7aa30b 0 0 4194304}, Status: { 0 false 0 }` This should log both key and value from the struct without it its difficult to understand and debug it.
> 
> It would be good if we just return the stdout and log the stdout in the logs that helps for debugging, actual struct is missing few details.

And what should be done with this function? It relies on the imgInfo struct.
https://github.com/ceph/ceph-csi/blob/cea8bf8110531284d272582b9c536ffdb2ece82b/e2e/rbd_helper.go#L1132-L1133

**Comment by OdedViner** [comment]
@Madhu-1 @nixpanic Which method would be better: `getImageStatus`, which returns a string output, or `getImageInfo`, which returns a struct with all parameters?

**Comment by Madhu-1** [comment]
> @Madhu-1 @nixpanic Which method would be better: `getImageStatus`, which returns a string output, or `getImageInfo`, which returns a struct with all parameters?

we could have a base function that returns the string and getImageStatus can use the base function and later do unmarshal and from the validation we will call the base function that returns the string data and print it.

File: e2e/rbd_helper.go [hunk 9]
```diff
@@ -1063,35 +1063,59 @@ func waitToRemoveImagesFromTrash(f *framework.Framework, poolName string, t int)
...
+	BlockNamePrefix string   `json:"block_name_prefix"`
+	Format          int      `json:"format"`
+	Features        []string `json:"features"`
+	OpFeatures      []string `json:"op_features"`
+	Flags           []string `json:"flags"`
+	CreateTimestamp string   `json:"create_timestamp"`
+	AccessTimestamp string   `json:"access_timestamp"`
+	ModifyTimestamp string   `json:"modify_timestamp"`
+	StripeUnit      int      `json:"stripe_unit"`
+	StripeCount     int      `json:"stripe_count"`
```
Comment (Madhu-1) [inline e2e/rbd_helper.go]: @OdedViner  i dont think we need all the fields in this struct unless we are using it, as we are returning the string as a output we are good for logging. please revert this back

File: e2e/rbd.go (hunk 7 above)
Comment (Madhu-1) [inline e2e/rbd.go]: can you please revert this back?

File: e2e/rbd_helper.go (hunk 9 above)
Comment (OdedViner) [reply e2e/rbd_helper.go]: done

File: e2e/rbd.go (hunk 7 above)
Comment (OdedViner) [reply e2e/rbd.go]: done

**Review by Madhu-1 — APPROVED** [review]

**Review by Madhu-1 — CHANGES_REQUESTED** [review]
@OdedViner changes LGTM , please squash the commits into 1

**Comment by OdedViner** [comment]
> @OdedViner changes LGTM , please squash the commits into 1

@Madhu-1 done

**Review by Madhu-1 — DISMISSED** [review]

**Comment by Madhu-1** [comment]
@OdedViner can you please fix CI problem

**Comment by OdedViner** [comment]
> @OdedViner can you please fix CI problem

@Madhu-1 I deleted the blank line on `getImageInfo` func

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

**Review by black-dragon74 — APPROVED** [review]
LGTM, thank you!

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio queue

**Comment by nixpanic** [comment]
@OdedViner, [a CI job failed](https://jenkins-ceph-csi.apps.ocp.cloud.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.29/detail/mini-e2e_k8s-1.29/567/pipeline) and resulted in the following output:

```
[FAILED] backend images not matching kubernetes resource count,image count 1 kubernetes resource count 0
  backend image Info:
   [csi-vol-76e28f0b-4ae2-43f7-b9e6-c8e28d891c25]
   images information and status Pool: replicapool, Image: csi-vol-76e28f0b-4ae2-43f7-b9e6-c8e28d891c25, Info: , Status: 
```

It looks like `Info` and `Status` are both empty for some reason, maybe you want to double check what it is doing?

**Comment by OdedViner** [comment]
> @OdedViner, [a CI job failed](https://jenkins-ceph-csi.apps.ocp.cloud.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.29/detail/mini-e2e_k8s-1.29/567/pipeline) and resulted in the following output:
> 
> ```
> [FAILED] backend images not matching kubernetes resource count,image count 1 kubernetes resource count 0
>   backend image Info:
>    [csi-vol-76e28f0b-4ae2-43f7-b9e6-c8e28d891c25]
>    images information and status Pool: replicapool, Image: csi-vol-76e28f0b-4ae2-43f7-b9e6-c8e28d891c25, Info: , Status: 
> ```
> 
> It looks like `Info` and `Status` are both empty for some reason, maybe you want to double check what it is doing?
@nixpanic 
@Madhu-1 @Madhu-1Can we re-run the job? Alternatively, I can create a PR with `validateRBDImageCount(f, 111, defaultRBDPool)`. The test is expected to fail so we can review the failure output.

**Comment by Madhu-1** [comment]
> 1Can we re-run the job? Alternatively, I can create a PR with `validateRBDImageCount(f, 111, defaultRBDPool)`. The test is expected to fail so we can review the failure output.

I see this happening as well, This happens when there is a delay in volume deletion where the volume is present in first get and gets deleted when we try to query in details (due to async deletion)

**Comment by OdedViner** [comment]
> > 1Can we re-run the job? Alternatively, I can create a PR with `validateRBDImageCount(f, 111, defaultRBDPool)`. The test is expected to fail so we can review the failure output.
> 
> I see this happening as well, This happens when there is a delay in volume deletion where the volume is present in first get and gets deleted when we try to query in details (due to async deletion)

@Madhu-1 is there a method  to fix it? or only add sleep before first `get`?

**Comment by Madhu-1** [comment]
> > > 1Can we re-run the job? Alternatively, I can create a PR with `validateRBDImageCount(f, 111, defaultRBDPool)`. The test is expected to fail so we can review the failure output.
> > 
> > 
> > I see this happening as well, This happens when there is a delay in volume deletion where the volume is present in first get and gets deleted when we try to query in details (due to async deletion)
> 
> @Madhu-1 is there a method to fix it? or only add sleep before first `get`?

This is very corner case there i no 100 % solution to fix it but we need more than sleep. we need to take tasks in to consideration when we do get call for the count.
