### PR TITLE
rbd: use ListChildrenAttributes() instead of ListChildren()

### LINKED ISSUE #5173: rbd: Avoid flattening child images which are in trash
# Describe the bug #

Currently, `ListChildren()` goceph function lists all child images regardless of their existence in trash.
https://github.com/ceph/ceph-csi/blob/43b150f14d2858f2bdcd268d8fac16377a98b8a4/internal/rbd/rbd_util.go#L2039

https://github.com/ceph/go-ceph/blob/e84ad6c5a35c0514773539c3462af300c3b50584/rbd/snapshot_nautilus.go#L138

We need to make use of new go-ceph API `ListChildrenWithParams` API in order to distinguish child images in trash and avoid trying to flatten them. 
https://github.com/ceph/go-ceph/pull/1079

### PR DESCRIPTION
**Pull request by Rakshith-R**
# Describe what this PR does #

This commit modifies listSnapAndChildren() to make use of ListChildrenAttributes() instead of ListChildren() which allows us to filter out images in trash.
This commit also order the alive images so that temp clone images are followed by images backing volume snapshots so that temp clone images are flattened first.

Is the change backward compatible?
Yes

Are there concerns around backward compatibility?
No

## Related issues ##

Fixes: #5173 

**Checklist:**

* [ ] **Commit Message Formatting**: Commit titles and messages follow
  guidelines in the [developer
  guide](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#commit-messages).
* [ ] Reviewed the developer guide on [Submitting a Pull
  Request](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#development-workflow)
* [ ] [Pending release
  notes](https://github.com/ceph/ceph-csi/blob/devel/PendingReleaseNotes.md)
  updated with breaking and/or notable changes for the next major release.
* [ ] Documentation has been updated, if necessary.
* [ ] Unit tests have been added, if necessary.
* [ ] Integration tests have been added, if necessary.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

* `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)

</details>

### CODE REVIEW

File: internal/rbd/rbd_util.go [hunk 1]
```diff
@@ -2038,12 +2041,28 @@ func (ri *rbdImage) listSnapAndChildren() ([]librbd.SnapInfo, []string, error) {
 		return nil, nil, err
 	}
 
-	// ListChildren() returns pools, images, err.
-	_, children, err := image.ListChildren()
+	// ListChildrenAttributes() returns child ImageSpec list, err.
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go]: you can drop this comment, I think the function is rather clear

File: internal/rbd/rbd_util.go [hunk 2]
```diff
@@ -2038,12 +2041,28 @@ func (ri *rbdImage) listSnapAndChildren() ([]librbd.SnapInfo, []string, error) {
...
 		return nil, nil, err
 	}
 
+	children := make([]string, 0)
+	volSnapChildren := make([]string, 0)
+	for _, child := range childImageSpecList {
+		if child.Trash {
+			continue
+		}
+		if strings.HasSuffix(child.ImageName, "-temp") {
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go]: Maybe consider adding a `isTempImage(child)` function?

File: internal/rbd/rbd_util.go [hunk 3]
```diff
@@ -2038,12 +2041,28 @@ func (ri *rbdImage) listSnapAndChildren() ([]librbd.SnapInfo, []string, error) {
...
+			children = append(children, child.ImageName)
+		} else {
+			volSnapChildren = append(volSnapChildren, child.ImageName)
+		}
+	}
+	// order the temp clone images first followed by the volume snapshots
+	// so that the temp clones are flattened first.
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go]: This is the 2nd comment about `temp clones are flattened first`. I don't get why that is the case. If that is a requirement of the returned list, mention something about the order. Or wherever the list is consumed, use some other way of inspecting the list. Might be cleaner to return two lists, so that the distinction is very clear.

Comment (Rakshith-R) [reply internal/rbd/rbd_util.go]: > This is the 2nd comment about `temp clones are flattened first`. I don't get why that is the case. If that is a requirement of the returned list, mention something about the order. Or wherever the list is consumed, use some other way of inspecting the list. Might be cleaner to return two lists, so that the distinction is very clear.

I've removed it from the function definition, since we still are returning full list of child images which are not in trash.

I've expanded the comment in this section with reasons why such ordering is done so it can be understood in the future.

Comment (nixpanic) [reply internal/rbd/rbd_util.go]: Thanks, that makes things a little bit clearer. I don't understand (yet) if, and why callers need to care about the order in the list that is returned. If callers need to care, or benefit from it, why not return separate lists? Or, a struct like `{ snaps, tempChildren, volSnapChildren }` so that callers of the function are very aware of the differences, and can decide how to handle them?

Comment (Rakshith-R) [reply internal/rbd/rbd_util.go]: > Thanks, that makes things a little bit clearer. I don't understand (yet) if, and why callers need to care about the order in the list that is returned. If callers need to care, or benefit from it, why not return separate lists? Or, a struct like `{ snaps, tempChildren, volSnapChildren }` so that callers of the function are very aware of the differences, and can decide how to handle them?

I've moved the logic to order images into the caller and added a struct for returned parameters.
PTAL

File: internal/rbd/rbd_util.go [hunk 4]
```diff
@@ -2025,26 +2029,49 @@ func (ri *rbdImage) DisableDeepFlatten() error {
 	return image.UpdateFeatures(librbd.FeatureDeepFlatten, false)
 }
 
-// listSnapAndChildren returns list of names of snapshots and child images.
-func (ri *rbdImage) listSnapAndChildren() ([]librbd.SnapInfo, []string, error) {
+type SnapAndChildrenInfo struct {
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go]: No need to export this, use `snapAndChildrenInfo` instead.

**Review by nixpanic — COMMENTED** [review]
Thanks, makes it much cleaner. Just a nit that needs addressing.

File: internal/rbd/controllerserver.go [hunk 5]
```diff
@@ -590,14 +590,23 @@ func (cs *ControllerServer) repairExistingVolume(ctx context.Context, req *csi.C
...
 		return status.Error(codes.Internal, err.Error())
 	}
+	// order the temp clone images first followed by the volume snapshot
+	// images so that the temp clone images are flattened first.
+	// This is done in order to:
+	// - increase number of snapshots which can be supported for
+	// changed block tracking(rbd snap diff).
+	// - favor scalability since multiple PVCs can be restored from same
+	// volumesnapshot versus just one PVC-PVC clone.
+	children := append(snapAndChildrenInfo.TempCloneChildren, snapAndChildrenInfo.VolumeSnapshotChildren...)
```
Comment (nixpanic) [inline internal/rbd/controllerserver.go]: **golangci-lint** complains about this. `append()` may modify the 1st parameter (`snapAndChildrenInfo`), which could cause confusion later on in case it is used again ([docs](https://pkg.go.dev/builtin#append)).

Instead, you could do it like this:
```go
children := make([]string, len(snapAndChildrenInfo.TempCloneChildren) + len(snapAndChildrenInfo.VolumeSnapshotChildren))
children = append(children, snapAndChildrenInfo.TempCloneChildren...)
children = append(children, snapAndChildrenInfo.VolumeSnapshotChildren...)
```

**Review by nixpanic — DISMISSED** [review]

**Comment by Rakshith-R** [comment]
> **golangci-lint** complains about this. `append()` may modify the 1st parameter (`snapAndChildrenInfo`), which could cause confusion later on in case it is used again ([docs](https://pkg.go.dev/builtin#append)).
> 
> Instead, you could do it like this:
> 
> ```go
> children := make([]string, len(snapAndChildrenInfo.TempCloneChildren) + len(snapAndChildrenInfo.VolumeSnapshotChildren))
> children = append(children, snapAndChildrenInfo.TempCloneChildren...)
> children = append(children, snapAndChildrenInfo.VolumeSnapshotChildren...)
> ```

It needs to be initialized with zero length :(
ci passes now
ptal

**Review by nixpanic — APPROVED** [review]

**Review by yati1998 — APPROVED** [review]

**Comment by Rakshith-R** [comment]
@mergifyio queue

**Comment by Rakshith-R** [comment]
Upgrade tests are failing due to 
https://github.com/ceph/ceph-csi/pull/5211

**Comment by Rakshith-R** [comment]
@mergifyio requeue
