### PR TITLE
fix: Invalid "invalid encryption kms configuration" error

### LINKED ISSUE #3759: Invalid "invalid encryption kms configuration" error
# Describe the bug #

After upgrading to v3.8.0, the following error appeared whereas I did not configure encryption:

```
csi-rbdplugin E0419 07:35:12.775698    6851 utils.go:210] ID: 69 Req-ID: 0001-0009-rook-ceph-0000000000000001-4aef4df9-b4a3-11ed-9485-b2ff204cea03 GRPC error: rpc error: code = Internal desc = invalid encryption kms configuration: missing encryption passphrase in secrets
```

Rolling back to v3.7.0 solved the issue.

This might be due to dc7ba684e3ba16a0f62569f815be5261162432e3 which removed and `else` clause.
So before (in v3.7.0) the `initKMS` procedure was interrupted when no specific KMS configuration is present (which is my case).
Now (in v3.8.0) a non-nil error is returned: 

```
diff --git a/internal/rbd/encryption.go b/internal/rbd/encryption.go
index c72113288..ea65f14aa 100644
--- a/internal/rbd/encryption.go
+++ b/internal/rbd/encryption.go
@@ -309,8 +309,6 @@ func (ri *rbdImage) initKMS(ctx context.Context, volOptions, credentials map[str
        kmsID, encType, err := ParseEncryptionOpts(ctx, volOptions, rbdDefaultEncryptionType)
        if err != nil {
                return err
-       } else if kmsID == "" {
-               return nil
        }
```

# Environment details #

- Image/version of Ceph CSI driver : v3.8.0
- Kernel version : 5.4.0
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : krbd
- Kubernetes cluster version : 1.25.4
- Ceph cluster version : 17.2.6

# Steps to reproduce #

1. Have the following StorageClass configuration:

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: rook-ceph-cluster
    meta.helm.sh/release-namespace: rook-ceph
    storageclass.kubernetes.io/is-default-class: "false"
  creationTimestamp: "2023-02-23T16:11:55Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: ceph-block
  resourceVersion: "795634683"
  uid: fb7f65ef-0bff-49a0-bb52-5699bde7ce92
parameters:
  clusterID: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  encrypted: "false"
  imageFeatures: layering
  imageFormat: "2"
  pool: ceph-blockpool
provisioner: rook-ceph.rbd.csi.ceph.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
```
2. Create a pods with a PVC using this storage class

# Actual results #

The error about an "invalid encryption kms" is raised (as described above)

# Expected behavior #

No error while mounting Ceph image

# Logs #

"csi-rbdplugin" logs:

```
W0419 07:32:17.161034    6851 rbd_attach.go:241] kernel version "5.4.0-137-generic" doesn't support cookie feature
E0419 07:33:10.655993    6851 utils.go:210] ID: 23 Req-ID: 0001-0009-rook-ceph-0000000000000001-4aef4df9-b4a3-11ed-9485-b2ff204cea03 GRPC error: rpc error: code = Internal desc = invalid encryption kms configuration: missing encryption passphrase in secrets
```

### PR DESCRIPTION
**Pull request by riya-singhal31**
this commit adds the validation for encryption
value as false, and sets the type as none

Fixes: #3759

### CODE REVIEW

File: internal/rbd/encryption.go [hunk 1]
```diff
@@ -341,7 +342,8 @@ func ParseEncryptionOpts(
 		encrypted, kmsID string
 	)
 	encrypted, ok = volOptions["encrypted"]
-	if !ok {
+	val, _ := strconv.ParseBool(encrypted)
```
Comment (Madhu-1) [inline internal/rbd/encryption.go]: I'm not sure why parsing is necessary when the encrypted key isn't configured

**Review by Madhu-1 — CHANGES_REQUESTED** [review]
Please add an E2E for it.

**Comment by riya-singhal31** [comment]
> Please add an E2E for it.

Yes, adding an unit test for it.

File: internal/rbd/encryption.go (hunk 1 above)
Comment (nixpanic) [reply internal/rbd/encryption.go]: No need to parse in case `!ok`, but it is possible that `encrypted: false` is set. Checking the boolean value of `encrypted` is important.

Maybe you prefer something like this?

```go
encrypted, ok = volOptions["encrypted"]
if !ok {
    return ....
} else if val, _ := strconv.ParseBool(encrypted): !val {
    return ...
}
```

I am not in favor of two the same `return` statement though. Converting the `encrypted` string to a boolean, even when not required, is not a huge performance loss, and I think the code will be cleaner.

File: internal/rbd/encryption_test.go [hunk 2]
```diff
@@ -0,0 +1,86 @@
...
+			},
+			fallbackType: util.EncryptionTypeBlock,
+			expectedKMS:  "",
+			expectedEnc:  util.EncryptionTypeNone,
+			expectedErr:  nil,
+		},
+		{
+			testName: "Valid Encryption Option With KMS ID",
+			volOptions: map[string]string{
+				"encrypted":       "true",
```
Comment (nixpanic) [inline internal/rbd/encryption_test.go:68]: can you add an other test with `encrypted` set to an invalid string (not `true` or `false`)?

Comment (riya-singhal31) [reply internal/rbd/encryption_test.go:68]: Done, thanks!

**Comment by Madhu-1** [comment]
@riya-singhal31 CI problem, you can run the tests locally by running commands like `CONTAINER_CMD=docker make containerized-test TARGET=go-lint` you just need to adjust the TARGET to run different tests

File: internal/rbd/encryption.go (hunk 1 above)
Comment (riya-singhal31) [reply internal/rbd/encryption.go]: We will need to follow the 2nd, so as to handle the case when the encrypted is not configured.

**Comment by riya-singhal31** [comment]
> @riya-singhal31 CI problem, you can run the tests locally by running commands like `CONTAINER_CMD=docker make containerized-test TARGET=go-lint` you just need to adjust the TARGET to run different tests

Sure, thanks Madhu.

File: e2e/rbd.go [hunk 3]
```diff
@@ -2872,6 +2872,56 @@ var _ = Describe("RBD", func() {
 				}
 			})
 
+			By("create storageClass with encrypted as false", func() {
+				encrypted := "false"
```
Comment (Madhu-1) [inline e2e/rbd.go]: no need for a new variable just set this in map at line 2886

File: internal/rbd/encryption.go [hunk 4]
```diff
@@ -344,6 +344,13 @@ func ParseEncryptionOpts(
 	if !ok {
 		return "", util.EncryptionTypeNone, nil
 	}
+	val, er := strconv.ParseBool(encrypted)
+	if er != nil {
+		return "", util.EncryptionTypeInvalid, fmt.Errorf("strconv.ParseBool: parsing %s: invalid syntax", encrypted)
```
Comment (Madhu-1) [inline internal/rbd/encryption.go]: Instead of defining our own error just return the error `er` here?

File: internal/rbd/encryption_test.go [hunk 5]
```diff
@@ -0,0 +1,100 @@
...
+
+func TestParseEncryptionOpts(t *testing.T) {
+	t.Parallel()
+	tests := []struct {
+		testName     string
+		volOptions   map[string]string
+		fallbackType util.EncryptionType
+		expectedKMS  string
+		expectedEnc  util.EncryptionType
+		expectedErr  string
```
Comment (Madhu-1) [inline internal/rbd/encryption_test.go]: Instead of a string, you can just check error is expected or not with a bool value here.

Comment (riya-singhal31) [reply internal/rbd/encryption_test.go]: Thanks for the review, Madhu.
Updated the PR with mentioned changes.

**Review by Madhu-1 — DISMISSED** [review]

File: internal/rbd/encryption.go [hunk 6]
```diff
@@ -341,8 +341,14 @@ func ParseEncryptionOpts(
 		encrypted, kmsID string
 	)
 	encrypted, ok = volOptions["encrypted"]
-	val, _ := strconv.ParseBool(encrypted)
-	if !ok || !val{
+	if !ok {
+		return "", util.EncryptionTypeNone, nil
+	}
+	val, er := strconv.ParseBool(encrypted)
```
Comment (nixpanic) [inline internal/rbd/encryption.go]: you can re-use both `ok` and `err` variables here. No need to introduce two new ones.

**Review by nixpanic — CHANGES_REQUESTED** [review]
just a small nit to make the code a little cleaner

**Comment by riya-singhal31** [comment]
> just a small nit to make the code a little cleaner

Thanks for the suggestion Niels, updated.

**Review by nixpanic — APPROVED** [review]

**Comment by riya-singhal31** [comment]
Hi @Madhu-1 ,
With the recent commit, the approval got removed. So, requesting you to please approve it again if you find it good.

**Review by Madhu-1 — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio queue

**Comment by riya-singhal31** [comment]
cherry-pick release-4.13

**Comment by riya-singhal31** [comment]
/cherry-pick-release-4.13

**Comment by riya-singhal31** [comment]
git cherry-pick -4.13
