### PR TITLE
cephfs: volumemounter probe

### LINKED ISSUE #60: Provisioner is kernel ceph only
If a storage class has `provisionVolume: true`, the provisioner fails on nodes without kernel ceph support, since `createVolume` has mountKernel hardcoded.  Does it make sense to use the mounter specified by volOptions.Mounter?

### PR DESCRIPTION
**Pull request by gman0**
Fixes #60 

The driver will now probe for either ceph fuse/kernel every time it's about to mount a cephfs volume.

This also affects `CreateVolume` and `DeleteVolume` where the mounting was hard-coded to ceph kernel client till now - mounter configuration and probing are now honored.

Probing is done by running:
* `ceph-fuse --version` for Ceph FUSE driver
* `mount.ceph` for Ceph kernel client

Expecting both to exit with `0`.

### CODE REVIEW

File: pkg/cephfs/volumemounter.go [hunk 1]
```diff
@@ -113,3 +114,63 @@ func unmountVolume(mountPoint string) error {
...
+
+	wantMounter := volOptions.Mounter
+
+	if wantMounter == "" {
+		wantMounter = DefaultVolumeMounter
+	}
+
+	// Verify that it's available
+
+	availableMounters := getAvailableMounters()
```
Comment (rootfs) [inline pkg/cephfs/volumemounter.go]: how about making `availableMounters` a global var? This will save a ceph-fuse call each time filesystem is to be mounted.

Comment (gman0) [reply pkg/cephfs/volumemounter.go]: Sure, I wasn't too sure about the use-cases here, TBH. Installing either of the mounters at runtime is not very plausible.

**Comment by rootfs** [comment]
thanks
