### PR TITLE
rbd: add support for bigger size restore/clone PVC

### LINKED ISSUE #1438: Allow bigger size restore/clone for RBD FileMode PVCs
# Describe the bug #

CSI spec allows a user to create bigger volumes at restore/clone path. Ideally we should enable it in our driver too. This issue tracks the requirement for RBD.

### LINKED ISSUE #1566: Allow bigger size restore/clone for RBD Blockmode  PVCs
# Describe the bug #

CSI spec allows a user to create bigger volumes at restore/clone path. Ideally we should enable it in our driver too. This issue tracks the requirement for RBD Block mode PVCs.

### PR DESCRIPTION
**Pull request by Madhu-1**
This PR allows the user to create the bigger PVC from the PVC and restore a snapshot to a bigger size PVC. and did require refactoring to avoid linter issues.

fixes: #1566
fixes: #1438

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

File: internal/rbd/controllerserver.go [hunk 1]
```diff
@@ -1397,6 +1394,33 @@ func (cs *ControllerServer) DeleteSnapshot(
...
+	rbdVol := generateVolFromSnap(rbdSnap)
+	err := rbdVol.Connect(cr)
+	if err != nil {
+		return status.Error(codes.Internal, err.Error())
+	}
+	defer rbdVol.Destroy()
+	// cleanup the image from trash if the error is image not found.
+	err = rbdVol.ensureImageCleanup(ctx)
+	if err != nil {
+		log.ErrorLog(ctx, "failed to delete rbd image: %s/%s with error: %v", rbdVol.Pool, rbdVol.VolName, err)
```
Comment (nixpanic) [inline internal/rbd/controllerserver.go]: while moving the code around, you are allowed to clean logging functions up too, just log `rbdVol` as `%q` so that the standard formatting of the image name is used (including optional rados namespace).

Same counts for the below logging of `rbdSnap`.

File: internal/rbd/controllerserver.go [hunk 2]
```diff
@@ -588,6 +596,14 @@ func (cs *ControllerServer) createVolumeFromSnapshot(
 
 	log.DebugLog(ctx, "create volume %s from snapshot %s", rbdVol.RequestName, rbdSnap.RbdSnapName)
 
+	// resize the volume if the size is different
+	if rbdSnap.SizeBytes != rbdVol.VolSize {
+		err = rbdVol.resize(rbdVol.VolSize)
```
Comment (nixpanic) [inline internal/rbd/controllerserver.go]: Reducing size is dangerous, that should not be done.

Consider placing these resize checks/actions in a helper function:

```go
err = rbdVol.Expand(rbdSnap.SizeBytes)
...

// Expand resizes the rbdImage to the given size, in case the rbdImage is smaller.
func (ri *rbdImage) Expand(size int) error {
    if ri.VolSize >= size {
         return nil
    }

    return ri.resize(size)
}
```

File: internal/rbd/nodeserver.go [hunk 3]
```diff
@@ -435,24 +435,13 @@ func (ns *NodeServer) stageTransaction(
 	}
 	transaction.isMounted = true
 
-	// resize if its fileSystemType static volume.
-	if staticVol && !isBlock {
-		var ok bool
-		resizer := mount.NewResizeFs(utilexec.New())
-		ok, err = resizer.NeedResize(devicePath, stagingTargetPath)
+	// As we are suppoting the restore of a volume to a bigger size and
```
Comment (nixpanic) [inline internal/rbd/nodeserver.go]: typo `suppoting`

File: internal/rbd/nodeserver.go [hunk 4]
```diff
@@ -463,6 +452,46 @@ func (ns *NodeServer) stageTransaction(
...
+		if err != nil {
+			log.ErrorLog(ctx, "failed to resize device %s, mapper %s: %w",
+				mapperPath, mapperFile, err)
+
+			return status.Errorf(codes.Internal,
+				"failed to resize device %s, mapper %s: %v", mapperPath, mapperFile, err)
+		}
+		// Use mapper device path for fs resize
+		devicePath = mapperPath
+	}
```
Comment (nixpanic) [inline internal/rbd/nodeserver.go:461]: empty lines between sections of code make things more readable, please use that to please the eyes of your fellow developers

File: internal/rbd/nodeserver.go [hunk 5]
```diff
@@ -463,6 +452,46 @@ func (ns *NodeServer) stageTransaction(
...
+	resizer := mount.NewResizeFs(utilexec.New())
+	ok, err = resizer.NeedResize(devicePath, stagingTargetPath)
+	if err != nil {
+		return status.Errorf(codes.Internal,
+			"need resize check failed on devicePath %s and staingPath %s, error: %v",
+			devicePath,
+			stagingTargetPath,
+			err)
+	}
+	if ok {
```
Comment (nixpanic) [inline internal/rbd/nodeserver.go]: In most flows we return early in case there is an error or nothing needs to be done. In such a coding style checking for `!ok` on this line and returning fits better. It also reduces the indention of the `resizer.Resize()` call, making the flow a little simpler to follow when just glancing over the code.

File: e2e/rbd.go [hunk 6]
```diff
@@ -3383,6 +3385,114 @@ var _ = Describe("RBD", func() {
 				}
 			})
 
+			By("restore snapshot to a bigger size PVC", func() {
```
Comment (nixpanic) [inline e2e/rbd.go:3359]: what is the benefit of these two nested `By()` calls?

**Review by nixpanic — CHANGES_REQUESTED** [review]
Mostly some small coding improvements to make understanding and maintaining the code a little easier. Nothing else outstanding, as far as I am concerned.

File: internal/rbd/controllerserver.go (hunk 2 above)
Comment (Madhu-1) [reply internal/rbd/controllerserver.go]: the smaller size is not allowed for now in kubernetes  (CO). will send a follow-up patch to introduce this check for cephcsi (for both cephfs and rbd) to disallow that operation as it might cause some problems like data loss etc.

File: e2e/rbd.go (hunk 6 above)
Comment (Madhu-1) [reply e2e/rbd.go:3359]: Having nested `by` helps to break larger testing into smaller pieces for better readability.

File: internal/rbd/controllerserver.go (hunk 2 above)
Comment (nixpanic) [reply internal/rbd/controllerserver.go]: Indeed **NEVER** reduce the size of an RBD volume.

Changing quotas for CephFS would be acceptable, in case the current consumption does not hit the limit.

Comment (Madhu-1) [reply internal/rbd/controllerserver.go]: https://github.com/ceph/ceph-csi/issues/2718

Comment (Madhu-1) [reply internal/rbd/controllerserver.go]: will do some testing for cephfs how it works the reducing size of a bigger size subvolume and will send follow-up for this one. opened #2718 for tracking it.

File: internal/rbd/rbd_util.go [hunk 7]
```diff
@@ -1053,9 +1053,33 @@ func genSnapFromSnapID(
...
+	if err != nil {
+		return fmt.Errorf("failed to update snapshot details for %q: %w", rbdSnap, err)
+	}
+
 	return err
 }
 
+// updateSnapshotDetails will copies the details from the rbdVolume to the
+// rbdSnapshot. example copying size from rbdVolume to rbdSnapshot.
+func updateSnapshotDetails(rbdSnap *rbdSnapshot) error {
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go:1070]: Not sure how I missed this in the preview review round...

Can `getImageInfo()` not be a function for `rbdImage` instead? That would make things much simpler.

File: internal/rbd/controllerserver.go (hunk 2 above)
Comment (nixpanic) [reply internal/rbd/controllerserver.go]: I still would like to see the check for resizing in a helper function. This if+resize block is repeated a lot.

**Comment by Madhu-1** [comment]
@pkalever PTAL mainly for encrypted PVC expansion.

**Comment by Madhu-1** [comment]
something is wrong. marking it as draft as i need to test all flows manuallly

File: internal/rbd/rbd_util.go (hunk 7 above)
Comment (nixpanic) [reply internal/rbd/rbd_util.go:1070]: hmm, this has not been addressed yet?

File: internal/rbd/controllerserver.go [hunk 8]
```diff
@@ -1397,6 +1394,39 @@ func (cs *ControllerServer) DeleteSnapshot(
...
+	}
+	defer rbdVol.Destroy()
+
+	err = rbdVol.openIoctx()
+	if err != nil {
+		return status.Error(codes.Internal, err.Error())
+	}
+
+	// cleanup the image from trash if the error is image not found.
+	err = rbdVol.ensureImageCleanup(ctx)
```
Comment (nixpanic) [inline internal/rbd/controllerserver.go:1423]: maybe make `ensureImageCleanup()` a function  of `rbdImage` so that you can call it on the `rbdSnap` directly?

File: internal/rbd/clone.go [hunk 9]
```diff
@@ -181,6 +181,16 @@ func (rv *rbdVolume) createCloneFromImage(ctx context.Context, parentVol *rbdVol
 		return err
 	}
 
+	// resize the image to the requested size is greater than the current size
+	if rv.VolSize > parentVol.VolSize {
```
Comment (nixpanic) [inline internal/rbd/clone.go]: repetitive code blocks, really should be done with a helper function

**Review by nixpanic — CHANGES_REQUESTED** [review]

File: internal/rbd/rbd_util.go (hunk 7 above)
Comment (Madhu-1) [reply internal/rbd/rbd_util.go:1070]: unfortunately, this is still needed as rbdImage is created with RbdSnapName and I moved the size to rbdImage struct.

File: internal/rbd/clone.go (hunk 9 above)
Comment (Madhu-1) [reply internal/rbd/clone.go]: should be fixed now

File: internal/rbd/controllerserver.go (hunk 2 above)
Comment (Madhu-1) [reply internal/rbd/controllerserver.go]: moved to a helper function

File: internal/rbd/controllerserver.go (hunk 8 above)
Comment (Madhu-1) [reply internal/rbd/controllerserver.go:1423]: This needs more changes than expected as i need to update multiple functions which am not touching in this PR. will revisit when working on the codebase cleanup.

File: e2e/rbd.go [hunk 10]
```diff
@@ -3338,6 +3340,199 @@ var _ = Describe("RBD", func() {
...
+				By("validate image deletion", func() {
+					validateRBDImageCount(f, 0, defaultRBDPool)
+					err := waitToRemoveImagesFromTrash(f, defaultRBDPool, deployTimeout)
+					if err != nil {
+						e2elog.Failf("failed to validate rbd images in pool %s trash: %v", defaultRBDPool, err)
+					}
+				})
+			})
+
+			By("clone PVC to a bigger size PVC", func() {
```
Comment (humblec) [inline e2e/rbd.go:3463]: Instead of adding a new test can we add one more clone case to the "exisitng" clone test ?

File: e2e/rbd.go [hunk 11]
```diff
@@ -3338,6 +3340,199 @@ var _ = Describe("RBD", func() {
...
+				By("clone PVC to bigger size pvc", func() {
```
Comment (humblec) [inline e2e/rbd.go]: why 2 `By`s sequentially here?

**Review by humblec — CHANGES_REQUESTED** [review]

File: e2e/rbd.go (hunk 10 above)
Comment (Madhu-1) [reply e2e/rbd.go:3463]: all clone tests need not go through the resize tests adding a separate test so that this can be reused for cephfs.

File: e2e/rbd.go (hunk 11 above)
Comment (Madhu-1) [reply e2e/rbd.go]: https://github.com/ceph/ceph-csi/pull/2716#discussion_r770352888 already discussed here

File: internal/rbd/rbd_util.go [hunk 12]
```diff
@@ -107,6 +107,9 @@ type rbdImage struct {
 	// identifying this rbd image
 	VolID string `json:"volID"`
 
+	// VolSize is the size of the RBD image backing this rbdVolume.
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go]: nit: this is now part of `rbdImage`, not `rbdVolume`

File: internal/rbd/controllerserver.go [hunk 13]
```diff
@@ -1001,7 +1001,7 @@ func (cs *ControllerServer) CreateSnapshot(
 		return nil, status.Error(codes.Internal, err.Error())
 	}
 	rbdSnap.RbdImageName = rbdVol.RbdImageName
-	rbdSnap.SizeBytes = rbdVol.VolSize
+	rbdSnap.VolSize = rbdVol.VolSize
```
Comment (nixpanic) [inline internal/rbd/controllerserver.go:1027]: this commit has a typo in the commit message (maintaing).

File: internal/rbd/controllerserver.go (hunk 8 above)
Comment (nixpanic) [reply internal/rbd/controllerserver.go:1423]: ok, thanks!

File: internal/rbd/rbd_util.go [hunk 14]
```diff
@@ -1703,6 +1703,16 @@ func cleanupRBDImageMetadataStash(metaDataPath string) error {
 	return nil
 }
 
+// expand checks if the requestedVolume size and the existing image size both
+// are same. If they are same, it returns nil else it resizes the image.
+func (rv *rbdVolume) expand() error {
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go:1716]: I was expecting to see `expand()` to have a `size` parameter... I guess this works too.

File: internal/rbd/nodeserver.go [hunk 15]
```diff
@@ -427,32 +427,93 @@ func (ns *NodeServer) stageTransaction(
...
+	var ok bool
+
+	// if its a non encrypted block device we dont need any expansion
+	if isBlock && !transaction.isEncrypted {
+		return nil
+	}
+
+	resizer := mount.NewResizeFs(utilexec.New())
+
+	if transaction.isEncrypted {
```
Comment (nixpanic) [inline internal/rbd/nodeserver.go:465]: a helper like `resizeEncryptedDevice()` might be good to have?

File: e2e/clone.go [hunk 16]
```diff
@@ -0,0 +1,84 @@
+package e2e
```
Comment (nixpanic) [inline e2e/clone.go:17]: probably should add a copyright/license header?

File: internal/rbd/rbd_util.go [hunk 17]
```diff
@@ -127,6 +127,12 @@ type rbdImage struct {
 	RequestName string
 	NamePrefix  string
 
+	// ParentName represents the parent image name of the image.
+	ParentName string
+	// Parent Pool is the pool that contains the parent image.
+	ParentPool      string
+	ImageFeatureSet librbd.FeatureSet
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go:134]: why export `ImageFeatureSet`?

File: internal/rbd/rbd_util.go (hunk 14 above)
Comment (Madhu-1) [reply internal/rbd/rbd_util.go:1716]: instead of passing one more input using struct fields internally

Comment (Madhu-1) [reply internal/rbd/rbd_util.go:1716]: instead of passing one more input using struct fields internally

File: e2e/clone.go (hunk 16 above)
Comment (Madhu-1) [reply e2e/clone.go:17]: we dont have copyright/license for the e2e tests

File: internal/rbd/rbd_util.go (hunk 17 above)
Comment (Madhu-1) [reply internal/rbd/rbd_util.go:134]: without this one, the golint was failing and most of the members of rbdImage are exported and it's for a reason?

File: e2e/rbd.go [hunk 18]
```diff
@@ -3338,6 +3340,199 @@ var _ = Describe("RBD", func() {
...
+						rawAppPath,
+						snapshotPath,
+						pvcBlockRestorePath,
+						appBlockRestorePath)
+					if err != nil {
+						e2elog.Failf("failed to validate restore bigger size clone: %v", err)
+					}
+				})
+
+				By("restore snapshot to bigger size encrypted PVC with VaultKMS", func() {
```
Comment (humblec) [inline e2e/rbd.go:3407]: `s/VaultKMS/Vault KMS` .

File: examples/rbd/pod-block-restore.yaml [hunk 19]
```diff
@@ -0,0 +1,17 @@
+---
```
Comment (humblec) [inline examples/rbd/pod-block-restore.yaml:1]: instead of adding new yaml here, can we stick or use exisitng one `pod-with-raw-block-volume` ?

File: examples/rbd/pvc-block-restore.yaml [hunk 20]
```diff
@@ -0,0 +1,17 @@
+---
```
Comment (humblec) [inline examples/rbd/pvc-block-restore.yaml:1]: same case here `rbd-pvc-restore`

File: e2e/clone.go (hunk 16 above)
Comment (nixpanic) [reply e2e/clone.go:17]: but we should?

File: internal/rbd/rbd_util.go (hunk 17 above)
Comment (nixpanic) [reply internal/rbd/rbd_util.go:134]: I hope that in the future we do not need to have the members exported, as that invites to not have a nice `rbdImage` API. It is fine for now.

**Review by nixpanic — DISMISSED** [review]
No real concerns. It would be good to have the copyright/licence header in new e2e files, but that is not a blocker.

File: e2e/clone.go (hunk 16 above)
Comment (Madhu-1) [reply e2e/clone.go:17]: will add to all the e2e files in follow-up.

**Comment by Madhu-1** [comment]
@nixpanic added Copyright for all files inside the e2e folder.

**Comment by Madhu-1** [comment]
@humblec PTAL there  is a requested change from you

**Comment by humblec** [comment]
Adding 3.5 milestone here for the tracker.

**Comment by humblec** [comment]
mostly looks good.. few minor comments.

File: examples/rbd/pvc-block-restore.yaml (hunk 20 above)
Comment (Madhu-1) [reply examples/rbd/pvc-block-restore.yaml:1]: rbd-pvc-restore is a filesystem PVC this is for BlockPVC

File: examples/rbd/pod-block-restore.yaml (hunk 19 above)
Comment (Madhu-1) [reply examples/rbd/pod-block-restore.yaml:1]: as new PVC is added keeping a different pod name

File: e2e/rbd.go (hunk 18 above)
Comment (Madhu-1) [reply e2e/rbd.go:3407]: this is a copy-paste from `By("create a PVC and bind it to an app with encrypted RBD volume with VaultKMS", func() {`

Comment (Madhu-1) [reply e2e/rbd.go:3407]: `By("Validate PVC restore from vaultKMS to vaultTenantSAKMS", func() {`

Comment (humblec) [reply e2e/rbd.go:3407]: ok.. then we can keep the same format

File: examples/rbd/pod-block-restore.yaml (hunk 19 above)
Comment (humblec) [reply examples/rbd/pod-block-restore.yaml:1]: yeah, thats what I was trying to avoid. As no changes in the PVC yamls. so I am checkign why we need new PVC and POD. Cant we use existing ones?

File: examples/rbd/pvc-block-restore.yaml (hunk 20 above)
Comment (humblec) [reply examples/rbd/pvc-block-restore.yaml:1]: it was a typo-- , I mean we have existing FS mode and Block Mode PVC yamls which can be reused..

Comment (Madhu-1) [reply examples/rbd/pvc-block-restore.yaml:1]: there is no existing block PVC restore.

File: examples/rbd/pod-block-restore.yaml (hunk 19 above)
Comment (Madhu-1) [reply examples/rbd/pod-block-restore.yaml:1]: not possible as we don't have the existing yamls in place, i don't see it as a major concern/blocker for this one

**Comment by Madhu-1** [comment]
@humblec PTAL

**Comment by humblec** [comment]
As discussed this looks good to me .. thanks . :+1:

**Review by humblec — APPROVED** [review]

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Review by Yuggupta27 — APPROVED** [review]

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
@mergifyio rebase
