### PR TITLE
cephfs: handle cephfs clone limit error

### LINKED ISSUE #3996: Add support for cephfs clone limit error
# Describe the bug #

We need to check for error when cphfs clones are rejected due to cloner threads being busy
and handle this error by sending appropriate CSI compliant error code to the external provisioner.

https://tracker.ceph.com/issues/59714

# Steps to reproduce #

1. Create many cephfs clones (or snapshot+restore) of a PVC with data in it.

# Actual results #

Most of the clones/restores will stay in pending for a long time.

# Expected behavior #

Ceph should reject clone creation requests when cloner threads are full with an error and CephCSI should handle this error by sending **appropriate CSI compliant error code** to the external provisioner.

### PR DESCRIPTION
**Pull request by karthik-us**
This is to pre-emptively add check for EAGAIN error returned from ceph as part of https://github.com/ceph/ceph/pull/52670 if all the clone threads are busy and return csi compatible error.

Fixes: #3996

### CODE REVIEW

**Comment by karthik-us** [comment]
@Rakshith-R @yati1998 @nixpanic PTAL.

**Comment by riya-singhal31** [comment]
Can we add e2e test for this?

**Comment by karthik-us** [comment]
> Can we add e2e test for this?

The ceph PR is still not merged under main or any release branch. I don't think we can test it with an e2e at the moment.

**Review by riya-singhal31 — DISMISSED** [review]
LGTM

**Review by yati1998 — COMMENTED** [review]
LGTM, but leaving the approval for Niels or Rakshith .

File: internal/cephfs/controllerserver.go [hunk 1]
```diff
@@ -134,6 +135,9 @@ func (cs *ControllerServer) createBackingVolumeFromSnapshotSource(
 	})
 	if err != nil {
 		log.ErrorLog(ctx, "failed to create clone from snapshot %s: %v", sID.FsSnapshotName, err)
+		if errors.Is(err, syscall.EAGAIN) {
```
Comment (nixpanic) [inline internal/cephfs/controllerserver.go:140]: Checking for the syscall error is not very clean, and is potentially not correct. It would be much better to check for a valid go-ceph error.

Can you explain how you verified that checking against `syscall.EAGAIN` is correct?

Comment (karthik-us) [reply internal/cephfs/controllerserver.go:140]: Currently go-ceph doesn't have a compatible error code for EAGAIN to check for. Since we get EAGAIN from ceph with the proposed change and that will be formated by go-ceph and sent back to csi, checking it against `syscall.EAGAIN` should work for the time being.

I will add a `TODO` note for implementing EAGAIN error handle in go-ceph and use that once available.

**Review by nixpanic — APPROVED** [review]

**Review by yati1998 — APPROVED** [review]

**Review by riya-singhal31 — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio queue

**Comment by Rakshith-R** [comment]
@Mergifyio rebase

**Comment by Rakshith-R** [comment]
@Mergifyio queue
