### PR TITLE
Remove metadata from snapshot/clone/parent RBD image

### LINKED ISSUE #2970: Remove metadata from clones
# Describe the bug #

This is in continuation with https://github.com/ceph/ceph-csi/pull/2898

During RBD clone operation all the clones will get the metadata from the parent we need to unset/remove the metadata in the below cases

During CreateSnapshot ->Unset the PVC metadata on the rbd image created for the snapshot
During CreateVolume From snapshot -> Unset the snapshot metadata from the rbd image created from the snapshot
During CreateVolume From Volume -> Unset the parent PVC metadata on the temp clone rbd image.

### PR DESCRIPTION
**Pull request by pkalever**
# Describe what this PR does #

Remove metadata on images for various scenarios:
* Unset the PVC metadata on the rbd image created for the snapshot
* Unset the snapshot metadata from the rbd image created from the snapshot
* Unset the parent PVC metadata on the temp clone rbd image
* Also add various testcases to validate unset of metadata
## Related issues ##

Fixes: #2970

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

File: internal/rbd/rbd_util.go [hunk 1]
```diff
@@ -1934,6 +1934,24 @@ func (rv *rbdVolume) setVolumeMetadata(parameters map[string]string) error {
 	return nil
 }
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go:1926]: this commit has _untility_ in the title :thinking:

File: internal/rbd/rbd_util.go [hunk 2]
```diff
@@ -1934,6 +1934,24 @@ func (rv *rbdVolume) setVolumeMetadata(parameters map[string]string) error {
...
 
+// unsetVolumeMetadata unset PV/PVC/PVCNamespace metadata on RBD image.
+func (rv *rbdVolume) unsetVolumeMetadata() error {
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go]: in order to keep aligned with the parameters passed to `setVolumeMetadata()`, it would be better to pass a `[]string` with the keys instead of fetching them inside the function

File: internal/rbd/rbd_util.go [hunk 3]
```diff
@@ -1946,3 +1964,22 @@ func (rv *rbdVolume) setSnapshotMetadata(parameters map[string]string) error {
 
 	return nil
 }
+
+// unsetSnapshotMetadata unset snapshot-name/snapshot-namespace/snapshotcontent-name metadata
+// on RBD image.
+func (rv *rbdVolume) unsetSnapshotMetadata() error {
+	for _, key := range k8s.GetSnaoshotMetadataKeys() {
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go]: `GetSnaoshotMetadataKeys`, _Snaoshot_?

File: internal/rbd/rbd_util.go [hunk 4]
```diff
@@ -1946,3 +1964,22 @@ func (rv *rbdVolume) setSnapshotMetadata(parameters map[string]string) error {
 
 	return nil
 }
+
+// unsetSnapshotMetadata unset snapshot-name/snapshot-namespace/snapshotcontent-name metadata
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go]: you probably do not need this function if you pass the keys as a `[]string`. It is the same as `unsetVolumeMetadata()`?

File: internal/util/k8s/parameters.go [hunk 5]
```diff
@@ -100,3 +109,12 @@ func GetSnapshotMetadata(parameters map[string]string) map[string]string {
 
 	return newParam
 }
+
+// GetSnapshotMetadataKeys return snapshot metadata keys.
+func GetSnaoshotMetadataKeys() []string {
```
Comment (nixpanic) [inline internal/util/k8s/parameters.go]: _Snaoshot_

File: e2e/rbd.go [hunk 6]
```diff
@@ -675,6 +676,36 @@ var _ = Describe("RBD", func() {
 					e2elog.Failf("expected volSnapContentName %q got %q", content.Name, volSnapContentName)
 				}
 
+				// make sure we had unset the PVC metadata on the rbd image created
+				// for the snapshot
+				pvcName, stdErr, err := execCommandInToolBoxPod(f,
+					fmt.Sprintf("rbd image-meta get %s --image=%s %s",
+						rbdOptions(defaultRBDPool), imageList[0], pvcNameKey),
+					rookNamespace)
+				if err == nil || !strings.Contains(err.Error(), "command terminated with exit code 2") ||
```
Comment (nixpanic) [inline e2e/rbd.go]: this is a very long if-check, maybe use a helper function as it is repeated often?

**Review by nixpanic — CHANGES_REQUESTED** [review]

File: internal/rbd/rbd_util.go (hunk 2 above)
Comment (pkalever) [reply internal/rbd/rbd_util.go]: That would be an unnecessary duplication of  `k8s.GetVolumeMetadataKeys()` everywhere. I would rather prefer it to be in one place.

File: internal/rbd/rbd_util.go (hunk 4 above)
Comment (pkalever) [reply internal/rbd/rbd_util.go]: Yeah, let's have unsetSnapshotMetadata like unsetVolumeMetadata separately, this will avoid certain confusion too.

**Review by pkalever — COMMENTED** [review]
Thanks for the review @nixpanic :-)

File: e2e/rbd.go [hunk 7]
```diff
@@ -675,6 +685,33 @@ var _ = Describe("RBD", func() {
...
+				}
+				pvName, stdErr, err := execCommandInToolBoxPod(f,
+					fmt.Sprintf("rbd image-meta get %s --image=%s %s",
+						rbdOptions(defaultRBDPool), imageList[0], pvNameKey),
+					rookNamespace)
+				if isKeyExist(err, stdErr) {
+					e2elog.Failf("PV name found on %s/%s %s=%s: err=%v stdErr=%q",
+						rbdOptions(defaultRBDPool), imageList[0], pvNameKey, pvName, err, stdErr)
+				}
+
```
Comment (Madhu-1) [inline e2e/rbd.go]: Do list of metadata with `rbd image-meta ls` and check anything related to PVC is present.

File: e2e/rbd.go [hunk 8]
```diff
@@ -686,6 +723,251 @@ var _ = Describe("RBD", func() {
...
+				}
+				volSnapContentName, stdErr, err := execCommandInToolBoxPod(f,
+					fmt.Sprintf("rbd image-meta get %s --image=%s %s",
+						rbdOptions(defaultRBDPool), imageList[0], volSnapContentNameKey),
+					rookNamespace)
+				if isKeyExist(err, stdErr) {
+					e2elog.Failf("found snapshotcontent name %s/%s %s=%s: err=%v stdErr=%q",
+						rbdOptions(defaultRBDPool), imageList[0], volSnapContentNameKey,
+						volSnapContentName, err, stdErr)
+				}
```
Comment (Madhu-1) [inline e2e/rbd.go]: use `ls` to list the metadata and check anything related to snapshot exists.

File: e2e/rbd.go [hunk 9]
```diff
@@ -686,6 +723,251 @@ var _ = Describe("RBD", func() {
 				validateRBDImageCount(f, 0, defaultRBDPool)
 			})
 
+			By("verify that we unset snapshot metadata on CreateVolume from snapshot", func() {
+				const (
```
Comment (Madhu-1) [inline e2e/rbd.go]: instead of adding a  new test please extend the existing test for the below 2 reasons
* As adding new tests for this one increases the test timings in the CI.
* This needs to be verified along with the CreateVolumeSnapshot test we don't need to have a separate test to validate the snapshot metadata.

File: e2e/rbd.go [hunk 10]
```diff
@@ -686,6 +723,251 @@ var _ = Describe("RBD", func() {
...
+						volSnapContentName, err, stdErr)
+				}
+
+				err = deletePVCAndApp("", f, pvcClone, appClone)
+				if err != nil {
+					e2elog.Failf("failed to delete pvc and application: %v", err)
+				}
+			})
+
+			By("verify that we unset parent PVC metadata on temp clone image", func() {
```
Comment (Madhu-1) [inline e2e/rbd.go]: instead of adding a new test please extend the existing test for the below 2 reasons

* As adding new tests for this one increases the test timings in the CI.
* This needs to be verified along with the CreateVolume test we don't need to have a separate test to validate the older metadata.

File: internal/rbd/clone.go [hunk 11]
```diff
@@ -190,6 +190,12 @@ func (rv *rbdVolume) doSnapClone(ctx context.Context, parentVol *rbdVolume) erro
 	if err != nil {
 		return err
 	}
+	err = tempClone.unsetVolumeMetadata()
+	if err != nil {
+		log.ErrorLog(ctx, "failed to unset volume metadata on temp clone: %v", err)
```
Comment (Madhu-1) [inline internal/rbd/clone.go]: log image name.

File: internal/rbd/clone.go [hunk 12]
```diff
@@ -190,6 +190,12 @@ func (rv *rbdVolume) doSnapClone(ctx context.Context, parentVol *rbdVolume) erro
 	if err != nil {
 		return err
 	}
+	err = tempClone.unsetVolumeMetadata()
```
Comment (Madhu-1) [inline internal/rbd/clone.go]: the tempClone should contain the metadata same as the image it's created for.

File: internal/rbd/controllerserver.go [hunk 13]
```diff
@@ -588,6 +588,12 @@ func (cs *ControllerServer) createVolumeFromSnapshot(
 
 		return err
 	}
+	err = rbdVol.unsetSnapshotMetadata()
+	if err != nil {
+		log.ErrorLog(ctx, "failed to unset snapshot metadata on rbd image: %v", err)
```
Comment (Madhu-1) [inline internal/rbd/controllerserver.go]: log rbdVol details

File: internal/rbd/rbd_util.go [hunk 14]
```diff
@@ -1934,6 +1934,24 @@ func (rv *rbdVolume) setVolumeMetadata(parameters map[string]string) error {
...
 
+// unsetVolumeMetadata unset PV/PVC/PVCNamespace metadata on RBD image.
+func (rv *rbdVolume) unsetVolumeMetadata() error {
+	for _, key := range k8s.GetVolumeMetadataKeys() {
+		value, err := rv.GetMetadata(key)
+		if errors.Is(err, librbd.ErrNotFound) {
+			continue
+		} else if err != nil {
+			return err
+		}
```
Comment (Madhu-1) [inline internal/rbd/rbd_util.go]: instead of getting the keys one by one, do `list` and Compare and remove it.

File: internal/rbd/rbd_util.go [hunk 15]
```diff
@@ -1934,6 +1934,24 @@ func (rv *rbdVolume) setVolumeMetadata(parameters map[string]string) error {
...
+		err = rv.RemoveMetadata(key)
+		if err != nil {
+			return fmt.Errorf("failed to unset metadata key %q, value %q on image: %w", key, value, err)
```
Comment (Madhu-1) [inline internal/rbd/rbd_util.go]: log rv vol details

File: internal/rbd/rbd_util.go [hunk 16]
```diff
@@ -1946,3 +1964,22 @@ func (rv *rbdVolume) setSnapshotMetadata(parameters map[string]string) error {
...
 }
+
+// unsetSnapshotMetadata unset snapshot-name/snapshot-namespace/snapshotcontent-name metadata
+// on RBD image.
+func (rv *rbdVolume) unsetSnapshotMetadata() error {
+	for _, key := range k8s.GetSnapshotMetadataKeys() {
+		value, err := rv.GetMetadata(key)
+		if errors.Is(err, librbd.ErrNotFound) {
+			continue
+		} else if err != nil {
```
Comment (Madhu-1) [inline internal/rbd/rbd_util.go]: instead of getting the keys one by one, do list and Compare and remove it.

File: internal/rbd/rbd_util.go [hunk 17]
```diff
@@ -1946,3 +1964,22 @@ func (rv *rbdVolume) setSnapshotMetadata(parameters map[string]string) error {
...
+			return err
+		}
+		err = rv.RemoveMetadata(key)
+		if err != nil {
+			return fmt.Errorf("failed to unset metadata key %q, value %q on image: %w", key, value, err)
```
Comment (Madhu-1) [inline internal/rbd/rbd_util.go]: log image details

**Review by Madhu-1 — CHANGES_REQUESTED** [review]

File: internal/rbd/clone.go (hunk 12 above)
Comment (pkalever) [reply internal/rbd/clone.go]: As discussed, let's do this on a need basis.

File: e2e/rbd.go (hunk 7 above)
Comment (pkalever) [reply e2e/rbd.go]: List will dump all the metadata at once
```
sh-4.4$ rbd image-meta list replicapool/csi-vol-29bf8a0a-ba45-11ec-bd09-fa9af733450f
There are 3 metadata on this image:

Key                               Value                                   
csi.storage.k8s.io/pv/name        pvc-890cb9a5-a5f8-42d9-825b-de780377c6ab
csi.storage.k8s.io/pvc/name       rbd-pvc                                 
csi.storage.k8s.io/pvc/namespace  default                                 

```

String.contains("csi.storage.k8s.io/pvc/name", "csi.storage.k8s.io/pvc/namespace  default")
Might return success. All I'm saying is, let's not take that chance.

@Madhu-1 WDYT?

Comment (Madhu-1) [reply e2e/rbd.go]: IMO Instead of getting separately multiple times, the listing is easy, list once and check it.

File: internal/rbd/rbd_util.go (hunk 2 above)
Comment (nixpanic) [reply internal/rbd/rbd_util.go]: it is out of balance with `setVolumeMetadata()`, so I prefer that you pass the keys. Possibly other metadata gets added later on, which does not get retrieved from the k8s API.

File: internal/rbd/rbd_util.go [hunk 18]
```diff
@@ -1934,6 +1946,29 @@ func (rv *rbdVolume) setVolumeMetadata(parameters map[string]string) error {
...
+// unsetVolumeMetadata unset PV/PVC/PVCNamespace metadata on RBD image.
+func (rv *rbdVolume) unsetVolumeMetadata() error {
+	list, err := rv.ListMetadata()
+	if err != nil {
+		return fmt.Errorf("failed to list metadata image %s/%s: %w", rv.Pool, rv.RbdImageName, err)
+	}
+
+	for k, v := range list {
+		for _, key := range k8s.GetVolumeMetadataKeys() {
+			if strings.Compare(k, key) != 0 {
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go]: why `strings.Compare` and not just `k == key`?

File: internal/rbd/rbd_util.go (hunk 4 above)
Comment (nixpanic) [reply internal/rbd/rbd_util.go]: the function is almost completely duplicated, if there really is a need for separate functions (hint: there probably is not), use a helper to improve maintainability.

File: internal/rbd/rbd_util.go (hunk 2 above)
Comment (pkalever) [reply internal/rbd/rbd_util.go]: I don't know how it becomes out of balance with `setVolumeMetadata()`, both the function are getting the keys with in the function. And in the future if the other metadata gets added later on it applies to `setVolumeMetadata()` too. So I would still let it just be it for now.

File: internal/rbd/rbd_util.go (hunk 18 above)
Comment (pkalever) [reply internal/rbd/rbd_util.go]: I was over thinking may be :-)

File: internal/rbd/rbd_util.go (hunk 4 above)
Comment (pkalever) [reply internal/rbd/rbd_util.go]: In addition to my previous comment,
Calling unsetVolumeMetadata() for Snapshot metadata looks a bit awkward to me, CodeReadabilty++

Comment (nixpanic) [reply internal/rbd/rbd_util.go]: just rename the function to `SetMetadataList(data map[string]string)` and `UnsetMetadataList(keys []string)`? The object for both Snapshot and Volume are `rbdVolume`, so no need to have Volume or Snapshot in the function names. CodeReadabilty++ and CodeMaintainability++

**Comment by pkalever** [comment]
@Mergifyio rebase

**Comment by pkalever** [comment]
@Mergifyio rebase

**Comment by pkalever** [comment]
@Mergifyio rebase

File: internal/rbd/rbd_util.go (hunk 2 above)
Comment (nixpanic) [reply internal/rbd/rbd_util.go]: Indeed! additional metadata should be passed as an argument to `setVolumeMetadata()`, so the caller of `unsetVolumeMetadata()` should have that as well. The `rbdVolume` functions are an API for external callers, and there should not be a dependency on hard-coded metadata keys that are not internal to the `rbdVolume`.

File: internal/rbd/rbd_util.go (hunk 4 above)
Comment (pkalever) [reply internal/rbd/rbd_util.go]: @nixpanic Done now, PTAL

File: internal/rbd/rbd_util.go (hunk 2 above)
Comment (pkalever) [reply internal/rbd/rbd_util.go]: @nixpanic Done now, PTAL

**Comment by pkalever** [comment]
@Madhu-1 @nixpanic @ceph/ceph-csi-contributors please review this changes. Thanks!

**Review by yati1998 — COMMENTED** [review]
LGTM, reserving merge rights for others.

File: internal/rbd/rbd_util.go [hunk 19]
```diff
@@ -1932,3 +1944,26 @@ func (rv *rbdVolume) setAllMetadata(parameters map[string]string) error {
...
+
+	for k, v := range list {
+		for _, key := range keys {
+			if k != key {
+				continue
+			}
+			err = rv.RemoveMetadata(key)
+			if err != nil && !strings.Contains(err.Error(), "No such file or directory") {
+				return fmt.Errorf("failed to unset metadata key %q, value %q on image %s/%s: %w",
+					k, v, rv.Pool, rv.RbdImageName, err)
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go]: just pass `rv` in `%q` as that will return a string with pool/namespace/imagename

File: e2e/rbd.go [hunk 20]
```diff
@@ -191,6 +191,15 @@ func validateRBDImageCount(f *framework.Framework, count int, pool string) {
 	}
 }
 
+func isKeyExist(err error, stdErr string) bool {
```
Comment (nixpanic) [inline e2e/rbd.go]: I do not get what this function does... the name does not describe the contents?

File: e2e/rbd.go [hunk 21]
```diff
@@ -652,6 +661,33 @@ var _ = Describe("RBD", func() {
 					e2elog.Failf("expected volSnapContentName %q got %q", content.Name, volSnapContentName)
 				}
 
+				// make sure we had unset the PVC metadata on the rbd image created
+				// for the snapshot
+				pvcName, stdErr, err := execCommandInToolBoxPod(f,
+					fmt.Sprintf("rbd image-meta get %s --image=%s %s",
```
Comment (nixpanic) [inline e2e/rbd.go:671]: please use a helper function for `rbd image-meta get ....`

**Review by nixpanic — CHANGES_REQUESTED** [review]
just a few nits, looks good otherwise

**Comment by pkalever** [comment]
@nixpanic addressed your review comments now, PTAL. Thanks!

**Comment by pkalever** [comment]
@Mergifyio rebase

File: internal/rbd/clone.go [hunk 22]
```diff
@@ -190,6 +191,13 @@ func (rv *rbdVolume) doSnapClone(ctx context.Context, parentVol *rbdVolume) erro
 	if err != nil {
 		return err
 	}
+	err = tempClone.unsetAllMetadata(k8s.GetSnapshotMetadataKeys())
+	if err != nil {
+		log.ErrorLog(ctx, "failed to unset volume metadata on temp clone image %s/%s: %v",
```
Comment (Madhu-1) [inline internal/rbd/clone.go]:
```suggestion
log.ErrorLog(ctx, "failed to unset volume metadata on temp clone image %s %v",
			tempClone, err)
```
tempClone already implements String interface,

File: internal/rbd/controllerserver.go [hunk 23]
```diff
@@ -588,6 +590,13 @@ func (cs *ControllerServer) createVolumeFromSnapshot(
 
 		return err
 	}
+	err = rbdVol.unsetAllMetadata(k8s.GetSnapshotMetadataKeys())
+	if err != nil {
+		log.ErrorLog(ctx, "failed to unset snapshot metadata on rbd image %s/%s: %v",
```
Comment (Madhu-1) [inline internal/rbd/controllerserver.go]: same here as well.

File: internal/rbd/controllerserver.go [hunk 24]
```diff
@@ -963,7 +972,7 @@ func (cs *ControllerServer) ValidateVolumeCapabilities(
 }
 
 // CreateSnapshot creates the snapshot in backend and stores metadata in store.
-// nolint:cyclop // TODO: reduce complexity
+// nolint:gocyclo,cyclop // TODO: reduce complexity.
```
Comment (Madhu-1) [inline internal/rbd/controllerserver.go:980]: adding nolint is not helpful we will forget about it once PR is merged and no use of having linter checks in CI isn't it?

File: internal/rbd/rbd_util.go [hunk 25]
```diff
@@ -1934,13 +1945,22 @@ func (rv *rbdVolume) setVolumeMetadata(parameters map[string]string) error {
...
+
+	for k, v := range list {
+		for _, key := range keys {
+			if k != key {
+				continue
+			}
+			err = rv.RemoveMetadata(key)
+			if err != nil && !strings.Contains(err.Error(), "No such file or directory") {
+				return fmt.Errorf("failed to unset metadata key %q, value %q on %q: %w", k, v, rv, err)
+			}
```
Comment (Madhu-1) [inline internal/rbd/rbd_util.go]: To unset why we need to list and remove it? just do RemoveMetadata and ignore not/no found error?

File: internal/rbd/controllerserver.go (hunk 24 above)
Comment (pkalever) [reply internal/rbd/controllerserver.go:980]: This function is already complex and at its best-simplified level. You can see it already has `cyclop`.
Excuses apart, we should consider scrubbing such complex functions sometimes.

**Comment by pkalever** [comment]
@Mergify rebase

**Comment by pkalever** [comment]
@Madhu-1 @nixpanic PTAL

File: internal/rbd/rbd_util.go [hunk 26]
```diff
@@ -1934,13 +1945,12 @@ func (rv *rbdVolume) setVolumeMetadata(parameters map[string]string) error {
...
-	for k, v := range k8s.GetSnapshotMetadata(parameters) {
-		err := rv.SetMetadata(k, v)
-		if err != nil {
-			return fmt.Errorf("failed to set metadata key %q, value %q on image: %w", k, v, err)
+// unsetAllMetadata unset all the metadata from arg keys on RBD image.
+func (rv *rbdVolume) unsetAllMetadata(keys []string) error {
+	for _, key := range keys {
+		err := rv.RemoveMetadata(key)
+		if err != nil && !strings.Contains(err.Error(), "No such file or directory") {
+			return fmt.Errorf("failed to unset metadata key %q on %q: %w", key, rv, err)
```
Comment (Madhu-1) [inline internal/rbd/rbd_util.go:1933]:
```suggestion
if err != nil && !errors.Is(err, rados.ErrNotFound) {
return fmt.Errorf("failed to unset metadata key %q on %q: %w", key, rv, err)
}
```

can we do like this?

**Review by Madhu-1 — COMMENTED** [review]
small suggestion on error handling

**Comment by pkalever** [comment]
@Madhu-1 @nixpanic PTAL

File: internal/rbd/clone.go [hunk 27]
```diff
@@ -188,6 +189,12 @@ func (rv *rbdVolume) doSnapClone(ctx context.Context, parentVol *rbdVolume) erro
 	if err != nil {
 		return err
 	}
+	err = tempClone.unsetAllMetadata(k8s.GetSnapshotMetadataKeys())
```
Comment (Madhu-1) [inline internal/rbd/clone.go]: you should be resetting the parent volume metadata here isn't it? or its snapshot metadata as its done here

File: internal/rbd/rbd_util.go [hunk 28]
```diff
@@ -1675,6 +1674,18 @@ func (ri *rbdImage) RemoveMetadata(key string) error {
 	return image.RemoveMetadata(key)
 }
 
+// ListMetadata returns a map containing all metadata assigned to the RBD
+// image.
+func (ri *rbdImage) ListMetadata() (map[string]string, error) {
```
Comment (Madhu-1) [inline internal/rbd/rbd_util.go]: is it used anywhere? if not please consider removing it.

File: internal/rbd/clone.go (hunk 27 above)
Comment (pkalever) [reply internal/rbd/clone.go]: YEs, good catch. Looks like it got messed up over various revisions of the patch sets. Thanks!

File: internal/rbd/rbd_util.go (hunk 28 above)
Comment (pkalever) [reply internal/rbd/rbd_util.go]: Sure! I just kept it reserving for future :-)

File: internal/rbd/clone.go [hunk 29]
```diff
@@ -188,6 +189,12 @@ func (rv *rbdVolume) doSnapClone(ctx context.Context, parentVol *rbdVolume) erro
 	if err != nil {
 		return err
 	}
+	err = tempClone.unsetAllMetadata(k8s.GetVolumeMetadataKeys())
```
Comment (Madhu-1) [inline internal/rbd/clone.go]: we should unset metadata at line 215 as if the `unsetAllMetadata` fails the tempClone need to be removed.

Comment (pkalever) [reply internal/rbd/clone.go]: ok

File: internal/rbd/controllerserver.go [hunk 30]
```diff
@@ -589,6 +591,12 @@ func (cs *ControllerServer) createVolumeFromSnapshot(
 
 		return err
 	}
+	err = rbdVol.unsetAllMetadata(k8s.GetSnapshotMetadataKeys())
```
Comment (Madhu-1) [inline internal/rbd/controllerserver.go:594]: not related to this PR I see a cleanup bug here. if the unsetAllMetadata or copyEncryptionConfig or expand fails we need to remove the clone. can you please open an issue for this one?

File: internal/rbd/controllerserver.go [hunk 31]
```diff
@@ -1072,9 +1080,14 @@ func (cs *ControllerServer) CreateSnapshot(
 	// Update the metadata on snapshot not on the original image
 	rbdVol.RbdImageName = rbdSnap.RbdSnapName
 
+	err = rbdVol.unsetAllMetadata(k8s.GetVolumeMetadataKeys())
```
Comment (Madhu-1) [inline internal/rbd/controllerserver.go:1083]: same here as well.

**Review by Madhu-1 — DISMISSED** [review]

File: internal/rbd/controllerserver.go (hunk 30 above)
Comment (pkalever) [reply internal/rbd/controllerserver.go:594]: Sure Madhu

Comment (pkalever) [reply internal/rbd/controllerserver.go:594]: https://github.com/ceph/ceph-csi/issues/3103

File: internal/rbd/controllerserver.go (hunk 31 above)
Comment (pkalever) [reply internal/rbd/controllerserver.go:1083]: https://github.com/ceph/ceph-csi/issues/3103

File: e2e/rbd.go [hunk 32]
```diff
@@ -191,6 +191,21 @@ func validateRBDImageCount(f *framework.Framework, count int, pool string) {
 	}
 }
 
+func formatImageMetaGetCmd(pool, image, key string) string {
+	return fmt.Sprintf("rbd image-meta get %s --image=%s %s", rbdOptions(pool), image, key)
+}
+
+// checkKeyError check for error conditions returned by get image-meta key,
```
Comment (yati1998) [inline e2e/rbd.go]: checkKeyError -> checkGetKeyError

**Review by yati1998 — DISMISSED** [review]
Just a small nit, else looks good to me.

File: e2e/rbd.go (hunk 32 above)
Comment (pkalever) [reply e2e/rbd.go]: Done now, thanks!

**Comment by pkalever** [comment]
@Mergifyio rebase

**Review by Madhu-1 — DISMISSED** [review]

**Review by nixpanic — DISMISSED** [review]

**Comment by nixpanic** [comment]
This can be rebased with Mergify, just have CI finish testing and merging other PRs.

**Comment by nixpanic** [comment]
@mergifyio rebase

File: internal/rbd/rbd_util.go (hunk 26 above)
Comment (pkalever) [reply internal/rbd/rbd_util.go:1933]: @Madhu-1 This is what I'm talking about in the call, can I revert this?
rbd upgrade test is failing with:
```
May 10 13:01:46.985: INFO: At 2022-05-10 12:51:48 +0100 BST - event for rbd-pvc-restore: {rbd.csi.ceph.com_csi-rbdplugin-provisioner-57c4f55c9c-thjpc_96186737-0ddd-4b5f-bef5-2df83e7ac0d1 } ProvisioningFailed: failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = Unknown desc = failed to unset metadata key "csi.storage.k8s.io/volumesnapshot/name" on "replicapool/csi-vol-92685dd1-d057-11ec-83c4-862ba5925cfb": rbd: ret=-2, No such file or directory
```

**Comment by pkalever** [comment]
Diff:
V3: https://github.com/ceph/ceph-csi/pull/3005#discussion_r866707138 is not working, so replaced errno with string comparison for now. Added a TODO, will address in future PRs

**Comment by pkalever** [comment]
/retest ci/centos/mini-e2e-helm/k8s-1.21
/retest ci/centos/mini-e2e-helm/k8s-1.23
```
May 11 10:33:45.243: FAIL: backend images not matching kubernetes resource count,image count 23 kubernetes resource count 21
```

**Review by Madhu-1 — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
> /retest all

It seems the CI jobs got stuck somehow. This PR is the 1st in the queue to be merged, hopefully things pass quickly.

**Comment by nixpanic** [comment]
@mergifyio unqueue

#3070 has passed CI, and should be able to get merged immediately. Let's try the new `dequeue` command

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio requeue

The other PR got merged, so this one is next now. Restarted CI jobs after rebasing.

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.23

Failed with:
```
    May 12 09:46:29.815: backend images not matching kubernetes resource count,image count 23 kubernetes resource count 21
```

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.23

Failed with:
```
May 12 10:50:53.103: FAIL: backend images not matching kubernetes resource count,image count 12 kubernetes resource count 11
```

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.23

Failed with:
```
May 12 12:14:55.114: FAIL: backend images not matching kubernetes resource count,image count 22 kubernetes resource count 21
```
