### PR TITLE
rbd: fix encrypted PVC with metadata KMS cannot be deleted

### LINKED ISSUE #5148: rbd: Encrypted PVC with Metadata KMS cannot be deleted
# Describe the bug #

Creating an encrypted Persistent Volume Claim with reclaim policy Retain, the Persistent Volume cannot be deleted after the Namespace with the corresponding secret of the encrypted volume was deleted.

```
I0216 12:40:22.228097       1 utils.go:266] ID: 42 Req-ID: 0001-0024-5e325bdb-0833-4d54-8d90-0bc07f43a580-0000000000000007-797f904b-8c83-4ab6-983d-c93d0500a7ca GRPC call: /csi.v1.Controller/DeleteVolume
I0216 12:40:22.228156       1 utils.go:267] ID: 42 Req-ID: 0001-0024-5e325bdb-0833-4d54-8d90-0bc07f43a580-0000000000000007-797f904b-8c83-4ab6-983d-c93d0500a7ca GRPC request: {"secrets":"***stripped***","volume_id":"0001-0024-5e325bdb-0833-4d54-8d90-0bc07f43a580-0000000000000007-797f904b-8c83-4ab6-983d-c93d0500a7ca"}
I0216 12:40:22.235003       1 omap.go:89] ID: 42 Req-ID: 0001-0024-5e325bdb-0833-4d54-8d90-0bc07f43a580-0000000000000007-797f904b-8c83-4ab6-983d-c93d0500a7ca got omap values: (pool="kubernetes", namespace="", name="csi.volume.797f904b-8c83-4ab6-983d-c93d0500a7ca"): map[csi.imageid:3ee7f9c1922985 csi.imagename:csi-vol-797f904b-8c83-4ab6-983d-c93d0500a7ca csi.volname:pvc-72bee4e6-4ffb-4065-98d2-b7fa005c7ea2 csi.volume.encryptKMS:mykms csi.volume.encryptionType:block csi.volume.owner:ceph-csi]
E0216 12:40:22.240139       1 utils.go:271] ID: 42 Req-ID: 0001-0024-5e325bdb-0833-4d54-8d90-0bc07f43a580-0000000000000007-797f904b-8c83-4ab6-983d-c93d0500a7ca GRPC error: rpc error: code = Internal desc = failed to get Secret ceph-csi/tenant-encryption: secrets "tenant-encryption" not found
```

# Environment details #

- Image/version of Ceph CSI driver : 3.13.0

# Steps to reproduce #

1. Install Ceph-CSI RBD with values
```
    encryptionKMSConfig:
      mykms:
        encryptionKMSType: "metadata"
        secretName: "tenant-encryption"
```
3. Create a namespace and a secret named "tenant-encryption" with an an `encryptionPassphrase`
2. Create PVC in this namespace with Storage Class which uses the metadata secrets encryption.
3. Delete the corresponding Secret
4. Try to delete PVC/PV

# Expected behavior #

PV should get deleted

### PR DESCRIPTION
**Pull request by zerotens**
# Describe what this PR does #

Creating an encrypted Persistent Volume Claim with reclaim policy Retain, the Persistent Volume cannot be deleted after the Namespace with the corresponding secret of the encrypted volume was deleted.

```
CSI DeleteVolume Request -> calls GenVolFromVolID -> calls generateVolumeFromVolumeID -> calls rbdVol.configureBlockEncryption which initiates the metadata kms provider
```

This fix moves the logic from the kms class initialization to the method where the encryption key is needed.
As the Delete Volume CSI request does not need or call the `FetchDEK` method, the volume get's deleted successfully.

## Is there anything that requires special attention ##

Do you have any questions?

Is the change backward compatible?

Are there concerns around backward compatibility?

## Related issues ##

Fixes: #5148 

**Checklist:**

* [x] **Commit Message Formatting**: Commit titles and messages follow
  guidelines in the [developer
  guide](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#commit-messages).
* [x] Reviewed the developer guide on [Submitting a Pull
  Request](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#development-workflow)
* [x] [Pending release
  notes](https://github.com/ceph/ceph-csi/blob/devel/PendingReleaseNotes.md)
  updated with breaking and/or notable changes for the next major release.
* [x] Documentation has been updated, if necessary.
* [x] Unit tests have been added, if necessary.
* [x] Integration tests have been added, if necessary.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

* `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)

</details>

### CODE REVIEW

File: internal/kms/secretskms.go [hunk 1]
```diff
@@ -184,7 +165,46 @@ func (kms secretsMetadataKMS) fetchEncryptionPassphrase(
...
+
+	encryptionPassphrase, err = smKMS.fetchEncryptionPassphrase(
+		kms.Config, kms.Tenant)
+	if err != nil {
+		if !errors.Is(err, errConfigOptionMissing) {
+			return "", err
+		}
+		// if 'userSecret' option is not specified, fetch encryptionPassphrase
+		// from storageclass secrets.
+		encryptionPassphrase, ok = kms.Secrets[encryptionPassphraseKey]
```
Comment (Rakshith-R) [inline internal/kms/secretskms.go]:
```suggestion
	encryptionPassphrase, err := kms.fetchEncryptionPassphrase(
		kms.Config, kms.Tenant)
	if err != nil {
		if !errors.Is(err, errConfigOptionMissing) {
			return "", err
		}
		// if 'userSecret' option is not specified, fetch encryptionPassphrase
		// from storageclass secrets.
		encryptionPassphrase, ok := kms.Secrets[encryptionPassphraseKey]
```
that method is already part of struct, I don't think another variable needs to created to call fetchEncryptionPassphrase ?

**Review by Rakshith-R — CHANGES_REQUESTED** [review]
thanks for debugging and fixing the issue !

Just a small nit.

File: internal/kms/secretskms.go (hunk 1 above)
Comment (zerotens) [reply internal/kms/secretskms.go]: Yes, you are right, i removed the local variable `smKMS`.

**Review by Rakshith-R — APPROVED** [review]
Thanks

**Comment by Madhu-1** [comment]
> /test ci/centos/mini-e2e/k8s-1.32

@iPraveenParihar please provide details in a comment about the cause of failure as well, it helps to identify unknown bugs

**Review by iPraveenParihar — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio queue

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e/k8s-1.32

The [logs](https://jenkins-ceph-csi.apps.ocp.cloud.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.32/detail/mini-e2e_k8s-1.32/85/pipeline) of the failure do not immediate show what the issue is, I think:
```
  [1mSTEP:[0m create a PVC and check PVC/PV metadata on RBD image [38;5;243m@ 02/20/25 11:57:08.555[0m
  I0220 11:57:08.558944 86817 pvc.go:60] Waiting up to &PersistentVolumeClaim{ObjectMeta:{rbd-pvc  rbd-1827    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[group:test] map[] [] [] []},Spec:PersistentVolumeClaimSpec{AccessModes:[ReadWriteOnce],Resources:VolumeResourceRequirements{Limits:ResourceList{},Requests:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},},VolumeName:,Selector:nil,StorageClassName:*csi-rbd-sc,VolumeMode:nil,DataSource:nil,DataSourceRef:nil,VolumeAttributesClassName:nil,},Status:PersistentVolumeClaimStatus{Phase:,AccessModes:[],Capacity:ResourceList{},Conditions:[]PersistentVolumeClaimCondition{},AllocatedResources:ResourceList{},AllocatedResourceStatuses:map[ResourceName]ClaimResourceStatus{},CurrentVolumeAttributesClassName:nil,ModifyVolumeStatus:nil,},} to be in Bound state
  I0220 11:57:08.558987 86817 pvc.go:63] waiting for PVC rbd-pvc (0 seconds elapsed)
  I0220 11:57:08.563534 86817 pvc.go:85] PVC rbd-pvc Event: Provisioning - External provisioner is provisioning volume for claim "rbd-1827/rbd-pvc"
  I0220 11:57:08.563572 86817 pvc.go:85] PVC rbd-pvc Event: ExternalProvisioning - Waiting for a volume to be created either by the external provisioner 'rbd.csi.ceph.com' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
  I0220 11:57:08.563799 86817 pvc.go:85] PVC rbd-pvc Event: Provisioning - External provisioner is provisioning volume for claim "rbd-1827/rbd-pvc"
  I0220 11:57:08.563817 86817 pvc.go:85] PVC rbd-pvc Event: ProvisioningSucceeded - Successfully provisioned volume pvc-e4aa7cac-30f1-4f5e-bc5c-af17b8764c9a
  I0220 11:57:08.563825 86817 pvc.go:85] PVC rbd-pvc Event: ExternalProvisioning - Waiting for a volume to be created either by the external provisioner 'rbd.csi.ceph.com' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
  I0220 11:57:08.563833 86817 pvc.go:85] PVC rbd-pvc Event: Provisioning - External provisioner is provisioning volume for claim "rbd-1827/rbd-pvc"
  I0220 11:57:08.563840 86817 pvc.go:85] PVC rbd-pvc Event: ProvisioningSucceeded - Successfully provisioned volume pvc-ca574bf2-9632-49b9-8125-66951fc004c2
  I0220 11:57:10.559694 86817 pvc.go:63] waiting for PVC rbd-pvc (2 seconds elapsed)
  I0220 11:57:10.563681 86817 pv.go:468] Waiting for PV pvc-8a23f93d-d21b-4d11-9485-c7f048ea55fb to bind to PVC rbd-pvc
  I0220 11:57:10.563735 86817 pv.go:790] Waiting up to timeout=10m0s for PersistentVolumeClaims [rbd-pvc] to have phase Bound
  I0220 11:57:10.567465 86817 pv.go:801] PersistentVolumeClaim rbd-pvc found and phase=Bound (3.716004ms)
  I0220 11:57:10.567495 86817 pv.go:763] Waiting up to 10m0s for PersistentVolume pvc-8a23f93d-d21b-4d11-9485-c7f048ea55fb to have phase Bound
  I0220 11:57:10.569559 86817 pv.go:771] PersistentVolume pvc-8a23f93d-d21b-4d11-9485-c7f048ea55fb found and phase=Bound (2.052301ms)
  I0220 11:57:10.574121 86817 exec_util.go:59] ExecWithOptions {Command:[/bin/sh -c rbd ls --format=json --pool=replicapool] Namespace:rook-ceph PodName:rook-ceph-tools-56ff7b659c-lvrcs ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
  I0220 11:57:10.574146 86817 exec_util.go:64] ExecWithOptions: Clientset creation
  I0220 11:57:10.574201 86817 exec_util.go:80] ExecWithOptions: execute(POST https://192.168.49.2:8443/api/v1/namespaces/rook-ceph/pods/rook-ceph-tools-56ff7b659c-lvrcs/exec?command=%2Fbin%2Fsh&command=-c&command=rbd+ls+--format%3Djson+--pool%3Dreplicapool&container=rook-ceph-tools&stderr=true&stdout=true)
  I0220 11:57:10.685176 86817 exec_util.go:59] ExecWithOptions {Command:[/bin/sh -c rados ls --pool=replicapool | grep -v default | grep -v csi.volume.group. |  grep -c ^csi.volume.] Namespace:rook-ceph PodName:rook-ceph-tools-56ff7b659c-lvrcs ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
  I0220 11:57:10.685215 86817 exec_util.go:64] ExecWithOptions: Clientset creation
  I0220 11:57:10.685248 86817 exec_util.go:80] ExecWithOptions: execute(POST https://192.168.49.2:8443/api/v1/namespaces/rook-ceph/pods/rook-ceph-tools-56ff7b659c-lvrcs/exec?command=%2Fbin%2Fsh&command=-c&command=rados+ls+--pool%3Dreplicapool+%7C+grep+-v+default+%7C+grep+-v+csi.volume.group.+%7C++grep+-c+%5Ecsi.volume.&container=rook-ceph-tools&stderr=true&stdout=true)
  I0220 11:57:10.807774 86817 exec_util.go:59] ExecWithOptions {Command:[/bin/sh -c rados ls --pool=replicapool] Namespace:rook-ceph PodName:rook-ceph-tools-56ff7b659c-lvrcs ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
  I0220 11:57:10.807838 86817 exec_util.go:64] ExecWithOptions: Clientset creation
  I0220 11:57:10.807873 86817 exec_util.go:80] ExecWithOptions: execute(POST https://192.168.49.2:8443/api/v1/namespaces/rook-ceph/pods/rook-ceph-tools-56ff7b659c-lvrcs/exec?command=%2Fbin%2Fsh&command=-c&command=rados+ls+--pool%3Dreplicapool&container=rook-ceph-tools&stderr=true&stdout=true)
  I0220 11:57:10.917795 86817 utils.go:251] additional debug info: rados ls command output: rbd_header.13de5595a987
  rbd_directory
  rbd_info
  csi.volume.aec40a24-45ed-4919-97ca-b2c5b00517b5
  rbd_task
  csi.volumes.default
  rbd_trash
  csi.volume.860bd5be-e492-4bd0-b3de-7ce56fa535e1
  rbd_id.csi-vol-aec40a24-45ed-4919-97ca-b2c5b00517b5
  , stdErr: 
  [38;5;9m[FAILED][0m in [It] - /go/src/github.com/ceph/ceph-csi/e2e/utils.go:254 [38;5;243m@ 02/20/25 11:57:10.918[0m
```

**Comment by nixpanic** [comment]
@mergifyio requeue

**Comment by Madhu-1** [comment]
> > /retest ci/centos/mini-e2e/k8s-1.32
> 
> The [logs](https://jenkins-ceph-csi.apps.ocp.cloud.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.32/detail/mini-e2e_k8s-1.32/85/pipeline) of the failure do not immediate show what the issue is, I think:
> 
> ```
>   �[1mSTEP:�[0m create a PVC and check PVC/PV metadata on RBD image �[38;5;243m@ 02/20/25 11:57:08.555�[0m
>   I0220 11:57:08.558944 86817 pvc.go:60] Waiting up to &PersistentVolumeClaim{ObjectMeta:{rbd-pvc  rbd-1827    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[group:test] map[] [] [] []},Spec:PersistentVolumeClaimSpec{AccessModes:[ReadWriteOnce],Resources:VolumeResourceRequirements{Limits:ResourceList{},Requests:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},},VolumeName:,Selector:nil,StorageClassName:*csi-rbd-sc,VolumeMode:nil,DataSource:nil,DataSourceRef:nil,VolumeAttributesClassName:nil,},Status:PersistentVolumeClaimStatus{Phase:,AccessModes:[],Capacity:ResourceList{},Conditions:[]PersistentVolumeClaimCondition{},AllocatedResources:ResourceList{},AllocatedResourceStatuses:map[ResourceName]ClaimResourceStatus{},CurrentVolumeAttributesClassName:nil,ModifyVolumeStatus:nil,},} to be in Bound state
>   I0220 11:57:08.558987 86817 pvc.go:63] waiting for PVC rbd-pvc (0 seconds elapsed)
>   I0220 11:57:08.563534 86817 pvc.go:85] PVC rbd-pvc Event: Provisioning - External provisioner is provisioning volume for claim "rbd-1827/rbd-pvc"
>   I0220 11:57:08.563572 86817 pvc.go:85] PVC rbd-pvc Event: ExternalProvisioning - Waiting for a volume to be created either by the external provisioner 'rbd.csi.ceph.com' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
>   I0220 11:57:08.563799 86817 pvc.go:85] PVC rbd-pvc Event: Provisioning - External provisioner is provisioning volume for claim "rbd-1827/rbd-pvc"
>   I0220 11:57:08.563817 86817 pvc.go:85] PVC rbd-pvc Event: ProvisioningSucceeded - Successfully provisioned volume pvc-e4aa7cac-30f1-4f5e-bc5c-af17b8764c9a
>   I0220 11:57:08.563825 86817 pvc.go:85] PVC rbd-pvc Event: ExternalProvisioning - Waiting for a volume to be created either by the external provisioner 'rbd.csi.ceph.com' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
>   I0220 11:57:08.563833 86817 pvc.go:85] PVC rbd-pvc Event: Provisioning - External provisioner is provisioning volume for claim "rbd-1827/rbd-pvc"
>   I0220 11:57:08.563840 86817 pvc.go:85] PVC rbd-pvc Event: ProvisioningSucceeded - Successfully provisioned volume pvc-ca574bf2-9632-49b9-8125-66951fc004c2
>   I0220 11:57:10.559694 86817 pvc.go:63] waiting for PVC rbd-pvc (2 seconds elapsed)
>   I0220 11:57:10.563681 86817 pv.go:468] Waiting for PV pvc-8a23f93d-d21b-4d11-9485-c7f048ea55fb to bind to PVC rbd-pvc
>   I0220 11:57:10.563735 86817 pv.go:790] Waiting up to timeout=10m0s for PersistentVolumeClaims [rbd-pvc] to have phase Bound
>   I0220 11:57:10.567465 86817 pv.go:801] PersistentVolumeClaim rbd-pvc found and phase=Bound (3.716004ms)
>   I0220 11:57:10.567495 86817 pv.go:763] Waiting up to 10m0s for PersistentVolume pvc-8a23f93d-d21b-4d11-9485-c7f048ea55fb to have phase Bound
>   I0220 11:57:10.569559 86817 pv.go:771] PersistentVolume pvc-8a23f93d-d21b-4d11-9485-c7f048ea55fb found and phase=Bound (2.052301ms)
>   I0220 11:57:10.574121 86817 exec_util.go:59] ExecWithOptions {Command:[/bin/sh -c rbd ls --format=json --pool=replicapool] Namespace:rook-ceph PodName:rook-ceph-tools-56ff7b659c-lvrcs ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
>   I0220 11:57:10.574146 86817 exec_util.go:64] ExecWithOptions: Clientset creation
>   I0220 11:57:10.574201 86817 exec_util.go:80] ExecWithOptions: execute(POST https://192.168.49.2:8443/api/v1/namespaces/rook-ceph/pods/rook-ceph-tools-56ff7b659c-lvrcs/exec?command=%2Fbin%2Fsh&command=-c&command=rbd+ls+--format%3Djson+--pool%3Dreplicapool&container=rook-ceph-tools&stderr=true&stdout=true)
>   I0220 11:57:10.685176 86817 exec_util.go:59] ExecWithOptions {Command:[/bin/sh -c rados ls --pool=replicapool | grep -v default | grep -v csi.volume.group. |  grep -c ^csi.volume.] Namespace:rook-ceph PodName:rook-ceph-tools-56ff7b659c-lvrcs ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
>   I0220 11:57:10.685215 86817 exec_util.go:64] ExecWithOptions: Clientset creation
>   I0220 11:57:10.685248 86817 exec_util.go:80] ExecWithOptions: execute(POST https://192.168.49.2:8443/api/v1/namespaces/rook-ceph/pods/rook-ceph-tools-56ff7b659c-lvrcs/exec?command=%2Fbin%2Fsh&command=-c&command=rados+ls+--pool%3Dreplicapool+%7C+grep+-v+default+%7C+grep+-v+csi.volume.group.+%7C++grep+-c+%5Ecsi.volume.&container=rook-ceph-tools&stderr=true&stdout=true)
>   I0220 11:57:10.807774 86817 exec_util.go:59] ExecWithOptions {Command:[/bin/sh -c rados ls --pool=replicapool] Namespace:rook-ceph PodName:rook-ceph-tools-56ff7b659c-lvrcs ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
>   I0220 11:57:10.807838 86817 exec_util.go:64] ExecWithOptions: Clientset creation
>   I0220 11:57:10.807873 86817 exec_util.go:80] ExecWithOptions: execute(POST https://192.168.49.2:8443/api/v1/namespaces/rook-ceph/pods/rook-ceph-tools-56ff7b659c-lvrcs/exec?command=%2Fbin%2Fsh&command=-c&command=rados+ls+--pool%3Dreplicapool&container=rook-ceph-tools&stderr=true&stdout=true)
>   I0220 11:57:10.917795 86817 utils.go:251] additional debug info: rados ls command output: rbd_header.13de5595a987
>   rbd_directory
>   rbd_info
>   csi.volume.aec40a24-45ed-4919-97ca-b2c5b00517b5
>   rbd_task
>   csi.volumes.default
>   rbd_trash
>   csi.volume.860bd5be-e492-4bd0-b3de-7ce56fa535e1
>   rbd_id.csi-vol-aec40a24-45ed-4919-97ca-b2c5b00517b5
>   , stdErr: 
>   �[38;5;9m[FAILED]�[0m in [It] - /go/src/github.com/ceph/ceph-csi/e2e/utils.go:254 �[38;5;243m@ 02/20/25 11:57:10.918�[0m
> ```

>[38;5;9m[FAILED] failed to validate omap count for rados ls --pool=replicapool | grep -v default | grep -v csi.volume.group. |  grep -c ^csi.volume.: expected omap object count 1, got 2[0m

i think there is a omap leak.

**Comment by Rakshith-R** [comment]
> > > /retest ci/centos/mini-e2e/k8s-1.32
> > 
> > 
> > The [logs](https://jenkins-ceph-csi.apps.ocp.cloud.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.32/detail/mini-e2e_k8s-1.32/85/pipeline) of the failure do not immediate show what the issue is, I think:
> > ```
> >   �[1mSTEP:�[0m create a PVC and check PVC/PV metadata on RBD image �[38;5;243m@ 02/20/25 11:57:08.555�[0m
> >   I0220 11:57:08.558944 86817 pvc.go:60] Waiting up to &PersistentVolumeClaim{ObjectMeta:{rbd-pvc  rbd-1827    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[group:test] map[] [] [] []},Spec:PersistentVolumeClaimSpec{AccessModes:[ReadWriteOnce],Resources:VolumeResourceRequirements{Limits:ResourceList{},Requests:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},},VolumeName:,Selector:nil,StorageClassName:*csi-rbd-sc,VolumeMode:nil,DataSource:nil,DataSourceRef:nil,VolumeAttributesClassName:nil,},Status:PersistentVolumeClaimStatus{Phase:,AccessModes:[],Capacity:ResourceList{},Conditions:[]PersistentVolumeClaimCondition{},AllocatedResources:ResourceList{},AllocatedResourceStatuses:map[ResourceName]ClaimResourceStatus{},CurrentVolumeAttributesClassName:nil,ModifyVolumeStatus:nil,},} to be in Bound state
> >   I0220 11:57:08.558987 86817 pvc.go:63] waiting for PVC rbd-pvc (0 seconds elapsed)
> >   I0220 11:57:08.563534 86817 pvc.go:85] PVC rbd-pvc Event: Provisioning - External provisioner is provisioning volume for claim "rbd-1827/rbd-pvc"
> >   I0220 11:57:08.563572 86817 pvc.go:85] PVC rbd-pvc Event: ExternalProvisioning - Waiting for a volume to be created either by the external provisioner 'rbd.csi.ceph.com' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
> >   I0220 11:57:08.563799 86817 pvc.go:85] PVC rbd-pvc Event: Provisioning - External provisioner is provisioning volume for claim "rbd-1827/rbd-pvc"
> >   I0220 11:57:08.563817 86817 pvc.go:85] PVC rbd-pvc Event: ProvisioningSucceeded - Successfully provisioned volume pvc-e4aa7cac-30f1-4f5e-bc5c-af17b8764c9a
> >   I0220 11:57:08.563825 86817 pvc.go:85] PVC rbd-pvc Event: ExternalProvisioning - Waiting for a volume to be created either by the external provisioner 'rbd.csi.ceph.com' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
> >   I0220 11:57:08.563833 86817 pvc.go:85] PVC rbd-pvc Event: Provisioning - External provisioner is provisioning volume for claim "rbd-1827/rbd-pvc"
> >   I0220 11:57:08.563840 86817 pvc.go:85] PVC rbd-pvc Event: ProvisioningSucceeded - Successfully provisioned volume pvc-ca574bf2-9632-49b9-8125-66951fc004c2
> >   I0220 11:57:10.559694 86817 pvc.go:63] waiting for PVC rbd-pvc (2 seconds elapsed)
> >   I0220 11:57:10.563681 86817 pv.go:468] Waiting for PV pvc-8a23f93d-d21b-4d11-9485-c7f048ea55fb to bind to PVC rbd-pvc
> >   I0220 11:57:10.563735 86817 pv.go:790] Waiting up to timeout=10m0s for PersistentVolumeClaims [rbd-pvc] to have phase Bound
> >   I0220 11:57:10.567465 86817 pv.go:801] PersistentVolumeClaim rbd-pvc found and phase=Bound (3.716004ms)
> >   I0220 11:57:10.567495 86817 pv.go:763] Waiting up to 10m0s for PersistentVolume pvc-8a23f93d-d21b-4d11-9485-c7f048ea55fb to have phase Bound
> >   I0220 11:57:10.569559 86817 pv.go:771] PersistentVolume pvc-8a23f93d-d21b-4d11-9485-c7f048ea55fb found and phase=Bound (2.052301ms)
> >   I0220 11:57:10.574121 86817 exec_util.go:59] ExecWithOptions {Command:[/bin/sh -c rbd ls --format=json --pool=replicapool] Namespace:rook-ceph PodName:rook-ceph-tools-56ff7b659c-lvrcs ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
> >   I0220 11:57:10.574146 86817 exec_util.go:64] ExecWithOptions: Clientset creation
> >   I0220 11:57:10.574201 86817 exec_util.go:80] ExecWithOptions: execute(POST https://192.168.49.2:8443/api/v1/namespaces/rook-ceph/pods/rook-ceph-tools-56ff7b659c-lvrcs/exec?command=%2Fbin%2Fsh&command=-c&command=rbd+ls+--format%3Djson+--pool%3Dreplicapool&container=rook-ceph-tools&stderr=true&stdout=true)
> >   I0220 11:57:10.685176 86817 exec_util.go:59] ExecWithOptions {Command:[/bin/sh -c rados ls --pool=replicapool | grep -v default | grep -v csi.volume.group. |  grep -c ^csi.volume.] Namespace:rook-ceph PodName:rook-ceph-tools-56ff7b659c-lvrcs ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
> >   I0220 11:57:10.685215 86817 exec_util.go:64] ExecWithOptions: Clientset creation
> >   I0220 11:57:10.685248 86817 exec_util.go:80] ExecWithOptions: execute(POST https://192.168.49.2:8443/api/v1/namespaces/rook-ceph/pods/rook-ceph-tools-56ff7b659c-lvrcs/exec?command=%2Fbin%2Fsh&command=-c&command=rados+ls+--pool%3Dreplicapool+%7C+grep+-v+default+%7C+grep+-v+csi.volume.group.+%7C++grep+-c+%5Ecsi.volume.&container=rook-ceph-tools&stderr=true&stdout=true)
> >   I0220 11:57:10.807774 86817 exec_util.go:59] ExecWithOptions {Command:[/bin/sh -c rados ls --pool=replicapool] Namespace:rook-ceph PodName:rook-ceph-tools-56ff7b659c-lvrcs ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
> >   I0220 11:57:10.807838 86817 exec_util.go:64] ExecWithOptions: Clientset creation
> >   I0220 11:57:10.807873 86817 exec_util.go:80] ExecWithOptions: execute(POST https://192.168.49.2:8443/api/v1/namespaces/rook-ceph/pods/rook-ceph-tools-56ff7b659c-lvrcs/exec?command=%2Fbin%2Fsh&command=-c&command=rados+ls+--pool%3Dreplicapool&container=rook-ceph-tools&stderr=true&stdout=true)
> >   I0220 11:57:10.917795 86817 utils.go:251] additional debug info: rados ls command output: rbd_header.13de5595a987
> >   rbd_directory
> >   rbd_info
> >   csi.volume.aec40a24-45ed-4919-97ca-b2c5b00517b5
> >   rbd_task
> >   csi.volumes.default
> >   rbd_trash
> >   csi.volume.860bd5be-e492-4bd0-b3de-7ce56fa535e1
> >   rbd_id.csi-vol-aec40a24-45ed-4919-97ca-b2c5b00517b5
> >   , stdErr: 
> >   �[38;5;9m[FAILED]�[0m in [It] - /go/src/github.com/ceph/ceph-csi/e2e/utils.go:254 �[38;5;243m@ 02/20/25 11:57:10.918�[0m
> > ```
> 
> > [38;5;9m[FAILED] failed to validate omap count for rados ls --pool=replicapool | grep -v default | grep -v csi.volume.group. |  grep -c ^csi.volume.: expected omap object count 1, got 2�[0m
> 
> i think there is a omap leak.


I don't think this issue related to this pr.
It failed before RBD tests related to encryption were encountere.

```
  [1mSTEP:[0m create a PVC and check PVC/PV metadata on RBD image [38;5;243m@ 02/20/25 11:57:08.555[0m
  I0220 11:57:08.558944 86817 pvc.go:60] Waiting up to &PersistentVolumeClaim{ObjectMeta:{rbd-pvc  rbd-1827    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[group:test] map[] [] [] []},Spec:PersistentVolumeClaimSpec{AccessModes:[ReadWriteOnce],Resources:VolumeResourceRequirements{Limits:ResourceList{},Requests:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},},VolumeName:,Selector:nil,StorageClassName:*csi-rbd-sc,VolumeMode:nil,DataSource:nil,DataSourceRef:nil,VolumeAttributesClassName:nil,},Status:PersistentVolumeClaimStatus{Phase:,AccessModes:[],Capacity:ResourceList{},Conditions:[]PersistentVolumeClaimCondition{},AllocatedResources:ResourceList{},AllocatedResourceStatuses:map[ResourceName]ClaimResourceStatus{},CurrentVolumeAttributesClassName:nil,ModifyVolumeStatus:nil,},} to be in Bound state
  I0220 11:57:08.558987 86817 pvc.go:63] waiting for PVC rbd-pvc (0 seconds elapsed)
  I0220 11:57:08.563534 86817 pvc.go:85] PVC rbd-pvc Event: Provisioning - External provisioner is provisioning volume for claim "rbd-1827/rbd-pvc"
  I0220 11:57:08.563572 86817 pvc.go:85] PVC rbd-pvc Event: ExternalProvisioning - Waiting for a volume to be created either by the external provisioner 'rbd.csi.ceph.com' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
  I0220 11:57:08.563799 86817 pvc.go:85] PVC rbd-pvc Event: Provisioning - External provisioner is provisioning volume for claim "rbd-1827/rbd-pvc"
  I0220 11:57:08.563817 86817 pvc.go:85] PVC rbd-pvc Event: ProvisioningSucceeded - Successfully provisioned volume pvc-e4aa7cac-30f1-4f5e-bc5c-af17b8764c9a
  I0220 11:57:08.563825 86817 pvc.go:85] PVC rbd-pvc Event: ExternalProvisioning - Waiting for a volume to be created either by the external provisioner 'rbd.csi.ceph.com' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
  I0220 11:57:08.563833 86817 pvc.go:85] PVC rbd-pvc Event: Provisioning - External provisioner is provisioning volume for claim "rbd-1827/rbd-pvc"
  I0220 11:57:08.563840 86817 pvc.go:85] PVC rbd-pvc Event: ProvisioningSucceeded - Successfully provisioned volume pvc-ca574bf2-9632-49b9-8125-66951fc004c2
  I0220 11:57:10.559694 86817 pvc.go:63] waiting for PVC rbd-pvc (2 seconds elapsed)
  I0220 11:57:10.563681 86817 pv.go:468] Waiting for PV pvc-8a23f93d-d21b-4d11-9485-c7f048ea55fb to bind to PVC rbd-pvc
  I0220 11:57:10.563735 86817 pv.go:790] Waiting up to timeout=10m0s for PersistentVolumeClaims [rbd-pvc] to have phase Bound
  I0220 11:57:10.567465 86817 pv.go:801] PersistentVolumeClaim rbd-pvc found and phase=Bound (3.716004ms)
  I0220 11:57:10.567495 86817 pv.go:763] Waiting up to 10m0s for PersistentVolume pvc-8a23f93d-d21b-4d11-9485-c7f048ea55fb to have phase Bound
  I0220 11:57:10.569559 86817 pv.go:771] PersistentVolume pvc-8a23f93d-d21b-4d11-9485-c7f048ea55fb found and phase=Bound (2.052301ms)
  I0220 11:57:10.574121 86817 exec_util.go:59] ExecWithOptions {Command:[/bin/sh -c rbd ls --format=json --pool=replicapool] Namespace:rook-ceph PodName:rook-ceph-tools-56ff7b659c-lvrcs ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
  I0220 11:57:10.574146 86817 exec_util.go:64] ExecWithOptions: Clientset creation
  I0220 11:57:10.574201 86817 exec_util.go:80] ExecWithOptions: execute(POST https://192.168.49.2:8443/api/v1/namespaces/rook-ceph/pods/rook-ceph-tools-56ff7b659c-lvrcs/exec?command=%2Fbin%2Fsh&command=-c&command=rbd+ls+--format%3Djson+--pool%3Dreplicapool&container=rook-ceph-tools&stderr=true&stdout=true)
  I0220 11:57:10.685176 86817 exec_util.go:59] ExecWithOptions {Command:[/bin/sh -c rados ls --pool=replicapool | grep -v default | grep -v csi.volume.group. |  grep -c ^csi.volume.] Namespace:rook-ceph PodName:rook-ceph-tools-56ff7b659c-lvrcs ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
  I0220 11:57:10.685215 86817 exec_util.go:64] ExecWithOptions: Clientset creation
  I0220 11:57:10.685248 86817 exec_util.go:80] ExecWithOptions: execute(POST https://192.168.49.2:8443/api/v1/namespaces/rook-ceph/pods/rook-ceph-tools-56ff7b659c-lvrcs/exec?command=%2Fbin%2Fsh&command=-c&command=rados+ls+--pool%3Dreplicapool+%7C+grep+-v+default+%7C+grep+-v+csi.volume.group.+%7C++grep+-c+%5Ecsi.volume.&container=rook-ceph-tools&stderr=true&stdout=true)
  I0220 11:57:10.807774 86817 exec_util.go:59] ExecWithOptions {Command:[/bin/sh -c rados ls --pool=replicapool] Namespace:rook-ceph PodName:rook-ceph-tools-56ff7b659c-lvrcs ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
  I0220 11:57:10.807838 86817 exec_util.go:64] ExecWithOptions: Clientset creation
  I0220 11:57:10.807873 86817 exec_util.go:80] ExecWithOptions: execute(POST https://192.168.49.2:8443/api/v1/namespaces/rook-ceph/pods/rook-ceph-tools-56ff7b659c-lvrcs/exec?command=%2Fbin%2Fsh&command=-c&command=rados+ls+--pool%3Dreplicapool&container=rook-ceph-tools&stderr=true&stdout=true)
  I0220 11:57:10.917795 86817 utils.go:251] additional debug info: rados ls command output: rbd_header.13de5595a987
  rbd_directory
  rbd_info
  csi.volume.aec40a24-45ed-4919-97ca-b2c5b00517b5
  rbd_task
  csi.volumes.default
  rbd_trash
  csi.volume.860bd5be-e492-4bd0-b3de-7ce56fa535e1
  rbd_id.csi-vol-aec40a24-45ed-4919-97ca-b2c5b00517b5
  , stdErr: 
  [38;5;9m[FAILED][0m in [It] - /go/src/github.com/ceph/ceph-csi/e2e/utils.go:254 [38;5;243m@ 02/20/25 11:57:10.918[0m
```

**Comment by iPraveenParihar** [comment]
>   I0220 11:57:10.917795 86817 utils.go:251] additional debug info: rados ls command output: rbd_header.13de5595a987
  rbd_directory
  rbd_info
  csi.volume.aec40a24-45ed-4919-97ca-b2c5b00517b5
  rbd_task
  csi.volumes.default
  rbd_trash
  csi.volume.860bd5be-e492-4bd0-b3de-7ce56fa535e1
  rbd_id.csi-vol-aec40a24-45ed-4919-97ca-b2c5b00517b5
  
  
  `csi.volume.aec40a24-45ed-4919-97ca-b2c5b00517b5` is from failed test. The stale entry `csi.volume.860bd5be-e492-4bd0-b3de-7ce56fa535e1` is not present in collected logs.
