### PR TITLE
e2e: add snapshot count validation

### LINKED ISSUE #3224: e2e: validate snapshot count after their creation
# Describe the bug #

As a good practice, always make sure to validate the snapshot count after we create them in the tests
Something like:
```
err = createSnapshot(&snap, deployTimeout)                            
if err != nil {                                                       
    e2elog.Failf("failed to create snapshot (%s): %v", snap.Name, err)
}                                                                     
snaps, err := listCephFSSnapshots(f, fileSystemName, subvolumes[0].Name, subvolumegroup)    
if err != nil {                                                                             
    e2elog.Failf("failed to list subvolume snapshots: %v", err)                             
}                                                                                           
if len(snaps) == 0 {                                                                        
    e2elog.Failf("cephFS snapshots list is empty %s/%s", fileSystemName, subvolumes[0].Name)
}                                                                                           
```

[Original conversation](https://github.com/ceph/ceph-csi/pull/3168#discussion_r909196029)

### PR DESCRIPTION
**Pull request by Madhu-1**
Add snapshot count validation for cephfs and NFS to avoid resource leaks.

fixes: #3224

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

File: e2e/cephfs.go [hunk 1]
```diff
@@ -118,6 +118,34 @@ func validateSubvolumeCount(f *framework.Framework, count int, fileSystemName, s
...
+		e2elog.Failf("failed to get pv: %v", err)
+	}
+	subVolumeName := pv.Spec.CSI.VolumeAttributes["subvolumeName"]
+	fsName := pv.Spec.CSI.VolumeAttributes["fsName"]
+	snaps, err := listCephFSSnapshots(f, fsName, subVolumeName, subvolumegroup)
+	if err != nil {
+		e2elog.Failf("failed to list subvolume snapshots: %v", err)
+	}
+	if len(snaps) != count {
+		e2elog.Failf("snapshots [%v]. snapshots count %d not matching expected count %v", snaps, len(snaps), count)
```
Comment (nixpanic) [inline e2e/cephfs.go]: **nit:** weirdly mixing `%d` and `%v` in the failure string. Both arguments are `int`, so use `%d` for both too?

File: e2e/cephfs.go [hunk 2]
```diff
@@ -118,6 +118,34 @@ func validateSubvolumeCount(f *framework.Framework, count int, fileSystemName, s
 	}
 }
 
+func validateSnapshotCount(f *framework.Framework, count int, subvolumegroup string, pvc *v1.PersistentVolumeClaim) {
```
Comment (nixpanic) [inline e2e/cephfs.go]: The function name might be conflicting with the RBD validation function? Both are in the same `e2e` package (yuck). Maybe include CephFS in the name somehow?

Comment (Madhu-1) [reply e2e/cephfs.go]: we dont have validateSnapshotCount in RBD but renamed this to include CephFS name

**Review by nixpanic — DISMISSED** [review]

**Review by Rakshith-R — DISMISSED** [review]

File: e2e/cephfs.go [hunk 3]
```diff
@@ -1016,6 +1047,8 @@ var _ = Describe(cephfsType, func() {
 				}
 				validateSubvolumeCount(f, 0, fileSystemName, subvolumegroup)
 				validateOmapCount(f, 0, cephfsType, metadataPool, volumesType)
+				validateCephFSSnapshotCount(f, 0, defaultSubvolumegroup, pvc)
```
Comment (nixpanic) [inline e2e/cephfs.go]: this fails because `pvc` was deleted at line 1002

**Comment by nixpanic** [comment]
CI job failed ([logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/rest/organizations/jenkins/pipelines/mini-e2e_k8s-1.25/runs/55/nodes/89/log/?start=0)):

```console
    [1mSTEP:[0m Test subvolume snapshot and restored PVC metadata [38;5;243m11/04/22 08:42:17.38[0m
    Nov  4 08:42:17.384: INFO: ExecWithOptions {Command:[/bin/sh -c ceph fsid] Namespace:rook-ceph PodName:rook-ceph-tools-7564bb9799-4qbhg ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
    Nov  4 08:42:17.384: INFO: >>> kubeConfig: /root/.kube/config
    Nov  4 08:42:17.384: INFO: ExecWithOptions: Clientset creation
    Nov  4 08:42:17.384: INFO: ExecWithOptions: execute(POST https://192.168.49.2:8443/api/v1/namespaces/rook-ceph/pods/rook-ceph-tools-7564bb9799-4qbhg/exec?command=%2Fbin%2Fsh&command=-c&command=ceph+fsid&container=rook-ceph-tools&container=rook-ceph-tools&stderr=true&stdout=true)
    Nov  4 08:42:17.990: INFO: >>> kubeConfig: /root/.kube/config
    Nov  4 08:42:17.996: INFO: Waiting up to &PersistentVolumeClaim{ObjectMeta:{csi-cephfs-pvc  cephfs-8081    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},Spec:PersistentVolumeClaimSpec{AccessModes:[ReadWriteMany],Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},},VolumeName:,Selector:nil,StorageClassName:*csi-cephfs-sc,VolumeMode:nil,DataSource:nil,DataSourceRef:nil,},Status:PersistentVolumeClaimStatus{Phase:,AccessModes:[],Capacity:ResourceList{},Conditions:[]PersistentVolumeClaimCondition{},AllocatedResources:ResourceList{},ResizeStatus:nil,},} to be in Bound state
    Nov  4 08:42:17.996: INFO: waiting for PVC csi-cephfs-pvc (0 seconds elapsed)
    Nov  4 08:42:19.998: INFO: waiting for PVC csi-cephfs-pvc (2 seconds elapsed)
    Nov  4 08:42:20.002: INFO: Waiting for PV pvc-27a3635a-3cee-4b56-a704-90c8dc2bef7e to bind to PVC csi-cephfs-pvc
    Nov  4 08:42:20.002: INFO: Waiting up to timeout=10m0s for PersistentVolumeClaims [csi-cephfs-pvc] to have phase Bound
    Nov  4 08:42:20.004: INFO: PersistentVolumeClaim csi-cephfs-pvc found and phase=Bound (1.595423ms)
    Nov  4 08:42:20.004: INFO: Waiting up to 10m0s for PersistentVolume pvc-27a3635a-3cee-4b56-a704-90c8dc2bef7e to have phase Bound
    Nov  4 08:42:20.005: INFO: PersistentVolume pvc-27a3635a-3cee-4b56-a704-90c8dc2bef7e found and phase=Bound (1.524408ms)
    Nov  4 08:42:20.009: INFO: >>> kubeConfig: /root/.kube/config
    Nov  4 08:42:20.013: INFO: snapshot with name cephfs-8081 created in cephfs-8081 namespace
    Nov  4 08:42:20.013: INFO: waiting for &{{VolumeSnapshot snapshot.storage.k8s.io/v1} {cephfs-8081  cephfs-8081    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []} {{0xc0033d8e20 <nil>} 0xc001f785b0} <nil>} to be in ready state
    Nov  4 08:42:20.014: INFO: waiting for snapshot cephfs-8081 (0 seconds elapsed)
    Nov  4 08:42:22.017: INFO: waiting for snapshot cephfs-8081 (2 seconds elapsed)
    Nov  4 08:42:22.026: INFO: ExecWithOptions {Command:[/bin/sh -c ceph fs subvolume snapshot ls myfs csi-vol-bb8c6398-05be-4900-a58b-663165515473 --group_name=csi --format=json] Namespace:rook-ceph PodName:rook-ceph-tools-7564bb9799-4qbhg ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
    Nov  4 08:42:22.026: INFO: >>> kubeConfig: /root/.kube/config
    Nov  4 08:42:22.026: INFO: ExecWithOptions: Clientset creation
    Nov  4 08:42:22.026: INFO: ExecWithOptions: execute(POST https://192.168.49.2:8443/api/v1/namespaces/rook-ceph/pods/rook-ceph-tools-7564bb9799-4qbhg/exec?command=%2Fbin%2Fsh&command=-c&command=ceph+fs+subvolume+snapshot+ls+myfs+csi-vol-bb8c6398-05be-4900-a58b-663165515473+--group_name%3Dcsi+--format%3Djson&container=rook-ceph-tools&container=rook-ceph-tools&stderr=true&stdout=true)
    Nov  4 08:42:22.574: INFO: failed to execute command: command terminated with exit code 2
    Nov  4 08:42:22.574: INFO: stdErr occurred: Error ENOENT: subvolume group 'csi' does not exist

    Nov  4 08:42:22.574: FAIL: failed to list subvolume snapshots: failed to execute command: command terminated with exit code 2
```

**Comment by nixpanic** [comment]
Looks like it failed again ([logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/rest/organizations/jenkins/pipelines/mini-e2e_k8s-1.25/runs/56/nodes/89/log/?start=0)):
```
    [1mSTEP:[0m create a PVC clone and bind it to an app [38;5;243m11/04/22 11:40:01.657[0m
    Nov  4 11:40:01.662: INFO: ExecWithOptions {Command:[/bin/sh -c ceph fsid] Namespace:rook-ceph PodName:rook-ceph-tools-7564bb9799-99rwh ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
    Nov  4 11:40:01.662: INFO: >>> kubeConfig: /root/.kube/config
    Nov  4 11:40:01.662: INFO: ExecWithOptions: Clientset creation
    Nov  4 11:40:01.662: INFO: ExecWithOptions: execute(POST https://192.168.49.2:8443/api/v1/namespaces/rook-ceph/pods/rook-ceph-tools-7564bb9799-99rwh/exec?command=%2Fbin%2Fsh&command=-c&command=ceph+fsid&container=rook-ceph-tools&container=rook-ceph-tools&stderr=true&stdout=true)
    Nov  4 11:40:02.306: INFO: >>> kubeConfig: /root/.kube/config
    Nov  4 11:40:02.316: INFO: Waiting up to &PersistentVolumeClaim{ObjectMeta:{cephcsi-nfs-pvc  nfs-8081    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},Spec:PersistentVolumeClaimSpec{AccessModes:[ReadWriteMany],Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},},VolumeName:,Selector:nil,StorageClassName:*csi-nfs-sc,VolumeMode:nil,DataSource:nil,DataSourceRef:nil,},Status:PersistentVolumeClaimStatus{Phase:,AccessModes:[],Capacity:ResourceList{},Conditions:[]PersistentVolumeClaimCondition{},AllocatedResources:ResourceList{},ResizeStatus:nil,},} to be in Bound state
    Nov  4 11:40:02.316: INFO: waiting for PVC cephcsi-nfs-pvc (0 seconds elapsed)
    Nov  4 11:40:04.318: INFO: waiting for PVC cephcsi-nfs-pvc (2 seconds elapsed)
    Nov  4 11:40:04.322: INFO: Waiting for PV pvc-b4edffe4-975d-4801-81a3-7d50efd4c664 to bind to PVC cephcsi-nfs-pvc
    Nov  4 11:40:04.322: INFO: Waiting up to timeout=10m0s for PersistentVolumeClaims [cephcsi-nfs-pvc] to have phase Bound
    Nov  4 11:40:04.323: INFO: PersistentVolumeClaim cephcsi-nfs-pvc found and phase=Bound (1.708082ms)
    Nov  4 11:40:04.323: INFO: Waiting up to 10m0s for PersistentVolume pvc-b4edffe4-975d-4801-81a3-7d50efd4c664 to have phase Bound
    Nov  4 11:40:04.325: INFO: PersistentVolume pvc-b4edffe4-975d-4801-81a3-7d50efd4c664 found and phase=Bound (1.765704ms)
    Nov  4 11:40:04.332: INFO: Waiting up to cephcsi-nfs-demo-pod to be in Running state
    Nov  4 11:40:06.339: INFO: ExecWithOptions {Command:[/bin/sh -c dd if=/dev/zero of=/var/lib/www/test bs=1M count=10 status=none] Namespace:nfs-8081 PodName:cephcsi-nfs-demo-pod ContainerName:web-server Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
    Nov  4 11:40:06.339: INFO: >>> kubeConfig: /root/.kube/config
    Nov  4 11:40:06.339: INFO: ExecWithOptions: Clientset creation
    Nov  4 11:40:06.339: INFO: ExecWithOptions: execute(POST https://192.168.49.2:8443/api/v1/namespaces/nfs-8081/pods/cephcsi-nfs-demo-pod/exec?command=%2Fbin%2Fsh&command=-c&command=dd+if%3D%2Fdev%2Fzero+of%3D%2Fvar%2Flib%2Fwww%2Ftest+bs%3D1M+count%3D10+status%3Dnone&container=web-server&container=web-server&stderr=true&stdout=true)
    Nov  4 11:40:06.511: INFO: ExecWithOptions {Command:[/bin/sh -c sha512sum /var/lib/www/test] Namespace:nfs-8081 PodName:cephcsi-nfs-demo-pod ContainerName:web-server Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
    Nov  4 11:40:06.511: INFO: >>> kubeConfig: /root/.kube/config
    Nov  4 11:40:06.511: INFO: ExecWithOptions: Clientset creation
    Nov  4 11:40:06.511: INFO: ExecWithOptions: execute(POST https://192.168.49.2:8443/api/v1/namespaces/nfs-8081/pods/cephcsi-nfs-demo-pod/exec?command=%2Fbin%2Fsh&command=-c&command=sha512sum+%2Fvar%2Flib%2Fwww%2Ftest&container=web-server&container=web-server&stderr=true&stdout=true)
    Nov  4 11:40:06.635: INFO: Calculated checksum  8
    Nov  4 11:40:06.639: INFO: Waiting for pod cephcsi-nfs-demo-pod to be deleted
    Nov  4 11:40:08.644: FAIL: failed to get pv: resource name may not be empty
```

**Comment by Madhu-1** [comment]
CI passed ready for the review.

**Comment by Madhu-1** [comment]
@nixpanic this is ready for review, CI passed

**Review by Rakshith-R — DISMISSED** [review]

**Review by nixpanic — DISMISSED** [review]

**Comment by humblec** [comment]
@Mergifyio rebase

**Comment by nixpanic** [comment]
This can be rebased with Mergify once #3519 is merged

**Comment by humblec** [comment]
@Mergifyio rebase

**Comment by humblec** [comment]
It looks like a genuine failure and has to be analyzed: https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.25/detail/mini-e2e-helm_k8s-1.25/102/pipeline


````
Nov 15 07:06:39.943: INFO: waiting for kubectl (delete -f "../deploy/rbd/kubernetes/csi-config-map.yaml" args []) to finish

    Nov 15 07:06:39.943: INFO: Running '/usr/bin/kubectl --server=https://192.168.49.2:8443/ --kubeconfig=/root/.kube/config --namespace=cephcsi-e2e-dbb66eaa77db delete -f ../deploy/rbd/kubernetes/csi-config-map.yaml'

    Nov 15 07:06:40.010: INFO: stderr: ""

    Nov 15 07:06:40.010: INFO: stdout: "configmap \"ceph-csi-config\" deleted\n"

    Nov 15 07:06:40.016: INFO: waiting for kubectl (delete -f args [--ignore-not-found=true]) to finish

    Nov 15 07:06:40.016: INFO: Running '/usr/bin/kubectl --server=https://192.168.49.2:8443/ --kubeconfig=/root/.kube/config --namespace=cephcsi-e2e-dbb66eaa77db --ignore-not-found=true delete -f -'

    Nov 15 07:06:40.085: INFO: stderr: "Warning: deleting cluster-scoped resources, not scoped to the provided namespace\n"

    Nov 15 07:06:40.085: INFO: stdout: "storageclass.storage.k8s.io \"csi-rbd-sc\" deleted\n"

    Nov 15 07:06:40.085: INFO: waiting for kubectl (delete -f args []) to finish

    Nov 15 07:06:40.085: INFO: Running '/usr/bin/kubectl --server=https://192.168.49.2:8443/ --kubeconfig=/root/.kube/config --namespace=cephcsi-e2e-dbb66eaa77db delete -f -'

    Nov 15 07:06:40.180: INFO: stderr: ""

    Nov 15 07:06:40.180: INFO: stdout: "service \"vault\" deleted\ndeployment.apps \"vault\" deleted\nconfigmap \"init-scripts\" deleted\njob.batch \"vault-init-job\" deleted\n"

    Nov 15 07:06:40.180: INFO: waiting for kubectl (delete -f args []) to finish

    Nov 15 07:06:40.180: INFO: Running '/usr/bin/kubectl --server=https://192.168.49.2:8443/ --kubeconfig=/root/.kube/config --namespace=cephcsi-e2e-dbb66eaa77db delete -f -'

    Nov 15 07:06:40.261: INFO: stderr: "Warning: deleting cluster-scoped resources, not scoped to the provided namespace\n"

    Nov 15 07:06:40.261: INFO: stdout: "serviceaccount \"rbd-csi-vault-token-review\" deleted\nclusterrole.rbac.authorization.k8s.io \"rbd-csi-vault-token-review\" deleted\nclusterrolebinding.rbac.authorization.k8s.io \"rbd-csi-vault-token-review\" deleted\n"

    Nov 15 07:06:40.261: INFO: waiting for kubectl (delete -f args []) to finish

    Nov 15 07:06:40.261: INFO: Running '/usr/bin/kubectl --server=https://192.168.49.2:8443/ --kubeconfig=/root/.kube/config --namespace=cephcsi-e2e-dbb66eaa77db delete -f -'

    Nov 15 07:06:40.329: INFO: stderr: ""

    Nov 15 07:06:40.329: INFO: stdout: "configmap \"ceph-csi-encryption-kms-config\" deleted\n"

    STEP: removing the label test.failure-domain/region off the node minikube 11/15/22 07:06:40.331

    STEP: verifying the node doesn't have the label test.failure-domain/region 11/15/22 07:06:40.351

    STEP: removing the label test.failure-domain/zone off the node minikube 11/15/22 07:06:40.355

    STEP: verifying the node doesn't have the label test.failure-domain/zone 11/15/22 07:06:40.363

    STEP: removing the label topology.rbd.csi.ceph.com/region off the node minikube 11/15/22 07:06:40.366

    STEP: verifying the node doesn't have the label topology.rbd.csi.ceph.com/region 11/15/22 07:06:40.377

    STEP: removing the label topology.rbd.csi.ceph.com/zone off the node minikube 11/15/22 07:06:40.381

    STEP: verifying the node doesn't have the label topology.rbd.csi.ceph.com/zone 11/15/22 07:06:40.389

  << End Captured GinkgoWriter Output


  Nov 15 07:06:35.319: expected omap object count 0, got 1

  In [It] at: /go/src/github.com/ceph/ceph-csi/e2e/utils.go:237

------------------------------
```

**Comment by Madhu-1** [comment]
CI passed, this is ready for review again.

**Comment by humblec** [comment]
looks like the recent failure is on reserving the machine. 
btw, I think we can squash the commits @Madhu-1

**Comment by Madhu-1** [comment]
> looks like the recent failure is on reserving the machine. btw, I think we can squash the commits @Madhu-1

both are not related to each other. it was addressed as part of the review comment. keeping it as a separate commit.

**Review by nixpanic — APPROVED** [review]

**Review by Rakshith-R — APPROVED** [review]

**Comment by Rakshith-R** [comment]
@mergifyio rebase
