### PR TITLE
util: NewK8sClient() should not panic on non-Kubernetes clusters

### LINKED ISSUE #2452: Using driver outside of K8S breaks in 3.4.0
# Describe the bug #

I'm using RBD driver with Nomad instead of K8S. Upgraded from 3,3.1 to 3.4.0
Controller works fine, however nodes fails to start with this error: `unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined`

# Environment details #

- Image/version of Ceph CSI driver : quay.io/cephcsi/cephcsi:v3.4.0
- Helm chart version :
- Kernel version : 4.19.0-17-amd64 debian 
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : krbd
- Kubernetes cluster version :
- Ceph cluster version : 16.2.5

# Steps to reproduce #

Running with this args outside a K8S cluster:

    args = [
          "--drivername=rbd.csi.ceph.com",
          "--v=5",
          "--type=rbd",
          "--nodeserver=true",
          "--nodeid=${NODE_ID}",
          "--instanceid=${POD_ID}",
          "--endpoint=${CSI_ENDPOINT}",
    ]

# Actual results #

```
F0829 11:50:48.287826       1 k8s.go:40] Failed to get cluster config with error: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
goroutine 55 [running]:
k8s.io/klog/v2.stacks(0xc00012c001, 0xc0003ae500, 0xbf, 0x24d)
	/go/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:1021 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x3060980, 0xc000000003, 0x0, 0x0, 0xc0002fcfc0, 0x25cc424, 0x6, 0x28, 0x418a00)
	/go/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:970 +0x191
k8s.io/klog/v2.(*loggingT).printDepth(0x3060980, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc000508830, 0x1, 0x1)
	/go/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:733 +0x16f
k8s.io/klog/v2.FatalDepth(...)
	/go/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:1495
github.com/ceph/ceph-csi/internal/util.FatalLogMsg(0x1ed5723, 0x2c, 0xc000074da8, 0x1, 0x1)
	/go/src/github.com/ceph/ceph-csi/internal/util/log.go:59 +0x118
github.com/ceph/ceph-csi/internal/util.NewK8sClient(0x0)
	/go/src/github.com/ceph/ceph-csi/internal/util/k8s.go:40 +0x1bc
github.com/ceph/ceph-csi/internal/rbd.runVolumeHealer(0xc000394360, 0x3060aa0, 0x0, 0x0)
	/go/src/github.com/ceph/ceph-csi/internal/rbd/rbd_healer.go:128 +0x37
github.com/ceph/ceph-csi/internal/rbd.(*Driver).Run.func1(0xc000362e10, 0x3060aa0)
	/go/src/github.com/ceph/ceph-csi/internal/rbd/driver.go:206 +0x3d
created by github.com/ceph/ceph-csi/internal/rbd.(*Driver).Run
	/go/src/github.com/ceph/ceph-csi/internal/rbd/driver.go:204 +0x925

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0004e8c68)
	/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc0004e8c60)
	/usr/local/go/src/sync/waitgroup.go:130 +0x65
github.com/ceph/ceph-csi/internal/csi-common.(*nonBlockingGRPCServer).Wait(0xc0004e8c60)
	/go/src/github.com/ceph/ceph-csi/internal/csi-common/server.go:76 +0x2d
github.com/ceph/ceph-csi/internal/rbd.(*Driver).Run(0xc000362e10, 0x3060aa0)
	/go/src/github.com/ceph/ceph-csi/internal/rbd/driver.go:212 +0x8ea
main.main()
	/go/src/github.com/ceph/ceph-csi/cmd/cephcsi.go:218 +0x330

goroutine 19 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x3060980)
	/go/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:1164 +0x8b
created by k8s.io/klog/v2.init.0
	/go/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:418 +0xdf

goroutine 10 [sleep]:
time.Sleep(0x6fc23ac00)
	/usr/local/go/src/runtime/time.go:193 +0xd2
sigs.k8s.io/controller-runtime/pkg/log.init.0.func1()
	/go/src/github.com/ceph/ceph-csi/vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go:63 +0x45
created by sigs.k8s.io/controller-runtime/pkg/log.init.0
	/go/src/github.com/ceph/ceph-csi/vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go:62 +0x35

goroutine 54 [runnable]:
syscall.Syscall(0x107, 0xffffffffffffff9c, 0xc0003a4200, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:20 +0x5
syscall.unlinkat(0xffffffffffffff9c, 0xc0003a41e0, 0xd, 0x0, 0x0, 0xc0003fd628)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:126 +0xac
syscall.Unlink(...)
	/usr/local/go/src/syscall/syscall_linux.go:182
os.Remove.func1(...)
	/usr/local/go/src/os/file_unix.go:300
os.ignoringEINTR(...)
	/usr/local/go/src/os/file_posix.go:245
os.Remove(0xc0003a41e0, 0xd, 0x1, 0x7ffd75806d1c)
	/usr/local/go/src/os/file_unix.go:299 +0x4d
github.com/ceph/ceph-csi/internal/csi-common.(*nonBlockingGRPCServer).serve(0xc0004e8c60, 0x7ffd75806d15, 0x13, 0x1e92301, 0x7, 0x21a4ff0, 0xc000010220, 0x21d0820, 0x0, 0x21c66a8, ...)
	/go/src/github.com/ceph/ceph-csi/internal/csi-common/server.go:97 +0xc19
created by github.com/ceph/ceph-csi/internal/csi-common.(*nonBlockingGRPCServer).Start
	/go/src/github.com/ceph/ceph-csi/internal/csi-common/server.go:71 +0xe5
```

# Expected behavior #

Was working fine on previous stable version

# Logs #

# Additional context #

Followed guide here: https://github.com/hashicorp/nomad/tree/main/demo/csi/ceph-csi-plugin

### PR DESCRIPTION
**Pull request by nixpanic**
When NewK8sClient() detects and error, it used to call FatalLogMsg()
which causes a panic. There are additional features that can be used on
Kubernetes clusters, but these are not a requirement for most
functionalities of the driver.

Instead of causing a panic, returning and logging the issue should
suffice. This allows using the driver on non-Kubernetes clusters again.

Fixes: #2452

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.22

Failed with #2264

**Review by Madhu-1 — DISMISSED** [review]

File: internal/kms/aws_metadata.go [hunk 1]
```diff
@@ -125,7 +125,12 @@ func initAWSMetadataKMS(args ProviderInitArgs) (EncryptionKMS, error) {
 }
 
 func (kms *AWSMetadataKMS) getSecrets() (map[string]interface{}, error) {
-	c := k8s.NewK8sClient()
+	c, err := k8s.NewK8sClient()
+	if err != nil {
+		return nil, fmt.Errorf("can not connect to Kubernetes to get "+
```
Comment (Rakshith-R) [inline internal/kms/aws_metadata.go]:
```suggestion
		return nil, fmt.Errorf("failed to connect to Kubernetes to get "+
```
:sweat_smile:  @nixpanic  Any reason to not follow this style as we have already discussed ?

**Comment by humblec** [comment]
lgtm, just waiting for approval as there is a question from @Rakshith-R here https://github.com/ceph/ceph-csi/pull/2466#discussion_r700094841

File: internal/kms/aws_metadata.go (hunk 1 above)
Comment (nixpanic) [reply internal/kms/aws_metadata.go]: Not sure if there is something specific we settled on? I can surely change it, but we should consider having some checks in the CI for this (is there an error-format-checker?).

If you want me to change this, just mark it **Request changes** so the PR is blocked from  merging :-)

Comment (Rakshith-R) [reply internal/kms/aws_metadata.go]: I dont mind either way, was just wondering if there was a reason for `can not ...` wording here.
Yes I think we need some ci checks 🤔.
https://github.com/ceph/ceph-csi/issues/2371#issuecomment-894085816

Comment (Rakshith-R) [reply internal/kms/aws_metadata.go]: I think we need to follow the format `failed to ..context.. : %v` so that it helps in debugging too(to know exactly the flow of the error)

**Review by Rakshith-R — CHANGES_REQUESTED** [review]
Just the error msg formatting, otherwise LGTM

File: internal/kms/aws_metadata.go (hunk 1 above)
Comment (nixpanic) [reply internal/kms/aws_metadata.go]: some errors have a prefix like `can not get ConfigMap ..., failed to connect ...`. I think that is acceptable :smile:

**Review by Rakshith-R — DISMISSED** [review]
👍😅

**Comment by nixpanic** [comment]
> Just the error msg formatting, otherwise LGTM

This has been corrected now. Also not logging the issue in `NewK8sClient()` anymore, all callers seem to log/return the error as well.

**Comment by Rakshith-R** [comment]
> > Just the error msg formatting, otherwise LGTM
> 
> This has been corrected now. Also not logging the issue in `NewK8sClient()` anymore, all callers seem to log/return the error as well.

@nixpanic 
Sorry, didn't point them in review/ change requested, other places also need similar formatting ?

**Comment by nixpanic** [comment]
> > > Just the error msg formatting, otherwise LGTM
> > 
> > 
> > This has been corrected now. Also not logging the issue in `NewK8sClient()` anymore, all callers seem to log/return the error as well.
> 
> @nixpanic
> Sorry, didn't point them in review/ change requested, other places also need similar formatting ?

I think (and hope) all are corrected now. Some have a `can not ...` prefix, but still contain the `failed to connect to Kubernetes` message.

**Review by Rakshith-R — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase
