### PR TITLE
rbd: fix parsing mapOptions

### LINKED ISSUE #2910: rbd: mapOptions `crush_location` cannot be used since it uses `:`
# Describe the bug #

mapOptions `crush_location` cannot be used since it uses `:` which is currently used as
a separator between mounter types.
`
E0301 10:19:13.615111    7348 utils.go:200] ID: 63 Req-ID: 0001-0009-rook-ceph-0000000000000001-fd37c41b-9948-11ec-ad32-0242ac110004 GRPC error: badly formatted map/unmap options: "krbd:read_from_replica=localize,crush_location=zone:zone1;"
`

This change was introduced in https://github.com/ceph/ceph-csi/pull/2643

cc @pkalever @ceph/ceph-csi-contributors

### PR DESCRIPTION
**Pull request by pkalever**
# Describe what this PR does #

Currently, we support

mapOption: "krbd:v1,v2,v3;nbd:v1,v2,v3"

- By omitting `krbd:` or `nbd:`, the option(s) apply to
  rbdDefaultMounter which is krbd.
- A user can _override_ the options for a mounter by specifying `krbd:`
  or `nbd:`.
  mapOption: "v1,v2,v3;nbd:v1,v2,v3"
  is effectively the same as the 1st example.
- Sections are split by `;`.
- If users want to specify common options for both `krbd` and `nbd`,
  they should mention them twice.

But in case if the krbd or nbd specifc options contian `:` within them,
then the parsing is failing now.

E0301 10:19:13.615111 7348 utils.go:200] ID: 63 Req-ID:
0001-0009-rook-ceph-0000000000000001-fd37c41b-9948-11ec-ad32-0242ac110004
GRPC error: badly formatted map/unmap options:
"krbd:read_from_replica=localize,crush_location=zone:zone1;"

This patch fix the above case where the options itself contain `:`
delimitor
ex: krbd:v1,v2,v3=v31:v32;nbd:v1,v2,v3"

## Is there anything that requires special attention ##

Please note, if you are using such options which contain `:` delimiter,
then it is mandatory to specify the mounter-type.

Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

## Related issues ##

Fixes: #2910

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

File: internal/rbd/rbd_attach.go [hunk 1]
```diff
@@ -228,21 +228,19 @@ func setRbdNbdToolFeatures() {
...
-	)
 	for _, item := range strings.Split(mapOptions, ";") {
 		var mounter, options string
 		if item == "" {
 			continue
 		}
-		s := strings.Split(item, ":")
-		switch len(s) {
-		case noKeyLength:
+		s := strings.SplitN(item, ":", 2)
```
Comment (Madhu-1) [inline internal/rbd/rbd_attach.go:236]: Add unit testing for failed mapoptions

**Review by Rakshith-R — APPROVED** [review]
LGTM,

**Review by Madhu-1 — APPROVED** [review]

**Comment by humblec** [comment]
isnt it good to update this format or details in SC examples too  @pkalever ?
