### PR TITLE
cephfs: create subvolume with VolumeNamePrefix

### LINKED ISSUE #1879: Parameter "volumeNamePrefix:" for CEPHFS StorageClass doe snot work
# Describe the bug #

The parameter option `volumeNamePrefix:` for CephFS does not work, it creates still volumes with following syntax `/volumes/csi/csi-vol-47451c7b-71d5-11eb-aac5-e6ad37bf8738` on CEPH cluster.

Used config:  
```yaml
# (optional) Prefix to use for naming subvolumes.
# If omitted, defaults to "csi-vol-".
volumeNamePrefix: "k8sINT-"
```
# Environment details #

- Image/version of Ceph CSI driver :
```bash
quay.io/cephcsi/cephcsi                            v3.2.0
k8s.gcr.io/sig-storage/csi-node-driver-registrar   v2.1.0
k8s.gcr.io/sig-storage/csi-attacher                v3.1.0
k8s.gcr.io/sig-storage/csi-provisioner             v2.1.0
k8s.gcr.io/sig-storage/csi-resizer                 v1.1.0
k8s.gcr.io/sig-storage/csi-snapshotter             v4.0.0
docker.io/rancher/fleet-agent                      v0.3.3
```
- Helm chart version :
not used
- Kernel version :
Linux vm-k3os-mst1int 5.4.0-54-generic #60 SMP Fri Nov 20 17:09:10 UTC 2020 x86_64 GNU/Linux
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) :
default/not set in SC
- Kubernetes cluster version :
```jq
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5+k3s2", GitCommit:"746cf4031370f443bf1230272bc79f2f72de2869", GitTreeState:"clean", BuildDate:"2020-12-18T01:41:55Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Ceph cluster version :
`ceph version 15.2.8 (bdf3eebcd22d7d0b3dd4d5501bee5bac354d5b55) octopus (stable)`
# Steps to reproduce #
1. have Ceph Cluster and Kubernetes
2. have CEPH CSI setup done
3. create SC for CEPHFS use
```yaml
# (optional) Prefix to use for naming subvolumes.
# If omitted, defaults to "csi-vol-".
volumeNamePrefix: "k8sINT-"
```
4. create PVC

# Actual results #

Volume created with wrong prefix `/volumes/csi/csi-vol-47451c7b-71d5-11eb-aac5-e6ad37bf8738`
# Expected behavior #
Volume created like this  `/volumes/csi/k8sINT-47451c7b-71d5-11eb-aac5-e6ad37bf8738`

# Logs #

If the issue is in PVC creation, deletion, cloning please attach complete logs
of below containers.

- csi-provisioner and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.
```
2021-02-18T11:15:03.7244566Z stderr F I0218 11:15:03.724024       1 controller.go:731] CreateVolumeRequest name:"pvc-2923dcbe-482c-4112-aef0-685519dd48e8" capacity_range:<required_bytes:1073741824 > volume_capabilities:<mount:<mount_flags:"debug" > access_mode:<mode:MULTI_NODE_MULTI_WRITER > > parameters:<key:"clusterID" value:"1086f4b6-6737-11eb-9111-00155db31e91" > parameters:<key:"csi.storage.k8s.io/pv/name" value:"pvc-2923dcbe-482c-4112-aef0-685519dd48e8" > parameters:<key:"csi.storage.k8s.io/pvc/name" value:"csi-cephfs-pvc" > parameters:<key:"csi.storage.k8s.io/pvc/namespace" value:"testceph" > parameters:<key:"fsName" value:"cephfs" > parameters:<key:"pool" value:"cephfs_ecpool" > parameters:<key:"volumeNamePrefix" value:"k8sINT-" > secrets:<key:"adminID" value:"userk8sINT" > secrets:<key:"adminKey" value:"AQANmS1goNiSNRAAWbrd87IfLwOLtDgNAhA+Ag==" > secrets:<key:"userID" value:"userk8sINT" > secrets:<key:"userKey" value:"AQANmS1goNiSNRAAWbrd87IfLwOLtDgNAhA+Ag==" > 
2021-02-18T11:15:03.7244729Z stderr F I0218 11:15:03.724408       1 connection.go:182] GRPC call: /csi.v1.Controller/CreateVolume
2021-02-18T11:15:03.724881303Z stderr F I0218 11:15:03.724417       1 connection.go:183] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-2923dcbe-482c-4112-aef0-685519dd48e8","parameters":{"clusterID":"1086f4b6-6737-11eb-9111-00155db31e91","csi.storage.k8s.io/pv/name":"pvc-2923dcbe-482c-4112-aef0-685519dd48e8","csi.storage.k8s.io/pvc/name":"csi-cephfs-pvc","csi.storage.k8s.io/pvc/namespace":"testceph","fsName":"cephfs","pool":"cephfs_ecpool","volumeNamePrefix":"k8sINT-"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"mount_flags":["debug"]}},"access_mode":{"mode":5}}]}
2021-02-18T11:15:03.806276214Z stderr F I0218 11:15:03.806114       1 connection.go:185] GRPC response: {"volume":{"capacity_bytes":1073741824,"volume_context":{"clusterID":"1086f4b6-6737-11eb-9111-00155db31e91","csi.storage.k8s.io/pv/name":"pvc-2923dcbe-482c-4112-aef0-685519dd48e8","csi.storage.k8s.io/pvc/name":"csi-cephfs-pvc","csi.storage.k8s.io/pvc/namespace":"testceph","fsName":"cephfs","pool":"cephfs_ecpool","subvolumeName":"csi-vol-8c66c813-71da-11eb-80aa-9a0d7d85b950","volumeNamePrefix":"k8sINT-"},"volume_id":"0001-0024-1086f4b6-6737-11eb-9111-00155db31e91-0000000000000006-8c66c813-71da-11eb-80aa-9a0d7d85b950"}}
2021-02-18T11:15:03.806285914Z stderr F I0218 11:15:03.806227       1 connection.go:186] GRPC error: <nil>
2021-02-18T11:15:03.806300015Z stderr F I0218 11:15:03.806240       1 controller.go:762] create volume rep: {CapacityBytes:1073741824 VolumeId:0001-0024-1086f4b6-6737-11eb-9111-00155db31e91-0000000000000006-8c66c813-71da-11eb-80aa-9a0d7d85b950 VolumeContext:map[clusterID:1086f4b6-6737-11eb-9111-00155db31e91 csi.storage.k8s.io/pv/name:pvc-2923dcbe-482c-4112-aef0-685519dd48e8 csi.storage.k8s.io/pvc/name:csi-cephfs-pvc csi.storage.k8s.io/pvc/namespace:testceph fsName:cephfs pool:cephfs_ecpool subvolumeName:csi-vol-8c66c813-71da-11eb-80aa-9a0d7d85b950 volumeNamePrefix:k8sINT-] ContentSource:<nil> AccessibleTopology:[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
2021-02-18T11:15:03.806325515Z stderr F I0218 11:15:03.806297       1 controller.go:838] successfully created PV pvc-2923dcbe-482c-4112-aef0-685519dd48e8 for PVC csi-cephfs-pvc and csi volume name 0001-0024-1086f4b6-6737-11eb-9111-00155db31e91-0000000000000006-8c66c813-71da-11eb-80aa-9a0d7d85b950
2021-02-18T11:15:04.153963626Z stderr F I0218 11:15:03.806306       1 controller.go:854] successfully created PV {GCEPersistentDisk:nil AWSElasticBlockStore:nil HostPath:nil Glusterfs:nil NFS:nil RBD:nil ISCSI:nil Cinder:nil CephFS:nil FC:nil Flocker:nil FlexVolume:nil AzureFile:nil VsphereVolume:nil Quobyte:nil AzureDisk:nil PhotonPersistentDisk:nil PortworxVolume:nil ScaleIO:nil Local:nil StorageOS:nil CSI:&CSIPersistentVolumeSource{Driver:cephfs.csi.ceph.com,VolumeHandle:0001-0024-1086f4b6-6737-11eb-9111-00155db31e91-0000000000000006-8c66c813-71da-11eb-80aa-9a0d7d85b950,ReadOnly:false,FSType:,VolumeAttributes:map[string]string{clusterID: 1086f4b6-6737-11eb-9111-00155db31e91,csi.storage.k8s.io/pv/name: pvc-2923dcbe-482c-4112-aef0-685519dd48e8,csi.storage.k8s.io/pvc/name: csi-cephfs-pvc,csi.storage.k8s.io/pvc/namespace: testceph,fsName: cephfs,pool: cephfs_ecpool,storage.kubernetes.io/csiProvisionerIdentity: 1613646592438-8081-cephfs.csi.ceph.com,subvolumeName: csi-vol-8c66c813-71da-11eb-80aa-9a0d7d85b950,volumeNamePrefix: k8sINT-,},ControllerPublishSecretRef:nil,NodeStageSecretRef:&SecretReference{Name:csi-secret,Namespace:ceph,},NodePublishSecretRef:nil,ControllerExpandSecretRef:&SecretReference{Name:csi-secret,Namespace:ceph,},}}
```
If the issue is in PVC resize please attach complete logs of below containers.

- csi-resizer and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in snapshot creation and deletion please attach complete logs
of below containers.

- csi-snapshotter and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC mounting please attach complete logs of below containers.

- csi-rbdplugin/csi-cephfsplugin and driver-registrar container logs from
  plugin pod from the node where the mount is failing.

- if required attach dmesg logs.

**Note:-** If its a rbd issue please provide only rbd related logs, if its a
cephfs issue please provide cephfs logs.

# Additional context #

For example:

Any existing bug report which describe about the similar issue/behavior

### PR DESCRIPTION
**Pull request by Madhu-1**
when the user provides an option for VolumeNamePrefix create a subvolume with the prefix which will be easy for the user to identify the subvolume that belongs to the storageclass.
  
fixes #1879 
  
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
> failed to list rbd images with error failed to list images 2021-02-19T06:56:26.982+0000 7fbef7de2500  0 monclient(hunting): authenticate timed out after 300

one more instance https://github.com/ceph/ceph-csi/issues/1875

File: e2e/cephfs.go [hunk 1]
```diff
@@ -261,6 +261,52 @@ var _ = Describe("cephfs", func() {
...
+				err = deletePVCAndValidatePV(f.ClientSet, pvc, deployTimeout)
+				if err != nil {
+					e2elog.Failf("failed to  delete PVC with error %v", err)
+				}
+				validateSubvolumeCount(f, 0, fileSystemName, subvolumegroup)
+				err = deleteResource(cephfsExamplePath + "storageclass.yaml")
+				if err != nil {
+					e2elog.Failf("failed to delete storageclass with error %v", err)
+				}
+				if !foundIt {
```
Comment (agarwal-mudit) [inline e2e/cephfs.go:305]: Why not move this check just after the for loop?

Comment (Madhu-1) [reply e2e/cephfs.go:305]: just to clean up the pvc and storageclass created as part of this test same pattern is followed in RBD as well https://github.com/ceph/ceph-csi/blob/master/e2e/rbd.go#L771-L827

**Review by agarwal-mudit — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.20

Failed to deploy Rook:
```
Checking CEPH cluster state: []
Wait for rook deploy... 55s
Error from server: etcdserver: request timed out
```
