### PR TITLE
rbd-nbd: add tests with different accessModes and volumeModes

### LINKED ISSUE #2262: nbd-tracker: e2e for all access mode and volume mode
# Describe the bug #

The idea is to cover e2e tests as much as possible for access modes like:
ReadWriteOnce
ReadWriteMany
ReadOnlyMany

with FS mode and Block mode (as needed).

### PR DESCRIPTION
**Pull request by pkalever**
# Describe what this PR does #

* Added tests using different accessModes and volumeModes for rbd-nbd
  * ReadWriteOnce   [RWO]:
    * Currently available tests already cover it.
  * Read Write Many [RWX]:
    * Added test for Block Volume Mode only.
    * RWX is restricted for FileSystem VolumeMode at ceph-csi see https://github.com/ceph/ceph-csi/pull/261 for more details
  * ReadOnlyMany    [ROX]:
    *  Added tests for Block and Filesystem Volume Modes

* Added helper functions to use deployment kind objects

Note: This PR doesn't consider the new accessMode ReadWriteOncePod [RWOP], this will be a future item to cover tests for both krbd and nbd.

## Related issues ##
Fixes: #2262

### CODE REVIEW

File: e2e/deployment.go [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+// object.
+func loadAppDeployment(path string) (*appsv1.Deployment, error) {
+	deploy := appsv1.Deployment{}
+	if err := unmarshal(path, &deploy); err != nil {
+		return nil, err
+	}
+
+	for i := range deploy.Spec.Template.Spec.Containers {
+		deploy.Spec.Template.Spec.Containers[i].ImagePullPolicy = v1.PullIfNotPresent
+	}
```
Comment (Madhu-1) [inline e2e/deployment.go]: let's not override this one. expect this to set this in deployment.yaml

File: e2e/deployment.go [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+
+// deleteDeploymentApp deletes the deployment object.
+func deleteDeploymentApp(name, ns string, c kubernetes.Interface, t int) error {
+	timeout := time.Duration(t) * time.Minute
+	err := c.AppsV1().Deployments(ns).Delete(context.TODO(), name, metav1.DeleteOptions{})
+	if err != nil {
+		return fmt.Errorf("failed to delete deployment: %w", err)
+	}
+	start := time.Now()
+	e2elog.Logf("Waiting for deployment %v to be deleted", name)
```
Comment (Madhu-1) [inline e2e/deployment.go]:
```suggestion
	e2elog.Logf("Waiting for deployment %q to be deleted", name)
```

File: e2e/deployment.go [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+	return wait.PollImmediate(poll, timeout, func() (bool, error) {
+		_, err := c.AppsV1().Deployments(ns).Get(context.TODO(), name, metav1.GetOptions{})
+		if err != nil {
+			if isRetryableAPIError(err) {
+				return false, nil
+			}
+			if apierrs.IsNotFound(err) {
+				return true, nil
+			}
+			e2elog.Logf("%s deployment  to be deleted (%d seconds elapsed)", name, int(time.Since(start).Seconds()))
```
Comment (Madhu-1) [inline e2e/deployment.go]:
```suggestion
e2elog.Logf("%q deployment  to be deleted (%d seconds elapsed)", name, int(time.Since(start).Seconds()))

```

File: e2e/deployment.go [hunk 4]
```diff
@@ -0,0 +1,105 @@
...
+
+		return false, nil
+	})
+}
+
+// waitForDeploymentInAvailableState wait for deployment to be in Available
+// condition.
+func waitForDeploymentInAvailableState(name, ns string, c kubernetes.Interface, t int) error {
+	timeout := time.Duration(t) * time.Minute
+	e2elog.Logf("Waiting up to %v to be in Available state", name)
```
Comment (Madhu-1) [inline e2e/deployment.go]:
```
	e2elog.Logf("Waiting up to %q to be in Available state", name)
```

File: e2e/deployment.go [hunk 5]
```diff
@@ -0,0 +1,105 @@
...
+
+	return wait.PollImmediate(poll, timeout, func() (bool, error) {
+		d, err := c.AppsV1().Deployments(ns).Get(context.TODO(), name, metav1.GetOptions{})
+		if err != nil {
+			return false, err
+		}
```
Comment (Madhu-1) [inline e2e/deployment.go]: add below check also

```go
if isRetryableAPIError(err) {
	return false, nil
}
```

File: e2e/rbd.go [hunk 6]
```diff
@@ -545,6 +547,374 @@ var _ = Describe("RBD", func() {
...
+					defaultSCName,
+					nil,
+					map[string]string{
+						"mounter":         "rbd-nbd",
+						"mapOptions":      nbdMapOptions,
+						"cephLogStrategy": e2eDefaultCephLogStrategy,
+					},
+					deletePolicy)
+				if err != nil {
+					e2elog.Failf("failed to create storageclass with error %v", err)
```
Comment (Madhu-1) [inline e2e/rbd.go]: `failed to create storageclass with error %v` to `failed to create storageclass: %v` please take care of this one and remove `with error` in all the places which are getting introduced in this PR. we are removing it from all the places

File: e2e/rbd.go [hunk 7]
```diff
@@ -545,6 +547,374 @@ var _ = Describe("RBD", func() {
...
+					// Make sure pod is running
+					err = waitForPodInRunningState(pod.Name, app.Namespace, f.ClientSet, deployTimeout, noError)
+					if err != nil {
+						e2elog.Failf("pod %q, not in running state, error %v", pod.Name, err)
+					}
+					_, _, err = execCommandInPodWithName(f, cmd, pod.Name, pod.Spec.Containers[0].Name, app.Namespace)
+					if err != nil {
+						e2elog.Failf("command %q failed with error %v", cmd, err)
+					}
+				}
```
Comment (Madhu-1) [inline e2e/rbd.go]: instead of checking all the pods in a deployment how about checking deployment status `waitForDeploymentComplete`  it self?

**Review by Madhu-1 — COMMENTED** [review]
just checking, is it possible to have a common helper function to avoid code duplication?

File: e2e/rbd.go (hunk 6 above)
Comment (pkalever) [reply e2e/rbd.go]: Why are we using this style only for storageclass msg?
Are you saying remove 'with error %v' and replace it with style ': %v' for all the logs?

File: e2e/rbd.go (hunk 7 above)
Comment (pkalever) [reply e2e/rbd.go]: Good idea :+1:

File: e2e/rbd.go (hunk 6 above)
Comment (Madhu-1) [reply e2e/rbd.go]: no for all the errors we are `with error` and replacing it with `: %v` https://github.com/ceph/ceph-csi/issues/2371

Comment (pkalever) [reply e2e/rbd.go]: Sorry I didn't follow this statement. Could you please repeat for me :-)

Comment (pkalever) [reply e2e/rbd.go]: I see it from link, you are referring to all the logs with 'with error %v' to be replaced by ': %v'

Comment (Madhu-1) [reply e2e/rbd.go]: yes, correct. please take care of it.

Comment (pkalever) [reply e2e/rbd.go]: Done now, thanks!

**Comment by pkalever** [comment]
> just checking, is it possible to have a common helper function to avoid code duplication?

Yes! At some point we need to keep efforts on writing more generic code for our e2e, it would be a big refactor of e2e/xyz.go. [which would be a different topic IMO]

Coming to this PR, it's adding tests just like any other test. You might have noticed I have already generalized the code into e2e/deployment.go as much as possible. If you feel like I missed something and we can move some more pieces into a common functions feel free to point it

Thanks!

File: e2e/deployment.go [hunk 8]
```diff
@@ -0,0 +1,106 @@
+package e2e
```
Comment (nixpanic) [inline e2e/deployment.go:17]: please add the license and copyright header

File: e2e/deployment.go [hunk 9]
```diff
@@ -0,0 +1,106 @@
...
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/apimachinery/pkg/util/wait"
+	"k8s.io/client-go/kubernetes"
+	deploymentutil "k8s.io/kubernetes/pkg/controller/deployment/util"
+	"k8s.io/kubernetes/test/e2e/framework"
+	e2elog "k8s.io/kubernetes/test/e2e/framework/log"
+)
+
+// execCommandInPodWithName run command in pods using podName.
+func execCommandInPodWithName(f *framework.Framework, c, pn, cn, ns string) (string, string, error) {
```
Comment (nixpanic) [inline e2e/deployment.go]: It really helps to use variables/parameters with a descriptive name. `c`, `pn` and `cn` do not tell me anything. `ns` usually stands for namespace, so  that's fine.

File: examples/rbd/fs-pod-rx.yaml [hunk 10]
```diff
@@ -0,0 +1,29 @@
...
+    spec:
+      containers:
+        - name: web-server
+          image: docker.io/library/nginx:latest
+          imagePullPolicy: IfNotPresent
+          volumeMounts:
+            - name: mypvc
+              mountPath: /var/lib/www/html
+      volumes:
+        - name: mypvc
```
Comment (nixpanic) [inline examples/rbd/fs-pod-rx.yaml]: This may not work when the pods run on different nodes, do not include that as an example as it might confuse users trying it out.

File: examples/rbd/block-pod-rx.yaml [hunk 11]
```diff
@@ -0,0 +1,30 @@
...
+          image: quay.io/centos/centos:latest
+          imagePullPolicy: IfNotPresent
+          command: ["/bin/sleep", "infinity"]
+          volumeDevices:
+            - name: data
+              devicePath: /dev/xvda
+      volumes:
+        - name: data
+          persistentVolumeClaim:
+            claimName: rx-pvc
```
Comment (nixpanic) [inline examples/rbd/block-pod-rx.yaml]: where does `rx-pvc` come from?

**Review by nixpanic — CHANGES_REQUESTED** [review]

File: e2e/deployment.go (hunk 9 above)
Comment (pkalever) [reply e2e/deployment.go]: Sure, parameter naming can be improved :+1:

File: e2e/deployment.go (hunk 8 above)
Comment (pkalever) [reply e2e/deployment.go:17]: I guess all the files in e2e/*.go miss the copyright info, I thought there might be some reason for this :-)
I will fix this up, thanks!

File: examples/rbd/fs-pod-rx.yaml (hunk 10 above)
Comment (pkalever) [reply examples/rbd/fs-pod-rx.yaml]: Yeah, could you also please suggest a better location for these files?

File: examples/rbd/block-pod-rx.yaml (hunk 11 above)
Comment (pkalever) [reply examples/rbd/block-pod-rx.yaml]: These templates can be used by both ROX and RWX PVC types, hence I just named it `rx-pvc`

These should be created by the test case. In the test case we are overriding this with:
```
app.Spec.Template.Spec.Volumes[0].PersistentVolumeClaim.ClaimName = pvc.Name
```

Comment (nixpanic) [reply examples/rbd/block-pod-rx.yaml]: Until now, all the examples can be applied without modifications. Please re-use one of the existing PVC-names for this example too.

Comments in the examples are not forbidden either, and it may make things easier to understand too!

File: e2e/deployment.go (hunk 8 above)
Comment (nixpanic) [reply e2e/deployment.go:17]: Yeah, they are missing in lots of files. Adding the license afterwards is bad practice... So, we'll try to add the license when new files get created.

Comment (pkalever) [reply e2e/deployment.go:17]: Ah! I almost made the changes locally and made a commit to fixing the license in all the files missing them ;-)
I will drop if that turns out to be a bad practice.

File: examples/rbd/fs-pod-rx.yaml (hunk 10 above)
Comment (nixpanic) [reply examples/rbd/fs-pod-rx.yaml]: Rename the file to `fs-pod-rox.yaml` and make the appropriate changes? Including a ROX example is fine.

File: examples/rbd/block-pod-rx.yaml (hunk 11 above)
Comment (pkalever) [reply examples/rbd/block-pod-rx.yaml]: I saw they are not consistent in all the examples, just that I didn't want to create more yamls for PVC's for just this tests, hence decided to reuse existing pvc.yaml with some tweaking in the tests itself like:

```
pvc.Spec.AccessModes = []v1.PersistentVolumeAccessMode{v1.ReadWriteMany}
volumeMode := v1.PersistentVolumeBlock                                  
pvc.Spec.VolumeMode = &volumeMode                                       
```


```
$ git grep "claimName"  examples/rbd/
examples/rbd/block-pod-clone.yaml:        claimName: block-pvc-clone
examples/rbd/pod-clone.yaml:        claimName: rbd-pvc-clone
examples/rbd/pod-restore.yaml:        claimName: rbd-pvc-restore
examples/rbd/pod.yaml:        claimName: rbd-pvc
examples/rbd/raw-block-pod.yaml:        claimName: raw-block-pvc
```

Anyway, I can just go with what's inside pvc.yaml :+1:

File: examples/rbd/fs-pod-rx.yaml (hunk 10 above)
Comment (pkalever) [reply examples/rbd/fs-pod-rx.yaml]: Yeah, good idea :+1:

File: examples/rbd/fs-pod-rox.yaml [hunk 12]
```diff
@@ -0,0 +1,29 @@
+---
+apiVersion: apps/v1
```
Comment (humblec) [inline examples/rbd/fs-pod-rox.yaml]: rename this file to start with `pod-fs`

File: e2e/rbd.go [hunk 13]
```diff
@@ -58,6 +58,8 @@ var (
 	appSmartClonePath      = rbdExamplePath + "pod-clone.yaml"
 	appBlockSmartClonePath = rbdExamplePath + "block-pod-clone.yaml"
 	snapshotPath           = rbdExamplePath + "snapshot.yaml"
+	rxAppPath              = rbdExamplePath + "fs-pod-rox.yaml"
```
Comment (humblec) [inline e2e/rbd.go]: start with app..

File: examples/rbd/fs-pod-rox.yaml (hunk 12 above)
Comment (pkalever) [reply examples/rbd/fs-pod-rox.yaml]: There is already block-pod-clone.yaml, Hence I made up block-pod-rox.yaml and fs-pod-rox.yaml :-)

File: e2e/rbd.go (hunk 13 above)
Comment (pkalever) [reply e2e/rbd.go]: There is rawAppPath already! Hence I just used rxRawAppPath

**Comment by pkalever** [comment]
@humblec Thanks for the review, the comments are cosmic. AFAIK there is no strict naming convention that we are binding to in e2e, I would love to see if anyone else has objections on the naming.

**Comment by pkalever** [comment]
```
X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute


```

https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.21/detail/mini-e2e_k8s-1.21/1651/

File: e2e/deployment.go [hunk 14]
```diff
@@ -0,0 +1,127 @@
...
+	_, err := clientSet.AppsV1().Deployments(app.Namespace).Create(context.TODO(), app, metav1.CreateOptions{})
+	if err != nil {
+		return fmt.Errorf("failed to create deploy: %w", err)
+	}
+
+	return waitForDeploymentInAvailableState(app.Name, app.Namespace, clientSet, deployTimeout)
+}
+
+// deleteDeploymentApp deletes the deployment object.
+func deleteDeploymentApp(name, ns string, clientSet kubernetes.Interface, deployTimeout int) error {
```
Comment (nixpanic) [inline e2e/deployment.go]: Consider using `clientSet` as 1st argument to all functions that need it. Some common ordering of arguments is pretty helpful when using these functions.

There are quite some functions already that make it user unfriendly. We should clean that up at one point, but that does not have priority. New functions, should probably use arguments in `framework/clientset, ..., timeout` order.

File: e2e/rbd.go (hunk 13 above)
Comment (humblec) [reply e2e/rbd.go]: most of the variable names regarding the app starts with app.., so I would suggest to be consistent on the naming. If one other correction is required , please feel free to do so.

**Comment by humblec** [comment]
> @humblec Thanks for the review, the comments are cosmic. AFAIK there is no strict naming convention that we are binding to in e2e, I would love to see if anyone else has objections on the naming.

@nixpanic wdyt?

File: e2e/deployment.go [hunk 15]
```diff
@@ -0,0 +1,173 @@
...
+	apierrs "k8s.io/apimachinery/pkg/api/errors"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/apimachinery/pkg/util/wait"
+	"k8s.io/client-go/kubernetes"
+	deploymentutil "k8s.io/kubernetes/pkg/controller/deployment/util"
+	"k8s.io/kubernetes/test/e2e/framework"
+	e2elog "k8s.io/kubernetes/test/e2e/framework/log"
+)
+
+// execCommandInPodWithName run command in pods using podName.
```
Comment (humblec) [inline e2e/deployment.go]: run command in pod?

File: e2e/deployment.go [hunk 16]
```diff
@@ -0,0 +1,173 @@
...
+	timeout := time.Duration(deployTimeout) * time.Minute
+	err := clientSet.AppsV1().Deployments(ns).Delete(context.TODO(), name, metav1.DeleteOptions{})
+	if err != nil {
+		return fmt.Errorf("failed to delete deployment: %w", err)
+	}
+	start := time.Now()
+	e2elog.Logf("Waiting for deployment %q to be deleted", name)
+
+	return wait.PollImmediate(poll, timeout, func() (bool, error) {
+		_, err := clientSet.AppsV1().Deployments(ns).Get(context.TODO(), name, metav1.GetOptions{})
```
Comment (humblec) [inline e2e/deployment.go:90]: may be better to be consistent on the clientSet variable like other e2e tests? like `c`?

File: e2e/deployment.go [hunk 17]
```diff
@@ -0,0 +1,173 @@
...
+
+			return false, fmt.Errorf("failed to get deployment: %w", err)
+		}
+
+		return false, nil
+	})
+}
+
+// waitForDeploymentInAvailableState wait for deployment to be in Available
+// condition.
```
Comment (humblec) [inline e2e/deployment.go]: condition/state?

File: e2e/deployment.go [hunk 18]
```diff
@@ -0,0 +1,173 @@
...
+		// When the deployment status and its underlying resources reach the
+		// desired state, we're done
+		if deployment.Status.Replicas == deployment.Status.ReadyReplicas {
+			return true, nil
+		}
+		e2elog.Logf(
+			"deployment status: expected replica count %d running replica count %d",
+			deployment.Status.Replicas,
+			deployment.Status.ReadyReplicas)
+		reason = fmt.Sprintf("deployment status: %#v", deployment.Status.String())
```
Comment (humblec) [inline e2e/deployment.go:159]: why `%#v` ?

File: e2e/deployment.go [hunk 19]
```diff
@@ -0,0 +1,173 @@
...
+
+		return false, nil
+	})
+
+	if errors.Is(err, wait.ErrWaitTimeout) {
+		err = fmt.Errorf("%s", reason)
+	}
+	if err != nil {
+		return fmt.Errorf("error waiting for deployment %q status to match expectation: %w", name, err)
```
Comment (humblec) [inline e2e/deployment.go]: to match desired state..

File: e2e/rbd.go [hunk 20]
```diff
@@ -545,6 +547,371 @@ var _ = Describe("RBD", func() {
...
+				if err != nil {
+					e2elog.Failf("failed to delete snapshot: %v", err)
+				}
+				// delete parent pvc
+				err = deletePVCAndValidatePV(f.ClientSet, pvc, deployTimeout)
+				if err != nil {
+					e2elog.Failf("failed to delete PVC: %v", err)
+				}
+				// validate created backend rbd images
+				validateRBDImageCount(f, 0, defaultRBDPool)
```
Comment (humblec) [inline e2e/rbd.go:774]: validate in trash too?

File: examples/rbd/fs-pod-rox.yaml [hunk 21]
```diff
@@ -0,0 +1,29 @@
...
+kind: Deployment
+metadata:
+  name: pod-fs-rx-volume
```
Comment (humblec) [inline examples/rbd/fs-pod-rox.yaml]: s/rx/rox .. or iow, thats the accessmode.

File: e2e/deployment.go (hunk 15 above)
Comment (pkalever) [reply e2e/deployment.go]: Sure

File: e2e/deployment.go (hunk 16 above)
Comment (pkalever) [reply e2e/deployment.go:90]: I got some valid review comments from Niels to make the params/args of the function descriptive, hence at least in the function definitions inside deployment.go I'm making sure that params naming are readable.

File: e2e/deployment.go (hunk 17 above)
Comment (pkalever) [reply e2e/deployment.go]: sure

File: e2e/deployment.go (hunk 18 above)
Comment (pkalever) [reply e2e/deployment.go:159]: This function is just a move from the previous pod.go, I have not made any logic changes to it.

If someone confirms there is no meaning for `%#v` use I can remove it, at least I don't know :-)

File: e2e/deployment.go [hunk 22]
```diff
@@ -0,0 +1,173 @@
...
+			return false, err
+		}
+		cond := deploymentutil.GetDeploymentCondition(d.Status, appsv1.DeploymentAvailable)
+
+		return cond != nil, nil
+	})
+}
+
+// Waits for the deployment to complete.
+func waitForDeploymentComplete(name, ns string, clientSet kubernetes.Interface, deployTimeout int) error {
```
Comment (humblec) [inline e2e/deployment.go]: it is better to keep an order , that said, the interfaces like framework, clientset..etc can be kept as first args followed with other args .

File: e2e/deployment.go (hunk 19 above)
Comment (pkalever) [reply e2e/deployment.go]: sure

File: examples/rbd/fs-pod-rox.yaml (hunk 21 above)
Comment (pkalever) [reply examples/rbd/fs-pod-rox.yaml]: I wanted to use the template for both ROX and RWX hence I named it RX intentionally.

What IOW stands for ?

File: e2e/deployment.go (hunk 22 above)
Comment (pkalever) [reply e2e/deployment.go]: Yes, I'm working on it now based on previous comments from Niels. Thanks!

File: e2e/deployment.go (hunk 14 above)
Comment (pkalever) [reply e2e/deployment.go]: Yes, make sense Niels. working on this now. Thanks!

File: e2e/deployment.go (hunk 18 above)
Comment (pkalever) [reply e2e/deployment.go:159]: Doesn't look like unintentional:
https://github.com/kubernetes/kubernetes/blob/master/test/utils/deployment.go#L103

File: examples/rbd/fs-pod-rox.yaml (hunk 21 above)
Comment (humblec) [reply examples/rbd/fs-pod-rox.yaml]: if the plan is to use the same template for both (rox and rwx) , may be we dont need rx over there.  `r` ->read, `w`->write, `x` -many is the abbreviation when it comes to accesmode. so `rx` is confusing. so better to remove `rx` from the name itself . 
iow-> in other words :)

File: e2e/rbd.go (hunk 20 above)
Comment (pkalever) [reply e2e/rbd.go:774]: sure :+1:

File: examples/rbd/fs-pod-rox.yaml (hunk 21 above)
Comment (pkalever) [reply examples/rbd/fs-pod-rox.yaml]: We already have pod.yaml and raw-block-pod.yaml already for ROX.

If  pod-fs-rx-volume.yaml and pod-block-rx-volume.yaml are confusing should I name them fs-vol-deployment.yaml and block-vol-deployment.yml ?

**Comment by pkalever** [comment]
@Madhu-1 @nixpanic @humblec @ceph/ceph-csi-contributors please help with the review :-)

File: e2e/rbd.go [hunk 23]
```diff
@@ -545,6 +547,402 @@ var _ = Describe("RBD", func() {
...
+				err = deletePVCAndDeploymentApp(f, "", pvc, app)
+				if err != nil {
+					e2elog.Failf("failed to delete PVC and application: %v", err)
+				}
+				// validate created backend rbd images
+				validateRBDImageCount(f, 0, defaultRBDPool)
+				// validate images in trash
+				err = waitToRemoveImagesFromTrash(f, defaultRBDPool, deployTimeout)
+				if err != nil {
+					e2elog.Failf("failed to validate rbd images in pool %s trash with error %v", rbdOptions(defaultRBDPool), err)
```
Comment (Madhu-1) [inline e2e/rbd.go]: `failed to validate rbd images in pool %s trash with error %v` to `failed to validate rbd images in pool %s trash: %v`

File: e2e/rbd.go [hunk 24]
```diff
@@ -545,6 +547,402 @@ var _ = Describe("RBD", func() {
...
+				if err != nil {
+					e2elog.Failf("failed to delete storageclass: %v", err)
+				}
+				err = createRBDStorageClass(f.ClientSet, f, defaultSCName, nil, nil, deletePolicy)
+				if err != nil {
+					e2elog.Failf("failed to create storageclass: %v", err)
+				}
+			})
+
+			By("Create ROX+FS Mode PVC and bind to multiple pods via deployment using rbd-nbd mounter", func() {
```
Comment (Madhu-1) [inline e2e/rbd.go:668]: for ROX use PVC to PVC cloning instead of creating a snapshot and restoring it?

File: e2e/rbd.go [hunk 25]
```diff
@@ -545,6 +547,402 @@ var _ = Describe("RBD", func() {
...
+				if err != nil {
+					e2elog.Failf("failed to delete storageclass: %v", err)
+				}
+				err = createRBDStorageClass(f.ClientSet, f, defaultSCName, nil, nil, deletePolicy)
+				if err != nil {
+					e2elog.Failf("failed to create storageclass: %v", err)
+				}
+			})
+
+			By("Create ROX+Block Mode PVC and bind to multiple pods via deployment using rbd-nbd mounter", func() {
```
Comment (Madhu-1) [inline e2e/rbd.go:790]: same here as well use PVC to PVC cloning?

File: examples/rbd/block-pod-rox.yaml [hunk 26]
```diff
@@ -0,0 +1,30 @@
+---
+apiVersion: apps/v1
```
Comment (Madhu-1) [inline examples/rbd/block-pod-rox.yaml]: change the file name from pod to deployment

File: examples/rbd/fs-pod-rox.yaml [hunk 27]
```diff
@@ -0,0 +1,29 @@
+---
```
Comment (Madhu-1) [inline examples/rbd/fs-pod-rox.yaml]: change the file name from pod to deployment

**Review by Madhu-1 — COMMENTED** [review]
few nits and questions

File: e2e/rbd.go (hunk 24 above)
Comment (pkalever) [reply e2e/rbd.go:668]: @Madhu-1 I was following "create ROX PVC clone and mount it to multiple pods" test.

File: e2e/rbd.go (hunk 23 above)
Comment (pkalever) [reply e2e/rbd.go]: OK

File: examples/rbd/block-pod-rox.yaml (hunk 26 above)
Comment (pkalever) [reply examples/rbd/block-pod-rox.yaml]: OK

File: examples/rbd/fs-pod-rox.yaml (hunk 27 above)
Comment (pkalever) [reply examples/rbd/fs-pod-rox.yaml]: OK

File: e2e/rbd.go (hunk 24 above)
Comment (Madhu-1) [reply e2e/rbd.go:668]: just trying to keep this case simple and also reduce the testing time. we can update the existing test cases so that it will also reduce the testing time also

Comment (pkalever) [reply e2e/rbd.go:668]: :+1:

File: examples/rbd/fs-vol-deployment.yaml [hunk 28]
```diff
@@ -0,0 +1,29 @@
+---
```
Comment (Madhu-1) [inline examples/rbd/fs-vol-deployment.yaml]: This is not useful at all for the users right as it's a replica `3` and pod can come upon any node? how about generating this template in e2e  tests only?

**Review by Madhu-1 — COMMENTED** [review]
left question LGTM

File: examples/rbd/fs-vol-deployment.yaml (hunk 28 above)
Comment (pkalever) [reply examples/rbd/fs-vol-deployment.yaml]: For me, reading the template would be much clear to understand :-) Let's not complicate it? (Just give it an another thought in this direction). Maybe you can suggest to me a location that holds templates for e2e tests only? I will consider moving this there.

Comment (Madhu-1) [reply examples/rbd/fs-vol-deployment.yaml]: IMO this is only for testing which is not useful for users. this can be done in the same way as https://github.com/ceph/ceph-csi/blob/devel/e2e/utils.go#L261-L303 having a helper function to return the deployment is useful.

Comment (pkalever) [reply examples/rbd/fs-vol-deployment.yaml]: I understand your point Madhu. What I'm saying is let's just keep the deployment in YAML form for readability. Will it be a concern if I move these templates to e2e/rbd/templates/ ?

Thanks in adavance!

Comment (Madhu-1) [reply examples/rbd/fs-vol-deployment.yaml]: am fine with it as long as it's not for users. lets hear from others also

**Comment by pkalever** [comment]
@mergifyio rebase

**Comment by pkalever** [comment]
@nixpanic @humblec @Madhu-1 please review. Thanks!

File: e2e/deployment.go (hunk 22 above)
Comment (Madhu-1) [reply e2e/deployment.go]: @pkalever the clientset should be placed before the strings. this is most common practice

Comment (Madhu-1) [reply e2e/deployment.go]: even as it's a copy-paste from other files. can you please correct it.

**Review by Madhu-1 — COMMENTED** [review]
LGTM. need one correction in e2e.

**Comment by pkalever** [comment]
> LGTM. need one correction in e2e.

@Madhu-1 fixed now, please take a look

**Review by Madhu-1 — DISMISSED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Comment by pkalever** [comment]
/retest ci/centos/mini-e2e-helm/k8s-1.20

```
X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute

```

**Comment by pkalever** [comment]
@nixpanic @humblec could you please provide your review. Thanks!

**Comment by pkalever** [comment]
@Mergifyio rebase

**Review by nixpanic — APPROVED** [review]

**Comment by pkalever** [comment]
@Mergifyio refresh

**Comment by Madhu-1** [comment]
added DNM to get https://github.com/ceph/ceph-csi/pull/2669 merged which is second in queue.

**Comment by Madhu-1** [comment]
removed DNM as #2669 is merged
