### PR TITLE
ci: Use temporary directory for unit tests

### LINKED ISSUE #4617: Failed to run `make go-test` failed locally
```
=== NAME  TestReadAffinity_GetReadAffinityMapOptions
    nodeserver_test.go:249: failed to create directory /etc/ceph-csi-config: mkdir /etc/ceph-csi-config: permission denied
    nodeserver_test.go:253: failed to write /etc/ceph-csi-config/config.json file content: open /etc/ceph-csi-config/config.json: no such file or directory
=== RUN   TestReadAffinity_GetReadAffinityMapOptions/Enabled_in_cluster-1_and_Enabled_in_CLI
=== CONT  TestIsMigrationVolID/wrong_volume_ID
=== CONT  TestIsMigrationVolID/wrong_mons_prefixed_volume_ID
=== CONT  TestIsMigrationVolID/Wrong_volume_ID
--- PASS: TestIsMigrationVolID (0.00s)
    --- PASS: TestIsMigrationVolID/correct_volume_ID (0.00s)
    --- PASS: TestIsMigrationVolID/wrong_image_prefixed_volume_ID (0.00s)
    --- PASS: TestIsMigrationVolID/wrong_volume_ID (0.00s)
    --- PASS: TestIsMigrationVolID/wrong_mons_prefixed_volume_ID (0.00s)
    --- PASS: TestIsMigrationVolID/Wrong_volume_ID (0.00s)
--- PASS: TestNodeServer_appendReadAffinityMapOptions (0.00s)
    --- PASS: TestNodeServer_appendReadAffinityMapOptions/both_empty_mapOptions_and_crushLocationMap (0.00s)
    --- PASS: TestNodeServer_appendReadAffinityMapOptions/filled_mapOptions,_empty_readAffinityMapOptions_&_non-default_mounter (0.00s)
    --- PASS: TestNodeServer_appendReadAffinityMapOptions/filled_mapOptions,_filled_crushLocationMap_&_non-default_mounter (0.00s)
    --- PASS: TestNodeServer_appendReadAffinityMapOptions/filled_mapOptions,_empty_readAffinityMapOptions_&_default_mounter (0.00s)
    --- PASS: TestNodeServer_appendReadAffinityMapOptions/empty_mapOptions,_filled_crushLocationMap_&_default_mounter (0.00s)
    --- PASS: TestNodeServer_appendReadAffinityMapOptions/filled_mapOptions,_filled_crushLocationMap_&_default_mounter (0.00s)
    --- PASS: TestNodeServer_appendReadAffinityMapOptions/empty_mapOptions,_filled_crushLocationMap_&_non-default_mounter (0.00s)
=== CONT  TestParseMigrationVolID/correct_volume_ID
=== CONT  TestParseMigrationVolID/volume_ID_without_'mon-'_prefix_string
=== CONT  TestParseMigrationVolID/volume_ID_with_unallowed_image_name
=== CONT  TestParseMigrationVolID/volume_ID_with_unallowed_migration_version_string
=== CONT  TestParseMigrationVolID/correct_volume_ID_with_'_'_pool_name
=== CONT  TestParseMigrationVolID/correct_volume_ID_with_more_than_one_mon
=== CONT  TestParseMigrationVolID/correct_volume_ID_with_single_mon
=== CONT  TestParseMigrationVolID/volume_ID_without_pool
=== CONT  TestParseMigrationVolID/volume_ID_without_image
=== CONT  TestParseMigrationVolID/volume_ID_without_mons
--- PASS: TestParseMigrationVolID (0.00s)
    --- PASS: TestParseMigrationVolID/correct_volume_ID (0.00s)
    --- PASS: TestParseMigrationVolID/volume_ID_without_'mon-'_prefix_string (0.00s)
    --- PASS: TestParseMigrationVolID/volume_ID_with_unallowed_image_name (0.00s)
    --- PASS: TestParseMigrationVolID/volume_ID_with_unallowed_migration_version_string (0.00s)
    --- PASS: TestParseMigrationVolID/correct_volume_ID_with_'_'_pool_name (0.00s)
    --- PASS: TestParseMigrationVolID/correct_volume_ID_with_more_than_one_mon (0.00s)
    --- PASS: TestParseMigrationVolID/volume_ID_without_pool (0.00s)
    --- PASS: TestParseMigrationVolID/volume_ID_without_image (0.00s)
    --- PASS: TestParseMigrationVolID/volume_ID_without_mons (0.00s)
    --- PASS: TestParseMigrationVolID/correct_volume_ID_with_single_mon (0.00s)
=== PAUSE TestReadAffinity_GetReadAffinityMapOptions/Enabled_in_cluster-1_and_Enabled_in_CLI
E0515 08:45:59.837777 2433752 rbd_util.go:361] krbd feature "journaling" not supported
--- PASS: TestIsKrbdFeatureSupported (0.00s)
    --- PASS: TestIsKrbdFeatureSupported/supported_feature (0.00s)
    --- PASS: TestIsKrbdFeatureSupported/not_supported_feature (0.00s)
=== RUN   TestReadAffinity_GetReadAffinityMapOptions/Disabled_in_cluster-2_and_Enabled_in_CLI
E0515 08:45:59.838103 2433752 nodeserver.go:123] failed to parse value of "myOption": ""
E0515 08:45:59.841158 2433752 nodeserver.go:123] failed to parse value of "myOption": "non-boolean"
=== PAUSE TestReadAffinity_GetReadAffinityMapOptions/Disabled_in_cluster-2_and_Enabled_in_CLI
--- PASS: TestParseBoolOption (0.00s)
=== RUN   TestReadAffinity_GetReadAffinityMapOptions/Enabled_in_cluster-3_with_empty_crush_labels_and_Enabled_in_CLI
=== PAUSE TestReadAffinity_GetReadAffinityMapOptions/Enabled_in_cluster-3_with_empty_crush_labels_and_Enabled_in_CLI
=== RUN   TestReadAffinity_GetReadAffinityMapOptions/Enabled_in_cluster-3_with_empty_crush_labels_and_Disabled_in_CLI
=== PAUSE TestReadAffinity_GetReadAffinityMapOptions/Enabled_in_cluster-3_with_empty_crush_labels_and_Disabled_in_CLI
=== RUN   TestReadAffinity_GetReadAffinityMapOptions/Absent_in_cluster-4_and_Enabled_in_CLI
=== PAUSE TestReadAffinity_GetReadAffinityMapOptions/Absent_in_cluster-4_and_Enabled_in_CLI
=== CONT  TestReadAffinity_GetReadAffinityMapOptions/Enabled_in_cluster-1_and_Enabled_in_CLI
=== CONT  TestReadAffinity_GetReadAffinityMapOptions/Enabled_in_cluster-3_with_empty_crush_labels_and_Disabled_in_CLI
=== CONT  TestReadAffinity_GetReadAffinityMapOptions/Enabled_in_cluster-3_with_empty_crush_labels_and_Enabled_in_CLI
=== CONT  TestReadAffinity_GetReadAffinityMapOptions/Disabled_in_cluster-2_and_Enabled_in_CLI
=== CONT  TestReadAffinity_GetReadAffinityMapOptions/Absent_in_cluster-4_and_Enabled_in_CLI
=== NAME  TestReadAffinity_GetReadAffinityMapOptions/Enabled_in_cluster-3_with_empty_crush_labels_and_Enabled_in_CLI
    nodeserver_test.go:310: 
        	Error Trace:	/home/mrajanna/workspace/src/github.com/ceph/ceph-csi/internal/rbd/nodeserver_test.go:310
        	Error:      	error fetching configuration for cluster ID "cluster-3": open /etc/ceph-csi-config/config.json: no such file or directory
        	Test:       	TestReadAffinity_GetReadAffinityMapOptions/Enabled_in_cluster-3_with_empty_crush_labels_and_Enabled_in_CLI
=== NAME  TestReadAffinity_GetReadAffinityMapOptions/Enabled_in_cluster-3_with_empty_crush_labels_and_Disabled_in_CLI
    nodeserver_test.go:310: 
        	Error Trace:	/home/mrajanna/workspace/src/github.com/ceph/ceph-csi/internal/rbd/nodeserver_test.go:310
        	Error:      	error fetching configuration for cluster ID "cluster-3": open /etc/ceph-csi-config/config.json: no such file or directory
        	Test:       	TestReadAffinity_GetReadAffinityMapOptions/Enabled_in_cluster-3_with_empty_crush_labels_and_Disabled_in_CLI
=== NAME  TestReadAffinity_GetReadAffinityMapOptions/Disabled_in_cluster-2_and_Enabled_in_CLI
    nodeserver_test.go:310: 
        	Error Trace:	/home/mrajanna/workspace/src/github.com/ceph/ceph-csi/internal/rbd/nodeserver_test.go:310
        	Error:      	error fetching configuration for cluster ID "cluster-2": open /etc/ceph-csi-config/config.json: no such file or directory
        	Test:       	TestReadAffinity_GetReadAffinityMapOptions/Disabled_in_cluster-2_and_Enabled_in_CLI
=== NAME  TestReadAffinity_GetReadAffinityMapOptions/Enabled_in_cluster-1_and_Enabled_in_CLI
    nodeserver_test.go:310: 
        	Error Trace:	/home/mrajanna/workspace/src/github.com/ceph/ceph-csi/internal/rbd/nodeserver_test.go:310
        	Error:      	error fetching configuration for cluster ID "cluster-1": open /etc/ceph-csi-config/config.json: no such file or directory
        	Test:       	TestReadAffinity_GetReadAffinityMapOptions/Enabled_in_cluster-1_and_Enabled_in_CLI
=== NAME  TestReadAffinity_GetReadAffinityMapOptions/Absent_in_cluster-4_and_Enabled_in_CLI
    nodeserver_test.go:310: 
        	Error Trace:	/home/mrajanna/workspace/src/github.com/ceph/ceph-csi/internal/rbd/nodeserver_test.go:310
        	Error:      	error fetching configuration for cluster ID "cluster-4": open /etc/ceph-csi-config/config.json: no such file or directory
        	Test:       	TestReadAffinity_GetReadAffinityMapOptions/Absent_in_cluster-4_and_Enabled_in_CLI
--- FAIL: TestReadAffinity_GetReadAffinityMapOptions (0.00s)
    --- FAIL: TestReadAffinity_GetReadAffinityMapOptions/Enabled_in_cluster-3_with_empty_crush_labels_and_Enabled_in_CLI (0.01s)
    --- FAIL: TestReadAffinity_GetReadAffinityMapOptions/Enabled_in_cluster-3_with_empty_crush_labels_and_Disabled_in_CLI (0.02s)
    --- FAIL: TestReadAffinity_GetReadAffinityMapOptions/Disabled_in_cluster-2_and_Enabled_in_CLI (0.02s)
    --- FAIL: TestReadAffinity_GetReadAffinityMapOptions/Enabled_in_cluster-1_and_Enabled_in_CLI (0.02s)
    --- FAIL: TestReadAffinity_GetReadAffinityMapOptions/Absent_in_cluster-4_and_Enabled_in_CLI (0.02s)
FAIL
FAIL	github.com/ceph/ceph-csi/internal/rbd	0.097s
```

Test should not fail when we run on a local machine, the problem is with the config.json file path, we need to create it with test folder with `tmpConfPath := t.TempDir() + "/ceph-csi.json"` like other tests

### PR DESCRIPTION
**Pull request by mayankpall**
ci: Use temporary directory for unit tests

This commit implements the use of a temporary directory for unit tests in order to ensure a clean and isolated environment for testing purposes.

Signed-off-by: Mayank Pal <mayankpal9654@gmail.com>

 Fixes #4617

### CODE REVIEW

**Comment by mayankpall** [comment]
@iPraveenParihar  Hopefully now it meets the requirement

**Comment by iPraveenParihar** [comment]
> @iPraveenParihar Hopefully now it meets the requirement

@mayankpall, please look at the following error and update the commit body.

✖   body's lines must not be longer than 80 characters [body-max-line-length]

**Comment by mayankpall** [comment]
Screenshot 2024-05-19 at 4 45 26 PM

@iPraveenParihar  edited it to shortest as possible.

**Comment by mayankpall** [comment]
@iPraveenParihar all checks have passed

**Review by iPraveenParihar — DISMISSED** [review]

File: internal/rbd/nodeserver_test.go [hunk 1]
```diff
@@ -243,7 +243,7 @@ func TestReadAffinity_GetReadAffinityMapOptions(t *testing.T) {
 	if err != nil {
 		t.Errorf("failed to marshal csi config info %v", err)
 	}
-	tmpConfPath := util.CsiConfigFile
+	tmpConfPath := t.TempDir() + "/ceph-csi.json"
 	err = os.Mkdir("/etc/ceph-csi-config", 0o600)
```
Comment (Madhu-1) [inline internal/rbd/nodeserver_test.go]: `err = os.Mkdir("/etc/ceph-csi-config", 0o600)` remove this one as its not required any more

**Review by Madhu-1 — CHANGES_REQUESTED** [review]

**Comment by mayankpall** [comment]
@Madhu-1  removed err = os.Mkdir("/etc/ceph-csi-config", 0o600)

File: internal/rbd/nodeserver_test.go [hunk 2]
```diff
@@ -243,8 +243,8 @@ func TestReadAffinity_GetReadAffinityMapOptions(t *testing.T) {
 	if err != nil {
 		t.Errorf("failed to marshal csi config info %v", err)
 	}
-	tmpConfPath := util.CsiConfigFile
-	err = os.Mkdir("/etc/ceph-csi-config", 0o600)
+	tmpConfPath := t.TempDir() + "/ceph-csi.json"
+
 	if err != nil {
 		t.Errorf("failed to create directory %s: %v", "/etc/ceph-csi-config", err)
 	}
```
Comment (Madhu-1) [inline internal/rbd/nodeserver_test.go]: Please remove this check as its not required

**Review by Madhu-1 — CHANGES_REQUESTED** [review]
Please squash all the commits into a single commit.

**Comment by mayankpall** [comment]
@Madhu-1  removed and squashed all the commits

**Review by Madhu-1 — APPROVED** [review]

**Review by iPraveenParihar — APPROVED** [review]

**Comment by iPraveenParihar** [comment]
@Madhu-1, can we skip e2e tests for this PR? Since changes are in unit tests?

**Comment by Madhu-1** [comment]
> @Madhu-1, can we skip e2e tests for this PR? Since changes are in unit tests?

yes that make sense, we can skip multi-arch buil and E2E for this kind of PR's

**Comment by iPraveenParihar** [comment]
@Mergifyio queue

**Comment by iPraveenParihar** [comment]
@mergifyio rebase

**Comment by iPraveenParihar** [comment]
@Mergifyio queue

**Comment by iPraveenParihar** [comment]
@Mergifyio refresh

**Comment by iPraveenParihar** [comment]
@Mergifyio queue default

**Comment by iPraveenParihar** [comment]
@Rakshith-R, can you take look at this?

Mergifyio can't queue due to
```
The merge queue pull request can't be updated
Details:

Unable to update: user mayankpall is unknown.
```

**Comment by Rakshith-R** [comment]
@mergifyio rebase

**Comment by Rakshith-R** [comment]
@mergifyio queue
