### PR TITLE
rbd: add support to expand encrypted volume

### LINKED ISSUE #1469: Allow expansion on "encrypted volumes"
# Describe the bug #

At present the expansion of volumes are blocked if the volume is encrypted. Considering expansion is a valid operation on an existing PVC, we should allow it eventhough volume is encrypted. 

I am still not sure, we have to reencrypt the volume after expansion with the same key or we can use different key. But either way this operation can go through. 

@vasyl-purchel any thoughts on this ?

### PR DESCRIPTION
**Pull request by pkalever**
# Describe what this PR does #

Previously in ControllerExpandVolume() we had a check for encrypted volumes and we use to fail for all expand requests on an encrypted volume. Also for Block VolumeMode PVCs NodeExpandVolume used to be ignored/skipped.                                                            
                                                                            
With these changes, we add support for the expansion of encrypted volumes. Also for raw Block VolumeMode PVCs with Encryption, we call NodeExpandVolume.
                                                                            
That said,                                                                  
With LUKS1, cryptsetup utility doesn't prompt for a passphrase on resizing the crypto mapper device. This is because LUKS1 devices don't use kernel keyring for volume keys.

Whereas, LUKS2 devices use kernel keyring for volume key by default, i.e. cryptsetup utility asks for a passphrase if it detects volume key was previously passed to dm-crypt via kernel keyring service, we are overriding the default by `--disable-keyring` option during cryptsetup open command. So that at the time of crypto mapper device resize we will not be prompted for any passphrase.

Fixes: #1469

### Other notable changes:

* fix bug in DeviceEncryptionStatus() which could lead to failures with unmap in the NodeUnstageVolume path for the encrypted volumes.
* Added testcases

### CODE REVIEW

File: internal/util/crypto.go [hunk 1]
```diff
@@ -28,8 +28,8 @@ import (
 )
 
 const (
-	mapperFilePrefix     = "luks-rbd-"
-	mapperFilePathPrefix = "/dev/mapper"
+	MapperFilePrefix     = "luks-rbd-"
```
Comment (nixpanic) [inline internal/util/crypto.go]: Please explain in the commit comment why this is needed. It is every much internal to the encryption functions that are provided in this file. Depending on the need for exposing this, it might be cleaner to add more helper functions so a real API is defined. Exported functions and constants *should* have descriptive comments.

File: internal/util/crypto.go [hunk 2]
```diff
@@ -286,7 +286,7 @@ func DeviceEncryptionStatus(ctx context.Context, devicePath string) (mappedDevic
 	if len(lines) < 1 {
 		return "", "", fmt.Errorf("device encryption status returned no stdout for %s", devicePath)
 	}
-	if !strings.HasSuffix(lines[0], " is active.") {
+	if !strings.Contains(lines[0], " is active") {
```
Comment (nixpanic) [inline internal/util/crypto.go:309]: hmm, how did this ever work before?!

I like a comment above the comparing of the string, show the (single line) output of what is expected to be returned. Could be an improvement if you have to re-work this PR.

File: internal/util/crypto.go [hunk 3]
```diff
@@ -296,7 +296,7 @@ func DeviceEncryptionStatus(ctx context.Context, devicePath string) (mappedDevic
 			return "", "", fmt.Errorf("device encryption status output for %s is badly formatted: %s",
 				devicePath, lines[i])
 		}
-		if strings.Compare(kv[0], "device") == 0 {
+		if strings.Contains(kv[0], "device") {
```
Comment (nixpanic) [inline internal/util/crypto.go]: the value should be `"device"`, why not just compare `kv[0] == "device"`?

File: docs/deploy-rbd.md [hunk 4]
```diff
@@ -63,6 +63,7 @@ make image-cephcsi
...
+| `encryptionType`                                                                                    | no                   | encryption type to use, currently supported types are luks1 and luks2 (defaults to luks2)                                                                                                                                                                                                                                                                                                                                                                                                               |
```
Comment (nixpanic) [inline docs/deploy-rbd.md]: why is this needed? are there still systems around that do not support luks2?

**Review by nixpanic — COMMENTED** [review]
Not sure if adding support for luks1 is needed, do we want to be compatible with older systems?

Might be good to add a test-case for a Filesystem PVC too, the order of extending block-device and filesystem is important.

File: internal/util/crypto.go (hunk 1 above)
Comment (pkalever) [reply internal/util/crypto.go]: I think, we already have a helper for that, I just discovered it. I will try to use it.

File: internal/util/crypto.go (hunk 2 above)
Comment (pkalever) [reply internal/util/crypto.go:309]: Sure, that should help.

File: internal/util/crypto.go (hunk 3 above)
Comment (pkalever) [reply internal/util/crypto.go]: Sorry, I initially had a different version. Later I forget to remove this, will fix it up.

File: docs/deploy-rbd.md (hunk 4 above)
Comment (pkalever) [reply docs/deploy-rbd.md]: It's the other way around. luks1 format remains fully supported. There should be a way to choose b/w available formats, hence it doesn't hurt to be flexible (when cryptosetup and kernel are ok with it, why not cephcsi?). Who knows in the future there could be other types (luks3 or whatever) :-)

**Review by pkalever — COMMENTED** [review]
> Might be good to add a test-case for a Filesystem PVC too, the order of extending block-device and filesystem is important.

Sure, I will plan to add for FS too, do we want them in the same PR? I guess not.


Thanks @nixpanic, expect a respin soon.

File: docs/deploy-rbd.md (hunk 4 above)
Comment (nixpanic) [reply docs/deploy-rbd.md]: Adding more features adds to the maintenance burden, so I prefer to only add features when needed.

What version of LUKS is currently the default or standard? If LUKS2 is still new and LUKS1 is more common to be used, then we would need to support both. However, if LUKS1 is mostly replaced by LUKS2, then I do not see a need to support LUKS1.

Comment (pkalever) [reply docs/deploy-rbd.md]: @nixpanic Cryptsetup currentrly supports different encryption operating modes to use with dm-crypt:

```
--type luks for using the default LUKS format version (LUKS1 with cryptsetup < 2.1.0, LUKS2 with cryptsetup ≥ 2.1.0),
--type luks1 for using LUKS1, the most common version of LUKS,
--type luks2 for using LUKS2, the latest available version of LUKS that allows additional extensions,
--type plain for using dm-crypt plain mode,
--type loopaes for a loopaes legacy mode,
--type tcrypt for a TrueCrypt compatibility mode.
```

We only tested ceph-csi with luks1 and luks2, so far. Also, its worth noting that luks1 remains stable, supported "forever"
Having these changes makes us flexible to opt b/w various format types.

Comment (nixpanic) [reply docs/deploy-rbd.md]: I am mostly interested by the default version of LUKS used by cryptsetup on the distributions that we support with Ceph-CSI. We build on CentOS-8 now, and I guess if that provides LUKS2 by default, we do not need to add LUKS1.

The additional tests, and maintenance to make sure we don't break LUKS1 support might not be worth the benefit. If LUKS1 is the current default and we expect users to have provisioned volumes with it, we probably need to maintain support for it, unfortunately.

If there ever will be a need to support different encryption operation modes, I don't know, but I hope single one will be sufficient for us.

Comment (Madhu-1) [reply docs/deploy-rbd.md]: Yes, I agree with the same related to support point of view we don't need to open more options to the user (testing backward compatibility, a regression can become a problem for cephcsi)

If you think this is required please feel free to open a feature request.

File: e2e/rbd.go [hunk 5]
```diff
@@ -713,6 +713,152 @@ var _ = Describe("RBD", func() {
...
+				if err != nil {
+					e2elog.Failf("failed to delete storageclass with error %v", err)
+				}
+				err = createRBDStorageClass(f.ClientSet, f, defaultSCName, nil, nil, deletePolicy)
+				if err != nil {
+					e2elog.Failf("failed to create storageclass with error %v", err)
+				}
+			})
+
+			By("Resize Encrypted Block PVC and check Device size", func() {
```
Comment (Madhu-1) [inline e2e/rbd.go]: can you please add a test for both filesystem and block and also checking PVC is encrypted or not validation is missing.

File: internal/rbd/nodeserver.go [hunk 6]
```diff
@@ -789,6 +789,24 @@ func (ns *NodeServer) NodeExpandVolume(
...
+		// The volume is encrypted, resize an active mapping
+		err = util.ResizeEncryptedVolume(ctx, mapperFile)
+		if err != nil {
+			util.ErrorLog(ctx, "failed to resize device %s, mapper %s: %w",
+				devicePath, mapperFile, err)
+			return &csi.NodeExpandVolumeResponse{}, err
+		}
+		// Use mapper device path for fs resize
+		devicePath = mapperPath
+	}
```
Comment (Madhu-1) [inline internal/rbd/nodeserver.go]: This is required only if the device is encrypted?  We are storing the encryption state in the metadata file, Have an if check here to do this only if it's encrypted.

Comment (pkalever) [reply internal/rbd/nodeserver.go]: The above block is only executed if the device is encrypted right ? mapper is only set for the encrypted devices.

Or did I missed anything in your question?

File: e2e/rbd.go (hunk 5 above)
Comment (pkalever) [reply e2e/rbd.go]: Sure, I will implement one for Block too

File: docs/deploy-rbd.md (hunk 4 above)
Comment (pkalever) [reply docs/deploy-rbd.md]: Well, I really didn't follow why we shouldn't support other encryption formats supported by cryptsetup and dm_encrypt, after all Ceph-CSI is operating at the very top of the stack.

Yes, this can be a feature request If that makes us happy here :-)

Will remove this commit in the later respin.

**Review by pkalever — COMMENTED** [review]
Thanks, Madhu & Niels, expect a respin to address the comment.

File: internal/rbd/nodeserver.go (hunk 6 above)
Comment (Madhu-1) [reply internal/rbd/nodeserver.go]: Yes this works, my idea was to use something like existing https://github.com/ceph/ceph-csi/blob/276918db1080e8e42aca19e2ca02312e6e240c9d/internal/rbd/rbd_attach.go#L333-L351 to avoid running `DeviceEncryptionStatus` for non encrypted devices

Comment (pkalever) [reply internal/rbd/nodeserver.go]: Maybe you are pointing to a different code block here.
But I understand your intention is to suggest getting the encryption status from the StashFile rather than running some real commands. Sure we can save some jiffies I guess.

Comment (nixpanic) [reply internal/rbd/nodeserver.go]: Encrypted devices have some metadata set, you can run `rbdVolume.checkRbdImageEncrypted()` or similar. Unfortunately there is not `rbdVolume` object created in this function :disappointed:

**Review by nixpanic — COMMENTED** [review]
some more comments :)

File: internal/rbd/nodeserver.go (hunk 6 above)
Comment (pkalever) [reply internal/rbd/nodeserver.go]: Yeah, let's check the stashFile :+1:

File: e2e/rbd.go [hunk 7]
```diff
@@ -713,6 +713,106 @@ var _ = Describe("RBD", func() {
 				}
 			})
 
+			By("create a PVC and bind it to an app encrypted RBD volume and validate LUKS format", func() {
```
Comment (Madhu-1) [inline e2e/rbd.go]: Is this extra test case needed?

File: internal/rbd/controllerserver.go [hunk 8]
```diff
@@ -1324,10 +1311,18 @@ func (cs *ControllerServer) ControllerExpandVolume(
 		return nil, err
 	}
 
-	if rbdVol.isEncrypted() {
-		return nil, status.Errorf(codes.InvalidArgument, "encrypted volumes do not support resize (%s)",
-			rbdVol)
+	nodeExpansion := true
+	// Get the nodeexpansion flag set based on the volume mode
```
Comment (Madhu-1) [inline internal/rbd/controllerserver.go]: can add more details to the comment on what we are doing here?

File: internal/util/crypto.go [hunk 9]
```diff
@@ -255,6 +255,16 @@ func OpenEncryptedVolume(ctx context.Context, devicePath, mapperFile, passphrase
 	return err
 }
 
+// ResizeEncryptedVolume resizes encrypted volume so that it can be used by the client.
+func ResizeEncryptedVolume(ctx context.Context, mapperFile string) error {
+	DebugLog(ctx, "Resizing LUKS device %s", mapperFile)
+	_, stderr, err := LuksResize(mapperFile)
+	if err != nil {
+		WarningLog(ctx, "failed to resize LUKS device %s: %s", mapperFile, stderr)
```
Comment (Madhu-1) [inline internal/util/crypto.go]: not sure about places this should be an error log, not the warning log.

**Review by Madhu-1 — COMMENTED** [review]
no major comments.

File: e2e/rbd.go (hunk 7 above)
Comment (pkalever) [reply e2e/rbd.go]: This was part of my previous changes, where I also had one for LUKS1 :-)
Thought we can reuse some part of the work. If you feel it adds no value we can drop, but just give it a thought please.

File: internal/rbd/controllerserver.go (hunk 8 above)
Comment (pkalever) [reply internal/rbd/controllerserver.go]: sure :+1:

File: internal/util/crypto.go (hunk 9 above)
Comment (pkalever) [reply internal/util/crypto.go]: This was inspired from OpenEncryptedVolume() function above.

Comment (Madhu-1) [reply internal/util/crypto.go]: Can you please change this to error log. OpenEncryptedVolume() can be corrected later

Comment (pkalever) [reply internal/util/crypto.go]: On it now.

Comment (pkalever) [reply internal/util/crypto.go]: Done with both.

**Comment by pkalever** [comment]
@Mergifyio rebase

**Comment by pkalever** [comment]
@Mergifyio rebase

**Comment by nixpanic** [comment]
golangci-lint failure needs to be addressed:
```
e2e/pod.go:220:33: `execCommandInContainer` - `cn` always receives `"csi-rbdplugin"` (unparam)
	f *framework.Framework, c, ns, cn string, opt *metav1.ListOptions) (string, string, error) {
	                               ^
```

File: internal/util/crypto.go (hunk 9 above)
Comment (nixpanic) [reply internal/util/crypto.go]: `OpenEncryptedVolume()` was moved to ErrorLog, this is still WarningLog?

File: internal/rbd/nodeserver.go [hunk 10]
```diff
@@ -841,36 +841,46 @@ func (ns *NodeServer) NodeExpandVolume(
...
-	return "", fmt.Errorf("failed to get device for stagingtarget path %v", volumePath)
+
+	mapperFile, mapperPath := util.VolumeMapper(volumeID)
+	if imgInfo.Encrypted {
+		// The volume is encrypted, resize an active mapping
+		err = util.ResizeEncryptedVolume(ctx, mapperFile)
+		if err != nil {
+			util.ErrorLog(ctx, "failed to resize device %s, mapper %s: %w",
+				devicePath, mapperFile, err)
+			return &csi.NodeExpandVolumeResponse{}, err
```
Comment (nixpanic) [inline internal/rbd/nodeserver.go]: This looks confusing to me. You return a `NodeExpandVolumeResponse{}` that indicates success, but also an error? If there is an error, return `nil` and a gRPC error with `status.Error*()`

File: internal/util/crypto.go [hunk 11]
```diff
@@ -260,7 +260,7 @@ func ResizeEncryptedVolume(ctx context.Context, mapperFile string) error {
 	DebugLog(ctx, "Resizing LUKS device %s", mapperFile)
 	_, stderr, err := LuksResize(mapperFile)
 	if err != nil {
-		WarningLog(ctx, "failed to resize LUKS device %s: %s", mapperFile, stderr)
+		ErrorLog(ctx, "failed to resize LUKS device %s: %s", mapperFile, stderr)
```
Comment (nixpanic) [inline internal/util/crypto.go:269]: ah, this part of the commit was expected in the previous one

File: e2e/rbd.go (hunk 7 above)
Comment (nixpanic) [reply e2e/rbd.go]: I do not think this needs extra validation, we do not care what the default LUKS format is?

**Review by nixpanic — CHANGES_REQUESTED** [review]

File: internal/util/crypto.go (hunk 9 above)
Comment (pkalever) [reply internal/util/crypto.go]: correct

File: internal/rbd/nodeserver.go (hunk 10 above)
Comment (pkalever) [reply internal/rbd/nodeserver.go]: good catch!

File: internal/util/crypto.go (hunk 11 above)
Comment (pkalever) [reply internal/util/crypto.go:269]: Yes, seem to have got confused with commits. adjusted now.

File: e2e/rbd.go (hunk 7 above)
Comment (pkalever) [reply e2e/rbd.go]: Sure, ok to remove.

**Review by pkalever — COMMENTED** [review]
Thanks @nixpanic

**Comment by pkalever** [comment]
@Mergifyio rebase

**Comment by Madhu-1** [comment]
@pkalever PR needs manual rebase

**Comment by pkalever** [comment]
> @pkalever PR needs manual rebase

@Madhu-1 done now.

File: internal/rbd/nodeserver.go [hunk 12]
```diff
@@ -875,38 +875,47 @@ func (ns *NodeServer) NodeExpandVolume(
...
+		// Use mapper device path for fs resize
+		devicePath = mapperPath
+	}
+
+	var ok bool
+	if req.GetVolumeCapability().GetBlock() == nil {
+		// TODO check size and return success or error
+		volumePath += "/" + volumeID
+		resizer := mount.NewResizeFs(utilexec.New())
+		ok, err = resizer.Resize(devicePath, volumePath)
```
Comment (Madhu-1) [inline internal/rbd/nodeserver.go:913]: can we have a short variable declaration  here, if not possible have `ok` declaration inside if block

```suggestion
ok, err := resizer.Resize(devicePath, volumePath)
```

**Review by Madhu-1 — DISMISSED** [review]
LGTM, small suggestion

File: internal/rbd/nodeserver.go (hunk 12 above)
Comment (pkalever) [reply internal/rbd/nodeserver.go:913]: I will better move the declaration inside. The suggested code might lead to shadow declaration of `err`?

Comment (pkalever) [reply internal/rbd/nodeserver.go:913]: @Madhu-1 done now. Thanks!

**Review by Madhu-1 — DISMISSED** [review]

**Review by nixpanic — DISMISSED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
@pkalever need to fix golangci-lint issues

**Comment by pkalever** [comment]
> @pkalever need to fix golangci-lint issues

Hopefully done now, it was `nlreturn`, thanks!

**Comment by Madhu-1** [comment]
> /test ci/centos/upgrade-tests-rbd

ETCD timeout

**Review by Madhu-1 — APPROVED** [review]

**Comment by nixpanic** [comment]
> > /test ci/centos/upgrade-tests-rbd
> 
> ETCD timeout

How!? Please link to the logs next time so we can see if improving the CI jobs is possible.

**Review by nixpanic — APPROVED** [review]
