### PR TITLE
rbd: fail fast in create volume for missmatch encryption

### LINKED ISSUE #2109: Testing encryption: pvc(unenc)->snapshot->pvc-restore(enc) Fails at mounting stage
# Describe the bug #

## Using vault based encryption 

Case 1: 
* Create a PVC without encryption
* Create a snapshot from PVC
* Restore to a new encrypted PVC
* Mount the PVC to application and check the mounting path in rbd plugin pod (mount |grep rbd) [**Fails to mount**]
* Read data from the application pod (kubectl exec)

Failed at mount stage -> encryptionStatus missing

rbd-provisioner logs : 

```shell
[rakshith@localhost Downloads]$ cat logs-from-csi-rbdplugin-in-csi-rbdplugin-provisioner-9db69594c-tccth.txt | grep pvc-15b08f17-5a18-4b74-bea5-3cbf54741247
I0601 07:03:36.571415       1 utils.go:163] ID: 78 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 GRPC call: /csi.v1.Controller/CreateVolume
I0601 07:03:36.571741       1 utils.go:167] ID: 78 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-15b08f17-5a18-4b74-bea5-3cbf54741247","parameters":{"clusterID":"rook-ceph","csi.storage.k8s.io/pv/name":"pvc-15b08f17-5a18-4b74-bea5-3cbf54741247","csi.storage.k8s.io/pvc/name":"rbd-pvc-restore","csi.storage.k8s.io/pvc/namespace":"default","encrypted":"true","encryptionKMSID":"vault-test","imageFeatures":"layering","imageFormat":"2","pool":"replicapool"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}}],"volume_content_source":{"Type":{"Snapshot":{"snapshot_id":"0001-0009-rook-ceph-0000000000000001-30013949-c2a7-11eb-b0f8-daf17a2bde7a"}}}}
I0601 07:03:36.572023       1 rbd_util.go:984] ID: 78 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 setting disableInUseChecks: false image features: [layering] mounter: rbd
I0601 07:03:36.595350       1 omap.go:84] ID: 78 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 got omap values: (pool="replicapool", namespace="", name="csi.snap.30013949-c2a7-11eb-b0f8-daf17a2bde7a"): map[csi.imageid:113a2f735cf7 csi.imagename:csi-snap-30013949-c2a7-11eb-b0f8-daf17a2bde7a csi.snapname:snapshot-b04e8341-051f-4761-817c-479f2f6aeb42 csi.source:csi-vol-b7c561eb-c2a2-11eb-b0f8-daf17a2bde7a csi.volume.owner:default]
I0601 07:03:36.596734       1 omap.go:84] ID: 78 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 got omap values: (pool="replicapool", namespace="", name="csi.volumes.default"): map[]
I0601 07:03:36.632677       1 omap.go:148] ID: 78 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 set omap keys (pool="replicapool", namespace="", name="csi.volumes.default"): map[csi.volume.pvc-15b08f17-5a18-4b74-bea5-3cbf54741247:7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a])
I0601 07:03:36.635957       1 omap.go:148] ID: 78 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 set omap keys (pool="replicapool", namespace="", name="csi.volume.7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a"): map[csi.imagename:csi-vol-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a csi.volname:pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 csi.volume.encryptKMS:vault-test csi.volume.owner:default])
I0601 07:03:36.635993       1 rbd_journal.go:472] ID: 78 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 generated Volume ID (0001-0009-rook-ceph-0000000000000001-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a) and image name (csi-vol-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a) for request name (pvc-15b08f17-5a18-4b74-bea5-3cbf54741247)
I0601 07:03:36.636965       1 omap.go:84] ID: 78 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 got omap values: (pool="replicapool", namespace="", name="csi.snap.30013949-c2a7-11eb-b0f8-daf17a2bde7a"): map[csi.imageid:113a2f735cf7 csi.imagename:csi-snap-30013949-c2a7-11eb-b0f8-daf17a2bde7a csi.snapname:snapshot-b04e8341-051f-4761-817c-479f2f6aeb42 csi.source:csi-vol-b7c561eb-c2a2-11eb-b0f8-daf17a2bde7a csi.volume.owner:default]
I0601 07:03:36.637036       1 rbd_util.go:1091] ID: 78 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 rbd: clone replicapool/csi-snap-30013949-c2a7-11eb-b0f8-daf17a2bde7a@csi-snap-30013949-c2a7-11eb-b0f8-daf17a2bde7a csi-vol-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a (features: [layering]) using mon 10.107.218.103:6789
I0601 07:03:36.696467       1 controllerserver.go:434] ID: 78 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 create volume pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 from snapshot csi-snap-30013949-c2a7-11eb-b0f8-daf17a2bde7a
I0601 07:03:36.696501       1 controllerserver.go:460] ID: 78 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 created volume pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 from snapshot csi-snap-30013949-c2a7-11eb-b0f8-daf17a2bde7a
I0601 07:03:36.696510       1 controllerserver.go:476] ID: 78 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 created volume pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 backed by image csi-vol-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a
I0601 07:03:36.731939       1 omap.go:148] ID: 78 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 set omap keys (pool="replicapool", namespace="", name="csi.volume.7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a"): map[csi.imageid:113a24322340])
I0601 07:03:36.811276       1 rbd_util.go:622] ID: 78 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 clone depth is (2), configured softlimit (4) and hardlimit (8) for replicapool/csi-vol-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a
I0601 07:03:36.811519       1 utils.go:174] ID: 78 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 GRPC response: {"volume":{"capacity_bytes":1073741824,"content_source":{"Type":{"Snapshot":{"snapshot_id":"0001-0009-rook-ceph-0000000000000001-30013949-c2a7-11eb-b0f8-daf17a2bde7a"}}},"volume_context":{"clusterID":"rook-ceph","csi.storage.k8s.io/pv/name":"pvc-15b08f17-5a18-4b74-bea5-3cbf54741247","csi.storage.k8s.io/pvc/name":"rbd-pvc-restore","csi.storage.k8s.io/pvc/namespace":"default","encrypted":"true","encryptionKMSID":"vault-test","imageFeatures":"layering","imageFormat":"2","imageName":"csi-vol-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a","journalPool":"replicapool","pool":"replicapool"},"volume_id":"0001-0009-rook-ceph-0000000000000001-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a"}}
I0601 07:03:36.839255       1 utils.go:163] ID: 79 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 GRPC call: /csi.v1.Controller/CreateVolume
I0601 07:03:36.839923       1 utils.go:167] ID: 79 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-15b08f17-5a18-4b74-bea5-3cbf54741247","parameters":{"clusterID":"rook-ceph","csi.storage.k8s.io/pv/name":"pvc-15b08f17-5a18-4b74-bea5-3cbf54741247","csi.storage.k8s.io/pvc/name":"rbd-pvc-restore","csi.storage.k8s.io/pvc/namespace":"default","encrypted":"true","encryptionKMSID":"vault-test","imageFeatures":"layering","imageFormat":"2","pool":"replicapool"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}}],"volume_content_source":{"Type":{"Snapshot":{"snapshot_id":"0001-0009-rook-ceph-0000000000000001-30013949-c2a7-11eb-b0f8-daf17a2bde7a"}}}}
I0601 07:03:36.840717       1 rbd_util.go:984] ID: 79 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 setting disableInUseChecks: false image features: [layering] mounter: rbd
I0601 07:03:36.860602       1 omap.go:84] ID: 79 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 got omap values: (pool="replicapool", namespace="", name="csi.snap.30013949-c2a7-11eb-b0f8-daf17a2bde7a"): map[csi.imageid:113a2f735cf7 csi.imagename:csi-snap-30013949-c2a7-11eb-b0f8-daf17a2bde7a csi.snapname:snapshot-b04e8341-051f-4761-817c-479f2f6aeb42 csi.source:csi-vol-b7c561eb-c2a2-11eb-b0f8-daf17a2bde7a csi.volume.owner:default]
I0601 07:03:36.861408       1 omap.go:84] ID: 79 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 got omap values: (pool="replicapool", namespace="", name="csi.volumes.default"): map[csi.volume.pvc-15b08f17-5a18-4b74-bea5-3cbf54741247:7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a]
I0601 07:03:36.862058       1 omap.go:84] ID: 79 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 got omap values: (pool="replicapool", namespace="", name="csi.volume.7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a"): map[csi.imageid:113a24322340 csi.imagename:csi-vol-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a csi.volname:pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 csi.volume.encryptKMS:vault-test csi.volume.owner:default]
I0601 07:03:36.896048       1 rbd_journal.go:330] ID: 79 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 found existing volume (0001-0009-rook-ceph-0000000000000001-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a) with image name (csi-vol-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a) for request (pvc-15b08f17-5a18-4b74-bea5-3cbf54741247)
I0601 07:03:36.978221       1 rbd_util.go:622] ID: 79 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 clone depth is (2), configured softlimit (4) and hardlimit (8) for replicapool/csi-vol-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a
I0601 07:03:36.978584       1 utils.go:174] ID: 79 Req-ID: pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 GRPC response: {"volume":{"capacity_bytes":1073741824,"content_source":{"Type":{"Snapshot":{"snapshot_id":"0001-0009-rook-ceph-0000000000000001-30013949-c2a7-11eb-b0f8-daf17a2bde7a"}}},"volume_context":{"clusterID":"rook-ceph","csi.storage.k8s.io/pv/name":"pvc-15b08f17-5a18-4b74-bea5-3cbf54741247","csi.storage.k8s.io/pvc/name":"rbd-pvc-restore","csi.storage.k8s.io/pvc/namespace":"default","encrypted":"true","encryptionKMSID":"vault-test","imageFeatures":"layering","imageFormat":"2","imageName":"csi-vol-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a","journalPool":"replicapool","pool":"replicapool"},"volume_id":"0001-0009-rook-ceph-0000000000000001-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a"}}
```

rbd-plugin logs : 

```shell
I0601 07:28:18.388984   29697 utils.go:163] ID: 265 Req-ID: 0001-0009-rook-ceph-0000000000000001-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a GRPC call: /csi.v1.Node/NodeStageVolume
I0601 07:28:18.389319   29697 utils.go:167] ID: 265 Req-ID: 0001-0009-rook-ceph-0000000000000001-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-15b08f17-5a18-4b74-bea5-3cbf54741247/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"clusterID":"rook-ceph","csi.storage.k8s.io/pv/name":"pvc-15b08f17-5a18-4b74-bea5-3cbf54741247","csi.storage.k8s.io/pvc/name":"rbd-pvc-restore","csi.storage.k8s.io/pvc/namespace":"default","encrypted":"true","encryptionKMSID":"vault-test","imageFeatures":"layering","imageFormat":"2","imageName":"csi-vol-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a","journalPool":"replicapool","pool":"replicapool","storage.kubernetes.io/csiProvisionerIdentity":"1622528857357-8081-rbd.csi.ceph.com"},"volume_id":"0001-0009-rook-ceph-0000000000000001-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a"}
I0601 07:28:18.389618   29697 rbd_util.go:984] ID: 265 Req-ID: 0001-0009-rook-ceph-0000000000000001-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a setting disableInUseChecks: false image features: [layering] mounter: rbd
I0601 07:28:18.413120   29697 omap.go:84] ID: 265 Req-ID: 0001-0009-rook-ceph-0000000000000001-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a got omap values: (pool="replicapool", namespace="", name="csi.volume.7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a"): map[csi.imageid:113a24322340 csi.imagename:csi-vol-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a csi.volname:pvc-15b08f17-5a18-4b74-bea5-3cbf54741247 csi.volume.encryptKMS:vault-test csi.volume.owner:default]
E0601 07:28:18.413405   29697 util.go:232] kernel 4.19.182 does not support required features
I0601 07:28:18.494625   29697 cephcmds.go:59] ID: 265 Req-ID: 0001-0009-rook-ceph-0000000000000001-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a command succeeded: rbd [device list --format=json --device-type krbd]
I0601 07:28:18.579880   29697 rbd_attach.go:242] ID: 265 Req-ID: 0001-0009-rook-ceph-0000000000000001-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a rbd: map mon 10.107.218.103:6789
I0601 07:28:18.681207   29697 cephcmds.go:59] ID: 265 Req-ID: 0001-0009-rook-ceph-0000000000000001-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a command succeeded: rbd [--id csi-rbd-node -m 10.107.218.103:6789 --keyfile=***stripped*** map replicapool/csi-vol-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a --device-type krbd --options noudev]
I0601 07:28:18.681273   29697 nodeserver.go:294] ID: 265 Req-ID: 0001-0009-rook-ceph-0000000000000001-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a rbd image: 0001-0009-rook-ceph-0000000000000001-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a/replicapool was successfully mapped at /dev/rbd2
I0601 07:28:18.697845   29697 encryption.go:67] ID: 265 Req-ID: 0001-0009-rook-ceph-0000000000000001-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a image replicapool/csi-vol-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a encrypted state not set
I0601 07:28:18.763619   29697 cephcmds.go:59] ID: 265 Req-ID: 0001-0009-rook-ceph-0000000000000001-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a command succeeded: rbd [unmap /dev/rbd2 --device-type krbd --options noudev]
E0601 07:28:18.763792   29697 utils.go:172] ID: 265 Req-ID: 0001-0009-rook-ceph-0000000000000001-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a GRPC error: rpc error: code = Internal desc = rbd image replicapool/csi-vol-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a found mounted with unexpected encryption status 
```

from ceph-toolbox :
```
[root@rook-ceph-tools-7467d8bf8-jc8hw /]# rbd image-meta ls --pool replicapool csi-vol-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a
There are 0 metadata on this image.
```

from rbdplugin (to check mounts): no mount found
```
[root@minikube /]# mount | grep csi-vol-7c55d8f3-c2a7-11eb-b0f8-daf17a2bde7a
```
# Environment details #

- Image/version of Ceph CSI driver : canary
- Helm chart version :
- Kernel version :
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) :
- Kubernetes cluster version :
- Ceph cluster version :

# Steps to reproduce #

See above

# Actual results #
### mount fails

# Expected behavior #
### Provisioning should fail with concise error

# Logs #

See above

### PR DESCRIPTION
**Pull request by Madhu-1**
CreateVolume will fail in the below cases
    
### create volume from the snapshot
* If the snapshot is encrypted and the requested volume  is not encrypted
* If the snapshot is not encrypted and the requested volume is encrypted
    
### create volume from volume
* If the parent volume is encrypted and requested volume is not encrypted
* If the parent volume is not encrypted and the requested volume is encrypted
    
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by nixpanic** [comment]
> verifying encrypted pvc creation from unencrypted PVC works #2109

This is not expected to work. Creating an encrypted volume from an unencrypted source is not going to be supported. If this is a feature that is needed, we need to:

1. create a new, empty RBD image
2. attach the new RBD image, setup encryption with `cryptsetup` (creates a new encrypted block-device)
3. read the data from the source RBD image, and write it to the encrypted block-device on top of the destination RBD image

**Comment by Madhu-1** [comment]
> > verifying encrypted pvc creation from unencrypted PVC works #2109
> 
> This is not expected to work. Creating an encrypted volume from an unencrypted source is not going to be supported. If this is a feature that is needed, we need to:
> 
> 1. create a new, empty RBD image
> 2. attach the new RBD image, setup encryption with `cryptsetup` (creates a new encrypted block-device)
> 3. read the data from the source RBD image, and write it to the encrypted block-device on top of the destination RBD image

There is no requirement yet for this one. This PR fails fast in create volume request instead of failing at mounting the PVC.

File: internal/rbd/controllerserver.go [hunk 1]
```diff
@@ -217,6 +217,37 @@ func validateRequestedVolumeSize(rbdVol, parentVol *rbdVolume, rbdSnap *rbdSnaps
...
+
+func checkValidEncryptionRequest(rbdVol, parentVol *rbdVolume, rbdSnap *rbdSnapshot) error {
+	// if snapshot is encrypted the request volume should also be encrypted
+	if rbdSnap != nil {
+		if rbdSnap.isEncrypted() && !rbdVol.isEncrypted() {
+			return status.Error(codes.InvalidArgument, "cannot create unencrypted volume from encrypted snapshot")
+		}
+		if !rbdSnap.isEncrypted() && rbdVol.isEncrypted() {
+			return status.Error(codes.InvalidArgument, "cannot create encrypted volume from unencrypted snapshot")
+		}
```
Comment (Rakshith-R) [inline internal/rbd/controllerserver.go]:
```suggestion
		switch {
		case rbdSnap.isEncrypted() && !rbdVol.isEncrypted():
			return status.Error(codes.InvalidArgument, "cannot create unencrypted volume from encrypted snapshot")

		case !rbdSnap.isEncrypted() && rbdVol.isEncrypted():
			return status.Error(codes.InvalidArgument, "cannot create encrypted volume from unencrypted snapshot")
		}
```

File: internal/rbd/controllerserver.go [hunk 2]
```diff
@@ -217,6 +217,37 @@ func validateRequestedVolumeSize(rbdVol, parentVol *rbdVolume, rbdSnap *rbdSnaps
...
+	}
+	// if parent volume is encrypted the request volume should also be encrypted
+	if parentVol != nil {
+		if parentVol.isEncrypted() && !rbdVol.isEncrypted() {
+			return status.Error(codes.InvalidArgument, "cannot create unencrypted volume from encrypted volume")
+		}
+		if !parentVol.isEncrypted() && rbdVol.isEncrypted() {
+			return status.Error(codes.InvalidArgument, "cannot create encrypted volume from unencrypted volume")
+		}
```
Comment (Rakshith-R) [inline internal/rbd/controllerserver.go]:
```suggestion
		switch {
		case parentVol.isEncrypted() && !rbdVol.isEncrypted():
			return status.Error(codes.InvalidArgument, "cannot create unencrypted volume from encrypted volume")

		case !parentVol.isEncrypted() && rbdVol.isEncrypted():
			return status.Error(codes.InvalidArgument, "cannot create encrypted volume from unencrypted volume")
		}
```

**Review by Rakshith-R — COMMENTED** [review]
Using switch instead if statements a bit more cleaner ?

File: internal/rbd/controllerserver.go (hunk 1 above)
Comment (Madhu-1) [reply internal/rbd/controllerserver.go]: I don't have any preference. will wait for others' suggestions.

File: internal/rbd/controllerserver_test.go [hunk 3]
```diff
@@ -0,0 +1,163 @@
+/*
+Copyright 2018 The Ceph-CSI Authors.
```
Comment (nixpanic) [inline internal/rbd/controllerserver_test.go]: date?

File: internal/rbd/controllerserver.go [hunk 4]
```diff
@@ -217,6 +217,37 @@ func validateRequestedVolumeSize(rbdVol, parentVol *rbdVolume, rbdSnap *rbdSnaps
...
+func checkValidCreateVolumeRequest(rbdVol, parentVol *rbdVolume, rbdSnap *rbdSnapshot, cr *util.Credentials) error {
+	err := validateRequestedVolumeSize(rbdVol, parentVol, rbdSnap, cr)
+	if err != nil {
+		return err
+	}
+
+	return checkValidEncryptionRequest(rbdVol, parentVol, rbdSnap)
+}
+
+func checkValidEncryptionRequest(rbdVol, parentVol *rbdVolume, rbdSnap *rbdSnapshot) error {
```
Comment (nixpanic) [inline internal/rbd/controllerserver.go]: can you use `src, dst *rbdImage` as arguments to this function?

File: internal/rbd/controllerserver.go (hunk 1 above)
Comment (nixpanic) [reply internal/rbd/controllerserver.go]: I think I prefer the switch/case, but I do not care *that* much either.

**Review by Rakshith-R — APPROVED** [review]

File: internal/rbd/controllerserver.go (hunk 1 above)
Comment (humblec) [reply internal/rbd/controllerserver.go]: Yeah. `switch` will be cleaner I believe.

**Review by humblec — DISMISSED** [review]

**Comment by Madhu-1** [comment]
@nixpanic PTAL

File: internal/rbd/controllerserver.go [hunk 5]
```diff
@@ -210,6 +210,39 @@ func validateRequestedVolumeSize(rbdVol, parentVol *rbdVolume, rbdSnap *rbdSnaps
...
+func checkValidCreateVolumeRequest(rbdVol, parentVol *rbdVolume, rbdSnap *rbdSnapshot, cr *util.Credentials) error {
+	err := validateRequestedVolumeSize(rbdVol, parentVol, rbdSnap, cr)
+	if err != nil {
+		return err
+	}
+
+	return checkValidEncryptionRequest(parentVol, rbdVol, rbdSnap)
+}
+
+func checkValidEncryptionRequest(src, dest *rbdVolume, rbdSnap *rbdSnapshot) error {
```
Comment (nixpanic) [inline internal/rbd/controllerserver.go]: A snapshot is encrypted if its parent volume is encrypted. I do not think there is a need to pass `rbdSnap` here.

```go
func checkValidEncryptionRequest(src, dest *rbdImage) error {
```

and then call  this function only with the source (parentVol or rbdSnap) and the destination. Handling multiple cases in this function is more complex and confusing than is needed.

**Review by nixpanic — CHANGES_REQUESTED** [review]
Please check if you can simplify the new function. `rbdVolume` and `rbdSnapshot` are both `rbdImage`. Passing 3 arguments for a function when for each invocation only 2 are really required is not very clean.

In case I'm mistaking, a clear comment above the function would be justified :-)

File: internal/rbd/controllerserver.go (hunk 5 above)
Comment (Madhu-1) [reply internal/rbd/controllerserver.go]: we are passing dest and rbdSnap for two different CreateVolume cases. One is with PVC-PVC clone and Restore snapshot to a new PVC. not sure how I can manage with only src and dest here.

**Comment by Madhu-1** [comment]
> assing 3 arguments for a function when for each invocation only 2 are really required is not very clean.

Not sure simplifying helps here. we are passing 3 arguments rbbVol,parentVol,snap to other function also `createBackingImage`  if really needed in will add two separate functions and also will add ` nolint:gocyclo // golangci-lint` to the CreateVolume as it increases the complexity of CreateVolume function.

File: internal/rbd/controllerserver.go (hunk 5 above)
Comment (nixpanic) [reply internal/rbd/controllerserver.go]: Sure, but is there not always a single source and a single destination? In `checkValidCreateVolumeRequest` you can call `checkValidEncryptionRequest` depending on `parentVol` or `rbdSnap`? Use `rbdSnap` unless it is `nil`, otherwise use `parentVol`?

Comment (Madhu-1) [reply internal/rbd/controllerserver.go]: In one or another place i need to check for nil objects. I thought doing it in checkValidEncryptionRequest and send proper detailed error message. Do you have any suggestions how the function(pseudo code) should be like?

Comment (nixpanic) [reply internal/rbd/controllerserver.go]: maybe something like this:

```go
func checkValidCreateVolumeRequest(rbdVol, parentVol *rbdVolume, rbdSnap *rbdSnapshot, cr *util.Credentials) error {
        err := validateRequestedVolumeSize(rbdVol, parentVol, rbdSnap, cr)
        if err != nil {
                return err
        }

        if rbdSnap != nil {
                err = checkValidEncryptionRequest(&rbdSnap.rbdImage, &rbdVol.rbdImage)
        } else {
                err = checkValidEncryptionRequest(&parentVol.rbdImage, &rbdVol.rbdImage)
        }

        return err
}

// checkValidEncryptionRequest verifies that both src and dest have the same
// encryption status.
func checkValidEncryptionRequest(src, dest *rbdImage) error {
        switch {
        case src.isEncrypted() && !dest.isEncrypted():
                return status.Errorf(codes.InvalidArgument, "cannot create unencrypted volume from encrypted volume")
        
        case !src.isEncrypted() && dest.isEncrypted():
                return status.Errorf(codes.InvalidArgument, "cannot create encrypted volume from unencrypted volume")
        }
        return nil
}
```

The error message should be clear in any case, the user would know if a clone or restore from snapshot is done.

Comment (Madhu-1) [reply internal/rbd/controllerserver.go]: @nixpanic but with the above pseudo-code even in the case of Restore from snapshot it's returning a common error message which holds good for PVC-PVC clone.

**Comment by Madhu-1** [comment]
@nixpanic PTAL implemented the suggestion

**Review by nixpanic — APPROVED** [review]

**Review by humblec — APPROVED** [review]

**Review by Rakshith-R — APPROVED** [review]
