### PR TITLE
cephfs: set Pool parameter to empty for Snapshot-backed volumes

### LINKED ISSUE #3820: cephfs: RO Restore fails when storageclass has pool paramter
# Describe the bug #

RO Restore will not be possible when cephfs storageclass has pool parameter mentionedd.

```
I0515 10:27:41.247279       1 utils.go:195] ID: 35 Req-ID: pvc-03876232-45cc-40f2-94d6-5455cac30b6c GRPC call: /csi.v1.Controller/CreateVolume
I0515 10:27:41.247448       1 utils.go:206] ID: 35 Req-ID: pvc-03876232-45cc-40f2-94d6-5455cac30b6c GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-03876232-45cc-40f2-94d6-5455cac30b6c","parameters":{"clusterID":"rook-ceph","csi.storage.k8s.io/pv/name":"pvc-03876232-45cc-40f2-94d6-5455cac30b6c","csi.storage.k8s.io/pvc/name":"cephfs-pvc-restore","csi.storage.k8s.io/pvc/namespace":"rook-ceph","fsName":"myfs","pool":"myfs-replicated"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{}},"access_mode":{"mode":3}}],"volume_content_source":{"Type":{"Snapshot":{"snapshot_id":"0001-0009-rook-ceph-0000000000000001-de98cf4b-1db4-4b36-8504-539763f55e9f"}}}}
I0515 10:27:41.250612       1 omap.go:88] ID: 35 Req-ID: pvc-03876232-45cc-40f2-94d6-5455cac30b6c got omap values: (pool="myfs-metadata", namespace="csi", name="csi.snap.de98cf4b-1db4-4b36-8504-539763f55e9f"): map[csi.imagename:csi-snap-de98cf4b-1db4-4b36-8504-539763f55e9f csi.snapname:snapshot-ee3d59fc-5121-4d58-b17e-92660d917d11 csi.source:csi-vol-f047da06-344c-4362-a312-9a07c64fe070]
E0515 10:27:41.277713       1 controllerserver.go:277] ID: 35 Req-ID: pvc-03876232-45cc-40f2-94d6-5455cac30b6c validation and extraction of volume options failed: cannot set pool for snapshot-backed volume
E0515 10:27:41.277826       1 utils.go:210] ID: 35 Req-ID: pvc-03876232-45cc-40f2-94d6-5455cac30b6c GRPC error: rpc error: code = InvalidArgument desc = cannot set pool for snapshot-backed volume
I0515 10:29:05.698175       1 utils.go:195] ID: 36 Req-ID: pvc-03876232-45cc-40f2-94d6-5455cac30b6c GRPC call: /csi.v1.Controller/CreateVolume
I0515 10:29:05.698909       1 utils.go:206] ID: 36 Req-ID: pvc-03876232-45cc-40f2-94d6-5455cac30b6c GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-03876232-45cc-40f2-94d6-5455cac30b6c","parameters":{"clusterID":"rook-ceph","csi.storage.k8s.io/pv/name":"pvc-03876232-45cc-40f2-94d6-5455cac30b6c","csi.storage.k8s.io/pvc/name":"cephfs-pvc-restore","csi.storage.k8s.io/pvc/namespace":"rook-ceph","fsName":"myfs","pool":"myfs-replicated"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{}},"access_mode":{"mode":3}}],"volume_content_source":{"Type":{"Snapshot":{"snapshot_id":"0001-0009-rook-ceph-0000000000000001-de98cf4b-1db4-4b36-8504-539763f55e9f"}}}}
I0515 10:29:05.709888       1 omap.go:88] ID: 36 Req-ID: pvc-03876232-45cc-40f2-94d6-5455cac30b6c got omap values: (pool="myfs-metadata", namespace="csi", name="csi.snap.de98cf4b-1db4-4b36-8504-539763f55e9f"): map[csi.imagename:csi-snap-de98cf4b-1db4-4b36-8504-539763f55e9f csi.snapname:snapshot-ee3d59fc-5121-4d58-b17e-92660d917d11 csi.source:csi-vol-f047da06-344c-4362-a312-9a07c64fe070]
E0515 10:29:05.725906       1 controllerserver.go:277] ID: 36 Req-ID: pvc-03876232-45cc-40f2-94d6-5455cac30b6c validation and extraction of volume options failed: cannot set pool for snapshot-backed volume
E0515 10:29:05.725992       1 utils.go:210] ID: 36 Req-ID: pvc-03876232-45cc-40f2-94d6-5455cac30b6c GRPC error: rpc error: code = InvalidArgument desc = cannot set pool for snapshot-backed volume
I0515 10:31:06.136888       1 utils.go:195] ID: 37 Req-ID: pvc-03876232-45cc-40f2-94d6-5455cac30b6c GRPC call: /csi.v1.Controller/CreateVolume
I0515 10:31:06.137169       1 utils.go:206] ID: 37 Req-ID: pvc-03876232-45cc-40f2-94d6-5455cac30b6c GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-03876232-45cc-40f2-94d6-5455cac30b6c","parameters":{"clusterID":"rook-ceph","csi.storage.k8s.io/pv/name":"pvc-03876232-45cc-40f2-94d6-5455cac30b6c","csi.storage.k8s.io/pvc/name":"cephfs-pvc-restore","csi.storage.k8s.io/pvc/namespace":"rook-ceph","fsName":"myfs","pool":"myfs-replicated"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{}},"access_mode":{"mode":3}}],"volume_content_source":{"Type":{"Snapshot":{"snapshot_id":"0001-0009-rook-ceph-0000000000000001-de98cf4b-1db4-4b36-8504-539763f55e9f"}}}}
I0515 10:31:06.143371       1 omap.go:88] ID: 37 Req-ID: pvc-03876232-45cc-40f2-94d6-5455cac30b6c got omap values: (pool="myfs-metadata", namespace="csi", name="csi.snap.de98cf4b-1db4-4b36-8504-539763f55e9f"): map[csi.imagename:csi-snap-de98cf4b-1db4-4b36-8504-539763f55e9f csi.snapname:snapshot-ee3d59fc-5121-4d58-b17e-92660d917d11 csi.source:csi-vol-f047da06-344c-4362-a312-9a07c64fe070]
E0515 10:31:06.175414       1 controllerserver.go:277] ID: 37 Req-ID: pvc-03876232-45cc-40f2-94d6-5455cac30b6c validation and extraction of volume options failed: cannot set pool for snapshot-backed volume
E0515 10:31:06.175536       1 utils.go:210] ID: 37 Req-ID: pvc-03876232-45cc-40f2-94d6-5455cac30b6c GRPC error: rpc error: code = InvalidArgument desc = cannot set pool for snapshot-backed volume
```

https://github.com/ceph/ceph-csi/blob/745d2ace920dbffd8aa0a0f98dfd28137186d6e6/internal/cephfs/store/volumeoptions.go#L543-L545

### PR DESCRIPTION
**Pull request by Rakshith-R**
# Describe what this PR does #

Set VolumeOptions.Pool parameter to empty for Snapshot-backed volumes. This Pool parameter is optional and  only used as 'pool_layout' parameter during subvolume and subvolume clone create request in cephcsi and not used for Snapshot-backed volume at all.
It is not saved anywhere for use in subsequent operations after create too. Therefore, We can set it to empty and not error out.

Refer: https://docs.ceph.com/en/latest/cephfs/fs-volumes/?highlight=pool_layout#fs-subvolumes

Resolves: #3820

### CODE REVIEW

File: internal/cephfs/store/volumeoptions.go [hunk 1]
```diff
@@ -542,9 +542,10 @@ func (vo *VolumeOptions) populateVolumeOptionsFromBackingSnapshot(
 		return fmtBackingSnapshotOptionMismatch("clusterID", vo.ClusterID, parentBackingSnapVolOpts.ClusterID)
 	}
 
-	if vo.Pool != "" {
-		return errors.New("cannot set pool for snapshot-backed volume")
-	}
+	// Pool parameters is optional and only used to set 'pool_layout' arguement for
+	// subvolume and subvolume clone create commands.
+	// Setting this to emtpy since it is not used with Snapshot-backed volume.
+	vo.Pool = ""
```
Comment (Madhu-1) [inline internal/cephfs/store/volumeoptions.go]: Add an E2E testing to ensure it works and we will not break it in the future.

File: internal/cephfs/store/volumeoptions.go [hunk 2]
```diff
@@ -542,9 +542,10 @@ func (vo *VolumeOptions) populateVolumeOptionsFromBackingSnapshot(
 		return fmtBackingSnapshotOptionMismatch("clusterID", vo.ClusterID, parentBackingSnapVolOpts.ClusterID)
 	}
 
-	if vo.Pool != "" {
-		return errors.New("cannot set pool for snapshot-backed volume")
-	}
+	// Pool parameters is optional and only used to set 'pool_layout' argument for
+	// subvolume and subvolume clone create commands.
+	// Setting this to empty since it is not used with Snapshot-backed volume.
+	vo.Pool = ""
```
Comment (nixpanic) [inline internal/cephfs/store/volumeoptions.go:548]: Why should this not be the same as the pool of the original volume?

File: internal/cephfs/store/volumeoptions.go (hunk 1 above)
Comment (Rakshith-R) [reply internal/cephfs/store/volumeoptions.go]: Done :+1:

File: internal/cephfs/store/volumeoptions.go (hunk 2 above)
Comment (Rakshith-R) [reply internal/cephfs/store/volumeoptions.go:548]: > Why should this not be the same as the pool of the original volume?

The original volume's pool is set only for [create pvc/clone cmd ](https://github.com/search?q=repo%3Aceph/ceph-csi%20PoolLayout&type=code) as `pool_layout` (pool is retrieved directly from pv attributes) and is not saved anywhere and not used anywhere else.

The `parentBackingSnapVolOpts` here does not have its pool parameter set.

File: internal/cephfs/store/volumeoptions.go [hunk 3]
```diff
@@ -542,9 +542,10 @@ func (vo *VolumeOptions) populateVolumeOptionsFromBackingSnapshot(
 		return fmtBackingSnapshotOptionMismatch("clusterID", vo.ClusterID, parentBackingSnapVolOpts.ClusterID)
 	}
 
-	if vo.Pool != "" {
-		return errors.New("cannot set pool for snapshot-backed volume")
-	}
+	// Pool parameters is optional and only used to set 'pool_layout' argument for
```
Comment (Madhu-1) [inline internal/cephfs/store/volumeoptions.go]: `Pool parameters` to `Pool parameter`

**Review by Madhu-1 — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase
