### PR TITLE
rbd: fix bug with missing supported_features 

### LINKED ISSUE #2678: csi-rbdplugin "supported_features: no such file or directory" error.
# Describe the bug #

I get the following error message from the "csi-rbdplugin" container in all "ceph-csi-rbd-nodeplugin" pods.

```
I1123 14:51:44.550509   12355 mount_linux.go:207] Cannot run systemd-run, assuming non-systemd OS
I1123 14:51:44.550539   12355 mount_linux.go:208] systemd-run output: System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
, failed with: exit status 1
E1123 14:51:44.553355   12355 rbd_util.go:241] reading file "/sys/bus/rbd/supported_features" failed: open /sys/bus/rbd/supported_features: no such file or directory
F1123 14:51:44.553380   12355 driver.go:163] open /sys/bus/rbd/supported_features: no such file or directory
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc0001b6001, 0xc0001e8c80, 0x6d, 0x24d)
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x31a8c00, 0xc000000003, 0x0, 0x0, 0xc000544cb0, 0x1, 0x26e3858, 0x9, 0xa3, 0x418e00)
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:975 +0x1e5
k8s.io/klog/v2.(*loggingT).printDepth(0x31a8c00, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc0002cc560, 0x1, 0x1)
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:735 +0x185
k8s.io/klog/v2.FatalDepth(...)
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:1500
github.com/ceph/ceph-csi/internal/util/log.FatalLogMsg(0xc000048280, 0x3f, 0x0, 0x0, 0x0)
        /go/src/github.com/ceph/ceph-csi/internal/util/log/log.go:59 +0x118
github.com/ceph/ceph-csi/internal/rbd.(*Driver).Run(0xc0000ae990, 0x31a8d20)
        /go/src/github.com/ceph/ceph-csi/internal/rbd/driver.go:163 +0xda5
main.main()
        /go/src/github.com/ceph/ceph-csi/cmd/cephcsi.go:223 +0x3a5
```

# Environment details #

- Image/version of Ceph CSI driver :  Canary and Git version: b2099eb3b1a46ed326ded1aa5b2601a418726d91
- Helm chart version :  ceph-csi-rbd-3.4.0
- Kernel version :
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : krbd
- Kubernetes cluster version :  v1.21.2
- Ceph cluster version :  14

# Steps to reproduce #

helm install
helm install -f rbd_values.yaml --namespace "ceph-csi-rbd" "ceph-csi-rbd" ceph-csi/ceph-csi-rbd

rbd_values.yaml contains the following changes

```
csiConfig:
  - clusterID: "xxxxx-xxxxe-4758-8aea-8ccf52xxx9f"
    monitors:
      - "10.33.xx.xx:6789"
      - "10.33.xx.xx:6789"
      - "10.33.xx.xx:6789"
```

```
storageClass:
  # Specifies whether the storageclass should be created
  create: true
  name: csi-rbd-sc
  clusterID: xxxxx-xxxxe-4758-8aea-8ccf52xxx9f
```
```
pool: "vmpool"
```
```
secret:
  # Specifies whether the secret should be created
  create: true
  name: csi-rbd-secret
  userID: admin
  userKey: "XXXXXXX"
```

# Actual results #

ceph-csi-rbd-nodeplugin-mbcvk               2/3     CrashLoopBackOff   18         71m
ceph-csi-rbd-nodeplugin-md9v5               2/3     CrashLoopBackOff   18         71m

# Expected behavior #

I expect to all pods are running :-)

# Logs #

 ceph-csi-rbd-nodeplugin/csi-rbdplugin

```
I1123 15:17:14.633032   20442 cephcsi.go:168] Driver version: canary and Git version: b2099eb3b1a46ed326ded1aa5b2601a418726d91
I1123 15:17:14.633307   20442 cephcsi.go:186] Initial PID limit is set to -1
I1123 15:17:14.633430   20442 cephcsi.go:192] Reconfigured PID limit to -1 (max)
I1123 15:17:14.633593   20442 cephcsi.go:217] Starting driver type: rbd with name: rbd.csi.ceph.com
I1123 15:17:14.650084   20442 mount_linux.go:207] Cannot run systemd-run, assuming non-systemd OS
I1123 15:17:14.650119   20442 mount_linux.go:208] systemd-run output: System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
, failed with: exit status 1
E1123 15:17:14.653174   20442 rbd_util.go:241] reading file "/sys/bus/rbd/supported_features" failed: open /sys/bus/rbd/supported_features: no such file or directory
F1123 15:17:14.653208   20442 driver.go:163] open /sys/bus/rbd/supported_features: no such file or directory
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000010001, 0xc0000e4500, 0x6d, 0x24d)
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x31a8c00, 0xc000000003, 0x0, 0x0, 0xc0000b78f0, 0x1, 0x26e3858, 0x9, 0xa3, 0x418e00)
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:975 +0x1e5
k8s.io/klog/v2.(*loggingT).printDepth(0x31a8c00, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc0003685a0, 0x1, 0x1)
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:735 +0x185
k8s.io/klog/v2.FatalDepth(...)
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:1500
github.com/ceph/ceph-csi/internal/util/log.FatalLogMsg(0xc000048580, 0x3f, 0x0, 0x0, 0x0)
        /go/src/github.com/ceph/ceph-csi/internal/util/log/log.go:59 +0x118
github.com/ceph/ceph-csi/internal/rbd.(*Driver).Run(0xc0000b0b10, 0x31a8d20)
        /go/src/github.com/ceph/ceph-csi/internal/rbd/driver.go:163 +0xda5
main.main()
        /go/src/github.com/ceph/ceph-csi/cmd/cephcsi.go:223 +0x3a5

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x31a8c00)
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
created by k8s.io/klog/v2.init.0
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:420 +0xdf

goroutine 37 [sleep]:
time.Sleep(0x6fc23ac00)
        /usr/local/go/src/runtime/time.go:193 +0xd2
sigs.k8s.io/controller-runtime/pkg/log.init.0.func1()
        /go/src/github.com/ceph/ceph-csi/vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go:63 +0x45
created by sigs.k8s.io/controller-runtime/pkg/log.init.0
        /go/src/github.com/ceph/ceph-csi/vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go:62 +0x35
```

### PR DESCRIPTION
**Pull request by pkalever**
# Describe what this PR does #

* continue running rbd driver when /sys/bus/rbd/supported_features file is
missing, do not bail out.
* handle when krbdFeatures is zero

## Related issues ##

Fixes: #2678 

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

File: internal/rbd/rbd_util.go [hunk 1]
```diff
@@ -265,11 +265,16 @@ func HexStringToInteger(hexString string) (uint, error) {
 // isKrbdFeatureSupported checks if a given Image Feature is supported by krbd
 // driver or not.
 func isKrbdFeatureSupported(ctx context.Context, imageFeatures string) bool {
+	supported := true
+	// return true when /sys/bus/rbd/supported_features is absent
+	// ex: kernel < v4.11.0
+	if _, err := os.Stat(krbdSupportedFeaturesFile); errors.Is(err, os.ErrNotExist) {
+		return supported
+	}
```
Comment (Madhu-1) [inline internal/rbd/rbd_util.go]: if `krbdFeatures` is 0 means we are not able to get the `supported_featurs`  we don't need to do stat again and again?

File: internal/rbd/rbd_util.go [hunk 2]
```diff
@@ -264,7 +264,12 @@ func HexStringToInteger(hexString string) (uint, error) {
 
 // isKrbdFeatureSupported checks if a given Image Feature is supported by krbd
 // driver or not.
-func isKrbdFeatureSupported(ctx context.Context, imageFeatures string) bool {
+func isKrbdFeatureSupported(ctx context.Context, imageFeatures string) (bool, error) {
+	// return false when /sys/bus/rbd/supported_features is absent
+	// ex: kernel < v4.11.0
+	if krbdFeatures == 0 {
```
Comment (Madhu-1) [inline internal/rbd/rbd_util.go:334]: if krbdFreatues is 0 just return true? as we don't need to support `tryOtherMounters` if we are not able to fetch the rbd features from the supported_features file.

Comment (Madhu-1) [reply internal/rbd/rbd_util.go:334]: @pkalever looks like this is not addressed. can you please check it again?

Comment (pkalever) [reply internal/rbd/rbd_util.go:334]: @Madhu-1 
Sorry! After all, I still strongly feel `isKrbdFeatureSupported()` should return an error when the file is not found instead of faking true/false. Can you just think over it once again, please?

File: internal/rbd/rbd_util_test.go [hunk 3]
```diff
@@ -346,8 +347,10 @@ func TestIsKrbdFeatureSupported(t *testing.T) {
 			if err != nil {
 				t.Errorf("HexStringToInteger(%s) failed", krbdSupportedFeaturesAttr)
 			}
-			supported := isKrbdFeatureSupported(ctx, tc.featureName)
-			if supported != tc.isSupported {
+			supported, err := isKrbdFeatureSupported(ctx, tc.featureName)
+			if err != nil && !errors.Is(err, os.ErrNotExist) {
```
Comment (nixpanic) [inline internal/rbd/rbd_util_test.go:354]: would be good to have a comment why `os.ErrNotExist` is ignored

File: internal/rbd/nodeserver.go [hunk 4]
```diff
@@ -241,8 +241,12 @@ func populateRbdVol(
 		return nil, status.Error(codes.Internal, err.Error())
 	}
 
-	if req.GetVolumeContext()["mounter"] == rbdDefaultMounter &&
-		!isKrbdFeatureSupported(ctx, strings.Join(rv.ImageFeatureSet.Names(), ",")) {
+	isFeatureExist, err := isKrbdFeatureSupported(ctx, strings.Join(rv.ImageFeatureSet.Names(), ","))
+	if errors.Is(err, os.ErrNotExist) {
+		// do not fallback if /sys/bus/rbd/supported_features is absent
+		isFeatureExist = true
```
Comment (nixpanic) [inline internal/rbd/nodeserver.go]: so, if the file is missing, assume the feature is present? Is that not problematic with new features on old RBD drivers?

Comment (pkalever) [reply internal/rbd/nodeserver.go]: We do not have a way to find what features are present when `/sys/bus/rbd/supported_features` is absent, indeed that is the reason why `/sys/bus/rbd/supported_features` file was introduced.

Are you suggesting that we should fallback to NBD if the `/sys/bus/rbd/supported_features` is absent?

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by pkalever** [comment]
@Mergifyio rebase

**Review by Madhu-1 — DISMISSED** [review]

File: internal/rbd/nodeserver.go (hunk 4 above)
Comment (nixpanic) [reply internal/rbd/nodeserver.go]: Just wondering what the most appropriate default would be. If `/sys/bus/rbd/supported_features` is missing, the driver is old, so fewer features would be supported. Consider having a list of supported features of the last driver version that does not provide this API.

Comment (pkalever) [reply internal/rbd/nodeserver.go]: @Madhu-1 what is your take on this? Instead should we fallback to NBD incase if the krbd driver is old then?

Comment (Madhu-1) [reply internal/rbd/nodeserver.go]: but it's not expected behavior for existing clusters.

Comment (pkalever) [reply internal/rbd/nodeserver.go]: Then I suppose this will be a breaking change and should be introduced in 3.7.0 only. Thoughts?

Comment (Madhu-1) [reply internal/rbd/nodeserver.go]: IMO this will be good only if nbd is stable and can be used in production for 3.7.0.

Comment (nixpanic) [reply internal/rbd/nodeserver.go]: do you know what features are supported by the most recent driver that does not have the `/sys/bus/rbd/supported_features` file? In case the file is missing, you could check if it is a feature that is supported long (enough).

Comment (pkalever) [reply internal/rbd/nodeserver.go]: Upstream /sys/bus/rbd/supported_features is part of Linux kernel v4.11.0
RBD_FEATURE_LAYERING is added around Linux v3.8,
RBD_FEATURE_STRIPINGV2 is added around v3.10,
RBD_FEATURE_EXCLUSIVE_LOCK is added around v4.9, and
RBD_FEATURE_DATA_POOL around v4.11

Comment (nixpanic) [reply internal/rbd/nodeserver.go]: The reporter of the issue used Linux 4.4.0. I guess some Debian version might still be on such an old kernel?

As you have the features and their kernel versions, you can use that (and ignore backports). In case `/sys/bus/rbd/supported_features` exists, use that as authoritative source.

Comment (pkalever) [reply internal/rbd/nodeserver.go]: @Madhu-1 Are you okay with ignoring backports too and basically with Niels comment above?

Comment (Madhu-1) [reply internal/rbd/nodeserver.go]: Yes, should be fine :+1:

Comment (nixpanic) [reply internal/rbd/nodeserver.go]: Waiting on an update for this, marking as required change.

**Review by nixpanic — CHANGES_REQUESTED** [review]

File: internal/rbd/nodeserver.go (hunk 4 above)
Comment (pkalever) [reply internal/rbd/nodeserver.go]: Done now, PTAL.

File: internal/rbd/rbd_util.go [hunk 5]
```diff
@@ -193,28 +203,94 @@ type migrationVolID struct {
...
+
+	if util.CheckKernelSupport(release, krbdDataPoolSupport) {
+		return strconv.FormatInt(rbdDataPoolSupportAttr, 16), nil
+	} else if util.CheckKernelSupport(release, krbdExclusiveLockSupport) {
+		return strconv.FormatInt(rbdExclusiveLockSupportAttr, 16), nil
+	} else if util.CheckKernelSupport(release, krbdStripingV2Support) {
+		return strconv.FormatInt(rbdStripingV2SupportAttr, 16), nil
+	} else if util.CheckKernelSupport(release, krbdLayeringSupport) {
+		return strconv.FormatInt(rbdLayeringSupportAttr, 16), nil
+	}
```
Comment (pkalever) [inline internal/rbd/rbd_util.go:268]: @Madhu-1 I don't see how to convert this if-Else to Switch as suggested by linter. Can I just add a nolint here? thoughts?

Comment (Madhu-1) [reply internal/rbd/rbd_util.go:268]: Yes should be fine :+1:  Please add a reason for adding nolint.

Comment (pkalever) [reply internal/rbd/rbd_util.go:268]: Sure. Thanks!

**Comment by pkalever** [comment]
@Madhu-1 @nixpanic PTAL.

**Review by yati1998 — DISMISSED** [review]
LGTM

File: internal/rbd/rbd_util.go [hunk 6]
```diff
@@ -193,28 +203,95 @@ type migrationVolID struct {
...
+			SubLevel:     0,
+			ExtraVersion: 0,
+			Distribution: "",
+			Backport:     false,
+		},
+	}
+)
+
+// prepareKrbdFeatureAttrs prepare krbd fearure set based on kernel version.
+// Minimum kernel version should be 3.6, else it will return error.
```
Comment (Madhu-1) [inline internal/rbd/rbd_util.go]: the minimal kernel is 3.6 or 3.8?

**Review by Madhu-1 — COMMENTED** [review]
I will let @nixpanic do the final review.

File: internal/rbd/rbd_util.go (hunk 6 above)
Comment (pkalever) [reply internal/rbd/rbd_util.go]: Typo, yes 3.8

**Comment by pkalever** [comment]
@Mergifyio rebase

**Comment by pkalever** [comment]
Diff b/w previous version and this version.
V2: Updated this PR resolving a merge conflict in noderserver.go because of https://github.com/ceph/ceph-csi/pull/3080

File: internal/rbd/rbd_util.go [hunk 7]
```diff
@@ -79,6 +79,16 @@ const (
 
 	// krbd attribute file to check supported features.
 	krbdSupportedFeaturesFile = "/sys/bus/rbd/supported_features"
+
+	rbdFeatureLayering      = (1 << 0) // RBD_FEATURE_LAYERING
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go]: these constants/#defines are already available in go-ceph:

- https://github.com/ceph/go-ceph/blob/master/rbd/features.go
- https://github.com/ceph/go-ceph/blob/master/rbd/features_nautilus.go

Better use those.

File: internal/rbd/rbd_util.go [hunk 8]
```diff
@@ -193,28 +203,95 @@ type migrationVolID struct {
...
+	}
+
+	krbdLayeringSupport = []util.KernelVersion{
+		{
+			Version:      3,
+			PatchLevel:   8,
+			SubLevel:     0,
+			ExtraVersion: 0,
+			Distribution: "",
+			Backport:     false,
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go]: you can leave the `ExtraVersion`, `Distribution` and `Backport` attributes out, those are default values anyway and will make the code little shorter.

File: internal/rbd/rbd_util.go [hunk 9]
```diff
@@ -193,28 +203,95 @@ type migrationVolID struct {
...
+		},
+	}
+)
+
+// prepareKrbdFeatureAttrs prepare krbd fearure set based on kernel version.
+// Minimum kernel version should be 3.8, else it will return error.
+// nolint: gocritic // cannot convert if-else to switch.
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go]: please do that, it is a minimal change and prevents needed cleanup later

File: internal/rbd/rbd_util.go [hunk 10]
```diff
@@ -193,28 +203,95 @@ type migrationVolID struct {
...
+func prepareKrbdFeatureAttrs() (string, error) {
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go]: why return a string, and not an int?

File: internal/rbd/rbd_util.go [hunk 11]
```diff
@@ -79,6 +79,16 @@ const (
 
 	// krbd attribute file to check supported features.
 	krbdSupportedFeaturesFile = "/sys/bus/rbd/supported_features"
+
+	rbdFeatureLayering      = (1 << 0) // RBD_FEATURE_LAYERING
+	rbdFeatureStripingV2    = (1 << 1) // RBD_FEATURE_STRIPINGV2
+	rbdFeatureExclusiveLock = (1 << 2) // RBD_FEATURE_EXCLUSIVE_LOCK
+	rbdFeatureDataPool      = (1 << 7) // RBD_FEATURE_DATA_POOL
+
+	rbdLayeringSupportAttr      = (rbdFeatureLayering)
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go]: you could use go-ceph's `FeatureSet` for this

File: internal/rbd/rbd_util.go [hunk 12]
```diff
@@ -239,9 +316,19 @@ func GetKrbdSupportedFeatures() (string, error) {
...
+			return "", err
+		}
+		attrs, err := prepareKrbdFeatureAttrs()
+		if err != nil {
+			log.ErrorLogMsg("preparing krd feature attributes failed, %v", err)
+
+			return "", err
+		}
+
+		return attrs, nil
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go]: it would be cleaner to do the `strconv.FormatInt()` here, less repeated code in `prepareKrbdFeatureAttrs()`

File: internal/rbd/nodeserver.go [hunk 13]
```diff
@@ -241,8 +241,13 @@ func populateRbdVol(
 		return nil, status.Error(codes.Internal, err.Error())
 	}
 
-	if rv.Mounter == rbdDefaultMounter &&
-		!isKrbdFeatureSupported(ctx, strings.Join(rv.ImageFeatureSet.Names(), ",")) {
+	isFeatureExist, err := isKrbdFeatureSupported(ctx, strings.Join(rv.ImageFeatureSet.Names(), ","))
+	if errors.Is(err, os.ErrNotExist) {
+		// do not fallback if /sys/bus/rbd/supported_features is absent and we are
+		// not in a position to prepare krbd feature attributes
+		isFeatureExist = true
```
Comment (nixpanic) [inline internal/rbd/nodeserver.go]: should this default to `true`? I would expect that if the kernel is too old, and the file does not exist, it is assumed the feature is not available either.

**Review by nixpanic — CHANGES_REQUESTED** [review]

File: internal/rbd/rbd_util.go (hunk 9 above)
Comment (pkalever) [reply internal/rbd/rbd_util.go]: @nixpanic 
I thought we cannot convert this if-else to switch, at least it's not straightforward to me. Can you recheck once?

File: internal/rbd/nodeserver.go (hunk 13 above)
Comment (pkalever) [reply internal/rbd/nodeserver.go]: @nixpanic are you saying, If the kernel is too old and the file doesn't exist and hence we set krbdFeatures to 0, so fall back to rbd-nbd?

**Comment by pkalever** [comment]
/retest ci/centos/mini-e2e-helm/k8s-1.22
```
May 11 14:03:25.573: FAIL: backend images not matching kubernetes resource count,image count 23 kubernetes resource count 21

```

File: internal/rbd/rbd_util.go (hunk 9 above)
Comment (nixpanic) [reply internal/rbd/rbd_util.go]: I guess, something like this:

```go
switch {
    case util.CheckKernelSupport(release, krbdDataPoolSupport):
        return librbd.FeatureDataPool, nil
    case ...:
        return ...
}
```

Comment (pkalever) [reply internal/rbd/rbd_util.go]: Oh, a switch without a value is possible!! I totally forget that :) Thanks!

File: internal/rbd/nodeserver.go (hunk 13 above)
Comment (nixpanic) [reply internal/rbd/nodeserver.go]: not sure how you mean that. But I read the code as "if no features can be detected, assume the feature is supported". And I think that is wrong, and would expect the kernel to not support the feature.

Comment (nixpanic) [reply internal/rbd/nodeserver.go]: Still waiting for a reply on this, thanks!

**Review by nixpanic — CHANGES_REQUESTED** [review]

File: internal/rbd/nodeserver.go (hunk 13 above)
Comment (pkalever) [reply internal/rbd/nodeserver.go]: @nixpanic 
Can you check now! Thanks.

**Comment by humblec** [comment]
@pkalever linter is faililng..

File: internal/rbd/nodeserver.go [hunk 14]
```diff
@@ -241,8 +241,14 @@ func populateRbdVol(
 		return nil, status.Error(codes.Internal, err.Error())
 	}
 
-	if rv.Mounter == rbdDefaultMounter &&
-		!isKrbdFeatureSupported(ctx, strings.Join(rv.ImageFeatureSet.Names(), ",")) {
+	isFeatureExist, err := isKrbdFeatureSupported(ctx, strings.Join(rv.ImageFeatureSet.Names(), ","))
+	if err != nil && !errors.Is(err, os.ErrNotExist) {
+		log.ErrorLog(ctx, "failed checking krbd features: %v", err)
```
Comment (humblec) [inline internal/rbd/nodeserver.go]: do we need to listout the feature as well?

File: internal/rbd/rbd_util.go [hunk 15]
```diff
@@ -192,28 +192,83 @@ type migrationVolID struct {
...
-		dependsOn:  []string{librbd.FeatureNameObjectMap},
-	},
-	librbd.FeatureNameJournaling: {
-		needRbdNbd: true,
-		dependsOn:  []string{librbd.FeatureNameExclusiveLock},
-	},
-	librbd.FeatureNameDeepFlatten: {
-		needRbdNbd: false,
-	},
+var (
```
Comment (humblec) [inline internal/rbd/rbd_util.go:195]: @pkalever can we also document the justifying link as source code comment for below version mapping as referecnce ?

File: internal/rbd/rbd_util.go [hunk 16]
```diff
@@ -238,9 +293,19 @@ func GetKrbdSupportedFeatures() (string, error) {
...
-		log.ErrorLogMsg("reading file %q failed: %v", krbdSupportedFeaturesFile, err)
+		if !errors.Is(err, os.ErrNotExist) {
+			log.ErrorLogMsg("reading file %q failed: %v", krbdSupportedFeaturesFile, err)
 
-		return "", err
+			return "", err
+		}
+		attrs, err := prepareKrbdFeatureAttrs()
+		if err != nil {
+			log.ErrorLogMsg("preparing krd feature attributes failed, %v", err)
```
Comment (humblec) [inline internal/rbd/rbd_util.go]: krd/krbd

File: internal/rbd/rbd_util.go (hunk 15 above)
Comment (pkalever) [reply internal/rbd/rbd_util.go:195]: There is nothing as such, I had to go to linux tree and find it myself :-(

**Review by nixpanic — APPROVED** [review]

**Comment by pkalever** [comment]
/restest ci/centos/mini-e2e-helm/k8s-1.21
/restest ci/centos/mini-e2e-helm/k8s-1.22
/restest ci/centos/mini-e2e-helm/k8s-1.23
```
May 13 10:31:50.222: FAIL: backend images not matching kubernetes resource count,image count 11 kubernetes resource count 10
```

**Review by humblec — APPROVED** [review]

**Review by yati1998 — APPROVED** [review]
