### PR TITLE
util: support systems using the new cgroup v2 structure

### LINKED ISSUE #3085: setting pids.max failed with cgroups v2
I just had a similar error when setting up a K8s on a newer Flatcar server, because that one now uses
the cgroupv2 layout.
So, https://github.com/ceph/ceph-csi/blob/1bd6297ecbdf11f1ebe6a4b20f8963b4bcebe13b/internal/util/pidlimit.go#L39 is not correct, since there is no directory `/sys/fs/cgroup/pids` any more.
It's now `/sys/fs/cgroup + *.scope + /pids.max`

_Originally posted by @Cytrian in https://github.com/ceph/ceph-csi/issues/3076#issuecomment-1117291753_

### PR DESCRIPTION
**Pull request by Cytrian**
With cgroup v2, the location of the `pids.max` file changed and so did the `/proc/self/cgroup` file

New /proc/self/cgroup file has only one line:
```
0::/user.slice/user-500.slice/session-14.scope
```

While the old file had a subsystem given for each line:
```
11:pids:/user.slice/user-500.slice/session-2.scope
10:blkio:/user.slice
9:net_cls,net_prio:/
8:perf_event:/
...
```

There is no directory per subsystem (e.g. /sys/fs/cgroup/pids) any more, all files are now in one directory.

## Related issues ##

Fixes: https://github.com/ceph/ceph-csi/issues/3085

### CODE REVIEW

**Comment by Madhu-1** [comment]
@Cytrian Thanks for the PR can you please fix DCO and commitlint problem. Please refer DOC [doc](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#certificate-of-origin) and commit message [doc](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#commit-messages) for help

**Review by Madhu-1 — COMMENTED** [review]
changes LGTM. waiting to fix DCO and commitlint

File: internal/util/pidlimit.go [hunk 1]
```diff
@@ -27,32 +27,48 @@ import (
...
+// There are two different cgroup structures, cgroup v1 and v2
+//
+// For cgroup v1, find the line containing the pids group from the /proc/self/cgroup file
+// $ grep ':pids:' /proc/self/cgroup
 // 7:pids:/kubepods.slice/kubepods-besteffort.slice/....scope
 // $ cat /sys/fs/cgroup/pids + *.scope + /pids.max.
+//
+// The entry for cgroup v2 is always in the format "0::...scope", no subsystem given.
+// (see https://www.kernel.org/doc/Documentation/cgroup-v2.txt)
+
```
Comment (nixpanic) [inline internal/util/pidlimit.go]: nit: unneeded empty line. The function comments are not standard anyway (does not start the 1st line with `// getCgroupPidsFile ... `, so it does not matter much.

**Review by nixpanic — CHANGES_REQUESTED** [review]
Please update the subject of the commit to have the right prefix, something like `util: ...`. Lines in the commit message should not be longer than 80 characters.

We also require a `Signed-off-by:` line in the commit message (use `git commit --amend -s`).

If you make  these changes, **commitlint** and **DCO** checks are expected to pass.

Thanks for your contribution, let us know if you need more assistance!

File: internal/util/pidlimit.go (hunk 1 above)
Comment (Cytrian) [reply internal/util/pidlimit.go]: Added function name and compacted comment.

**Review by Madhu-1 — APPROVED** [review]

**Review by yati1998 — APPROVED** [review]

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.22

Spurious failure:
```
May  5 13:31:12.860: FAIL: backend images not matching kubernetes resource count,image count 24 kubernetes resource count 21
```

**Review by humblec — APPROVED** [review]

**Comment by humblec** [comment]
@nixpanic iic, the requested changes are addressed in latest refresh of the patch.. may be remove the `change requested`?

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.22

Failed with:
```
May  5 17:10:11.482: backend images not matching kubernetes resource count,image count 23 kubernetes resource count 21
```

**Review by nixpanic — APPROVED** [review]
