### PR TITLE
rbd: use DeepCopy to create a thick-provisioned clone

### LINKED ISSUE #2077: Thick PVC clone does not  make thick PVC
# Describe the bug #
When the a thick provisioned PVC is cloned using a thick provisioning enabled storage class of parent PVC, the cloned volume is not thick provisioned. The clone PVC will reach Bound state without thick provisioning.

Also see #2071

### PR DESCRIPTION
**Pull request by nixpanic**
To create a full-allocated RBD image from a snapshot/clone DeepCopy()
can be used. This is needed when the parent of the new volume is
thick-provisioner, so that the new volume is independent of the parent
and thick-provisioned as well.

Things that need to be done:

- [x] manually tested and confirmed allocations with `rbd du`
- [x] rebase on top of the next go-ceph release (v0.10.0 #2147)
- [x] add e2e verification test

Fixes: #2077

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

**Comment by nixpanic** [comment]
This PR depends on #2147, once that is merged, the **[DNM]** label can be dropped.

**Comment by nixpanic** [comment]
@mergifyio rebase

File: internal/rbd/rbd_util.go [hunk 1]
```diff
@@ -1505,6 +1505,29 @@ func (rv *rbdVolume) RepairThickProvision() error {
...
+	if err != nil {
+		return err
+	}
+
+	err = dest.openIoctx()
+	if err != nil {
+		return err
+	}
+
+	image, err := rv.open()
```
Comment (Madhu-1) [inline internal/rbd/rbd_util.go:1528]: image needs to be closed?

**Comment by Madhu-1** [comment]
tested it locally its failed to mount the clone PVC to application pod
```log
Events:
  Type     Reason                  Age                   From                     Message
  ----     ------                  ----                  ----                     -------
  Normal   Scheduled               5m29s                 default-scheduler        Successfully assigned default/csirbd-demo-pod to minicluster2
  Normal   SuccessfulAttachVolume  5m29s                 attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-16c4ed55-9f7a-487a-8040-caf9c56475f2"
  Warning  FailedMount             3m26s                 kubelet                  Unable to attach or mount volumes: unmounted volumes=[mypvc], unattached volumes=[mypvc default-token-glr45]: timed out waiting for the condition
  Warning  FailedMount             72s                   kubelet                  Unable to attach or mount volumes: unmounted volumes=[mypvc], unattached volumes=[default-token-glr45 mypvc]: timed out waiting for the condition
  Warning  FailedMount             57s (x10 over 5m13s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-16c4ed55-9f7a-487a-8040-caf9c56475f2" : rpc error: code = Internal desc = an error (exit status 2) occurred while running ceph args: [rbd task add flatten replicapool/csi-vol-fdb11c26-cd8f-11eb-836d-0242ac110005 --id csi-rbd-node --keyfile=***stripped*** -m 192.168.50.61:6789]
```

**Comment by Madhu-1** [comment]
When No PVC is present on the kubernetes the images exists in the trash
and the ceph cluster is still using 16 Gib (PVC size was 15 Gib)

```
[root@dhcp53-170 rbd]# kubectl delete -f pvc-clone.yaml 
persistentvolumeclaim "rbd-pvc-clone" deleted
[root@dhcp53-170 rbd]# kubectl delete -f pvc.yaml 
persistentvolumeclaim "rbd-pvc" deleted
[root@dhcp53-170 rbd]# kubectl get pvc
No resources found in default namespace.
[root@dhcp53-170 rbd]# kubectl get pv
No resources found
```
```
# ceph -s
  cluster:
    id:     d6d71dda-7470-418a-9186-e63e55f71efc
    health: HEALTH_WARN
            mon is allowing insecure global_id reclaim
 
  services:
    mon: 1 daemons, quorum a (age 18m)
    mgr: a(active, since 18m)
    osd: 1 osds: 1 up (since 18m), 1 in (since 18m)
 
  data:
    pools:   2 pools, 33 pgs
    objects: 3.85k objects, 15 GiB
    usage:   16 GiB used, 34 GiB / 50 GiB avail
    pgs:     33 active+clean
 
  io:
    client:   681 B/s rd, 0 op/s rd, 0 op/s wr
 
sh-4.4# rbd ls --pool=replicapool
sh-4.4# 
sh-4.4# rbd trash ls --pool=replicapool
10be52dc3ad6 csi-vol-fdb11c26-cd8f-11eb-836d-0242ac110005-temp
10be534682a8 csi-vol-d6a94576-cd8f-11eb-836d-0242ac110005
```

**Comment by Madhu-1** [comment]
when provisioner pod is restarted when Thick clone is getting created the thick clone will not consume expected size on ceph cluster

```
[root@dhcp53-170 rbd]# kubectl get pvc
NAME            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
rbd-pvc         Bound    pvc-6ce1452f-689d-4903-a6b4-af4720151818   15Gi       RWO            rook-ceph-block   69s
rbd-pvc-clone   Bound    pvc-caff5817-86a2-45df-843f-19ad8cd81e8a   15Gi       RWO            rook-ceph-block   37s

sh-4.4# rbd du replicapool/csi-vol-d791f254-cd92-11eb-8352-0242ac110005
warning: fast-diff map is not enabled for csi-vol-d791f254-cd92-11eb-8352-0242ac110005. operation may be slow.
NAME                                          PROVISIONED  USED   
csi-vol-d791f254-cd92-11eb-8352-0242ac110005       15 GiB  936 MiB
sh-4.4# rbd du replicapool/csi-vol-c477b45f-cd92-11eb-8352-0242ac110005
warning: fast-diff map is not enabled for csi-vol-c477b45f-cd92-11eb-8352-0242ac110005. operation may be slow.
NAME                                          PROVISIONED  USED  
csi-vol-c477b45f-cd92-11eb-8352-0242ac110005       15 GiB  15 GiB
sh-4.4# rbd info replicapool/csi-vol-c477b45f-cd92-11eb-8352-0242ac110005
rbd image 'csi-vol-c477b45f-cd92-11eb-8352-0242ac110005':
	size 15 GiB in 3840 objects
	order 22 (4 MiB objects)
	snapshot_count: 1
	id: 124edb32d808
	block_name_prefix: rbd_data.124edb32d808
	format: 2
	features: layering, operations
	op_features: clone-parent, snap-trash
	flags: 
	create_timestamp: Tue Jun 15 04:33:03 2021
	access_timestamp: Tue Jun 15 04:33:03 2021
	modify_timestamp: Tue Jun 15 04:33:03 2021
sh-4.4# rbd info replicapool/csi-vol-d791f254-cd92-11eb-8352-0242ac110005
rbd image 'csi-vol-d791f254-cd92-11eb-8352-0242ac110005':
	size 15 GiB in 3840 objects
	order 22 (4 MiB objects)
	snapshot_count: 0
	id: 124e9cae7648
	block_name_prefix: rbd_data.124e9cae7648
	format: 2
	features: layering, deep-flatten
	op_features: 
	flags: 
	create_timestamp: Tue Jun 15 04:33:33 2021
	access_timestamp: Tue Jun 15 04:33:33 2021
	modify_timestamp: Tue Jun 15 04:33:33 2021
sh-4.4# 

```

File: internal/rbd/clone.go [hunk 2]
```diff
@@ -147,6 +146,59 @@ func (rv *rbdVolume) generateTempClone() *rbdVolume {
 }
 
 func (rv *rbdVolume) createCloneFromImage(ctx context.Context, parentVol *rbdVolume) error {
+	j, err := volJournal.Connect(rv.Monitors, rv.RadosNamespace, rv.conn.Creds)
+	if err != nil {
+		return status.Error(codes.Internal, err.Error())
+	}
+	defer j.Destroy()
+
+	// TODO: if rv exists, delete the image and start over?
```
Comment (Madhu-1) [inline internal/rbd/clone.go]: if rv exists the call won't come here as the image will be found  at https://github.com/ceph/ceph-csi/blob/devel/internal/rbd/rbd_journal.go#L283 ?

File: internal/rbd/rbd_util.go (hunk 1 above)
Comment (nixpanic) [reply internal/rbd/rbd_util.go:1528]: yes! will add a defer for it.

File: internal/rbd/clone.go (hunk 2 above)
Comment (nixpanic) [reply internal/rbd/clone.go]: Yes, probably. The image metadata should have the thick-provisioned key, if it is missing copying the image should start over again.

**Comment by nixpanic** [comment]
> when provisioner pod is restarted when Thick clone is getting created the thick clone will not consume expected size on ceph cluster

In this case, `DeepCopy()` was aborted and needs to be restarted. This is still TODO at the moment.

**Comment by Madhu-1** [comment]
> > when provisioner pod is restarted when Thick clone is getting created the thick clone will not consume expected size on ceph cluster
> 
> In this case, `DeepCopy()` was aborted and needs to be restarted. This is still TODO at the moment.

:+1: This will be addressed in the next PR?

File: internal/rbd/clone.go [hunk 3]
```diff
@@ -197,41 +236,39 @@ func (rv *rbdVolume) createCloneFromImage(ctx context.Context, parentVol *rbdVol
...
+	if rv.ThickProvision {
+		err = tempClone.DeepCopy(rv)
 		if err != nil {
-			return fmt.Errorf("failed to copy encryption config for %q: %w", rv, err)
+			return fmt.Errorf("failed to deep copy %q into %q: %w", parentVol, rv, err)
+		}
+	} else {
+		// flatten clone
+		errFlatten = tempClone.flattenRbdImage(ctx, rv.conn.Creds, false, rbdHardMaxCloneDepth, rbdSoftMaxCloneDepth)
+		if errFlatten != nil {
```
Comment (humblec) [inline internal/rbd/clone.go:248]: @nixpanic if `Flatten` failed here, do we need to return error ? or can we move ahead without failing? I understand,  this is normal/general workflow we have so far/till now, so ideally should keep the same. But double confirming, is it mandatory to flatten before creating a snap from temporary clone image?.

**Comment by nixpanic** [comment]
On Wed, Jun 16, 2021 at 05:19:42AM -0700, Humble Devassy Chirammal wrote:
> @humblec commented on this pull request.
> 
> 
> 
> >  		if err != nil {
> -			return fmt.Errorf("failed to copy encryption config for %q: %w", rv, err)
> +			return fmt.Errorf("failed to deep copy %q into %q: %w", parentVol, rv, err)
> +		}
> +	} else {
> +		// flatten clone
> +		errFlatten = tempClone.flattenRbdImage(ctx, rv.conn.Creds, false, rbdHardMaxCloneDepth, rbdSoftMaxCloneDepth)
> +		if errFlatten != nil {
> 
> @nixpanic if `Flatten` failed here, do we need to return error ? or can we move ahead without failing? I understand,  this is normal/general workflow we have so far/till now, so ideally should keep the same. But double confirming, is it mandatory to flatten before creating a snap from temporary clone image?. 

Sorry, I am not sure what you are asking...

The previous behaviour is not changed for non-thick-provisioned cloning.
Is that something you are concerned about?

For thick-provisioned cloning, the DeepCopy() function is expected to do
the flattening. I might have understood that incorrectly, as it seems
the 'deep-flatten' option is still enabled once DeepCopy() has finished.
In that case, additional flattening might still be required?

**Comment by nixpanic** [comment]
> > > when provisioner pod is restarted when Thick clone is getting created the thick clone will not consume expected size on ceph cluster
> > 
> > 
> > In this case, `DeepCopy()` was aborted and needs to be restarted. This is still TODO at the moment.
> 
> +1 This will be addressed in the next PR?

I am including that in this PR, with an additional commit.

File: internal/rbd/controllerserver.go [hunk 4]
```diff
@@ -366,7 +366,23 @@ func (cs *ControllerServer) repairExistingVolume(ctx context.Context, req *csi.C
...
+			thick, err := rbdVol.isThickProvisioned()
+			if err != nil {
+				return nil, status.Errorf(codes.Aborted, "failed to verify thick-provisioned volume %q: %s", rbdVol, err)
+			} else if !thick {
+				err = deleteImage(ctx, rbdVol, cr)
+				if err != nil {
+					return nil, status.Errorf(codes.Aborted, "failed to delete partially cloned volume %q: %s", rbdVol, err)
+				}
+				return nil, status.Errorf(codes.Aborted, "cloning thick-provisioned volume %q has been interrupted, please retry", rbdVol)
+			}
```
Comment (Madhu-1) [inline internal/rbd/controllerserver.go:388]: if the image is deleted when the next request comes the omap will get deleted. do we need to wait for the next CreateVolume to handle omap deletion or we can delete the reserved omap entry here only?

File: internal/rbd/rbd_util.go [hunk 5]
```diff
@@ -1508,6 +1508,49 @@ func (rv *rbdVolume) RepairThickProvision() error {
...
+	}
+	defer image.Close()
+
+	err = image.DeepCopy(dest.ioctx, dest.RbdImageName, opts)
+	if err != nil {
+		return err
+	}
+
+	// deep-flatten is not supported by all clients, so disable it
+	return dest.DisableDeepFlatten()
```
Comment (Madhu-1) [inline internal/rbd/rbd_util.go:1540]: Question: instead of disabling for all clients. can we disable this during mapping time in node server https://github.com/ceph/ceph-csi/blob/devel/internal/rbd/nodeserver.go#L270?

File: internal/rbd/controllerserver.go [hunk 6]
```diff
@@ -366,7 +366,23 @@ func (cs *ControllerServer) repairExistingVolume(ctx context.Context, req *csi.C
...
+		// the image should be marked as thick-provisioned, unless it
+		// was aborted in flight. In order to restart the
+		// thick-cloning, delete the volume and let the caller retry
+		// from the start.
+		if isThickProvisionRequest(req.GetParameters()) {
+			thick, err := rbdVol.isThickProvisioned()
+			if err != nil {
+				return nil, status.Errorf(codes.Aborted, "failed to verify thick-provisioned volume %q: %s", rbdVol, err)
+			} else if !thick {
+				err = deleteImage(ctx, rbdVol, cr)
```
Comment (Madhu-1) [inline internal/rbd/controllerserver.go]: @nixpanic is this manually tested by restarting the provisioner pod and working fine?

**Review by Madhu-1 — COMMENTED** [review]
Left few questions LGTM.

File: internal/rbd/controllerserver.go (hunk 4 above)
Comment (nixpanic) [reply internal/rbd/controllerserver.go:388]: While testing I noticed that this isn't sufficient, the image entry needs to be removed from the journal here too.

File: internal/rbd/rbd_util.go (hunk 5 above)
Comment (nixpanic) [reply internal/rbd/rbd_util.go:1540]: I prefer to have a single approach everywhere. Having deep-flatten enabled on some images and not on others sounds confusing.

File: internal/rbd/controllerserver.go (hunk 6 above)
Comment (nixpanic) [reply internal/rbd/controllerserver.go]: manually testing it, but it is not working completely yet

**Comment by nixpanic** [comment]
Please review again :pray: Manual tests now succeed (including provisioner restart while cloning).

File: e2e/rbd_helper.go [hunk 7]
```diff
@@ -424,6 +430,16 @@ func validateEncryptedPVC(f *framework.Framework, pvc *v1.PersistentVolumeClaim,
 	return validateEncryptedImage(f, rbdImageSpec, app)
 }
 
+func isThickPVC(f *framework.Framework, pvc *v1.PersistentVolumeClaim, app *v1.Pod) error {
```
Comment (humblec) [inline e2e/rbd_helper.go:433]: @nixpanic may be a quick source comment about these functions `isThickPVC and isEncryptedPVC`  can be added

**Comment by humblec** [comment]
@nixpanic LGTM, a minor comment from me, but that can be ignored too.

File: internal/rbd/controllerserver.go [hunk 8]
```diff
@@ -366,7 +366,27 @@ func (cs *ControllerServer) repairExistingVolume(ctx context.Context, req *csi.C
...
```
Comment (Madhu-1) [inline internal/rbd/controllerserver.go]: still, need to delete the intermediate clone and temp snapshot?

File: internal/rbd/rbd_util.go [hunk 9]
```diff
@@ -1508,6 +1508,49 @@ func (rv *rbdVolume) RepairThickProvision() error {
 	return nil
 }
 
+// DeepCopy creates an independent image (dest) from the source image. This
+// process may take some time when the image is large.
+func (rv *rbdVolume) DeepCopy(dest *rbdVolume) error {
+	opts := librbd.NewRbdImageOptions()
+	defer opts.Destroy()
+
+	// when doing DeepCopy, also flatten the new image
```
Comment (humblec) [inline internal/rbd/rbd_util.go:1517]: @nixpanic @Madhu-1 I am not sure we have to explictly do  a flattening of the new image here . iic,after deep copy the new image is flattened,in that case we dont need to do that, but I could be wrong

Comment (nixpanic) [reply internal/rbd/rbd_util.go:1517]: That is done by passing `ImageOptionFlatten` which is done on the next line, hence this comment.

File: internal/rbd/controllerserver.go (hunk 8 above)
Comment (nixpanic) [reply internal/rbd/controllerserver.go]: yes, I think so...

File: e2e/rbd_helper.go (hunk 7 above)
Comment (nixpanic) [reply e2e/rbd_helper.go:433]: I do not think that is needed, the names of the functions are pretty self explaining.

File: internal/rbd/controllerserver.go (hunk 8 above)
Comment (nixpanic) [reply internal/rbd/controllerserver.go]: using `cleanUpSnapshot()` instead of `deleteImage()` should take care of this, I think.

**Review by Madhu-1 — APPROVED** [review]

**Review by Rakshith-R — APPROVED** [review]

**Review by humblec — APPROVED** [review]
