### PR TITLE
rbd: cleanup inconsistent state in `reserveSnap()` after a failure

### LINKED ISSUE #4945: rbd: `reserveSnap()` should cleanup its state in case of a failure
`reserveSnap()` could set certain attributes of `rbdSnap`, but can fail later on. In case of a failure, attributes set in `rbdSnap` may not be consistent. The function should cleanup its state in case of a failure (`UndoReserveName()`), and only change rbdSnap attributes on success.

https://github.com/ceph/ceph-csi/blob/d5849a4801fa9f3383cefc4f96e18fcad420dc80/internal/rbd/rbd_journal.go#L403-L421

_Originally posted by @iPraveenParihar in https://github.com/ceph/ceph-csi/pull/4502#discussion_r1814796388_

### PR DESCRIPTION
**Pull request by nixpanic**
`reserveSnap()` can potentially fail halfway through, in that case it
needs to undo the snapshot reservation and restore modified attributes
of the snapshot.

Fixes: #4945

### CODE REVIEW

File: internal/rbd/rbd_journal.go [hunk 1]
```diff
@@ -388,6 +388,18 @@ func (ri *rbdImage) repairImageID(ctx context.Context, j *journal.Connection, fo
...
+	origReservedID := rbdSnap.ReservedID
+	origRbdSnapName := rbdSnap.RbdSnapName
+	origVolID := rbdSnap.VolID
+	defer func() {
+		if err != nil {
+			rbdSnap.ReservedID = origReservedID
+			rbdSnap.RbdSnapName = origRbdSnapName
+			rbdSnap.VolID = origVolID
+		}
+	}()
```
Comment (Madhu-1) [inline internal/rbd/rbd_journal.go:401]: @nixpanic any specific reason to preserve and restore these values? i assume if the reservation is done properly these values will be set and not overridden to any values isnt it?

Comment (nixpanic) [reply internal/rbd/rbd_journal.go:401]: there are these two calls that overwrite the attributes in any case (success of error):
```
rbdSnap.ReservedID, rbdSnap.RbdSnapName, err = j.ReserveName(...
```
and
```
rbdSnap.VolID, err = util.GenerateVolID(...
```
So, if something goes wrong, it looks nicer to reset the attributes that may have been modified by a failing call.

Comment (nixpanic) [reply internal/rbd/rbd_journal.go:401]: Setting those attributes only at the end of the function is tricky too, `undoSnapReservation()` expects them to be set in order to clean things up in the journal.

File: internal/rbd/rbd_journal.go [hunk 2]
```diff
@@ -405,6 +417,17 @@ func reserveSnap(ctx context.Context, rbdSnap *rbdSnapshot, rbdVol *rbdVolume, c
 		ctx, rbdSnap.JournalPool, journalPoolID, rbdSnap.Pool, imagePoolID,
 		rbdSnap.RequestName, rbdSnap.NamePrefix, rbdVol.RbdImageName, kmsID, rbdSnap.ReservedID, rbdVol.Owner,
 		"", encryptionType)
+	defer func() {
+		// only undo the reservation when an error occurred
+		if err == nil {
+			return
+		}
+
+		undoErr := undoSnapReservation(ctx, rbdSnap, cr)
```
Comment (Rakshith-R) [inline internal/rbd/rbd_journal.go:426]: This should be and is already called outside after reserveSnap() calls ?

https://github.com/ceph/ceph-csi/blob/devel/internal/rbd/controllerserver.go#L1194
https://github.com/ceph/ceph-csi/blob/devel/internal/rbd/controllerserver.go#L1194

Comment (nixpanic) [reply internal/rbd/rbd_journal.go:426]: That is not sufficient in  case `reserveSnap()` had an internal error. That is the reason why this change was suggested in the 1st place. A failing function should cleanup its own internal partially-completed state on a failure, `reserveSnap()` did not do that yet.

**Comment by nixpanic** [comment]
@Madhu-1 @Rakshith-R , any other concerns?

File: internal/rbd/rbd_journal.go (hunk 1 above)
Comment (Madhu-1) [reply internal/rbd/rbd_journal.go:401]: @nixpanic the ReserveID and RbdSnapName names are not set earlier its only set by calling the `j.ReserveName` function, IMO we dont need to preserve anything and also  calling the defer incase of error should be enough.  same goes for volID as well.

**Review by Rakshith-R — APPROVED** [review]

**Comment by Rakshith-R** [comment]
> @Madhu-1 @Rakshith-R , any other concerns?

LGTM.

File: internal/rbd/rbd_journal.go (hunk 1 above)
Comment (nixpanic) [reply internal/rbd/rbd_journal.go:401]: @Madhu-1 if they are not expected to be set, shall I add a check and error message in case they are not an empty string?

Comment (Madhu-1) [reply internal/rbd/rbd_journal.go:401]: currently we dont have any case where they are set before calling this function. there are callers doing undo reservation and that will fail or not required

* Call Reserve to do reservation
* Undo if there is any error

we updated the current code to do undo internally if something fails.

Doesnt hurt to have this code but this will result in extra error/logs when we try to call the Undo function multiple times.


Let me know what do you prefer

1. Merge the current changes
2. Add a check to ensure the values are not set before calling `reserveSnap` internal function
3. Dont revert back and allow override.

Comment (nixpanic) [reply internal/rbd/rbd_journal.go:401]: The current PR as it is shows what a function should do/restore. There are no callers that will call `undoSnapReservation()` in case `reserveSnap()` fails, so there should not be additional logs for that.

When a function returns an error, there should be no need for the caller to undo whatever internals the function may, or may not, have done. Everything internal to the function should stay there. For the more complex cases, a special `undo` function can be returned, similar to what [`Manager.getGroupUUID()`](https://github.com/ceph/ceph-csi/blob/cea8bf8110531284d272582b9c536ffdb2ece82b/internal/rbd/manager.go#L117-L166) does.

Merging the current PR as it is should be fine IMHO, @Madhu-1, but I am also fine with improving it some way you recommend.

Comment (Madhu-1) [reply internal/rbd/rbd_journal.go:401]: https://github.com/ceph/ceph-csi/blob/devel/internal/rbd/controllerserver.go#L1194
https://github.com/ceph/ceph-csi/blob/devel/internal/rbd/controllerserver.go#L1194 might trigger an additional log

**Review by Madhu-1 — APPROVED** [review]

File: internal/rbd/rbd_journal.go (hunk 1 above)
Comment (nixpanic) [reply internal/rbd/rbd_journal.go:401]: No, it would not. In case there is an error returned by `reserveSnap()`, the `defer` where `undoSnapReservation()` is called will never be reached.

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio queue
