### PR TITLE
Cephfs: Failed to delete snapshot

### LINKED ISSUE #1647: Cephfs: Failed to Delete snapshot when backend subvolume and snapshot is deleted
## Describe the bug 

Failed to delete voluesnapshot when backend subvolume (pvc) and ceph fs subvolume snapshot is deleted

## steps to reproduce it
* Install ceph cluster which doesn't have the snapshot-retention feature (install rook+ceph from master branch)
* Create PVC
* Create snapshot
* Delete PVC ---> Here PVC deletion fails (as its having snapshots)
* Now go and delete the snapshot and subvolume manually
* Now check is PV delete after sometime
* Now try to delete volumesnapshot with kubectl (snapshot deletion will fail)

## Expected result

As the backend resources are deleted we need to return success to the user

```Logs
I1030 08:34:06.316306       1 utils.go:132] ID: 97 Req-ID: 0001-0009-rook-ceph-0000000000000001-911e53f0-1a81-11eb-911f-0242ac110007 GRPC call: /csi.v1.Controller/DeleteSnapshot
I1030 08:34:06.317052       1 utils.go:133] ID: 97 Req-ID: 0001-0009-rook-ceph-0000000000000001-911e53f0-1a81-11eb-911f-0242ac110007 GRPC request: {"secrets":"***stripped***","snapshot_id":"0001-0009-rook-ceph-0000000000000001-911e53f0-1a81-11eb-911f-0242ac110007"}
I1030 08:34:06.324740       1 omap.go:72] ID: 97 Req-ID: 0001-0009-rook-ceph-0000000000000001-911e53f0-1a81-11eb-911f-0242ac110007 got omap values: (pool="myfs-metadata", namespace="csi", name="csi.snap.911e53f0-1a81-11eb-911f-0242ac110007"): map[csi.imagename:csi-snap-911e53f0-1a81-11eb-911f-0242ac110007 csi.snapname:snapshot-bbaca9ef-2a37-4581-ba56-92c18fb22ad0 csi.source:csi-vol-8a672fe1-1a81-11eb-911f-0242ac110007]
E1030 08:34:06.330559       1 volume.go:95] ID: 97 Req-ID: 0001-0009-rook-ceph-0000000000000001-911e53f0-1a81-11eb-911f-0242ac110007 failed to get subvolume info for the vol csi-vol-8a672fe1-1a81-11eb-911f-0242ac110007: rados: ret=-2, No such file or directory: "subvolume 'csi-vol-8a672fe1-1a81-11eb-911f-0242ac110007' does not exist"
E1030 08:34:06.331019       1 utils.go:136] ID: 97 Req-ID: 0001-0009-rook-ceph-0000000000000001-911e53f0-1a81-11eb-911f-0242ac110007 GRPC error: rpc error: code = Internal desc = invalid command

```

### PR DESCRIPTION
**Pull request by yati1998**
Failed to delete volumesnapshot when backend subvolume (pvc) and ceph fs subvolume snapshot is deleted

Fixes #1647

Signed-off-by: Yati Padia <ypadia@redhat.com>

### CODE REVIEW

File: internal/cephfs/controllerserver.go [hunk 1]
```diff
@@ -689,6 +689,22 @@ func (cs *ControllerServer) DeleteSnapshot(ctx context.Context, req *csi.DeleteS
 			}
 			return &csi.DeleteSnapshotResponse{}, nil
 		}
+		// if the error is ErrVolumeNotFound, delete the snapshot as the
+		// snapshot and subvolume is already deleted
+		if errors.Is(err, ErrVolumeNotFound) {
+			util.ErrorLog(ctx, "Volume not present")
+			err = volOpt.deleteSnapshot(ctx, volumeID(sid.FsSnapshotName), volumeID(sid.FsSubvolName))
```
Comment (Madhu-1) [inline internal/cephfs/controllerserver.go]: question: is it possible to delete a snapshot of the subvolume that is already deleted?

**Review by Madhu-1 — CHANGES_REQUESTED** [review]
@yati1998 please add E2E testing.

File: internal/cephfs/controllerserver.go [hunk 2]
```diff
@@ -689,6 +689,22 @@ func (cs *ControllerServer) DeleteSnapshot(ctx context.Context, req *csi.DeleteS
 			}
 			return &csi.DeleteSnapshotResponse{}, nil
 		}
+		// if the error is ErrVolumeNotFound, delete the snapshot as the
+		// snapshot and subvolume is already deleted
```
Comment (humblec) [inline internal/cephfs/controllerserver.go]: If subvolume is deleted I expect the snapshots taken from the volume also does not exist, in that case, deleting a snapshot from the backend does not add value I believe. We have to correct the omap or journal entries though.

Comment (yati1998) [reply internal/cephfs/controllerserver.go]: Yes True. we just need to correct the omap entries. I will update the PR.

File: internal/cephfs/controllerserver.go (hunk 1 above)
Comment (yati1998) [reply internal/cephfs/controllerserver.go]: No, here we are already deleting the subvolume and snapshot from backend. Hence,  we just need to check for the omap entries.

**Comment by yati1998** [comment]
> @yati1998 please add E2E testing.

sure.

File: internal/cephfs/controllerserver.go (hunk 2 above)
Comment (humblec) [reply internal/cephfs/controllerserver.go]: @yati1998 yeah, just omap cleanup is enough :+1:

File: e2e/cephfs_helper.go [hunk 3]
```diff
@@ -147,3 +150,43 @@ func getSubvolumePath(f *framework.Framework, filesystem, subvolgrp, subvolume s
...
+func deleteBackingCephFSSubvolumeSnapshot(f *framework.Framework, pvc *v1.PersistentVolumeClaim, snap *snapapi.VolumeSnapshot) error {
+	snapshotName, err := getSnapName(snap.Namespace, snap.Name)
+	if err != nil {
+		return err
+	}
+	imageData, err := getImageInfoFromPVC(pvc.Namespace, pvc.Name, f)
+	if err != nil {
+		return err
+	}
+	cmd := fmt.Sprintf("ceph fs subvolume snapshot rm myfs %s %s %s", imageData.imageName, snapshotName, subvolumegroup)
```
Comment (nixpanic) [inline e2e/cephfs_helper.go]: Instead of hard-coding `myfs`, you can use the global variable `fileSystemName`.

**Review by nixpanic — CHANGES_REQUESTED** [review]
LGTM, just a small change needed before this can be merged :+1:

File: e2e/cephfs_helper.go [hunk 4]
```diff
@@ -147,3 +150,43 @@ func getSubvolumePath(f *framework.Framework, filesystem, subvolgrp, subvolume s
...
+	_, stdErr, err := execCommandInToolBoxPod(f, cmd, rookNamespace)
```
Comment (Madhu-1) [inline e2e/cephfs_helper.go:185]: you need to delete both snapshot and subvolume to hit this issue right?

**Review by nixpanic — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]
