### PR TITLE
rbd: journal based mirroring for point-in-time and crash consistent images

### LINKED ISSUE #2018: rbd-nbd: Journal based mirroring for point-in-time and crash consistent images
# Describe the feature you'd like to have #

Journal-based RADOS block device mirroring ensures point-in-time consistent replicas of all changes to an image, including reads and writes, block device resizing, snapshots, clones, and flattening.

Journaling-based mirroring records all modifications to an image in the order in which they occur. This ensures that a crash-consistent mirror of an image is available.

# Additional context #

This is not possible with krbd mounter, we need rbd-nbd to achieve crash-consistent image mirroring.

### PR DESCRIPTION
**Pull request by pkalever**
# Describe what this PR does #

Journal-based RADOS block device mirroring ensures point-in-time
consistent replicas of all changes to an image, including reads and
writes, block device resizing, snapshots, clones, and flattening.

Journaling-based mirroring records all modifications to an image in the
order in which they occur. This ensures that a crash-consistent mirror
of an image is available.

Mirroring when configured in journal mode, mirroring will
utilize the RBD journaling image feature to replicate the image
contents. If the RBD journaling image feature is not yet enabled on the
image, it will be automatically enabled.

## Related issues ##

Fixes: #2018
Signed-off-by: Prasanna Kumar Kalever \<prasanna.kalever@redhat.com\>

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

File: internal/rbd/replicationcontrollerserver.go [hunk 1]
```diff
@@ -123,6 +126,8 @@ func getMirroringMode(ctx context.Context, parameters map[string]string) (librbd
 	switch imageMirroringMode(val) {
 	case imageMirrorModeSnapshot:
 		mirroringMode = librbd.ImageMirrorModeSnapshot
+	case imageMirrorModeJournal:
+		mirroringMode = librbd.ImageMirrorModeJournal
```
Comment (nixpanic) [inline internal/rbd/replicationcontrollerserver.go:130]: This should probably be added to the unit-test for the function too, assuming there is a unit-test for it.

The same counts for `validateSchedulingDetails()`.

**Review by nixpanic — CHANGES_REQUESTED** [review]

File: internal/rbd/replicationcontrollerserver.go [hunk 2]
```diff
@@ -139,6 +144,8 @@ func validateSchedulingDetails(parameters map[string]string) error {
 	val := parameters[imageMirroringKey]
 
 	switch imageMirroringMode(val) {
+	case imageMirrorModeJournal:
+		return nil
```
Comment (Madhu-1) [inline internal/rbd/replicationcontrollerserver.go]: return error message as scheduling is not applicable for journal mode

Comment (pkalever) [reply internal/rbd/replicationcontrollerserver.go]: Do you mean log an INFO msg? we definitely do not want the callee to bail out right?

Comment (Madhu-1) [reply internal/rbd/replicationcontrollerserver.go]: >return status.Error(codes.InvalidArgument, "scheduling is only supported for snapshot mode")

scheduling is not supported for journal mode isn't it? we need to return an error message to the user as it's a user input error.  I think that is already handled below at line 155.we can remove this check

File: internal/rbd/replicationcontrollerserver.go (hunk 1 above)
Comment (pkalever) [reply internal/rbd/replicationcontrollerserver.go:130]: Added the changes to validateSchedulingDetails, unit test for getMirroringMode is missing!

File: internal/rbd/replicationcontrollerserver.go (hunk 2 above)
Comment (pkalever) [reply internal/rbd/replicationcontrollerserver.go]: Added the comment as discussed.

**Comment by pkalever** [comment]
Just for reviewers confidence:

Tested it and it works!!!

on cluster1:
```
[pkalever@dhcp53-159 minikube-ceph-mirror]$ kubectl exec -it pod/rook-ceph-tools-555c879675-zgdv9 -n rook-ceph -- sh
sh-4.4$ rbd list replicapool
csi-vol-dummy-8139307c-d2eb-4f0f-ad60-cdc76ab4723e
csi-vol-f2575521-51d1-11ec-a6c4-0242ac110005
sh-4.4$ rbd info replicapool/csi-vol-f2575521-51d1-11ec-a6c4-0242ac110005
rbd image 'csi-vol-f2575521-51d1-11ec-a6c4-0242ac110005':
        size 8 GiB in 2048 objects
        order 22 (4 MiB objects)
        snapshot_count: 0
        id: 3741af224506
        block_name_prefix: rbd_data.3741af224506
        format: 2
        features: layering, exclusive-lock, journaling
        op_features: 
        flags: 
        create_timestamp: Tue Nov 30 11:37:49 2021
        access_timestamp: Tue Nov 30 11:37:49 2021
        modify_timestamp: Tue Nov 30 11:37:49 2021
        journal: 3741af224506
        mirroring state: enabled
        mirroring mode: journal
        mirroring global id: 12d9a2b2-2fef-4fa7-9c3a-a396aa9eb008
        mirroring primary: true
sh-4.4$ 

```

cluster2:
```
[pkalever@dhcp53-159 minikube-ceph-mirror]$  kubectl exec -it pod/rook-ceph-tools-555c879675-2bkcv -n rook-ceph -- sh
sh-4.4$ rbd list replicapool                                                                                         
csi-vol-dummy-8139307c-d2eb-4f0f-ad60-cdc76ab4723e                                                                   
csi-vol-f2575521-51d1-11ec-a6c4-0242ac110005                                                                         
sh-4.4$ rbd info replicapool/csi-vol-f2575521-51d1-11ec-a6c4-0242ac110005                                            
rbd image 'csi-vol-f2575521-51d1-11ec-a6c4-0242ac110005':                                                            
        size 8 GiB in 2048 objects                                                                                   
        order 22 (4 MiB objects)                                                                                     
        snapshot_count: 0                                                                                            
        id: 12174c45646b3                                                                                            
        block_name_prefix: rbd_data.12174c45646b3                                                                    
        format: 2                                                                                                    
        features: layering, exclusive-lock, journaling                                                               
        op_features:                                                                                                 
        flags:                                                                                                       
        create_timestamp: Tue Nov 30 11:40:27 2021                                                                   
        access_timestamp: Tue Nov 30 11:40:27 2021                                                                   
        modify_timestamp: Tue Nov 30 11:40:27 2021                                                                   
        journal: 12174c45646b3                                                                                       
        mirroring state: enabled                                                                                     
        mirroring mode: journal                                                                                      
        mirroring global id: 12d9a2b2-2fef-4fa7-9c3a-a396aa9eb008                                                    
        mirroring primary: false                                                                                     
sh-4.4$                                                                                                              
```

File: internal/rbd/replicationcontrollerserver_test.go [hunk 3]
```diff
@@ -98,10 +98,10 @@ func TestValidateSchedulingDetails(t *testing.T) {
 		{
 			"when mirroring mode is journal",
 			map[string]string{
-				imageMirroringKey:     "journal",
+				imageMirroringKey:     string(imageMirrorModeJournal),
 				schedulingIntervalKey: "1h",
```
Comment (nixpanic) [inline internal/rbd/replicationcontrollerserver_test.go:104]: The `schedulingIntervalKey` is not used with journal-mode? Does this need some validation and warn about a parameter that is not used?

Comment (pkalever) [reply internal/rbd/replicationcontrollerserver_test.go:104]: Sure!

**Review by Madhu-1 — APPROVED** [review]

**Comment by pkalever** [comment]
@nixpanic resolved the comments and the tests are back with green, could you please take a look?

File: internal/rbd/replicationcontrollerserver.go [hunk 4]
```diff
@@ -133,12 +138,24 @@ func getMirroringMode(ctx context.Context, parameters map[string]string) (librbd
...
 	var err error
 
 	val := parameters[imageMirroringKey]
 
 	switch imageMirroringMode(val) {
+	case imageMirrorModeJournal:
+		// journal mirror mode does not require scheduling parameters
+		if _, ok := parameters[schedulingIntervalKey]; ok {
+			log.WarningLog(ctx, "%s parameter cannot be used with %s mirror mode, ignoring it",
+				schedulingIntervalKey, string(imageMirrorModeJournal))
```
Comment (nixpanic) [inline internal/rbd/replicationcontrollerserver.go:151]: nit: no need to convert this to a string, that should be done automatically. It is done in other places already, so not blocking this PR, but might be good to clean it up later.

**Review by nixpanic — APPROVED** [review]
