### PR TITLE
ci: pre-pull busybox container image

### LINKED ISSUE #2029: k8s-e2e-external-storage is failing with docker limit
External storage testing is failing with the below error message

```
Apr 28 09:35:34.104: INFO: At 2021-04-28 09:30:26 +0100 BST - event for pod-eb165813-6e8a-4476-a40b-73c0bada26c0: {kubelet minikube} Pulling: Pulling image "docker.io/library/busybox:1.29"
Apr 28 09:35:34.104: INFO: At 2021-04-28 09:30:27 +0100 BST - event for pod-eb165813-6e8a-4476-a40b-73c0bada26c0: {kubelet minikube} Failed: Failed to pull image "docker.io/library/busybox:1.29": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
Apr 28 09:35:34.104: INFO: At 2021-04-28 09:30:27 +0100 BST - event for pod-eb165813-6e8a-4476-a40b-73c0bada26c0: {kubelet minikube} Failed: Error: ErrImagePull
Apr 28 09:35:34.104: INFO: At 2021-04-28 09:30:27 +0100 BST - event for pod-eb165813-6e8a-4476-a40b-73c0bada26c0: {kubelet minikube} BackOff: Back-off pulling image "docker.io/library/busybox:1.29"
Apr 28 09:35:34.104: INFO: At 2021-04-28 09:30:27 +0100 BST - event for pod-eb165813-6e8a-4476-a40b-73c0bada26c0: {kubelet minikube} Failed: Error: ImagePullBackOff
```

### PR DESCRIPTION
**Pull request by Madhu-1**
pre-pull the required busy box container image in k8s-e2e-external-storage.

closes #2029

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Review by humblec — APPROVED** [review]

File: k8s-e2e-external-storage.groovy [hunk 1]
```diff
@@ -152,6 +152,11 @@ node('cico-workspace') {
 				// single-node-k8s.sh pushes the image into minikube
 				podman_pull(ci_registry, "docker.io", rook_ceph_cluster_image - d_io_regex)
 			}
+
+			// busy box is used in external storage testing
+			podman_pull(ci_registry, "docker.io", "library/busybox:1.29")
```
Comment (pkalever) [inline k8s-e2e-external-storage.groovy:157]: should we use tag, `latest`, or `stable` instead of `1.29` specific version?

Comment (Madhu-1) [reply k8s-e2e-external-storage.groovy:157]: This is the image that gets pulled by kubernetes E2E. AFAIK we don't have the option to specify the image

Comment (nixpanic) [reply k8s-e2e-external-storage.groovy:157]: I have pushed this to the CI local registry:
```
$ podman push docker.io/library/busybox:1.29 registry-ceph-csi.apps.ocp.ci.centos.org/library/busybox:1.29
```

**Review by nixpanic — APPROVED** [review]

File: k8s-e2e-external-storage.groovy (hunk 1 above)
Comment (Madhu-1) [reply k8s-e2e-external-storage.groovy:157]: Thanks @nixpanic
