### PR TITLE
rbd: Update return error message when delete volume failed

### LINKED ISSUE #5132: Message is not right when delete pv failed
# Describe the bug #

I delete pv failed, message is 'volume deletion failed: rpc error: code = Internal desc = rbd: ret=-39, Directory not empty'. 
After analysis the log of csi, the actual failed reason is 'access denied'

Image

```
kubectl logs csi-rbdplugin-provisioner-686ddd4f4c-9f5qr -n cephfs -c csi-rbdplugin

W0126 12:46:49.107929      1 rbd_util.go:596] ID: 251312 Req-ID: 0001-0024-92ab6c78-7edc-11ee-aec4-5e807f521aec-0000000000000006-1b5a6cea-f2c2-4b62-83f3-95d0424077a3 access denied to Ceph MGR-based rbd commands on cluster ID (92ab6c78-7edc-11ee-aec4-5e807f521aec)

E0126 12:46:49.160690      1 rbd_util.go:689] ID: 251311 Req-ID: 0001-0024-92ab6c78-7edc-11ee-aec4-5e807f521aec-0000000000000006-b7dc20db-47ad-42a5-8d6d-37b40afd3af1 failed to delete rbd image: kubernetes/csi-vol-b7dc20db-47ad-42a5-8d6d-37b40afd3af1-temp, rbd: ret=-39, Directory not empty
```

# Environment details #

- Image/version of Ceph CSI driver : v3.13.0
- Helm chart version :
- Kernel version :
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) :
- Kubernetes cluster version : 1.25
- Ceph cluster version :

# Steps to reproduce #

1. create ceph client key whitch has not permission to delete pv but can create
1. create pv
1. delete pv

# Actual results #

pv is in deleting status with error message 'volume deletion failed: rpc error: code = Internal desc = rbd: ret=-39, Directory not empty'

# Expected behavior #

pv is in deleting status with error message 'access denied to Ceph MGR-based rbd commands on cluster ID xxxxxx'

# Logs #
If the issue is in PVC creation, deletion, cloning please attach complete logs
of below containers.

- csi-provisioner and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

```
kubectl logs csi-rbdplugin-provisioner-686ddd4f4c-9f5qr -n cephfs -c csi-rbdplugin

W0126 12:46:49.107929      1 rbd_util.go:596] ID: 251312 Req-ID: 0001-0024-92ab6c78-7edc-11ee-aec4-5e807f521aec-0000000000000006-1b5a6cea-f2c2-4b62-83f3-95d0424077a3 access denied to Ceph MGR-based rbd commands on cluster ID (92ab6c78-7edc-11ee-aec4-5e807f521aec)

E0126 12:46:49.160690      1 rbd_util.go:689] ID: 251311 Req-ID: 0001-0024-92ab6c78-7edc-11ee-aec4-5e807f521aec-0000000000000006-b7dc20db-47ad-42a5-8d6d-37b40afd3af1 failed to delete rbd image: kubernetes/csi-vol-b7dc20db-47ad-42a5-8d6d-37b40afd3af1-temp, rbd: ret=-39, Directory not empty
```

If the issue is in PVC resize please attach complete logs of below containers.

- csi-resizer and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in snapshot creation and deletion please attach complete logs
of below containers.

- csi-snapshotter and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC mounting please attach complete logs of below containers.

- csi-rbdplugin/csi-cephfsplugin and driver-registrar container logs from
  plugin pod from the node where the mount is failing.

- if required attach dmesg logs.

**Note:-** If its a rbd issue please provide only rbd related logs, if its a
cephFS issue please provide cephFS logs.

# Additional context #

For example:

Any existing bug report which describe about the similar issue/behavior

### PR DESCRIPTION
**Pull request by ecosysbin**
# Describe what this PR does #

Issue: When delete pv failed, error message shows 'volume deletion failed: rpc error:
code = Internal desc = rbd: ret=-39, Directory not empty', the actual failed reason is 'access denied'

Fixes: https://github.com/ceph/ceph-csi/issues/5132

This commit ensures ceph-csi return right error massage.

### CODE REVIEW

**Comment by nixpanic** [comment]
@mergifyio rebase

The build failures have been addressed. If all is well, the CI jobs should pass now.

File: internal/rbd/rbd_util.go [hunk 1]
```diff
@@ -878,10 +882,9 @@ func (ri *rbdImage) flattenRbdImage(
 			err := ri.flatten()
 			if err != nil {
 				log.ErrorLog(ctx, "rbd failed to flatten image %s %s: %v", ri.Pool, ri.RbdImageName, err)
-
-				return err
 			}
 		}
+		return knownErr
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go]: there needs to be an empty line before each `return`, otherwise golangci-lint complains about it
image

**Review by nixpanic — COMMENTED** [review]
Hi @ecosysbin, there are two minor CI failures that you need to address before we can get this merged:

1. line length in the commit message should be < 80 characters, please add some line-breaks
2. before each `return` statemens, golangci-lint expects an empty line

Please correct these things, and force-push your branch again. Ideally rebase your branch on the latest master, so that an unrelated build failure is prevented.

Thanks!

File: internal/rbd/rbd_util.go (hunk 1 above)
Comment (ecosysbin) [reply internal/rbd/rbd_util.go]: Ok， I have done it.

File: internal/rbd/rbd_util.go [hunk 2]
```diff
@@ -705,20 +709,20 @@ func (ri *rbdImage) trashRemoveImage(ctx context.Context) error {
...
 		return err
 	}
 
-	if !rbdCephMgrSupported {
+	if !rbdCephMgrSupported && knownErr != nil {
 		err = librbd.TrashRemove(ri.ioctx, ri.ImageID, true)
 		if err != nil {
-			log.ErrorLog(ctx, "failed to delete rbd image: %s, %v", ri, err)
-
-			return err
```
Comment (Rakshith-R) [inline internal/rbd/rbd_util.go]: Thanks for catching this and the pr !

Present code hides trash remove task error while the current pr changes hide trash remove error.

Let's just return both error when librbd.TrashRemove cmd fails like suggested below:

```golang
		trashRemoveErr = librbd.TrashRemove(ri.ioctx, ri.ImageID, true)
		if err != nil {
			log.ErrorLog(ctx, "failed to delete rbd image: %s, %v", ri, trashRemoveErr)

			return fmt.Errorf("failed to add task to remove image: %w, failed to trash remove image: %w",err, trashRemoveError)
```

I would be more comfortable with this kind of simple change.

File: internal/rbd/rbd_util.go [hunk 3]
```diff
@@ -878,10 +882,10 @@ func (ri *rbdImage) flattenRbdImage(
 			err := ri.flatten()
 			if err != nil {
 				log.ErrorLog(ctx, "rbd failed to flatten image %s %s: %v", ri.Pool, ri.RbdImageName, err)
-
-				return err
 			}
 		}
+
+		return knownErr
```
Comment (Rakshith-R) [inline internal/rbd/rbd_util.go]: This will involve similar changes as suggested with trash remove error.

**Review by Rakshith-R — CHANGES_REQUESTED** [review]

File: internal/rbd/rbd_util.go (hunk 2 above)
Comment (ecosysbin) [reply internal/rbd/rbd_util.go]: Ok， it's a good idea. I have done it.

File: internal/rbd/rbd_util.go [hunk 4]
```diff
@@ -705,20 +709,22 @@ func (ri *rbdImage) trashRemoveImage(ctx context.Context) error {
...
+	if !rbdCephMgrSupported && knownErr != nil {
+		trashRemoveError := librbd.TrashRemove(ri.ioctx, ri.ImageID, true)
+		if trashRemoveError != nil {
+			log.ErrorLog(ctx, "failed to delete rbd image: %s, %v", ri, trashRemoveError)
 
-			return err
+			return fmt.Errorf("failed to add task to remove image: %w, failed to trash remove image: %w", knownErr, trashRemoveError)
 		}
+
+		return knownErr
```
Comment (Rakshith-R) [inline internal/rbd/rbd_util.go]:
```suggestion
```

This is not required since trashremove has done the job?

File: internal/rbd/rbd_util.go [hunk 5]
```diff
@@ -869,19 +875,21 @@ func (ri *rbdImage) flattenRbdImage(
...
+			flattenImageErr := ri.flatten()
 			if err != nil {
 				log.ErrorLog(ctx, "rbd failed to flatten image %s %s: %v", ri.Pool, ri.RbdImageName, err)
 
-				return err
+				return fmt.Errorf("failed to add task to remove image: %w, failed to flatten image: %w", knownErr, flattenImageErr)
 			}
 		}
+
+		return knownErr
```
Comment (Rakshith-R) [inline internal/rbd/rbd_util.go]:
```suggestion
```
This is not required since trashremove has done the job?

File: internal/rbd/rbd_util.go (hunk 4 above)
Comment (nixpanic) [inline internal/rbd/rbd_util.go]: Why is it required to return the `knownErr` here? `librbd.TrashRemove()` was a success, so the goal of the function (removing the image from the trash) was achieved.

**Review by Rakshith-R — CHANGES_REQUESTED** [review]
one more comment.

File: internal/rbd/rbd_util.go (hunk 4 above)
Comment (ecosysbin) [reply internal/rbd/rbd_util.go]: Ok, I have modify it.

File: internal/rbd/rbd_util.go (hunk 5 above)
Comment (ecosysbin) [reply internal/rbd/rbd_util.go]: Ok, I have done it.

File: internal/rbd/rbd_util.go (hunk 4 above)
Comment (ecosysbin) [reply internal/rbd/rbd_util.go]: ok，I have modified it

**Review by nixpanic — DISMISSED** [review]
Thanks! Looks good to me :+1:

File: internal/rbd/rbd_util.go [hunk 6]
```diff
@@ -705,19 +709,19 @@ func (ri *rbdImage) trashRemoveImage(ctx context.Context) error {
...
-		err = librbd.TrashRemove(ri.ioctx, ri.ImageID, true)
-		if err != nil {
-			log.ErrorLog(ctx, "failed to delete rbd image: %s, %v", ri, err)
+	if !rbdCephMgrSupported && knownErr != nil {
+		trashRemoveError := librbd.TrashRemove(ri.ioctx, ri.ImageID, true)
+		if trashRemoveError != nil {
+			log.ErrorLog(ctx, "failed to delete rbd image: %s, %v", ri, trashRemoveError)
 
-			return err
+			return fmt.Errorf("failed to add task to remove image: %v, failed to trash remove image: %v", knownErr, trashRemoveError)
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go]: Need to use `%w` for error formatting, not `%v`. This causes **golangci-lint** to fail:

image

Comment (ecosysbin) [reply internal/rbd/rbd_util.go]: At the begin, It was set %w and it also show golangci-lint to fail, so I want to try %v. Now, I recovered to %w.

**Comment by Rakshith-R** [comment]
hey @ecosysbin 
There's golangci lint failure
https://github.com/ceph/ceph-csi/actions/runs/13340136953/job/37320372109?pr=5138

```
internal/rbd/rbd_util.go:724: the line is 124 characters long, which exceeds the maximum of 120 characters. (lll)
level=info msg="[runner] Processors filtering stat (in/out): diff: 1/1, max_same_issues: 1/1, path_prefixer: 1/1, cgo: 381/294, path_prettifier: 294/294, skip_files: 294/294, max_per_file_from_linter: 1/1, path_shortener: 1/1, severity-rules: 1/1, invalid_issue: 294/294, exclude: 294/294, uniq_by_line: 1/1, nolint: 228/1, max_from_linter: 1/1, fixer: 1/1, skip_dirs: 294/294, autogenerated_exclude: 294/294, exclude-rules: 294/228, sort_results: 1/1, filename_unadjuster: 294/294, identifier_marker: 294/294, source_code: 1/1"
			return fmt.Errorf("failed to add task to remove image: %w, failed to trash remove image: %w", knownErr, trashRemoveError)
```

Please take a look.

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
@Rakshith-R , please check again, the golangci-lint issue seems to have been addressed.

**Comment by ecosysbin** [comment]
@Rakshith-R , please check again, the golangci-lint issue seems to have been addressed.

**Comment by ecosysbin** [comment]
@Rakshith-R Hello, please check again, the golangci-lint issue seems to have been addressed.

**Review by Rakshith-R — APPROVED** [review]

**Comment by Rakshith-R** [comment]
> @Rakshith-R Hello, please check again, the golangci-lint issue seems to have been addressed.

Sorry, missed the ping.

**Comment by Rakshith-R** [comment]
@mergifyio rebase

**Comment by Rakshith-R** [comment]
@mergifyio queue

**Comment by ecosysbin** [comment]
@nixpanic  I see the CI error shows 'Error cloning remote repo 'origin'', what can we do next step?
ERROR: Error cloning remote repo 'origin'
ERROR: Maximum checkout retry attempts reached, aborting

**Comment by Rakshith-R** [comment]
> @nixpanic I see the CI error shows 'Error cloning remote repo 'origin'', what can we do next step? ERROR: Error cloning remote repo 'origin' ERROR: Maximum checkout retry attempts reached, aborting

I think its a CI issue, not due to this pr.
We'll take care of this.
