### PR TITLE
Rbd: Fix image flattening when snapshot and parent PVC is deleted

### LINKED ISSUE #2044: RBD: Failed to mount cloned PVC when parent PVC and snapshot is deleted
With kernel v3.10.x failed to mount the PVC when the parent PVC and snapshot is deleted

```
  Normal   Scheduled               10s              default-scheduler        Successfully assigned default/csirbd-demo-pod to minikube
  Normal   SuccessfulAttachVolume  10s              attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-ebfbcb08-41ee-4042-bcb9-24b4d7b096da"
  Warning  FailedMount             3s (x4 over 7s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-ebfbcb08-41ee-4042-bcb9-24b4d7b096da" : rpc error: code = Internal desc = image not found: RBD image not found

```

steps to reproduce the issue

* Create PVC
* Create Snapshot from PVC
* Delete PVC
* Create Clone from snapshot
* Delete snapshot
* Mount PVC clone to application pod
* Delete PVC clone and application pod

### PR DESCRIPTION
**Pull request by Madhu-1**
For flattening we call checkImageChainHasFeature which internally calls to `getImageInfo` returns the parent name even if the parent is in the trash when we try to open the parent image to get its information it fails as the image not found. we should treat the error as nil if the parent is not found.

flatten the image if the deep-flatten feature is present on the images in the chain or if the images in the chain are not zero, as we cannot check the deep-flatten feature of the images which are in the trash.
    
resolves #2044 
resolves #1544 

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

File: internal/rbd/rbd_util.go [hunk 1]
```diff
@@ -719,7 +719,14 @@ func (rv *rbdVolume) checkImageChainHasFeature(ctx context.Context, feature uint
 		}
 		err = vol.getImageInfo()
 		if err != nil {
-			util.ErrorLog(ctx, "failed to get image info for %s: %s", vol, err)
+			// call to getImageInfo returns the parent name even if the parent
+			// is in the trash, when we try to open the parent image to get its
+			// information it fails because it is already in trash. We should
+			// treat error as nil if the parent is not found.
+			if errors.Is(err, ErrImageNotFound) {
```
Comment (Yuggupta27) [inline internal/rbd/rbd_util.go:726]: Just a question, In case Parent image is not found, why isn't this caught in `getImageInfo()` here? https://github.com/ceph/ceph-csi/blob/8d7c66363daa007c9c28085629b123beb197ece4/internal/rbd/rbd_util.go#L1162

Comment (Madhu-1) [reply internal/rbd/rbd_util.go:726]: `parentInfo, err := image.GetParent()`  will return the parent details even if the parent is in trash, and above `ErrNotFound` will get hit only if the parent is not deleted completely. when you try to call `getImageInfo` for parent again as we are checking the images in the chain it will fail with  `ErrImageNotFound` in rv.open() function call

Comment (Yuggupta27) [reply internal/rbd/rbd_util.go:726]: Got it! Thanks for explaining :)

File: e2e/rbd.go [hunk 2]
```diff
@@ -1088,6 +1088,111 @@ var _ = Describe("RBD", func() {
 				}
 			})
 
+			By("validate PVC mounting if snapshot and parent PVC are deleted", func() {
+				// snapshot beta is only supported from v1.17+
+				if k8sVersionGreaterEquals(f.ClientSet, 1, 17) {
```
Comment (nixpanic) [inline e2e/rbd.go]: Nit: can you add the test like this?
```golang
                                if !k8sVersionGreaterEquals(f.ClientSet, 1, 16) {
                                        Skip("pvc clone is only supported from v1.16+")
                                }
```

That way, indention is a little less, and it makes it easier to drop support for deprecated Kubernetes versions at a later time.

File: internal/rbd/rbd_util.go [hunk 3]
```diff
@@ -726,7 +726,7 @@ func (rv *rbdVolume) checkImageChainHasFeature(ctx context.Context, feature uint
 			if errors.Is(err, ErrImageNotFound) {
 				return false, nil
 			}
-			util.ErrorLog(ctx, "failed to get image info for %s: %s", vol, err)
+			util.ErrorLog(ctx, "failed to get image info for %s: %s", vol.String(), err)
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go:729]: `.String()` gets called implicitly when using the `%s` formatting. I do not think this commit makes a difference?

Comment (Madhu-1) [reply internal/rbd/rbd_util.go:729]: No, currently the log looks like below,
```text
21-04-30T23:21:52.581603843Z E0430 23:21:52.581535   24684 rbd_util.go:589] ID: 2896 Req-ID: 0001-0011-rook-ceph-0000000000000001-6fc62615-aa0a-11eb-b36c-0a580a800411 failed to get image info for {%!s(*[]util.TopologyConstrainedPool=<nil>) <nil> map[] csi-snap-bec4c10d-aa09-11eb-b36c-0a580a800411   172.30.41.228:6789,172.30.166.153:6789,172.30.55.186:6789  replicapool   csi-snap-bec4c10d-aa09-11eb-b36c-0a580a800411 %!s(rbd.FeatureSet=257)           %!s(int64=10737418240) %!s(bool=false) %!s(bool=false) %!s(bool=false) %!s(bool=false) <nil>  seconds:1619824736 nanos:697795370 %!s(*util.ClusterConnection=&{0xc0001a71e0 0xc000111620}) %!s(*rados.IOContext=&{0x7f0490078b20})}: image not found: RBD image not found
```
to fix this one am explicitly calling the String() function

Comment (Madhu-1) [reply internal/rbd/rbd_util.go:729]: This is because the String function is implemented as a pointer method, let me change it to value type it should also fix the issue. sample code https://play.golang.org/p/2vCy5-a6B3m

Comment (Madhu-1) [reply internal/rbd/rbd_util.go:729]: okay looks like am getting a CI error if I consider pass by value
```
hugeParam: ri is heavy (208 bytes); consider passing it by pointer (gocritic)
```

Comment (nixpanic) [reply internal/rbd/rbd_util.go:729]: Hmm, maybe it is needed to pass `&vol` to the log function to get the `.String()` automatic?
See https://play.golang.org/p/VlyKSYbO3uv for my modified test.

I do not really care that much though, using `.String()` is fine, as we have that in many other places already.

**Review by nixpanic — APPROVED** [review]

**Review by Yuggupta27 — APPROVED** [review]

File: internal/rbd/rbd_util.go (hunk 3 above)
Comment (nixpanic) [reply internal/rbd/rbd_util.go:729]: See #2051 for an issue that can be used to cleanup the `.String()` calling.

**Comment by Madhu-1** [comment]
> /retest ci/centos/upgrade-tests-cephfs

created https://github.com/ceph/ceph-csi/issues/2052 to track it

File: internal/rbd/rbd_util.go (hunk 1 above)
Comment (humblec) [reply internal/rbd/rbd_util.go:726]: @Madhu-1 just to confirm, returning the image info even when an image is in trash can be avoided with any options in Ceph side ? just trying to understand is it on core side or a limitation in above layer.

Comment (Madhu-1) [reply internal/rbd/rbd_util.go:726]: the above cannot be avoided as when you ask for parent details using go-ceph `GetParent` function it provides the parent details but it won't return any details like the image is in the trash or not.
It's possible to check the image is in the trash but it will be a costly operator as we need to list all the images in the trash and do a comparison.

**Comment by Madhu-1** [comment]
> /test ci/centos/mini-e2e-helm/k8s-1.20

Failure due to https://github.com/ceph/ceph-csi/issues/2052

File: internal/rbd/rbd_util.go (hunk 1 above)
Comment (humblec) [reply internal/rbd/rbd_util.go:726]: > the above cannot be avoided as when you ask for parent details using go-ceph `GetParent` function it provides the parent details but it won't return any details like the image is in the trash or not.

Ok.. so looks like its a go ceph limitation then? if thats the case, I believe the image in trash or not is kind of a good enhancement we need on GetParent call or related calls. Because it can help us in various code paths in CSI layer and avoid some logic errors/complexities.  wdyt @Madhu-1 ?

Comment (Madhu-1) [reply internal/rbd/rbd_util.go:726]: can you open an issue in go-ceph and see if it's possible to get this information?

Comment (humblec) [reply internal/rbd/rbd_util.go:726]: > can you open an issue in go-ceph and see if it's possible to get this information?

Sure..!

Comment (Madhu-1) [reply internal/rbd/rbd_util.go:726]: @humblec anything else is required on this PR? if not I would like to get it in.

**Review by humblec — APPROVED** [review]

File: internal/rbd/rbd_util.go (hunk 1 above)
Comment (humblec) [reply internal/rbd/rbd_util.go:726]: Lets get this in with priority. Thanks :+1:

**Comment by nixpanic** [comment]
btw, is this a replacement for #1544 from @pkalever?

**Comment by Madhu-1** [comment]
> /test ci/centos/mini-e2e/k8s-1.20

`stdErr occurred: 2021-05-04T10:56:41.047+0000 7efe90bf4500  0 monclient(hunting): authenticate timed out after 300` error

**Comment by Madhu-1** [comment]
> /test ci/centos/mini-e2e-helm/k8s-1.20

`May  4 11:55:06.679: FAIL: failed to create storageclass with error error getting fsid 2021-05-04T10:55:00.009+0000 7f344d47f700  0 monclient(hunting): authenticate timed out after 300` error

**Comment by nixpanic** [comment]
No need to retry testing for now, just do a `mergifyio rebase` when #2028 is merged,

**Comment by Madhu-1** [comment]
> btw, is this a replacement for #1544 from @pkalever?

Yes this will replace #1544

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
E2E failed for known errors
