### PR TITLE
rbd: remove forcePromote function

### LINKED ISSUE #5349: remove timeout for the force promote command in rbd
# Describe the bug #

When the timeout was added, rbd mirroring was still in it's early stage and we needed a. workaround for the force promote to not get stuck and get it called again if it is not executed within a stipulated timeframe.
But, with the current enhancements around rbd and osds the timeout option can be remove for the force promote command and we should wait for the command to complete and return the result. If it's taking more time, that means the image is very large and it actually requires time to rollback the image from scratch.

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
# Describe what this PR does #

Remove `ForcePromote` function as we don't need a timeout for force promote to work anymore. The issue has been fixed in rbd and force promote is supposed to work without the timeout.

Fixes: #5349

### CODE REVIEW

File: internal/rbd/mirror.go [hunk 1]
```diff
@@ -187,40 +186,12 @@ func (rm *rbdMirror) Promote(ctx context.Context, force bool) error {
...
-		"rbd",
-		promoteArgs...,
-	)
-	if err != nil {
-		return fmt.Errorf("failed to promote image %q with error: %w", rm, err)
-	}
-
-	if stderr != "" {
-		return fmt.Errorf("failed to promote image %q with stderror: %s", rm, stderr)
+	if force {
```
Comment (Madhu-1) [inline internal/rbd/mirror.go]: instead of if/else logging, log the force flag as well

Comment (Nikhil-Ladha) [reply internal/rbd/mirror.go]: Done.

**Review by Madhu-1 — APPROVED** [review]

**Review by iPraveenParihar — APPROVED** [review]

**Comment by iPraveenParihar** [comment]
Since the changes are in RBD mirroring code and we don't yet have mirroring related e2e. We can skip running e2e.

**Comment by iPraveenParihar** [comment]
@Mergifyio rebase
