### PR TITLE
e2e: set rbd-nbd mounter tests cephLogStrategy to preserve

### LINKED ISSUE #2451: rbd-nbd logs are not getting dumped to the CI log collection
# Describe the bug #

Unfortunately, the CI logs dump is not working as expected:

```
###
### going to execute: minikube_ssh sudo find /var/log/ceph/ -type f | xargs sudo tail -n +1
###
Warning: Permanently added '192.168.39.84' (ECDSA) to the list of known hosts.
###
### execution finished: minikube_ssh sudo find /var/log/ceph/ -type f | xargs sudo tail -n +1
###
```

### PR DESCRIPTION
**Pull request by pkalever**
# Describe what this PR does #

This is to preserve the rbd-nbd logs post unmap, so that the CI can dump
the available logs from logdir.

Fixes: #2451
Signed-off-by: Prasanna Kumar Kalever \<prasanna.kalever@redhat.com\>

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

**Comment by pkalever** [comment]
I think CI doesn't need any changes further as we already have:
https://github.com/ceph/ceph-csi/blob/ci/centos/system-status.sh#L43

**Comment by Madhu-1** [comment]
JFYI quay.io is down. so all E2E will fail, for now, no need to restart the tests

File: e2e/rbd.go [hunk 1]
```diff
@@ -1028,9 +1032,10 @@ var _ = Describe("RBD", func() {
 						defaultSCName,
 						nil,
 						map[string]string{
-							"imageFeatures": "layering,journaling,exclusive-lock",
-							"mounter":       "rbd-nbd",
-							"mapOptions":    nbdMapOptions,
+							"imageFeatures":   "layering,journaling,exclusive-lock",
+							"mounter":         "rbd-nbd",
+							"mapOptions":      nbdMapOptions,
+							"cephLogStrategy": "preserve",
```
Comment (Madhu-1) [inline e2e/rbd.go]: define a const for preserve and reuse it.

**Review by Madhu-1 — COMMENTED** [review]
small suggestion LGTM

File: e2e/rbd.go (hunk 1 above)
Comment (pkalever) [reply e2e/rbd.go]: done

**Comment by pkalever** [comment]
ci/centos/mini-e2e-helm/k8s-1.21  fails with:

```
X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute


```

**Review by Madhu-1 — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]

**Comment by pkalever** [comment]
https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/rest/organizations/jenkins/pipelines/mini-e2e-helm_k8s-1.20/runs/2682/nodes/97/log/?start=0

```
[1mSTEP[0m: create a storageclass with ceph-fuse, mount-options and a PVC then bind it to an app
Oct  4 16:55:02.364: INFO: ExecWithOptions {Command:[/bin/sh -c ceph fsid] Namespace:rook-ceph PodName:rook-ceph-tools-7467d8bf8-5jf74 ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
Oct  4 16:55:02.364: INFO: >>> kubeConfig: /root/.kube/config
Oct  4 16:55:03.300: INFO: Waiting up to &PersistentVolumeClaim{ObjectMeta:{csi-cephfs-pvc  cephfs-694    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},Spec:PersistentVolumeClaimSpec{AccessModes:[ReadWriteMany],Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},},VolumeName:,Selector:nil,StorageClassName:*csi-cephfs-sc,VolumeMode:nil,DataSource:nil,DataSourceRef:nil,},Status:PersistentVolumeClaimStatus{Phase:,AccessModes:[],Capacity:ResourceList{},Conditions:[]PersistentVolumeClaimCondition{},},} to be in Bound state
Oct  4 16:55:03.300: INFO: waiting for PVC csi-cephfs-pvc (0 seconds elapsed)
Oct  4 16:55:05.303: INFO: waiting for PVC csi-cephfs-pvc (2 seconds elapsed)
Oct  4 16:55:05.308: INFO: Waiting for PV pvc-667fc098-75af-48a9-b2ee-90f47b646a8d to bind to PVC csi-cephfs-pvc
Oct  4 16:55:05.308: INFO: Waiting up to timeout=10m0s for PersistentVolumeClaims [csi-cephfs-pvc] to have phase Bound
Oct  4 16:55:05.311: INFO: PersistentVolumeClaim csi-cephfs-pvc found and phase=Bound (2.934071ms)
Oct  4 16:55:05.311: INFO: Waiting up to 10m0s for PersistentVolume pvc-667fc098-75af-48a9-b2ee-90f47b646a8d to have phase Bound
Oct  4 16:55:05.313: INFO: PersistentVolume pvc-667fc098-75af-48a9-b2ee-90f47b646a8d found and phase=Bound (1.971743ms)
Oct  4 16:55:05.321: INFO: Waiting up to csi-cephfs-demo-pod to be in Running state
Oct  4 17:05:05.329: FAIL: failed to validate CephFS pvc and application binding with error timed out waiting for the condition
```

**Comment by pkalever** [comment]
```
X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute

```

https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/k8s-e2e-external-storage-1.21/detail/k8s-e2e-external-storage-1.21/1321/pipeline

https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.20/detail/mini-e2e-helm_k8s-1.20/2690/pipeline

https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.22/detail/mini-e2e-helm_k8s-1.22/651/pipeline
