### PR TITLE
rbd : Fix dataPool in createVolumeResponse

### LINKED ISSUE #2828: Wrong dataPool referenced when creating pv with topologyconstrainedPools
Using erasure-coded constrainedDataPools as follow:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: block-topology-ec
provisioner: ceph.rbd.csi.ceph.com
parameters:
    clusterID: test

    imageFormat: "2"
    imageFeatures: layering


    pool: default-replicated
    dataPool: default-erasure

    topologyConstrainedPools: |
      [
        {
          "poolName": "pool-replicated-zone1",
          "dataPool": "pool-erasure-zone1",

          "domainSegments": [
            {
              "domainLabel":"zone",
              "value":"zone1"
            }
          ]
       },
       {
          "poolName": "pool-replicated-zone2",
          "dataPool": "pool-erasure-zone2",

          "domainSegments": [
            {
              "domainLabel":"zone",
              "value":"zone2"
            }
          ]
       },
       {
          "poolName": "pool-replicated-zone3",
          "dataPool": "pool-erasure-zone3",
          
          "domainSegments": [
            { 
              "domainLabel":"zone",
              "value":"zone3"
            }
          ]
       }
      ]

volumeBindingMode: WaitForFirstConsumer
```
And proper tagging of the nodes (topology.kubernetes.io/zone: zone1/2/3), deploying topology contrained pool works ok.
```
rbd  -p pool-replicated-zone3  -p pool-replicated-zone3 info csi-vol-386734ac-7edd-11ec-a2c5-3a73ec2b3d1a|grep pool
	data_pool: pool-erasure-zone3
	features: layering, data-pool
```
However, dataPool referenced in PV is set as the default data-pool.
```
kubectl get pv pvc-5d721f53-6cb3-4b19-bb1b-3a72ff55bf89 -o yaml |grep -i -e pool  -e handle
      dataPool: default-erasure
      journalPool: repldefault
      pool: pool-replicated-zone3
    volumeHandle: 0001-0009-rook-ceph-0000000000000005-386734ac-7edd-11ec-a2c5-3a73ec2b3d1a
```

### PR DESCRIPTION
**Pull request by sbskas**
rbd: Fix dataPool in createVolumeResponse 

return the dataPool used to create the image instead of the default one provided by the createVolumeRequest.
In case of topologyConstrainedDataPools, they may differ.

Signed-off-by: Sébastien Bernard <sebastien.bernard@sfr.com>

# Describe what this PR does #
Onliner to fix the dataPool attribute in the pv object.

## Related issues ##

Fixes: #2828

### CODE REVIEW

**Comment by Rakshith-R** [comment]
> /retest all

jenkins ci was not triggered here earlier at all

File: internal/rbd/controllerserver.go [hunk 1]
```diff
@@ -165,6 +165,7 @@ func (cs *ControllerServer) parseVolCreateRequest(
 func buildCreateVolumeResponse(req *csi.CreateVolumeRequest, rbdVol *rbdVolume) *csi.CreateVolumeResponse {
 	volumeContext := req.GetParameters()
 	volumeContext["pool"] = rbdVol.Pool
+	volumeContext["dataPool"] = rbdVol.DataPool
```
Comment (Madhu-1) [inline internal/rbd/controllerserver.go]: set this only if the DataPool is not empty?

Comment (sbskas) [reply internal/rbd/controllerserver.go]: rbdVol is set here
https://github.com/ceph/ceph-csi/blob/28fef9b3797e41f277d11d9a3bde11e971994503/internal/rbd/rbd_util.go#L1150-L1159
I think the value is safe to copy here.

Comment (Madhu-1) [reply internal/rbd/controllerserver.go]: my concern is when we create PVC from storageclass without `dataPool` we should not set the `dataPool=""` in the PV object.

Comment (sbskas) [reply internal/rbd/controllerserver.go]: Indeed, you're right.
I've added a check.

File: internal/rbd/controllerserver.go [hunk 2]
```diff
@@ -170,6 +170,11 @@ func buildCreateVolumeResponse(req *csi.CreateVolumeRequest, rbdVol *rbdVolume)
 	if rbdVol.RadosNamespace != "" {
 		volumeContext["radosNamespace"] = rbdVol.RadosNamespace
 	}
+
+	if len(rbdVol.DataPool) > 0 {
```
Comment (Madhu-1) [inline internal/rbd/controllerserver.go]: can you change this check to `rbdVol.DataPool != ""` as its a string check?

**Review by Madhu-1 — COMMENTED** [review]
small suggestion

**Comment by sbskas** [comment]
@Madhu-1 I don't understand. The e2e failed on cephfs ? The patch is related to rbd not cephfs.

**Comment by Madhu-1** [comment]
> @Madhu-1 I don't understand. The e2e failed on cephfs ? The patch is related to rbd not cephfs.

not related, its an intermediate known failure.

**Review by Madhu-1 — COMMENTED** [review]
@sbskas can you please squash the commits into 1, this PR is having 2 commits.

**Review by Madhu-1 — APPROVED** [review]

**Review by Rakshith-R — APPROVED** [review]

**Comment by Rakshith-R** [comment]
@merigifyio rebase

**Comment by Rakshith-R** [comment]
@mergifyio rebase
