### PR TITLE
rbd: fix missing data pool

### LINKED ISSUE #4761: CSI snapshots of an erasure-coded-backed volume stores snapshot data in the metadata pool
For reference, I asked about the following in the Ceph Slack: https://ceph-storage.slack.com/archives/C05522L7P60/p1723555634369239

# Describe the bug #
When creating snapshots of erasure-coded RBD volumes the data is stored in the replicated metadata pool.

From the investigation into the ceph-csi code, the data pool option is not set during `CreateSnapshot`->`GenVolFromVolID`.
This instance of rbdVolume is passed to `doSnapshotClone`, which calls `createRBDClone`.
During the clone process:
- a snapshot is created of the original volume
- a new rbd image is created from the snapshot of the original image <- issue happens here
- the original snapshot is deleted

`cloneRbdImageFromSnapshot` copies the RBD image options from the `cloneRbdVol`, created based on the rbdVolume generated from `GenVolFromVolID`. These options are passed to `librbd.CloneImage` and thus copies the data into the erasure-coded metadata pool, rather than keeping the data in the original erasure-coded pool.

This can be seen when inspecting the image in rbd with `rbd info`, the image is missing the data_pool field:
```
rbd info -p ec-metadatapool-us-east-1b csi-snap-12f5524f-de0d-4c21-bc4f-af843960337b
rbd image 'csi-snap-12f5524f-de0d-4c21-bc4f-af843960337b':
	size 30 GiB in 7680 objects
	order 22 (4 MiB objects)
	snapshot_count: 1
	id: 1933d7e8dc4d58
	block_name_prefix: rbd_data.1933d7e8dc4d58
	format: 2
	features: layering, deep-flatten, operations
	op_features: clone-child
	flags: 
	create_timestamp: Sat Aug 10 09:40:32 2024
	access_timestamp: Sat Aug 10 09:40:32 2024
	modify_timestamp: Sat Aug 10 09:40:32 2024
	parent: ec-metadatapool-us-east-1b/csi-vol-5aea1d4e-6575-492e-ad9d-f1c378d9f21c@a0684712-eadf-40b9-8d33-e46711a19fc2
	overlap: 30 GiB
```

Compare this to the original image:
```
rbd image 'csi-vol-5aea1d4e-6575-492e-ad9d-f1c378d9f21c':
	size 30 GiB in 7680 objects
	order 22 (4 MiB objects)
	snapshot_count: 88
	id: 17e84e87be3a0c
	data_pool: ec-blockpool-us-east-1b
	block_name_prefix: rbd_data.17.17e84e87be3a0c
	format: 2
	features: layering, exclusive-lock, object-map, fast-diff, deep-flatten, data-pool, operations
	op_features: clone-parent, snap-trash
	flags: 
	create_timestamp: Thu Aug  8 14:44:59 2024
	access_timestamp: Mon Aug 12 10:24:16 2024
	modify_timestamp: Thu Aug  8 14:44:59 2024
```

# Steps to reproduce #

Steps to reproduce the behavior: Snapshot an erasure-coded volume

# Expected behavior #

The snapshot should remain within the original erasure-coded pool and not have data copied to the replicated metadata pool.

### PR DESCRIPTION
**Pull request by iPraveenParihar**
# Describe what this PR does #

## Problem:

This commit adds populateDataPool() to retrieve the data pool
from the source RBD image, ensuring the data pool is present
in snapshot image.

Fixes: #4761 

## Future concerns ##

List items that are not part of the PR and do not impact it's
functionality, but are work items that can be taken up subsequently.

**Checklist:**

* [x] **Commit Message Formatting**: Commit titles and messages followguidelines in the [developer guide](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#commit-messages).
* [x] Reviewed the developer guide on [Submitting a Pull Request](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#development-workflow)
* [ ] [Pending release notes](https://github.com/ceph/ceph-csi/blob/devel/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next major release.
* [ ] Documentation has been updated, if necessary.
* [ ] Unit tests have been added, if necessary.
* [ ] Integration tests have been added, if necessary.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

* `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)

</details>

### CODE REVIEW

**Comment by Madhu-1** [comment]
@iPraveenParihar i have added complete E2E testing for EC https://github.com/ceph/ceph-csi/pull/6087 please feel free to pick that changes and run on top of this to verify everything works

**Comment by iPraveenParihar** [comment]
> @iPraveenParihar i have added complete E2E testing for EC #6087 please feel free to pick that changes and run on top of this to verify everything works

@Madhu-1 the e2e has passed!

File: internal/rbd/rbd_util.go [hunk 1]
```diff
@@ -536,6 +536,52 @@ func (ri *rbdImage) getImageID() error {
 	return nil
 }
 
+// getDataPoolID returns the data pool ID for the RBD image.
+// For images with erasure-coded data pools, this returns the ID of the pool
```
Comment (Madhu-1) [inline internal/rbd/rbd_util.go]:
```suggestion
// For an image with an erasure-coded data pool, this returns the ID of the pool
```

File: internal/rbd/rbd_util.go [hunk 2]
```diff
@@ -536,6 +536,52 @@ func (ri *rbdImage) getImageID() error {
...
+		return util.InvalidPoolID, err
+	}
+
+	return poolID, nil
+}
+
+// populateDataPool retrieves and sets the data pool name for erasure-coded volumes.
+// For images with a separate data pool (e.g., erasure-coded pools), this ensures
+// the DataPool field is populated so that clones and snapshots preserve the data
+// pool configuration. Errors are logged but not returned as this is non-fatal.
```
Comment (Madhu-1) [inline internal/rbd/rbd_util.go]:
```suggestion
// populateDataPool retrieves and sets the data pool name for erasure-coded volume.
// For image with a separate data pool (e.g., erasure-coded pool), this ensures
// the DataPool field is populated so that clone and snapshot preserve the data
// pool configuration. Errors are logged but not returned as this is non-fatal.
```

File: internal/rbd/rbd_util.go [hunk 3]
```diff
@@ -536,6 +536,52 @@ func (ri *rbdImage) getImageID() error {
...
+func (rv *rbdVolume) populateDataPool(ctx context.Context, cr *util.Credentials) {
+	dataPoolID, err := rv.getDataPoolID()
+	if err != nil {
+		log.ErrorLog(ctx, "failed to get data pool ID for volume %s: %v", rv, err)
+
+		return
+	}
+
+	if dataPoolID == util.InvalidPoolID {
```
Comment (Madhu-1) [inline internal/rbd/rbd_util.go]: When will this be reached? i assume this will happen for the replicated pool, if yes please add a comment about this check

**Review by Madhu-1 — COMMENTED** [review]
small doc nits, LGTM

File: internal/rbd/rbd_util.go [hunk 4]
```diff
@@ -536,6 +536,53 @@ func (ri *rbdImage) getImageID() error {
...
+	}
+
+	return poolID, nil
+}
+
+// populateDataPool retrieves and sets the data pool name for erasure-coded volume.
+// For image with a separate data pool (e.g., erasure-coded pool), this ensures
+// the DataPool field is populated so that clone and snapshot preserve the data
+// pool configuration. Errors are logged but not returned as this is non-fatal.
+func (rv *rbdVolume) populateDataPool(ctx context.Context, cr *util.Credentials) {
```
Comment (Madhu-1) [inline internal/rbd/rbd_util.go]: good to return an error from this function and handle it at the caller

File: internal/rbd/rbd_util.go [hunk 5]
```diff
@@ -1242,8 +1281,13 @@ func generateVolumeFromVolumeID(
 		}
 	}
 	err = rbdVol.getImageInfo()
+	if err != nil {
+		return rbdVol, err
+	}
 
-	return rbdVol, err
+	rbdVol.populateDataPool(ctx, cr)
```
Comment (Rakshith-R) [inline internal/rbd/rbd_util.go]: poolID is avaiable in this function flow.
pass poolID and if it does not match dataPoolID, then fetch dataPoolName and populate it ?

**Review by Rakshith-R — COMMENTED** [review]
just a small nit.

**Review by Rakshith-R — COMMENTED** [review]
PVC-PVC clone e2e with temp -image check still needs to be added ? 
+ small nit

File: e2e/rbd.go [hunk 6]
```diff
@@ -1195,6 +1195,327 @@ var _ = Describe("RBD", func() {
...
+					logAndFail("failed to delete snapshot: %v", err)
+				}
+				err = deletePVCAndValidatePV(f.ClientSet, pvc, deployTimeout)
+				if err != nil {
+					logAndFail("failed to delete PVC: %v", err)
+				}
+				validateRBDImageCount(f, 0, defaultRBDPool)
+
+				// Delete erasure-coded storageclass and restore default
+				err = deleteResource(rbdExamplePath + "storageclass.yaml")
```
Comment (Rakshith-R) [inline e2e/rbd.go]: you used another name for ec storageclass, so this step is just deleting and creating the same sc.

Comment (iPraveenParihar) [reply e2e/rbd.go]: The ec class is deleted just below that and the default class is deleted (may-be modified) and re-created.

Comment (Rakshith-R) [reply e2e/rbd.go]: got it,
but you already deleted regular sc at line 1262, then this is a repetition

**Review by Rakshith-R — COMMENTED** [review]
just small nit,
everything else looks good

File: e2e/rbd.go (hunk 6 above)
Comment (iPraveenParihar) [reply e2e/rbd.go]: fixed it!

**Review by Madhu-1 — DISMISSED** [review]

**Review by Rakshith-R — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Comment by iPraveenParihar** [comment]
@mergifyio queue
