### PR TITLE
cephfs: use new 'ceph fs resize' command when available

### LINKED ISSUE #1002: CephFS CSI driver not update quota when pvc request size resized
# Describe the bug #
Change in pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileshare
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: csi-cephfs-sc
```
storage: 20Mi

pv and pvc object in kubernetes changed
```
k get pv
pvc-60f6f968-050b-4a28-9112-db8de1747e6b   20Mi       RWX            Delete           Bound       default/fileshare                               csi-cephfs-sc            120m
k get pvc
fileshare        Bound    pvc-60f6f968-050b-4a28-9112-db8de1747e6b   20Mi       RWX            csi-cephfs-sc   121m
```

but quota on cephfs directory not changed
```
getfattr -n ceph.quota.max_bytes 5f858910-7fcf-408d-a14b-4c192aaa546e/
# file: 5f858910-7fcf-408d-a14b-4c192aaa546e/
ceph.quota.max_bytes="10485760"

```
# Environment details #

- Image/version of Ceph CSI driver
2.1.0
- helm chart version
- Kubernetes cluster version
1.16.9
- Logs
`k logs ceph-csi-cephfs-provisioner-6d7cb9978b-b58nh -c csi-resizer`
```
I0502 15:37:39.591857       1 controller.go:225] Started PVC processing "default/fileshare"
I0502 15:37:39.612923       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"fileshare", UID:"60f6f968-050b-4a28-9112-db8de1747e6b", APIVersion:"v1", ResourceVersion:"79966", FieldPath:""}): type: 'Normal' reason: 'Resizing' External resizer is resizing volume pvc-60f6f968-050b-4a28-9112-db8de1747e6b
I0502 15:37:39.622313       1 connection.go:182] GRPC call: /csi.v1.Controller/ControllerExpandVolume
I0502 15:37:39.622335       1 connection.go:183] GRPC request: {"capacity_range":{"required_bytes":20971520},"secrets":"***stripped***","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["debug"]}},"access_mode":{"mode":5}},"volume_id":"0001-0024-bcd0d202-fba8-4352-b25d-75c89258d5ab-0000000000000001-22b377c5-8c7b-11ea-b1ba-ea0c41f9366d"}
I0502 15:37:41.505427       1 connection.go:185] GRPC response: {"capacity_bytes":20971520}
I0502 15:37:41.506125       1 connection.go:186] GRPC error: <nil>
I0502 15:37:41.506139       1 controller.go:364] Resize volume succeeded for volume "pvc-60f6f968-050b-4a28-9112-db8de1747e6b", start to update PV's capacity
I0502 15:37:41.543608       1 controller.go:370] Update capacity of PV "pvc-60f6f968-050b-4a28-9112-db8de1747e6b" to 20Mi succeeded
I0502 15:37:41.551288       1 controller.go:399] Resize PVC "default/fileshare" finished
I0502 15:37:41.551661       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"fileshare", UID:"60f6f968-050b-4a28-9112-db8de1747e6b", APIVersion:"v1", ResourceVersion:"79966", FieldPath:""}): type: 'Normal' reason: 'VolumeResizeSuccessful' Resize volume succeeded

```
# Steps to reproduce #

install csi cephfs driver from helm chart 2.1.0
config storage class
create pvc, wait for pv
change request storage size in pvc - look on cephfs quotas

### PR DESCRIPTION
**Pull request by Madhu-1**
the cephfs resize command is available if the ceph cluster version is greater than or equal to 14.2.8 the cephcsi has to do a ceph cluster version check to verify ceph fs subvolume resize functionality is supported or not

ceph change log:https://docs.ceph.com/docs/master/releases/nautilus/#v14-2-8-nautilus

Fixes #1002

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

File: internal/cephfs/volume.go [hunk 1]
```diff
@@ -34,6 +34,15 @@ var (
 	// Subvolume group create gets called every time the plugin loads, though it doesn't result in error
 	// its unnecessary
 	cephfsInit = false
+
+	// ceph fs subvolume resize is supported from 14.2.8 onwards
+	maxCephVersionForResize      = 14
+	patchCephVersionForResize    = 2
```
Comment (humblec) [inline internal/cephfs/volume.go:40]: @Madhu-1 major,minor, patch would be good I believe insteda of max, patch, and subLevel

**Comment by humblec** [comment]
@Madhu-1 regardless of we use `resize` command, the current `create` command with a bigger size should also work, Isnt it ? just to make it clear

**Comment by Madhu-1** [comment]
> @Madhu-1 regardless of we use `resize` command, the current `create` command with a bigger size should also work, Isnt it ? just to make it clear

@humblec create won't work if the cluster version is greater than 14.2.7 please check #1002 for more details

**Comment by humblec** [comment]
> > @Madhu-1 regardless of we use `resize` command, the current `create` command with a bigger size should also work, Isnt it ? just to make it clear
> 
> @humblec create won't work if the cluster version is greater than 14.2.7 please check #1002 for more details


@madhu-1 this is what I am trying to confirm, in that sense its a backward compatibility break that too in a 'patch" version!! which I dont expect to happen !! We really have to make sure such breakage does not happen. 

@dillaman any thoughts here on how we can avoid this ?

File: internal/cephfs/volume.go [hunk 2]
```diff
@@ -34,6 +34,15 @@ var (
 	// Subvolume group create gets called every time the plugin loads, though it doesn't result in error
 	// its unnecessary
 	cephfsInit = false
+
+	// ceph fs subvolume resize is supported from 14.2.8 onwards
+	majorCephVersionForResize = 14
+	minorCephVersionForResize = 2
+	patchCephVersionForResize = 8
```
Comment (nixpanic) [inline internal/cephfs/volume.go:41]: This version checking is not sufficient. 15.0.x does not have the support. You'll need to do something like `kernelSupportsQuota()`, or just try to execute the new command, and fallback to the old way of resizing (like RBD does for deleting images through a task, or inline).

File: internal/cephfs/volume_test.go [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+*/
+
+package cephfs
+
+import (
+	"context"
+	"testing"
+)
+
+func Test_checkVersionIsGreater(t *testing.T) {
```
Comment (nixpanic) [inline internal/cephfs/volume_test.go:24]: don't use `_` in function names or variables, follow the Golang standards instead.

File: internal/cephfs/volume_test.go [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+				"a.b.c",
+			},
+			false,
+			true,
+		},
+		{
+			"valid ceph version which supports resize",
+			args{
+				context.TODO(),
+				"14.2.8",
```
Comment (nixpanic) [inline internal/cephfs/volume_test.go:75]: Add a test for version 15.0 that does not have the resize support, and 15.2.2(?) that should get it

**Comment by nixpanic** [comment]
Suggested subject for the commit and PR:

    cephfs: use new 'ceph fs resize' command when available

File: internal/cephfs/volume.go (hunk 2 above)
Comment (Madhu-1) [reply internal/cephfs/volume.go:41]: are you sure that 15.0.x doesn't have support?  let me remove the complete check of ceph version based on the command availability we can do it.

File: internal/cephfs/volume_test.go (hunk 3 above)
Comment (Madhu-1) [reply internal/cephfs/volume_test.go:24]: This is auto generated testcase from my editor. do you mean CI didn't catch it?

File: internal/cephfs/volume_test.go (hunk 4 above)
Comment (Madhu-1) [reply internal/cephfs/volume_test.go:75]: am removing check for kernel version

File: internal/cephfs/volume.go (hunk 2 above)
Comment (nixpanic) [reply internal/cephfs/volume.go:41]: I thought it got added to Ceph 15.2.x, but I can be wrong. It is a backported feature in any case, so I think it it not in all 15.x versions.

File: internal/cephfs/volume_test.go (hunk 4 above)
Comment (nixpanic) [reply internal/cephfs/volume_test.go:75]: no need to check the kernel version? (ah, maybe Ceph version?)

**Comment by Madhu-1** [comment]
i have removed the check for ceph version. if the command is available then we will use it if its not available we will use ceph fs create command

File: internal/cephfs/volume.go [hunk 5]
```diff
@@ -134,6 +140,44 @@ func createVolume(ctx context.Context, volOptions *volumeOptions, cr *util.Crede
...
+		err := execCommandErr(
+			ctx,
+			"ceph",
+			args[:]...)
+
+		if err == nil {
+			resizeSupportedList[volOptions.ClusterID] = true
+			return nil
+		}
+		if !strings.Contains(err.Error(), inValidCommmand) {
```
Comment (nixpanic) [inline internal/cephfs/volume.go:172]: Some comments here would help. In case the command is invalid, fall-through and do the resize with `createVolume()` instead.

File: internal/cephfs/volume.go [hunk 6]
```diff
@@ -134,6 +140,44 @@ func createVolume(ctx context.Context, volOptions *volumeOptions, cr *util.Crede
 	return nil
 }
 
+func resizeVolume(ctx context.Context, volOptions *volumeOptions, cr *util.Credentials, volID volumeID, bytesQuota int64) error {
```
Comment (nixpanic) [inline internal/cephfs/volume.go:143]: Maybe add a comment about the fallback logic that happens in this function? The `ceph fs subvolume resize` command was added in recent Ceph versions, in case it is not available apply the resize through the ol `ceph volume create` command?

File: internal/cephfs/controllerserver.go [hunk 7]
```diff
@@ -361,7 +361,7 @@ func (cs *ControllerServer) ControllerExpandVolume(ctx context.Context, req *csi
 
 	RoundOffSize := util.RoundOffBytes(req.GetCapacityRange().GetRequiredBytes())
 
-	if err = createVolume(ctx, volOptions, cr, volumeID(volIdentifier.FsSubvolName), RoundOffSize); err != nil {
+	if err = resizeVolume(ctx, volOptions, cr, volumeID(volIdentifier.FsSubvolName), RoundOffSize); err != nil {
 		klog.Errorf(util.Log(ctx, "failed to expand volume %s: %v"), volumeID(volIdentifier.FsSubvolName), err)
```
Comment (nixpanic) [inline internal/cephfs/controllerserver.go:365]: Is 'expand' actually correct here? Can CephFS not shrink volumes?

Comment (Madhu-1) [reply internal/cephfs/controllerserver.go:365]: it's supported in cephfs. but it's not supported in kubernetes word, you cannot shrink the PVC

**Comment by Madhu-1** [comment]
@nixpanic added some comments to the function

File: internal/cephfs/controllerserver.go (hunk 7 above)
Comment (nixpanic) [reply internal/cephfs/controllerserver.go:365]: yeah, I thought so... but it may get added to CSI at one point? Bu I guess we'll just fix this up when we're testing that.

**Comment by Madhu-1** [comment]
@humblec PTAL

**Comment by humblec** [comment]
> @humblec PTAL

@Madhu-1  Just to double confirm, does `resizevolume` work on clusters <14.2.8 ?

**Comment by Madhu-1** [comment]
> > @humblec PTAL
> 
> @Madhu-1 Just to double confirm, does `resizevolume` work on clusters <14.2.8 ?

cephcsi current E2E runs on 14.2.4

**Comment by Madhu-1** [comment]
> Could a new patch release be available soon for this critical issue?

yeah sure will take it in for next patch release

**Comment by yanchicago** [comment]
What's the planned date for the next patch? Really a needed fix.

**Comment by Madhu-1** [comment]
> What's the planned date for the next patch? Really a needed fix
will  do a release in the next 2 days

**Comment by yanchicago** [comment]
Many thanks.
