### PR TITLE
rbd: add volume locks for reclaimspace operations

### LINKED ISSUE #4637: csi-addons/rbd: make use of volume locks for reclaim space operations
# Describe the bug #

Reclaim space operations need to be protected with volume locks similar to other calls to prevent multiple process executing rbd sparsify / fstrim on same volume.

refer: https://github.com/ceph/ceph-csi/blob/devel/internal/csi-addons/rbd/replication.go#L238

# Environment details #

- Image/version of Ceph CSI driver : all
- Helm chart version : all 
- Kernel version : all
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : krbd
- Kubernetes cluster version : all
- Ceph cluster version : all

# Steps to reproduce #

1. Setup details: '...'
1. Deployment to trigger the issue '....'
1. See error

# Actual results #

Multiple rbd sparsify/ fstrim can be triggered in case the process takes too long and controller times out.

# Expected behavior #

Only one rbd sparsify/ fstrim process per volume should run at a time.

### PR DESCRIPTION
**Pull request by iPraveenParihar**
# Describe what this PR does #

This commit adds VolumeLocks on reclaimspace operations to
prevent multiple process executing rbd sparsify/fstrim on
same volume.

## Related issues ##

Closes: #4637, #4648

**Checklist:**

* [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#commit-messages).
* [x] Reviewed the developer guide on [Submitting a Pull Request](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#development-workflow)
* [x] [Pending release notes](https://github.com/ceph/ceph-csi/blob/devel/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next major release.
* [x] Documentation has been updated, if necessary.
* [x] Unit tests have been added, if necessary.
* [x] Integration tests have been added, if necessary.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

* `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)

</details>

### CODE REVIEW

File: internal/csi-addons/rbd/reclaimspace.go [hunk 1]
```diff
@@ -90,12 +99,14 @@ func (rscs *ReclaimSpaceControllerServer) ControllerReclaimSpace(
...
 	*rs.UnimplementedReclaimSpaceNodeServer
+	// Embed ControllerServer as it implements helper functions
+	*rbdutil.ControllerServer
 }
 
 // NewReclaimSpaceNodeServer creates a new IdentityServer which handles the
 // Identity Service requests from the CSI-Addons specification.
-func NewReclaimSpaceNodeServer() *ReclaimSpaceNodeServer {
-	return &ReclaimSpaceNodeServer{}
+func NewReclaimSpaceNodeServer(c *rbdutil.ControllerServer) *ReclaimSpaceNodeServer {
```
Comment (Madhu-1) [inline internal/csi-addons/rbd/reclaimspace.go]: You need to use `NewNodeServer` not the ControllerServer for node level operations.

**Review by Madhu-1 — CHANGES_REQUESTED** [review]

File: internal/csi-addons/rbd/reclaimspace.go (hunk 1 above)
Comment (iPraveenParihar) [reply internal/csi-addons/rbd/reclaimspace.go]: Ahh, made typo!
Thanks, will fixed it.

File: internal/rbd/driver/driver.go [hunk 2]
```diff
@@ -213,7 +210,7 @@ func (r *Driver) setupCSIAddonsServer(conf *util.Config) error {
 	r.cas.RegisterService(is)
 
 	if conf.IsControllerServer {
-		rs := casrbd.NewReclaimSpaceControllerServer()
+		rs := casrbd.NewReclaimSpaceControllerServer(NewControllerServer(r.cd))
```
Comment (Rakshith-R) [inline internal/rbd/driver/driver.go]:
```suggestion
		rs := casrbd.NewReclaimSpaceControllerServer(r.cs)
```

File: internal/rbd/driver/driver.go [hunk 3]
```diff
@@ -224,7 +221,9 @@ func (r *Driver) setupCSIAddonsServer(conf *util.Config) error {
 	}
 
 	if conf.IsNodeServer {
-		rs := casrbd.NewReclaimSpaceNodeServer()
+		rs := casrbd.NewReclaimSpaceNodeServer(
+			NewNodeServer(r.cd, conf.Vtype, nodeLabels, topology, crushLocationMap),
+		)
```
Comment (Rakshith-R) [inline internal/rbd/driver/driver.go]:
```suggestion
		rs := casrbd.NewReclaimSpaceNodeServer(r.ns)
```

**Review by Rakshith-R — COMMENTED** [review]
Can we use already created controller and node servers ?

File: internal/rbd/driver/driver.go (hunk 2 above)
Comment (iPraveenParihar) [reply internal/rbd/driver/driver.go]: Yes, we should use the same already created Controller and Node Server struct, as they will share the same sets of locks. Since the ReplicationServer uses a new ControllerServer struct, I decided to follow the same for ReclaimSpace ControllerServer/NodeServer.

Comment (Rakshith-R) [reply internal/rbd/driver/driver.go]: I forgot about the sharing locks with cephcsi controllerserver and nodeserver.

Let's just add new volume locks for both reclaimspace node&controller server in this pr and open a new issue to discuss whether we should share it with the default servers or not.

Both sparsify and fstrim are blocking operation, that's why we may need further discussion.

cc @Madhu-1

File: internal/rbd/driver/driver.go [hunk 4]
```diff
@@ -43,6 +43,8 @@ type Driver struct {
 	cas *csiaddons.CSIAddonsServer
 }
 
+var nodeLabels, topology, crushLocationMap map[string]string
```
Comment (Rakshith-R) [inline internal/rbd/driver/driver.go]: Let's just add volumeLocks to the rs controller and node server structs directly instead of inheriting and adding global variables.

File: internal/rbd/driver/driver.go (hunk 2 above)
Comment (Madhu-1) [reply internal/rbd/driver/driver.go]: lets discuss on this one and we need to see can what will happen when we try to do nodeserver operations like (expand/umount) etc when the fstrim is going on can it leads to corruption etc. based on that we can have central/shared locking. Is it allowed to expand or remove the image when the ControllerReclaimOperation is going on etc.

File: internal/rbd/driver/driver.go [hunk 5]
```diff
@@ -213,7 +211,9 @@ func (r *Driver) setupCSIAddonsServer(conf *util.Config) error {
 	r.cas.RegisterService(is)
 
 	if conf.IsControllerServer {
-		rs := casrbd.NewReclaimSpaceControllerServer()
+		rs := casrbd.NewReclaimSpaceControllerServer(&rbd.ControllerServer{
+			VolumeLocks: util.NewVolumeLocks(),
+		})
```
Comment (Madhu-1) [inline internal/rbd/driver/driver.go]: I dont think we need to define locking here, we already have `casrbd.NewReplicationServer(NewControllerServer(r.cd))` at line 222 which is already initializing the locking internally we don't need to do it explicitly.

File: internal/rbd/driver/driver.go [hunk 6]
```diff
@@ -224,7 +224,9 @@ func (r *Driver) setupCSIAddonsServer(conf *util.Config) error {
 	}
 
 	if conf.IsNodeServer {
-		rs := casrbd.NewReclaimSpaceNodeServer()
+		rs := casrbd.NewReclaimSpaceNodeServer(&rbd.NodeServer{
+			VolumeLocks: util.NewVolumeLocks(),
```
Comment (Madhu-1) [inline internal/rbd/driver/driver.go]: same here as well can you please check?

Comment (Madhu-1) [reply internal/rbd/driver/driver.go]: you might need to pass `NewNodeServer(r.cd)`

Comment (iPraveenParihar) [reply internal/rbd/driver/driver.go]: `NewNodeServer()` needs other params to be passed. So instead created NodeServer struct with volumeLocks
https://github.com/ceph/ceph-csi/blob/9574fa881bc6e2840ebb135d49fef0c1c5c84b9a/internal/rbd/driver/driver.go#L69-L81

Comment (Madhu-1) [reply internal/rbd/driver/driver.go]: got it. the aim looks to be new locks instead of sharing as per https://github.com/ceph/ceph-csi/pull/4641#discussion_r1616689529, lets do this one.

**Review by Madhu-1 — COMMENTED** [review]
LGTM, please test this change manually and share the result to ensure nothing breaks as we don't have any E2E tests for this one.

**Comment by iPraveenParihar** [comment]
Created a PVC of 1Gi and wrote dummy data of 500M and deleted it.
```
root@rbd-pod-test:/# dd if=/dev/zero of=/var/lib/www/html/dummy-file bs=1M count=500
500+0 records in
500+0 records out
524288000 bytes (524 MB, 500 MiB) copied, 1.6972 s, 309 MB/s
root@rbd-pod-test:/# sync
root@rbd-pod-test:/# rm /var/lib/www/html/dummy-file
root@rbd-pod-test:/# ls -l /var/lib/www/html/
total 16
drwx------ 2 root root 16384 May 29 07:23 lost+found
```
before ReclaimSpace operation - 

```
[root@c1 /]# rbd du -p replicapool
warning: fast-diff map is not enabled for csi-vol-58a49f13-ff2e-4415-b1a8-21ec59d95017. operation may be slow.
NAME                                          PROVISIONED  USED
csi-vol-58a49f13-ff2e-4415-b1a8-21ec59d95017        1 GiB  528 MiB
```

created ReclaimSpaceJob for the PVC
```
pm@dhcp53-176:~$ cat <<EOF | k create -f -
> apiVersion: csiaddons.openshift.io/v1alpha1
kind: ReclaimSpaceJob
metadata:
  name: sample-1
spec:
  target:
    persistentVolumeClaim: rbd-pvc-test
  backOffLimit: 10
  retryDeadlineSeconds: 900
  timeout: 600
> EOF
reclaimspacejob.csiaddons.openshift.io/sample-1 created
```

/NodeReclaimSpace - `fstrim` operation succeed 

```
I0529 07:29:28.134875 2566810 utils.go:198] ID: 23 GRPC call: /reclaimspace.ReclaimSpaceNode/NodeReclaimSpace
I0529 07:29:28.138386 2566810 utils.go:199] ID: 23 GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com/cff6345ad1aff4cb25770de65b8012a934530bfd9d29bc77c557332df5607126/globalmount","volume_capability":{"AccessType":{"Mount":{}},"access_mode":{"mode":7}},"volume_id":"0001-0009-rook-ceph-0000000000000008-58a49f13-ff2e-4415-b1a8-21ec59d95017"}
I0529 07:29:28.439310 2566810 cephcmds.go:105] ID: 23 command succeeded: fstrim [/var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com/cff6345ad1aff4cb25770de65b8012a934530bfd9d29bc77c557332df5607126/globalmount/0001-0009-rook-ceph-0000000000000008-58a49f13-ff2e-4415-b1a8-21ec59d95017]
```

```
[root@c1 /]# rbd du -p replicapool
warning: fast-diff map is not enabled for csi-vol-58a49f13-ff2e-4415-b1a8-21ec59d95017. operation may be slow.
NAME                                          PROVISIONED  USED
csi-vol-58a49f13-ff2e-4415-b1a8-21ec59d95017        1 GiB  304 MiB
```

/ControllerReclaimSpace - `sparsify` command succeed
```
I0529 07:29:28.589924       1 utils.go:198] ID: 26 GRPC call: /reclaimspace.ReclaimSpaceController/ControllerReclaimSpace
I0529 07:29:28.595724       1 utils.go:199] ID: 26 GRPC request: {"parameters":{"clusterID":"rook-ceph","encryptionKMSID":"azure-test","imageFeatures":"layering","imageFormat":"2","imageName":"csi-vol-58a49f13-ff2e-4415-b1a8-21ec59d95017","journalPool":"replicapool","pool":"replicapool","storage.kubernetes.io/csiProvisionerIdentity":"1716966822191-8666-rook-ceph.rbd.csi.ceph.com"},"secrets":"***stripped***","volume_id":"0001-0009-rook-ceph-0000000000000008-58a49f13-ff2e-4415-b1a8-21ec59d95017"}
I0529 07:29:28.690999       1 omap.go:89] ID: 26 got omap values: (pool="replicapool", namespace="", name="csi.volume.58a49f13-ff2e-4415-b1a8-21ec59d95017"): map[csi.imageid:73c2aff800e79 csi.imagename:csi-vol-58a49f13-ff2e-4415-b1a8-21ec59d95017 csi.volname:pvc-ffd7ee84-6ae9-47fc-8eb0-32d9c255b92b csi.volume.owner:reclaim-ns]
I0529 07:29:28.761741       1 reclaimspace.go:77] ID: 26 volume with ID "0001-0009-rook-ceph-0000000000000008-58a49f13-ff2e-4415-b1a8-21ec59d95017" is in use, skipping sparsify operation
I0529 07:29:28.762193       1 utils.go:205] ID: 26 GRPC response: {}
I0529 07:31:26.161922       1 utils.go:198] ID: 27 GRPC call: /reclaimspace.ReclaimSpaceController/ControllerReclaimSpace
I0529 07:31:26.163979       1 utils.go:199] ID: 27 GRPC request: {"parameters":{"clusterID":"rook-ceph","encryptionKMSID":"azure-test","imageFeatures":"layering","imageFormat":"2","imageName":"csi-vol-58a49f13-ff2e-4415-b1a8-21ec59d95017","journalPool":"replicapool","pool":"replicapool","storage.kubernetes.io/csiProvisionerIdentity":"1716966822191-8666-rook-ceph.rbd.csi.ceph.com"},"secrets":"***stripped***","volume_id":"0001-0009-rook-ceph-0000000000000008-58a49f13-ff2e-4415-b1a8-21ec59d95017"}
I0529 07:31:26.171744       1 omap.go:89] ID: 27 got omap values: (pool="replicapool", namespace="", name="csi.volume.58a49f13-ff2e-4415-b1a8-21ec59d95017"): map[csi.imageid:73c2aff800e79 csi.imagename:csi-vol-58a49f13-ff2e-4415-b1a8-21ec59d95017 csi.volname:pvc-ffd7ee84-6ae9-47fc-8eb0-32d9c255b92b csi.volume.owner:reclaim-ns]
I0529 07:31:26.697576       1 utils.go:205] ID: 27 GRPC response: {}
```

```
[root@c1 /]# rbd du -p replicapool
warning: fast-diff map is not enabled for csi-vol-58a49f13-ff2e-4415-b1a8-21ec59d95017. operation may be slow.
NAME                                          PROVISIONED  USED
csi-vol-58a49f13-ff2e-4415-b1a8-21ec59d95017        1 GiB  28 MiB
```





@Madhu-1, will this be enough for the test?

**Review by Madhu-1 — DISMISSED** [review]

File: internal/csi-addons/rbd/reclaimspace.go [hunk 7]
```diff
@@ -37,12 +37,14 @@ import (
 // of CSI-addons reclaimspace controller service spec.
 type ReclaimSpaceControllerServer struct {
 	*rs.UnimplementedReclaimSpaceControllerServer
+	// Embed ControllerServer as it implements helper functions
+	*rbdutil.ControllerServer
```
Comment (nixpanic) [inline internal/csi-addons/rbd/reclaimspace.go]: It would be cleaner to pass `*util.VolumeLocks` and have that as an attribute of this struct.

File: internal/csi-addons/rbd/reclaimspace.go [hunk 8]
```diff
@@ -90,12 +99,14 @@ func (rscs *ReclaimSpaceControllerServer) ControllerReclaimSpace(
 // of CSI-addons reclaimspace controller service spec.
 type ReclaimSpaceNodeServer struct {
 	*rs.UnimplementedReclaimSpaceNodeServer
+	// Embed NodeServer as it implements helper functions
+	*rbdutil.NodeServer
```
Comment (nixpanic) [inline internal/csi-addons/rbd/reclaimspace.go]: same here, it would be cleaner to pass `*util.VolumeLocks` and have that as an attribute of this struct.

**Review by nixpanic — CHANGES_REQUESTED** [review]

**Comment by iPraveenParihar** [comment]
@Mergifyio rebase

File: internal/csi-addons/rbd/reclaimspace.go [hunk 9]
```diff
@@ -37,12 +37,13 @@ import (
 // of CSI-addons reclaimspace controller service spec.
 type ReclaimSpaceControllerServer struct {
 	*rs.UnimplementedReclaimSpaceControllerServer
+	*util.VolumeLocks
```
Comment (nixpanic) [inline internal/csi-addons/rbd/reclaimspace.go]: that is not exactly what I meant, please consider this, making it a private/internal member of the struct:

```go
type ReclaimSpaceControllerServer struct {
    *rs.UnimplementedReclaimSpaceControllerServer

    // volumeLocks are shared with the CSI Controller
    volumeLocks *util.VolumeLocks
}

func NewReclaimSpaceControllerServer(vl *util.VolumeLocks) *ReclaimSpaceControllerServer {
    return &ReclaimSpaceControllerServer{
        volumeLocks: vl,
    }
}
```

That way, the same instance of VolumeLocks can be shared between both of the controllers.

File: internal/rbd/driver/driver.go [hunk 10]
```diff
@@ -70,14 +70,14 @@ func NewNodeServer(
...
-) (*rbd.NodeServer, error) {
+) *rbd.NodeServer {
 	cliReadAffinityMapOptions := util.ConstructReadAffinityMapOption(crushLocationMap)
 	ns := rbd.NodeServer{
 		DefaultNodeServer: csicommon.NewDefaultNodeServer(d, t, cliReadAffinityMapOptions, topology, nodeLabels),
 		VolumeLocks:       util.NewVolumeLocks(),
 	}
 
-	return &ns, nil
+	return &ns
```
Comment (nixpanic) [inline internal/rbd/driver/driver.go:80]: this is an unrelated change, and should probably be part of a separate commit (or even PR)

File: internal/csi-addons/rbd/reclaimspace.go [hunk 11]
```diff
@@ -90,12 +98,13 @@ func (rscs *ReclaimSpaceControllerServer) ControllerReclaimSpace(
 // of CSI-addons reclaimspace controller service spec.
 type ReclaimSpaceNodeServer struct {
 	*rs.UnimplementedReclaimSpaceNodeServer
+	*util.VolumeLocks
```
Comment (nixpanic) [inline internal/csi-addons/rbd/reclaimspace.go]: same here, don't inherit the functions of the struct, just add a new member for it.

File: internal/csi-addons/rbd/reclaimspace.go (hunk 9 above)
Comment (iPraveenParihar) [reply internal/csi-addons/rbd/reclaimspace.go]: @nixpanic, based on your comment https://github.com/ceph/ceph-csi/issues/4648#issuecomment-2140176480, If there is no downside of not sharing VolumeLocks? then would it be safe to share VolumeLocks with rbd ControllerServer?

Something like this?
```go
return &ReclaimSpaceControllerServer{
    volumeLocks: util.NewVolumeLocks()
}
```

File: internal/csi-addons/rbd/reclaimspace.go [hunk 12]
```diff
@@ -90,12 +98,13 @@ func (rscs *ReclaimSpaceControllerServer) ControllerReclaimSpace(
...
 }
 
 // NewReclaimSpaceNodeServer creates a new IdentityServer which handles the
 // Identity Service requests from the CSI-Addons specification.
 func NewReclaimSpaceNodeServer() *ReclaimSpaceNodeServer {
-	return &ReclaimSpaceNodeServer{}
+	return &ReclaimSpaceNodeServer{VolumeLocks: util.NewVolumeLocks()}
```
Comment (Madhu-1) [inline internal/csi-addons/rbd/reclaimspace.go]: we should reuse the lock from the node server like https://github.com/ceph/ceph-csi/pull/4690/files#diff-d44bddac57ff52af0445463bf6fe3e03b7aed04b3d41ea639d35c01522a74808R233. can you please address this one.

Comment (iPraveenParihar) [reply internal/csi-addons/rbd/reclaimspace.go]: Okay, so will share VolumeLocks? Then I'll close this https://github.com/ceph/ceph-csi/issues/4648?

Comment (Madhu-1) [reply internal/csi-addons/rbd/reclaimspace.go]: @iPraveenParihar yes please

**Review by Madhu-1 — DISMISSED** [review]

**Comment by iPraveenParihar** [comment]
Fixed CI failures, @Madhu-1 can you re-approve please?

**Review by Madhu-1 — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio queue

**Comment by nixpanic** [comment]
@mergifyio requeue

**multi-arch-build** failed to download some Ceph packages

**Comment by nixpanic** [comment]
@mergifyio requeue
