### PR TITLE
cephfs: check ENOTEMPTY when removing subvolume

### LINKED ISSUE #1491: Cephfs: check ENOTEMPTY in  DeleteVolume for subvolumes having snapshots
Currently, if the subvolume has the snapshots and the `--retain-snaps`feature is not present on the subvolume we will attempt for the subvolume deletion, due to this from the logs its not clear why the subvolume deletion is failing.
Incase `--retain-snaps` feature is not present we should check for the snapshots to give better error message to the user.

### PR DESCRIPTION
**Pull request by Madhu-1**
return a proper error message to the user when the subvolume has the snapshots and it cannot be removed until the snapshots on the subvolume have to be deleted.

fixes #1491
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

File: internal/cephfs/controllerserver.go [hunk 1]
```diff
@@ -343,6 +343,9 @@ func (cs *ControllerServer) DeleteVolume(ctx context.Context, req *csi.DeleteVol
 
 	if err = purgeVolume(ctx, volumeID(vID.FsSubvolName), cr, volOptions, false); err != nil {
 		util.ErrorLog(ctx, "failed to delete volume %s: %v", volID, err)
+		if errors.Is(err, ErrVolumeHasSnapshots) {
+			return nil, status.Error(codes.FailedPrecondition, err.Error())
+		}
 		// All errors other than ErrVolumeNotFound should return an error back to the caller
```
Comment (Yuggupta27) [inline internal/cephfs/controllerserver.go:349]: Does this comment needs changing?

**Review by Yuggupta27 — COMMENTED** [review]
Minor comment. Looks Good otherwise :+1:

**Review by Yuggupta27 — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]

**Review by humblec — APPROVED** [review]
