### PR TITLE
rbd: copy passphrase for encrypted clones

### LINKED ISSUE #1470: Allow snapshot creation on an encrypted volume
# Describe the bug #

At present, snapshot creation is blocked on a volume which is already encrypted. The reason to disallow this operation was to avoid the possibilities of the  attack   on encryption key.  

Considering our current snapshot implementation create a new CLONED volume in backend , I feel, we can use a new key for the snapshot volume. However we have to figure out the the possibile solutions on this.

@vasyl-purchel please share your thoughts as well.

### PR DESCRIPTION
**Pull request by nixpanic**
When a source volume is encrypted, the passphrase needs to be copied and
stored for the newly cloned volume.

This requires the `rbdImage.encryption` component to be configured, and that
is what most of the changes in this PR make possible.

Fixes: #1470

## Notes for reviewers

This PR contains a large number of commits. The easiest to review these is by going to https://github.com/ceph/ceph-csi/pull/1918/commits and clicking the title of the 1st change. Then use the `[next]` button in the top blue bar where the subject of the change is written to go to the next commit.

Each single commit is relatively simple, reviewing all changes at once will be close to impossible.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

**Comment by nixpanic** [comment]
> /retest ci/centos/upgrade-tests-cephfs

Deploying the snapshot controller failed:
```
snapshotter controller creation failed
```

File: e2e/rbd.go [hunk 1]
```diff
@@ -749,6 +749,36 @@ var _ = Describe("RBD", func() {
...
+				scOpts := map[string]string{
+					"encrypted":       "true",
+					"encryptionKMSID": "secrets-metadata-test",
+				}
+				err = createRBDStorageClass(f.ClientSet, f, nil, scOpts, deletePolicy)
+				if err != nil {
+					e2elog.Failf("failed to create storageclass with error %v", err)
+				}
+
+				validatePVCClone(pvcPath, appPath, pvcSmartClonePath, appSmartClonePath, f)
```
Comment (Madhu-1) [inline e2e/rbd.go]: can we validate clone is also encrypted to make sure the app gets the encrypted device when using clone PVC?

File: internal/journal/voljournal.go [hunk 2]
```diff
@@ -691,9 +691,22 @@ func (conn *Connection) GetImageAttributes(ctx context.Context, pool, objectUUID
 }
 
 // StoreImageID stores the image ID in omap.
-func (conn *Connection) StoreImageID(ctx context.Context, pool, reservedUUID, imageID string) error {
-	err := setOMapKeys(ctx, conn, pool, conn.config.namespace, conn.config.cephUUIDDirectoryPrefix+reservedUUID,
-		map[string]string{conn.config.csiImageIDKey: imageID})
+func (conn *Connection) StoreImageID(ctx context.Context, pool, reservedUUID, imageID, kmsID, owner string) error {
```
Comment (Madhu-1) [inline internal/journal/voljournal.go]: the function is doing more work than storing the imageID. can we have a separate function to store the encryption ID and owner ?

File: internal/rbd/controllerserver.go [hunk 3]
```diff
@@ -274,7 +271,16 @@ func (cs *ControllerServer) CreateVolume(ctx context.Context, req *csi.CreateVol
 				return nil, err
 			}
 		}
-		return buildCreateVolumeResponse(ctx, req, rbdVol)
+
+		if parentVol != nil && parentVol.isEncrypted() {
```
Comment (Madhu-1) [inline internal/rbd/controllerserver.go]: the same need to be handled for snapshot also?

File: internal/rbd/rbd_util.go [hunk 4]
```diff
@@ -1071,6 +1106,29 @@ func (rv *rbdVolume) cloneRbdImageFromSnapshot(ctx context.Context, pSnapOpts *r
 		return fmt.Errorf("failed to create rbd clone: %w", err)
 	}
 
+	// delete the cloned image if a next step fails
+	deleteClone := true
+	defer func() {
+		if deleteClone {
+			err = librbd.RemoveImage(rv.ioctx, rv.RbdImageName)
```
Comment (Madhu-1) [inline internal/rbd/rbd_util.go:1113]: use rv.DeleteImage which uses manager tasks to delete the image?

File: e2e/rbd.go [hunk 5]
```diff
@@ -749,6 +749,36 @@ var _ = Describe("RBD", func() {
...
+				}
+				scOpts := map[string]string{
+					"encrypted":       "true",
+					"encryptionKMSID": "secrets-metadata-test",
+				}
+				err = createRBDStorageClass(f.ClientSet, f, nil, scOpts, deletePolicy)
+				if err != nil {
+					e2elog.Failf("failed to create storageclass with error %v", err)
+				}
+
```
Comment (Madhu-1) [inline e2e/rbd.go:558]: Add an e2e to validate encrypted PVC+ snapshot +restore also

File: internal/rbd/controllerserver.go (hunk 3 above)
Comment (nixpanic) [reply internal/rbd/controllerserver.go]: no, that does not seem to be required

File: internal/journal/voljournal.go (hunk 2 above)
Comment (nixpanic) [reply internal/journal/voljournal.go]: Maybe this change is not needed, as `ReserveName()` should set the correct metadata already. I'll try dropping this change and see how it goes.

File: internal/rbd/rbd_util.go (hunk 4 above)
Comment (nixpanic) [reply internal/rbd/rbd_util.go:1113]: Not sure that is needed, it is only for an error case that the just created image needs to be removed again.

Because the `deleteImage()` helper uses CephMgr, it also needs access to the Credentials, which are not available here. I think it would clutter the code more than is useful.

File: internal/rbd/controllerserver.go [hunk 6]
```diff
@@ -226,6 +221,7 @@ func validateRequestedVolumeSize(rbdVol, parentVol *rbdVolume, rbdSnap *rbdSnaps
 }
 
 // CreateVolume creates the volume in backend.
+// nolint:gocyclo // encrypted cloning/snapshots added more complexity, this needs to be addressed
```
Comment (nixpanic) [inline internal/rbd/controllerserver.go]: fwiw, I have an extra commit that cleans up the `nolint` annotation. It will be posted with the next update of this PR.

File: internal/rbd/controllerserver.go (hunk 3 above)
Comment (Madhu-1) [reply internal/rbd/controllerserver.go]: what if during creating a clone from snapshot operation the rbd image got created but the encryption information is not stored (maybe in midway the controller restarted?)

File: internal/rbd/rbd_util.go (hunk 4 above)
Comment (Madhu-1) [reply internal/rbd/rbd_util.go:1113]: RemoveImage directly from the ceph is time-consuming that's why we brought a manager to handle the image deletion asynchronous. I think this is fine for now.

File: internal/journal/voljournal.go (hunk 2 above)
Comment (Madhu-1) [reply internal/journal/voljournal.go]: Yes, correct. This is for post metadata reservation, Once the Reservation is done, we need to reserve the imageID at last after creating the image.

Comment (nixpanic) [reply internal/journal/voljournal.go]: Dropping this does not seem to affect the functioning, so that looks good :+1: This change will not be included in the next update.

File: internal/rbd/controllerserver.go (hunk 3 above)
Comment (nixpanic) [reply internal/rbd/controllerserver.go]: A next call would return a `VolumeOperationAlreadyExists` error, just like in other places where the provisioning is partially done and aborted. I do not think it is easy to recover from that automatically.

File: e2e/rbd.go (hunk 5 above)
Comment (nixpanic) [reply e2e/rbd.go:558]: oh, yes, I was planning to add that, but seem to have forgotton

File: e2e/rbd.go (hunk 1 above)
Comment (nixpanic) [reply e2e/rbd.go]: I guess so, will see if I can add that when reworking the e2e commit

Comment (nixpanic) [reply e2e/rbd.go]: this has been added now too

File: e2e/rbd.go (hunk 5 above)
Comment (nixpanic) [reply e2e/rbd.go:558]: Done!

File: internal/rbd/controllerserver.go (hunk 3 above)
Comment (Madhu-1) [reply internal/rbd/controllerserver.go]: I still feel like this is also needed for a snapshot. during vol Exist check for restoring rbd image from snapshot the parentVol is empty we need to check  if the volume encrypted if is restored from a snapshot

**Comment by Madhu-1** [comment]
@nixpanic E2E is failing

**Comment by nixpanic** [comment]
> @nixpanic E2E is failing

```
Apr  8 18:10:15.871: FAIL: failed to create storageclass with error volumesnapshotclasses.snapshot.storage.k8s.io "csi-rbdplugin-snapclass" already exists
```

The Snapshot tests should also delete the snapshotclass once they are done. Will address it right away!

File: e2e/rbd_helper.go [hunk 7]
```diff
@@ -279,6 +268,37 @@ func validateEncryptedPVCAndAppBinding(pvcPath, appPath, kms string, f *framewor
...
+	imageData, err := getImageInfoFromPVC(pvc.Namespace, pvc.Name, f)
+	if err != nil {
+		return err
+	}
+	rbdImageSpec := imageSpec(defaultRBDPool, imageData.imageName)
+
+	return validateEncryptedImage(f, rbdImageSpec, app)
+}
+
+func validateEncryptedImage(f *framework.Framework, rbdImageSpec string, app *v1.Pod) error {
```
Comment (humblec) [inline e2e/rbd_helper.go:285]: @nixpanic please add some source code comment about this function.

File: internal/util/util.go [hunk 8]
```diff
@@ -319,3 +319,15 @@ func contains(s []string, key string) bool {
 
 	return false
 }
+
+func getKeys(m map[string]interface{}) []string {
```
Comment (humblec) [inline internal/util/util.go:326]: please add some source code comment.

File: internal/rbd/clone.go [hunk 9]
```diff
@@ -46,7 +46,10 @@ import (
 func (rv *rbdVolume) checkCloneImage(ctx context.Context, parentVol *rbdVolume) (bool, error) {
 	// generate temp cloned volume
 	tempClone := rv.generateTempClone()
+	defer tempClone.Destroy()
+
```
Comment (humblec) [inline internal/rbd/clone.go:50]: nit: may be this extra line is not required

File: internal/rbd/controllerserver.go [hunk 10]
```diff
@@ -274,7 +270,8 @@ func (cs *ControllerServer) CreateVolume(ctx context.Context, req *csi.CreateVol
 				return nil, err
 			}
 		}
-		return buildCreateVolumeResponse(ctx, req, rbdVol)
+
```
Comment (humblec) [inline internal/rbd/controllerserver.go:275]: @nixpanic is this new line intentionally kept?

File: internal/rbd/encryption.go [hunk 11]
```diff
@@ -111,6 +111,41 @@ func (ri *rbdImage) setupEncryption(ctx context.Context) error {
 	return nil
 }
 
+func (ri *rbdImage) copyEncryptionConfig(cp *rbdImage) error {
```
Comment (humblec) [inline internal/rbd/encryption.go:118]: good to have a source code comment about this newly introduced functiion @nixpanic

File: internal/rbd/encryption.go [hunk 12]
```diff
@@ -111,6 +111,41 @@ func (ri *rbdImage) setupEncryption(ctx context.Context) error {
...
+	// get the unencrypted passphrase
```
Comment (humblec) [inline internal/rbd/encryption.go:124]: Isnt this we are getting `crypt` passphrase . Got confused by above comment saying `unencrypted` passphrase

File: e2e/rbd_helper.go (hunk 7 above)
Comment (nixpanic) [reply e2e/rbd_helper.go:285]: will do!

File: internal/util/util.go (hunk 8 above)
Comment (nixpanic) [reply internal/util/util.go:326]: ok!

File: internal/rbd/clone.go (hunk 9 above)
Comment (nixpanic) [reply internal/rbd/clone.go:50]: not required, but with the extra line it makes it easier to read

File: internal/rbd/controllerserver.go (hunk 10 above)
Comment (nixpanic) [reply internal/rbd/controllerserver.go:275]: Yes. After a closing `}`, if the next statement is not related to the previous code-block, I prefer an empty line to split the parts of the code.

File: internal/rbd/encryption.go (hunk 11 above)
Comment (nixpanic) [reply internal/rbd/encryption.go:118]: Sure, I'll add that.

File: internal/rbd/encryption.go (hunk 12 above)
Comment (nixpanic) [reply internal/rbd/encryption.go:124]: yes, `unencrypted` is correct. Passphrases can be encrypted per volume, so a copy of the passphrase for the next volume will get (potentially) encrypted differently. The unencrypted passphrase will remain the same. I hope the comments inside the function make this process clear.

A new comment describing the function will also clarify this more.

File: internal/rbd/controllerserver.go (hunk 3 above)
Comment (Madhu-1) [reply internal/rbd/controllerserver.go]:
```go
// check after vol exists from snapshot
if rbdSnap.isEncrypted() {
			rbdSnap.conn = rbdVol.conn.Copy()
			err = rbdSnap.copyEncryptionConfig(&rbdVol.rbdImage)
			if err != nil {
				return nil, fmt.Errorf("failed to clone encryption config: %w", err)
			}
		}
```

File: internal/rbd/controllerserver.go (hunk 10 above)
Comment (humblec) [reply internal/rbd/controllerserver.go:275]: Ok.. Sure..

File: internal/rbd/controllerserver.go (hunk 3 above)
Comment (nixpanic) [reply internal/rbd/controllerserver.go]: I think this is now addressed with the added `repairEncryptionConfig()` function.

File: internal/util/crypto.go [hunk 13]
```diff
@@ -243,7 +249,10 @@ func EncryptVolume(ctx context.Context, devicePath, passphrase string) error {
 // OpenEncryptedVolume opens volume so that it can be used by the client.
 func OpenEncryptedVolume(ctx context.Context, devicePath, mapperFile, passphrase string) error {
 	DebugLog(ctx, "Opening device %s with LUKS on %s", devicePath, mapperFile)
-	_, _, err := LuksOpen(devicePath, mapperFile, passphrase)
+	_, stderr, err := LuksOpen(devicePath, mapperFile, passphrase)
+	if err != nil {
+		WarningLog(ctx, "failed to open LUKS device %q: %s", devicePath, stderr)
```
Comment (Madhu-1) [inline internal/util/crypto.go:254]: this should be an error log not a warning log? logging err with stderror might also be helpfull

**Review by Madhu-1 — DISMISSED** [review]
LGTM

File: internal/util/crypto.go (hunk 13 above)
Comment (nixpanic) [reply internal/util/crypto.go:254]: I'd leave that up to the caller. The caller can log the returned error with a level it deems appropriate. Only because it is a failure, I didn't think Info-level would be suitable.

**Comment by humblec** [comment]
@nixpanic mostly looks good! , one quick check here  would be updating the encryption doc is needed or not, I feel we can add some notes in the encryption doc about the encrypted clones. wdyt?

File: internal/rbd/snapshot.go [hunk 14]
```diff
@@ -89,7 +89,16 @@ func generateVolFromSnap(rbdSnap *rbdSnapshot) *rbdVolume {
 	vol.RadosNamespace = rbdSnap.RadosNamespace
 	vol.RbdImageName = rbdSnap.RbdSnapName
 	vol.ImageID = rbdSnap.ImageID
-	return vol
+
+	if rbdSnap.isEncrypted() {
+		vol.conn = rbdSnap.conn.Copy()
+		err := rbdSnap.copyEncryptionConfig(&vol.rbdImage)
```
Comment (nixpanic) [inline internal/rbd/snapshot.go]: This is wrong for the case where the KMS uses the VolID for encrypting.decrypting the passphrase (SecretMetadataKMS). The encryption of the passphrase for the new rbdVolume is done with an incorrect VolID.

**Comment by nixpanic** [comment]
Now most features manually tested with VaultTokenKMS and SecretMetadataKMS. The 2nd failed in CI, with issues that could be reproduced.

@Madhu-1 @humblec please review again (hopefully last time!)

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e

Deploying snapshot controller failed:
```
snapshotter controller creation failed
```

**Comment by nixpanic** [comment]
> /retest ci/centos/upgrade-tests-cephfs

Deploying snapshot controller failed:
```
snapshotter controller creation failed
```

**Comment by nixpanic** [comment]
**ci/centos/mini-e2e-helm/k8s-1.20** failed with:
```
Apr  9 17:55:12.145: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
```

See #1969 

And so did **ci/centos/mini-e2e/k8s-1.19** https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.19/detail/mini-e2e_k8s-1.19/1098/pipeline

**Comment by nixpanic** [comment]
Some e2e tests fail in **STEP: create ROX PVC clone and mount it to multiple pods**. This might be related to the cleanup of the VolumeSnapshotClass that was previously not done.

**Comment by nixpanic** [comment]
> Some e2e tests fail in **STEP: create ROX PVC clone and mount it to multiple pods**. This might be related to the cleanup of the VolumeSnapshotClass that was previously not done.

All ready to go! Create/Delete the SnapshotClass when needed solved the failures.

**Review by Madhu-1 — APPROVED** [review]

**Review by humblec — APPROVED** [review]
