### PR TITLE
e2e: retry when a "transport is closing" error is hit

### LINKED ISSUE #2613: e2e: spurious failure error while getting pvc: `rpc error: code = Unavailable desc = transport is closing`
[logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.20/detail/mini-e2e_k8s-1.20/2995/pipeline) contain an error that is marked as fatal:

```
Nov  3 04:33:14.187: INFO: waiting for PVC rbd-13180 (78 seconds elapsed)
Nov  3 04:33:20.188: INFO: waiting for PVC rbd-13180 (84 seconds elapsed)
Nov  3 04:33:23.455: INFO: Error getting pvc "rbd-13180" in namespace "rbd-1318": rpc error: code = Unavailable desc = transport is closing
Nov  3 04:33:23.455: INFO: failed to create PVC and application (rbd-13180): failed to get pvc: rpc error: code = Unavailable desc = transport is closing
Nov  3 04:33:23.455: FAIL: creating PVCs and applications failed, 1 errors were logged
```

There should be a retry when there is an error mentioning `transport is closing`.

_Originally posted by @nixpanic in https://github.com/ceph/ceph-csi/issues/2611#issuecomment-958712946_

### PR DESCRIPTION
**Pull request by nixpanic**
There have been occasional CI job failures due to "transport is closing"
errors. Adding this error to the isRetryableAPIError() function should
make sure to retry the request until the connection is restored.

Fixes: #2613

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

**Review by humblec — APPROVED** [review]

File: e2e/errors.go [hunk 1]
```diff
@@ -41,6 +41,11 @@ func isRetryableAPIError(err error) bool {
 		return true
 	}
 
+	// "transport is closing" is an internal gRPC err, we can not use ErrConnClosing
+	if strings.Contains(err.Error(), "transport is closing") {
+		return true
+	}
```
Comment (pkalever) [inline e2e/errors.go:47]: instead can we simply:
```
    return strings.Contains(err.Error(), "transport is closing")
```

Comment (nixpanic) [reply e2e/errors.go:47]: that is not how the other checks do it either, I prefer to stick with how the rest of the function works

**Review by pkalever — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e/k8s-1.21

https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.21/detail/mini-e2e_k8s-1.21/1734/pipeline

```
[1mSTEP[0m: create a PVC and bind it to an app using rbd-nbd mounter with encryption
Nov 11 08:06:48.506: INFO: waiting for kubectl (delete -f args []) to finish
Nov 11 08:06:48.506: INFO: Running '/usr/bin/kubectl --server=https://192.168.39.199:8443 --kubeconfig=/root/.kube/config --namespace=cephcsi-e2e-18396e81 delete -f -'
Nov 11 08:06:48.637: INFO: stderr: "warning: deleting cluster-scoped resources, not scoped to the provided namespace\n"
Nov 11 08:06:48.637: INFO: stdout: "storageclass.storage.k8s.io \"csi-rbd-sc\" deleted\n"
Nov 11 08:06:48.643: INFO: ExecWithOptions {Command:[/bin/sh -c ceph fsid] Namespace:rook-ceph PodName:rook-ceph-tools-7467d8bf8-hp8p6 ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
Nov 11 08:06:48.643: INFO: >>> kubeConfig: /root/.kube/config
Nov 11 08:06:50.890: INFO: Waiting up to &PersistentVolumeClaim{ObjectMeta:{rbd-pvc  rbd-1318    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},Spec:PersistentVolumeClaimSpec{AccessModes:[ReadWriteOnce],Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},},VolumeName:,Selector:nil,StorageClassName:*csi-rbd-sc,VolumeMode:nil,DataSource:nil,DataSourceRef:nil,},Status:PersistentVolumeClaimStatus{Phase:,AccessModes:[],Capacity:ResourceList{},Conditions:[]PersistentVolumeClaimCondition{},},} to be in Bound state
Nov 11 08:06:50.890: INFO: waiting for PVC rbd-pvc (0 seconds elapsed)
Nov 11 08:06:52.893: INFO: waiting for PVC rbd-pvc (2 seconds elapsed)
Nov 11 08:06:52.900: INFO: Waiting for PV pvc-4ecad1a4-6264-43e9-899e-4a320657cba4 to bind to PVC rbd-pvc
Nov 11 08:06:52.900: INFO: Waiting up to timeout=10m0s for PersistentVolumeClaims [rbd-pvc] to have phase Bound
Nov 11 08:06:52.902: INFO: PersistentVolumeClaim rbd-pvc found and phase=Bound (2.473521ms)
Nov 11 08:06:52.902: INFO: Waiting up to 10m0s for PersistentVolume pvc-4ecad1a4-6264-43e9-899e-4a320657cba4 to have phase Bound
Nov 11 08:06:52.904: INFO: PersistentVolume pvc-4ecad1a4-6264-43e9-899e-4a320657cba4 found and phase=Bound (2.312858ms)
Nov 11 08:06:52.916: INFO: Waiting up to csi-rbd-demo-pod to be in Running state
Nov 11 08:07:12.934: INFO: ExecWithOptions {Command:[/bin/sh -c rbd image-meta get replicapool/csi-vol-5340536c-42c6-11ec-9142-fa2e771ed721 rbd.csi.ceph.com/encrypted] Namespace:rook-ceph PodName:rook-ceph-tools-7467d8bf8-hp8p6 ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
Nov 11 08:07:12.934: INFO: >>> kubeConfig: /root/.kube/config
Nov 11 08:07:13.948: INFO: ExecWithOptions {Command:[/bin/sh -c lsblk -o TYPE,MOUNTPOINT | grep '/var/lib/www/html' | awk '{print $1}'] Namespace:rbd-1318 PodName:csi-rbd-demo-pod ContainerName:web-server Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
Nov 11 08:07:13.948: INFO: >>> kubeConfig: /root/.kube/config
Nov 11 08:07:14.098: FAIL: failed to validate encrypted pvc with error  not equal to crypt
```

Seems to be #2610

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e-helm/k8s-1.22

Failed with #2264

**Comment by nixpanic** [comment]
@mergifyio rebase
