### PR TITLE
cephfs: remove extra check for restore size

### LINKED ISSUE #3147: cephfs: failed to create pvc from snapshot
* During the Snapshot creation operation we return the parent PVC size in the snapshot and create a response, Whenever a PVC is requested to create from the snapshot we have a check-in external snapshotter to make sure the user is not requesting to create a small size PVC than the snapshot -> We have a problem here, even though the snapshot size is smaller we are expecting the user to create the restore PVC to be the same size as of the parent PVC. (we don't have a bug in code here but It's a waste of space here)

* During CreateVolumeRequest we have a check-in cephcsi to make sure we are not allowing users to create the PVC smaller than the Snapshot, Here we are checking the size of the parent subvolume instead of the snapshot. if the parent subvolume is resized before creating the PVC, new PVC need to be same size of the expanded Parent PVC. (its a bug in code)

# Test result

## Create PVC of size 1 Gib and write some data to it

```bash
[🎩︎]mrajanna@fedora rook $]kubectl get pvc
NAME         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
cephfs-pvc   Bound    pvc-3f7e7771-f82f-4902-80c0-5b7a4dfc0096   1Gi        RWO            rook-cephfs       19h
rbd-pvc      Bound    pvc-80cda5d7-6c2f-4894-9800-9be420e0c4cb   1Gi        RWO            rook-ceph-block   19h
[🎩︎]mrajanna@fedora rook $]cd deploy/examples/csi/cephfs/
[🎩︎]mrajanna@fedora cephfs $]kubectl create -f pod.yaml 
pod/csicephfs-demo-pod created
[🎩︎]mrajanna@fedora cephfs $]kubectl exec -it pod/csicephfs-demo-pod -- sh
# df -h
Filesystem                                                                                                        Size  Used Avail Use% Mounted on
overlay                                                                                                            28G  6.0G   21G  23% /
tmpfs                                                                                                              64M     0   64M   0% /dev
tmpfs                                                                                                             2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/vda1                                                                                                          28G  6.0G   21G  23% /etc/hosts
shm                                                                                                                64M     0   64M   0% /dev/shm
10.108.71.87:6789:/volumes/csi/csi-vol-8582dc02-e0c8-11ec-89cf-12ca6b7d5e5e/c7818636-d38b-49a5-bba0-a7eacde382c1  1.0G     0  1.0G   0% /var/lib/www/html
tmpfs                                                                                                             3.9G   12K  3.9G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                                                                                             2.0G     0  2.0G   0% /proc/acpi
tmpfs                                                                                                             2.0G     0  2.0G   0% /proc/scsi
tmpfs                                                                                                             2.0G     0  2.0G   0% /sys/firmware
# cd /var/lib/www/html
# dd if=/dev/zero of=testfile bs=1024 count=10240

10240+0 records in
10240+0 records out
10485760 bytes (10 MB, 10 MiB) copied, 0.0537541 s, 195 MB/s
# df -h
Filesystem                                                                                                        Size  Used Avail Use% Mounted on
overlay                                                                                                            28G  6.0G   21G  23% /
tmpfs                                                                                                              64M     0   64M   0% /dev
tmpfs                                                                                                             2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/vda1                                                                                                          28G  6.0G   21G  23% /etc/hosts
shm                                                                                                                64M     0   64M   0% /dev/shm
10.108.71.87:6789:/volumes/csi/csi-vol-8582dc02-e0c8-11ec-89cf-12ca6b7d5e5e/c7818636-d38b-49a5-bba0-a7eacde382c1  1.0G  8.0M 1016M   1% /var/lib/www/html
tmpfs                                                                                                             3.9G   12K  3.9G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                                                                                             2.0G     0  2.0G   0% /proc/acpi
tmpfs                                                                                                             2.0G     0  2.0G   0% /proc/scsi
tmpfs                                                                                                             2.0G     0  2.0G   0% /sys/firmware
```

## Create a snapshot from the PVC here
```
[🎩︎]mrajanna@fedora cephfs $]kubectl create -f snapshotclass.yaml 
volumesnapshotclass.snapshot.storage.k8s.io/csi-cephfsplugin-snapclass created
[🎩︎]mrajanna@fedora cephfs $]kubectl create -f snapshot.yaml 
volumesnapshot.snapshot.storage.k8s.io/cephfs-pvc-snapshot created
[🎩︎]mrajanna@fedora cephfs $]kubectl get volumesnapshotclass
NAME                         DRIVER                          DELETIONPOLICY   AGE
csi-cephfsplugin-snapclass   rook-ceph.cephfs.csi.ceph.com   Delete           12s
[🎩︎]mrajanna@fedora cephfs $]kubectl get volumesnapshot
NAME                  READYTOUSE   SOURCEPVC    SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS                SNAPSHOTCONTENT                                    CREATIONTIME   AGE
cephfs-pvc-snapshot   true         cephfs-pvc                           1Gi           csi-cephfsplugin-snapclass   snapcontent-62d3863c-2294-469c-9867-1e3dd6b05478   12s            12s
```

## Write data to fill up 1Gib PVC
```
# dd if=/dev/zero of=testfile1 bs=1024 count=1024000
1024000+0 records in
1024000+0 records out
1048576000 bytes (1.0 GB, 1000 MiB) copied, 3.14953 s, 333 MB/s
# ^C
# 
# df 0h
df: 0h: No such file or directory
# df -h
Filesystem                                                                                                        Size  Used Avail Use% Mounted on
overlay                                                                                                            28G  6.0G   21G  23% /
tmpfs                                                                                                              64M     0   64M   0% /dev
tmpfs                                                                                                             2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/vda1                                                                                                          28G  6.0G   21G  23% /etc/hosts
shm                                                                                                                64M     0   64M   0% /dev/shm
10.108.71.87:6789:/volumes/csi/csi-vol-8582dc02-e0c8-11ec-89cf-12ca6b7d5e5e/c7818636-d38b-49a5-bba0-a7eacde382c1  1.0G  968M   56M  95% /var/lib/www/html
tmpfs                                                                                                             3.9G   12K  3.9G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                                                                                             2.0G     0  2.0G   0% /proc/acpi
tmpfs                                                                                                             2.0G     0  2.0G   0% /proc/scsi
tmpfs                                                                                                             2.0G     0  2.0G   0% /sys/firmware
# 
```

## Create Restore PVC of 1Gib here

```
[🎩︎]mrajanna@fedora cephfs $]kubectl create -f pvc-restore.yaml 
persistentvolumeclaim/cephfs-pvc-restore created
[🎩︎]mrajanna@fedora cephfs $]kubectl get pvc
NAME                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
cephfs-pvc           Bound    pvc-3f7e7771-f82f-4902-80c0-5b7a4dfc0096   1Gi        RWO            rook-cephfs       19h
cephfs-pvc-restore   Bound    pvc-8ff792bf-ba6f-4243-957f-03b3c4210fbb   1Gi        RWX            rook-cephfs       15s
```

```warning
As we can see here the creation of 1Gi PVC succeeded here
```
## Resize the parent pvc to Gib
```
[🎩︎]mrajanna@fedora cephfs $]kubectl get pvc
NAME         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
cephfs-pvc   Bound    pvc-3f7e7771-f82f-4902-80c0-5b7a4dfc0096   2Gi        RWO            rook-cephfs       19h
```

## Now try to create the 1Gib PVC from snapshot 
```
[🎩︎]mrajanna@fedora cephfs $]kubectl create -f pvc-restore.yaml 
persistentvolumeclaim/cephfs-pvc-restore created
[🎩︎]mrajanna@fedora cephfs $]kubectl describe pvc/cephfs-pvc-restore
Name:          cephfs-pvc-restore
Namespace:     default
StorageClass:  rook-cephfs
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
               volume.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
DataSource:
  APIGroup:  snapshot.storage.k8s.io
  Kind:      VolumeSnapshot
  Name:      cephfs-pvc-snapshot
Used By:     <none>
Events:
  Type     Reason                Age               From                                                                                                              Message
  ----     ------                ----              ----                                                                                                              -------
  Normal   ExternalProvisioning  9s (x2 over 15s)  persistentvolume-controller                                                                                       waiting for a volume to be created, either by external provisioner "rook-ceph.cephfs.csi.ceph.com" or manually created by the system administrator
  Normal   Provisioning          7s (x5 over 15s)  rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-5d79c5fffd-7hpmt_ff27eb76-b005-4ca8-a4aa-0dbc7669fc3d  External provisioner is provisioning volume for claim "default/cephfs-pvc-restore"
  Warning  ProvisioningFailed    7s (x5 over 15s)  rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-5d79c5fffd-7hpmt_ff27eb76-b005-4ca8-a4aa-0dbc7669fc3d  failed to provision volume with StorageClass "rook-cephfs": rpc error: code = InvalidArgument desc = cannot restore from snapshot 0001-0009-rook-ceph-0000000000000001-7764436f-e168-11ec-89cf-12ca6b7d5e5e: volume size 2147483648 is smaller than source volume size 1073741824
```

As we can see here the PVC creation fails.

### PR DESCRIPTION
**Pull request by Madhu-1**
Looks like the cephfs snapshot size is buggy and it's getting removed in ceph fs. we cannot get the size of the snapshot during the CreateVolume call, so we cannot do any size check at CreateVolume to check if the restore size is smaller or not.

As we are removing this check it also fixes #3147 but we dont have any validation at the CSI level for smaller restore we need to depend on kubernetes external-provisioner for it.

fixes: #3147

ceph tracker https://tracker.ceph.com/issues/55822 to remove size from snapshot API.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Review by yati1998 — DISMISSED** [review]

**Comment by Madhu-1** [comment]
Adding DNM and converting it to draft as the discussion is going on for snapshot-size

**Comment by nixpanic** [comment]
On Mon, Jun 13, 2022 at 11:51:55PM -0700, Madhu Rajanna wrote:
> Looks like the cephfs snapshot size is buggy and it&#39;s getting
> removed in ceph fs. we cannot get the size of the snapshot during the
> CreateVolume call, so we cannot do any size check at CreateVolume to
> check if the restore size is smaller or not.

If this is buggy, add a reference to the Ceph issue tracker please.

**Comment by Madhu-1** [comment]
> On Mon, Jun 13, 2022 at 11:51:55PM -0700, Madhu Rajanna wrote: Looks like the cephfs snapshot size is buggy and it&#39;s getting removed in ceph fs. we cannot get the size of the snapshot during the CreateVolume call, so we cannot do any size check at CreateVolume to check if the restore size is smaller or not.
> If this is buggy, add a reference to the Ceph issue tracker please.

Done!

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
Removing DNM as discussed in the team meeting.  we are good to consider this one.

**Comment by Madhu-1** [comment]
@nixpanic PTAL

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by Madhu-1** [comment]
Resolved merge conflicts and rebased

File: internal/cephfs/controllerserver.go [hunk 1]
```diff
@@ -205,23 +205,7 @@ func checkValidCreateVolumeRequest(
...
-		if vol.Size < parentVol.Size {
-			return fmt.Errorf(
-				"cannot restore from snapshot %s: volume size %d is smaller than source volume size %d",
-				sID.SnapshotID,
-				parentVol.Size,
-				vol.Size)
-		}
-
 		if vol.BackingSnapshot {
-			if vol.Size != parentVol.Size {
```
Comment (Madhu-1) [inline internal/cephfs/controllerserver.go:217]: @gman0 I am removing this check as it can cause a problem if the parent subvolume is resized after taking a snapshot, please check if am missing anything.

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Review by Rakshith-R — APPROVED** [review]

**Comment by Madhu-1** [comment]
@humblec @nixpanic PTAL

**Review by nixpanic — APPROVED** [review]

**Comment by Rakshith-R** [comment]
@mergifyio rebase

**Review by Yuggupta27 — APPROVED** [review]
