### PR TITLE
[RBD Async DR] Fix resize/Delete volume when it moved to another cluster

### LINKED ISSUE #1936: [RBD Async DR] Not able to resize/Delete volume when it moved to another cluster
we have implemented omap regeneration as part of https://github.com/ceph/ceph-csi/pull/1641

During Async mirroring only the RBD images are mirrored to the secondary site, and when the user creates the static PVCs on the failover we need to regenerate the omap data. The volumeHandle in PV spec is an encoded string that contains clusterID and poolID and image UUID, The clusterID and poolID won't remain the same on both the clusters, for that cephcsi need to generate the new volume handle and its to create a mapping between new volume handle and old volume handle with that whenever cephcsi gets csi requests it check if the mapping exists it will pull the new volume handle and continues other operations.

The new controller watches for the PVs created, It checks if the omap exists if it doesn't it will regenerate the entire omap data.

During few operations like (ControllerExpand, DeleteVolume) we will get the volume handle as the omap is stored in the rados pool we need 
the pool name first to get the volume handle mapping.

I0325 10:58:38.423582       1 utils.go:132] ID: 37 Req-ID: 0001-0009-rook-ceph-0000000000000001-3cadbf3c-8d57-11eb-8968-0242ac110006 GRPC call: /csi.v1.Controller/ControllerExpandVolume
I0325 10:58:38.427109       1 utils.go:133] ID: 37 Req-ID: 0001-0009-rook-ceph-0000000000000001-3cadbf3c-8d57-11eb-8968-0242ac110006 GRPC request: {"capacity_range":{"required_bytes":10737418240},"secrets":"***stripped***","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_id":"0001-0009-rook-ceph-0000000000000001-3cadbf3c-8d57-11eb-8968-0242ac110006"}
E0325 10:58:38.438318       1 omap.go:77] ID: 37 Req-ID: 0001-0009-rook-ceph-0000000000000001-3cadbf3c-8d57-11eb-8968-0242ac110006 omap not found (pool="device_health_metrics", namespace="", name="csi.volume.3cadbf3c-8d57-11eb-8968-0242ac110006"): rados: ret=-2, No such file or directory
W0325 10:58:38.439255       1 voljournal.go:636] ID: 37 Req-ID: 0001-0009-rook-ceph-0000000000000001-3cadbf3c-8d57-11eb-8968-0242ac110006 unable to read omap keys: pool or key missing: key not found: rados: ret=-2, No such file or directory
E0325 10:58:38.453466       1 rbd_journal.go:601] ID: 37 Req-ID: 0001-0009-rook-ceph-0000000000000001-3cadbf3c-8d57-11eb-8968-0242ac110006 failed to get image id device_health_metrics/csi-vol-3cadbf3c-8d57-11eb-8968-0242ac110006: image not found: RBD image not found
E0325 10:58:38.454078       1 utils.go:136] ID: 37 Req-ID: 0001-0009-rook-ceph-0000000000000001-3cadbf3c-8d57-11eb-8968-0242ac110006 GRPC error: rpc error: code = NotFound desc = volume ID 0001-0009-rook-ceph-0000000000000001-3cadbf3c-8d57-11eb-8968-0242ac110006 not found

## Suggested implementation

* Omap generator adds volume handle mapping in to new configmap
* Mount the new configmap as a volume to the cephcsi pods
* cephcsi checks for the volume handle mapping in the mounted volume
* If the volume handle mapping exists get the new volume handle
* Based on the new VolumeHandle decode it and use it

### PR DESCRIPTION
**Pull request by Madhu-1**
In the case of the Async DR, the volumeID will not be the same if the clusterID or the PoolID is different, With Earlier implementation, it is expected that the new volumeID mapping is stored in the rados omap pool. In the case of the
ControllerExpand or the DeleteVolume Request, the only volumeID will be sent it's not possible to find the corresponding poolID in the new cluster.

With This Change, it works as below

The csi-rbdplugin-controller will watch for the PV objects, when there are any PV objects created it will check the omap already exists, If the omap doesn't exist it will generate the new volumeID and it checks for the volumeID mapping entry in the PV annotation, if the mapping does not exist, it will add the new entry to the PV annotation.

The cephcsi will check for the PV annotations if the omap does not exist if the mapping exists in the PV annotation, it will use the new volumeID for further operations.

fixes: #1936
closes: #1938 (this is an alternative)
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
@nixpanic as discussed one more approach other than  https://github.com/ceph/ceph-csi/pull/1938 to fix this issue

File: internal/rbd/rbd_journal.go [hunk 1]
```diff
@@ -25,6 +25,13 @@ import (
 	"github.com/ceph/ceph-csi/internal/util"
 )
 
+const (
+	// PVVolumeHandleLabel is the annotation key set on the PV object.
+	PVVolumeHandleLabel = "CephCSIVolumeHandle"
```
Comment (nixpanic) [inline internal/rbd/rbd_journal.go]: Labels are commonly formatted like `csi.ceph.io/volume-handle`. All lowercase, with a prefix (`csi.ceph.io/`) for the application/component, and sub-label (`volume-handle`) as real 'label'.

It would be good to adapt such a format here too.

File: internal/rbd/rbd_util.go [hunk 2]
```diff
@@ -881,6 +867,31 @@ func genVolFromVolID(ctx context.Context, volumeID string, cr *util.Credentials,
 	return rbdVol, err
 }
 
+// genVolFromVolID generates a rbdVolume structure from the provided identifier, updating
+// the structure with elements from on-disk image metadata as well.
+func genVolFromVolID(ctx context.Context, volumeID string, cr *util.Credentials, secrets map[string]string) (*rbdVolume, error) {
+	vol, err := generateVolumeFromVolumeID(ctx, volumeID, cr, secrets)
+	if errors.Is(err, util.ErrKeyNotFound) || errors.Is(err, util.ErrPoolNotFound) {
```
Comment (nixpanic) [inline internal/rbd/rbd_util.go]: Easier to do the `if` the other way around. A small body inside the statement returning `nil, err`, and continue with the rest outside the if-statement like it is the default behaviour.

When an error occurs, ideally return `nil` and an error, not some incomplete `vol` object. Make sure to call `vol.Destroy()` in error cases too.

File: internal/rbd/rbd_journal.go [hunk 3]
```diff
@@ -496,7 +502,7 @@ func RegenerateJournal(imageName, volumeID, pool, journalPool, requestName strin
 
 	err := vi.DecomposeCSIID(rbdVol.VolID)
 	if err != nil {
-		return fmt.Errorf("%w: error decoding volume ID (%s) (%s)",
+		return rbdVol.VolID, fmt.Errorf("%w: error decoding volume ID (%s) (%s)",
```
Comment (nixpanic) [inline internal/rbd/rbd_journal.go]: In error cases, it is better to return an empty string.

File: internal/controller/persistentvolume/persistentvolume.go [hunk 4]
```diff
@@ -122,6 +122,40 @@ func checkStaticVolume(pv *corev1.PersistentVolume) (bool, error) {
...
+		}
+	}
+	// check PV label exists
+	if _, ok := pv.Labels[rbd.PVReplicatedLabel]; ok {
+		replicationLabelExists = true
+	}
+	if replicationLabelExists && volumeIDExistInAnnotation {
+		return nil
+	}
+	pv.Labels[rbd.PVReplicatedLabel] = "true"
```
Comment (nixpanic) [inline internal/controller/persistentvolume/persistentvolume.go]: I'm not a big fan of `true` strings, maybe some status like `volume-handle-detected`? Just a nit, not required to change as the value is not *that* important.

**Review by nixpanic — COMMENTED** [review]
I prefer this approach much more over #1936, thanks for posting this version!

At the moment you're watching for PVs, I hope this can be moved towards the VolumeReplication CR at a later time. From there you can then get the PVC and PV too.

File: internal/controller/persistentvolume/persistentvolume.go [hunk 5]
```diff
@@ -122,6 +122,40 @@ func checkStaticVolume(pv *corev1.PersistentVolume) (bool, error) {
 	return static, nil
 }
 
+// storeVolumeIDInPV stores the new volumeID in PV object.
+func (r ReconcilePersistentVolume) storeVolumeIDInPV(pv *corev1.PersistentVolume, newVolumeID string) error {
+	// take a lock to avoid concurrent update of configmap
```
Comment (nixpanic) [inline internal/controller/persistentvolume/persistentvolume.go]: not sure what this comment means

File: internal/controller/persistentvolume/persistentvolume.go [hunk 6]
```diff
@@ -122,6 +122,40 @@ func checkStaticVolume(pv *corev1.PersistentVolume) (bool, error) {
 	return static, nil
 }
 
+// storeVolumeIDInPV stores the new volumeID in PV object.
+func (r ReconcilePersistentVolume) storeVolumeIDInPV(pv *corev1.PersistentVolume, newVolumeID string) error {
```
Comment (nixpanic) [inline internal/controller/persistentvolume/persistentvolume.go:128]: There probably should be a verification that the PV is a Ceph-CSI one?

File: internal/rbd/rbd_journal.go (hunk 1 above)
Comment (Madhu-1) [reply internal/rbd/rbd_journal.go]: This is for annotation sorry need to change the name. is it suggested to use `csi.ceph.io/volume-handle` for annotation too?

File: internal/rbd/rbd_util.go (hunk 2 above)
Comment (Madhu-1) [reply internal/rbd/rbd_util.go]: Need to return vol even in case of error to destroy the context and to release the lock

File: internal/rbd/rbd_journal.go (hunk 1 above)
Comment (nixpanic) [reply internal/rbd/rbd_journal.go]: Yes, I think so. Identifying the application/component that set a Label or Annotation seems to be good practice.

File: internal/rbd/rbd_util.go (hunk 2 above)
Comment (nixpanic) [reply internal/rbd/rbd_util.go]: really? where is the lock taken then? Ideally it should be released at the same level...

Comment (Madhu-1) [reply internal/rbd/rbd_util.go]: the lock was taken on the volumeID when and common function is added to cleanup it https://github.com/ceph/ceph-csi/pull/1924/files#diff-3792fcc7313c4d1e0b81c4d3ff7ac714b9d299130641673729196b2a4a1d6f2aR175-R186. if the PR is merged I will rework that one. Will fix it in this PR.

File: internal/controller/persistentvolume/persistentvolume.go (hunk 6 above)
Comment (Madhu-1) [reply internal/controller/persistentvolume/persistentvolume.go:128]: The check already exists. the controller will reconcile the only PV created for this Driver.

File: internal/controller/persistentvolume/persistentvolume.go (hunk 5 above)
Comment (Madhu-1) [reply internal/controller/persistentvolume/persistentvolume.go]: Leftover removing it

File: internal/controller/persistentvolume/persistentvolume.go [hunk 7]
```diff
@@ -122,6 +122,39 @@ func checkStaticVolume(pv *corev1.PersistentVolume) (bool, error) {
...
+	if v, ok := pv.Annotations[rbd.PVVolumeHandleAnnotationKey]; ok {
+		if v == newVolumeID {
```
Comment (agarwal-mudit) [inline internal/controller/persistentvolume/persistentvolume.go:130]: if this is true, why will it go to Line 141?

Comment (Madhu-1) [reply internal/controller/persistentvolume/persistentvolume.go:130]: as its already existing in annotation, it will get return at line 129

Comment (agarwal-mudit) [reply internal/controller/persistentvolume/persistentvolume.go:130]: yeah, then why do we need to check it again in 141

File: internal/rbd/rbd_journal.go [hunk 8]
```diff
@@ -25,6 +25,15 @@ import (
 	"github.com/ceph/ceph-csi/internal/util"
 )
 
+const (
+	// PVVolumeHandleAnnotationKey is the annotation key set on the PV object.
+	PVVolumeHandleAnnotationKey = "csi.ceph.io/volume-handle"
+	// PVReplicatedLabelKey is the label key set on PV object.
+	PVReplicatedLabelKey = "CephCSIReplicatedVolume"
```
Comment (nixpanic) [inline internal/rbd/rbd_journal.go]: Same as with annotations, use `csi.ceph.io/repliacted-volume` to follow the naming other projects do

**Comment by ShyamsundarR** [comment]
Annotations are better than config maps.

@Madhu-1 and me discussed an alternate that provides configuration to the CSI driver for the required mapping, than annotate PVs. Madhu is thinking through the same, and if we discuss and find that a better long term alternative, we would possibly got that route.

Till then, without hopefully confusing matters further, this is an acceptable stand-in for the problem being resolved.

File: internal/rbd/rbd_journal.go (hunk 8 above)
Comment (Madhu-1) [reply internal/rbd/rbd_journal.go]: done.

**Review by nixpanic — DISMISSED** [review]
CI failures happened due to timeouts.

Just use `@mergifyio rebase` to re-test once a 2nd approval is in.

**Comment by Madhu-1** [comment]
@humblec PTAL

**Comment by humblec** [comment]
> @humblec PTAL

@Madhu-1 do we have any design doc (https://github.com/ceph/ceph-csi/pull/1938#issuecomment-810304643) for this async work in general ( may be one which cover the integration to the other component too ?) apart from the one available here https://github.com/ceph/ceph-csi/blob/devel/docs/design/proposals/rbd-mirror.md for reference ? the one available here does not carry much information and I am finding difficulty to get the workflow , so the ask.

**Comment by Madhu-1** [comment]
> > @humblec PTAL
> 
> @Madhu-1 do we have any design doc ([#1938 (comment)](https://github.com/ceph/ceph-csi/pull/1938#issuecomment-810304643)) for this async work in general ( may be one which cover the integration to the other component too ?) apart from the one available here https://github.com/ceph/ceph-csi/blob/devel/docs/design/proposals/rbd-mirror.md for reference ? the one available here does not carry much information and I am finding difficulty to get the workflow , so the ask.

@humblec as i  already explain the currently planned design for you and its clear, this is the doc which I have created initially https://hackmd.io/1Pbj_9rzQ2SwK80GK6-qWg?both. i don't have the LLD

**Comment by humblec** [comment]
> > > @humblec PTAL
> > 
> > 
> > @Madhu-1 do we have any design doc ([#1938 (comment)](https://github.com/ceph/ceph-csi/pull/1938#issuecomment-810304643)) for this async work in general ( may be one which cover the integration to the other component too ?) apart from the one available here https://github.com/ceph/ceph-csi/blob/devel/docs/design/proposals/rbd-mirror.md for reference ? the one available here does not carry much information and I am finding difficulty to get the workflow , so the ask.
> 
> @humblec as i already explain the currently planned design for you and its clear, this is the doc which I have created initially https://hackmd.io/1Pbj_9rzQ2SwK80GK6-qWg?both. i don't have the LLD

@Madhu-1 looks like many changes  from the initial thoughts keep happening  and was struggling to keep updated on those. Thanks for the link. Hopefully it helps :) .

>https://github.com/ceph/ceph-csi/pull/1946#issuecomment-811115845
>

Are we saying the annotation method ( this PR) will be kept as a `temporary` one ?  if yes, what  are we planning as a permanent solution mentioned by above ?

**Comment by Madhu-1** [comment]
> > > > @humblec PTAL
> > > 
> > > 
> > > @Madhu-1 do we have any design doc ([#1938 (comment)](https://github.com/ceph/ceph-csi/pull/1938#issuecomment-810304643)) for this async work in general ( may be one which cover the integration to the other component too ?) apart from the one available here https://github.com/ceph/ceph-csi/blob/devel/docs/design/proposals/rbd-mirror.md for reference ? the one available here does not carry much information and I am finding difficulty to get the workflow , so the ask.
> > 
> > 
> > @humblec as i already explain the currently planned design for you and its clear, this is the doc which I have created initially https://hackmd.io/1Pbj_9rzQ2SwK80GK6-qWg?both. i don't have the LLD
> 
> @Madhu-1 looks like many changes from the initial thoughts keep happening and was struggling to keep updated on those. Thanks for the link. Hopefully it helps :) .
> 
> > [#1946 (comment)](https://github.com/ceph/ceph-csi/pull/1946#issuecomment-811115845)
> 
> Are we saying the annotation method ( this PR) will be kept as a `temporary` one ? if yes, what are we planning as a permanent solution mentioned by above ?

Yes am working on a new design need to check the feasibility, it takes some time (not soon) to get the design doc out.

File: internal/controller/persistentvolume/persistentvolume.go [hunk 9]
```diff
@@ -161,11 +179,18 @@ func (r ReconcilePersistentVolume) reconcilePV(obj runtime.Object) error {
 		}
 		defer cr.DeleteCredentials()
 
-		err = rbd.RegenerateJournal(imageName, volumeHandler, pool, journalPool, requestName, cr)
```
Comment (humblec) [inline internal/controller/persistentvolume/persistentvolume.go]: @Madhu-1 we call `regeneratejournal` without any locking in place, so while reconciling a PV, if regenrateJournal() was called more than once, Isnt there a possibility of a race scenario ?

File: internal/controller/persistentvolume/persistentvolume.go [hunk 10]
```diff
@@ -161,11 +179,18 @@ func (r ReconcilePersistentVolume) reconcilePV(obj runtime.Object) error {
...
+		rbdVolID, err := rbd.RegenerateJournal(imageName, volumeHandler, pool, journalPool, requestName, cr)
 		if err != nil {
 			util.ErrorLogMsg("failed to regenerate journal %s", err)
 			return err
 		}
+		if rbdVolID != volumeHandler {
+			err = r.storeVolumeIDInPV(pv, rbdVolID)
```
Comment (humblec) [inline internal/controller/persistentvolume/persistentvolume.go]: imo, the storeVolumeIDinPV should be a protected call. Otherwise the other parallel request may see a inconsistency in some scenarios.

File: internal/rbd/rbd_util.go [hunk 11]
```diff
@@ -881,6 +867,32 @@ func genVolFromVolID(ctx context.Context, volumeID string, cr *util.Credentials,
...
+	}
+	pvlist, pErr := c.CoreV1().PersistentVolumes().List(context.TODO(), listOpt)
+	if pErr != nil {
+		return vol, pErr
+	}
+	for i := range pvlist.Items {
+		if pvlist.Items[i].Spec.CSI != nil && pvlist.Items[i].Spec.CSI.VolumeHandle == volumeID {
+			if v, ok := pvlist.Items[i].Annotations[PVVolumeHandleAnnotationKey]; ok {
+				util.UsefulLog(ctx, "found new volumeID %s for existing volumeID %s", v, volumeID)
+				return generateVolumeFromVolumeID(ctx, v, cr, secrets)
```
Comment (humblec) [inline internal/rbd/rbd_util.go:897]: @Madhu-1 this is bit confusing. That said, Is it a problem if we see new volume ID for existing Volume ID?  can we add some source code comment about this block logic ?

Comment (Madhu-1) [reply internal/rbd/rbd_util.go:897]: @humblec it's not a problem. add more comments

**Comment by humblec** [comment]
@Madhu-1 looks like latest patchset address https://github.com/ceph/ceph-csi/pull/1946#discussion_r607932043,  is this ready for review or you are still polishing it ?

**Comment by Madhu-1** [comment]
> @Madhu-1 looks like latest patchset address [#1946 (comment)](https://github.com/ceph/ceph-csi/pull/1946#discussion_r607932043), is this ready for review or you are still polishing it ?

This is ready for review

File: internal/rbd/rbd_util.go [hunk 12]
```diff
@@ -883,6 +869,38 @@ func genVolFromVolID(ctx context.Context, volumeID string, cr *util.Credentials,
...
+// the structure with elements from on-disk image metadata as well.
+func genVolFromVolID(ctx context.Context, volumeID string, cr *util.Credentials, secrets map[string]string) (*rbdVolume, error) {
+	vol, err := generateVolumeFromVolumeID(ctx, volumeID, cr, secrets)
+	if !errors.Is(err, util.ErrKeyNotFound) && !errors.Is(err, util.ErrPoolNotFound) {
+		return vol, err
+	}
+
+	// If the volume details are not found in the OMAP it can be a mirrored RBD
+	// image and the OMAP is already generated and the volumeHandle might not
+	// be the same in the PV.Spec.CSI.VolumeHandle. Check the PV annotation for
```
Comment (humblec) [inline internal/rbd/rbd_util.go:882]: if the volume details are not in OMAP , it could also be any static PV customer created in that cluster ( without mirroring), Isnt it ? why I am asking this is to confirm, we wont confuse with static PVs created by the admin and the mirrored PVs and thus land into performing different operations. or we are good to distinguish the PVs based on the key set by replication operator just for mirroring ?

File: internal/rbd/rbd_util.go [hunk 13]
```diff
@@ -883,6 +869,38 @@ func genVolFromVolID(ctx context.Context, volumeID string, cr *util.Credentials,
...
+	// the new volumeHandle. If the new volumeHandle is found, generate the RBD
+	// volume structure from the new volumeHandle.
+	c := util.NewK8sClient()
+	listOpt := metav1.ListOptions{
+		LabelSelector: PVReplicatedLabelKey,
+	}
+	pvlist, pErr := c.CoreV1().PersistentVolumes().List(context.TODO(), listOpt)
```
Comment (humblec) [inline internal/rbd/rbd_util.go:889]: This is a heavy operation, that said, listing out all the PVs in the cluster and fetching the volume handle looks to cause performance issues especially in large clusters,.

File: internal/rbd/rbd_util.go [hunk 14]
```diff
@@ -777,9 +778,8 @@ func genSnapFromSnapID(ctx context.Context, rbdSnap *rbdSnapshot, snapshotID str
 	return err
 }
 
-// genVolFromVolID generates a rbdVolume structure from the provided identifier, updating
-// the structure with elements from on-disk image metadata as well.
-func genVolFromVolID(ctx context.Context, volumeID string, cr *util.Credentials, secrets map[string]string) (*rbdVolume, error) {
+// generateVolumeFromVolumeID generates a rbdVolume structure from the provided identifier.
+func generateVolumeFromVolumeID(ctx context.Context, volumeID string, cr *util.Credentials, secrets map[string]string) (*rbdVolume, error) {
```
Comment (humblec) [inline internal/rbd/rbd_util.go:782]: nit: compared to previous scenarios, with the introduction of mirroring, iic, there is a possibility of volumeID being `nil`. If yes, DecompoeCSIID can be  avoided at start of this function if volumeID is nil.

File: internal/rbd/rbd_util.go [hunk 15]
```diff
@@ -883,6 +869,38 @@ func genVolFromVolID(ctx context.Context, volumeID string, cr *util.Credentials,
...
+	c := util.NewK8sClient()
+	listOpt := metav1.ListOptions{
+		LabelSelector: PVReplicatedLabelKey,
+	}
+	pvlist, pErr := c.CoreV1().PersistentVolumes().List(context.TODO(), listOpt)
+	if pErr != nil {
+		return vol, pErr
+	}
+	for i := range pvlist.Items {
+		if pvlist.Items[i].Spec.CSI != nil && pvlist.Items[i].Spec.CSI.VolumeHandle == volumeID {
```
Comment (humblec) [inline internal/rbd/rbd_util.go:894]: if the listOpt is `PVReplicatedLabelKey` why do we want to check whether its a CSI spec below?.

File: internal/rbd/rbd_util.go (hunk 12 above)
Comment (Madhu-1) [reply internal/rbd/rbd_util.go:882]: AFAIC this won't be called for static PVC. and we don't support any operator for static PVC except mounting and unmounting?

File: internal/rbd/rbd_util.go (hunk 13 above)
Comment (Madhu-1) [reply internal/rbd/rbd_util.go:889]: This will be fetched only if the omap is not found and we are fetching based on the selector. as this is a temp solution i don't see a problem with it.

File: internal/rbd/rbd_util.go (hunk 14 above)
Comment (Madhu-1) [reply internal/rbd/rbd_util.go:782]: @humblec can you please suggest in which scenario the volumeId can be nil?

File: internal/rbd/rbd_util.go (hunk 15 above)
Comment (Madhu-1) [reply internal/rbd/rbd_util.go:894]: It's safer check to check for nil pointer before accessing it.

File: internal/rbd/rbd_util.go (hunk 12 above)
Comment (ShyamsundarR) [reply internal/rbd/rbd_util.go:882]: Also, due to the label selector, the static PV created by users would be exempt from the selection. This should not be an issue.

File: internal/rbd/rbd_util.go (hunk 14 above)
Comment (ShyamsundarR) [reply internal/rbd/rbd_util.go:782]: Did a cursory check for `nil` possibility, did not find any.

**Review by ShyamsundarR — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]
