### PR TITLE
cephfs: fix unmountVolume function

### LINKED ISSUE #1860: Failed to Delete Application using cephfs PVC
Looks like NodeUnpublish is failing when the target path is already umounted

## Steps to reproduce

* Create Cephfs PVC and application
* Manually `umount` the target path from the cephfs-plugin container
* Try to delete the application

Analysis  from the issue where we hit the bug in https://github.com/ceph/ceph-csi/pull/1811
```
I0209 10:10:23.315530       1 utils.go:132] ID: 42 Req-ID: 0001-0024-c3feb7b7-cf6b-4154-b66f-fb09df8d20b7-0000000000000001-fc81f537-6abe-11eb-9ad3-e6ef196d01c3 GRPC call: /csi.v1.Node/NodeUnpublishVolume
I0209 10:10:23.315688       1 utils.go:133] ID: 42 Req-ID: 0001-0024-c3feb7b7-cf6b-4154-b66f-fb09df8d20b7-0000000000000001-fc81f537-6abe-11eb-9ad3-e6ef196d01c3 GRPC request: {"target_path":"/var/lib/kubelet/pods/9d150e08-6b25-478d-96a6-03bfd96f907a/volumes/kubernetes.io~csi/pvc-2a3650cd-8454-40e8-ae4b-31a7f6034dec/mount","volume_id":"0001-0024-c3feb7b7-cf6b-4154-b66f-fb09df8d20b7-0000000000000001-fc81f537-6abe-11eb-9ad3-e6ef196d01c3"}
I0209 10:14:06.241861       1 cephcmds.go:59] ID: 42 Req-ID: 0001-0024-c3feb7b7-cf6b-4154-b66f-fb09df8d20b7-0000000000000001-fc81f537-6abe-11eb-9ad3-e6ef196d01c3 command succeeded: umount [/var/lib/kubelet/pods/9d150e08-6b25-478d-96a6-03bfd96f907a/volumes/kubernetes.io~csi/pvc-2a3650cd-8454-40e8-ae4b-31a7f6034dec/mount]
I0209 10:14:06.242222       1 nodeserver.go:277] ID: 42 Req-ID: 0001-0024-c3feb7b7-cf6b-4154-b66f-fb09df8d20b7-0000000000000001-fc81f537-6abe-11eb-9ad3-e6ef196d01c3 cephfs: successfully unbinded volume 0001-0024-c3feb7b7-cf6b-4154-b66f-fb09df8d20b7-0000000000000001-fc81f537-6abe-11eb-9ad3-e6ef196d01c3 from /var/lib/kubelet/pods/9d150e08-6b25-478d-96a6-03bfd96f907a/volumes/kubernetes.io~csi/pvc-2a3650cd-8454-40e8-ae4b-31a7f6034dec/mount
I0209 10:14:06.242277       1 utils.go:138] ID: 42 Req-ID: 0001-0024-c3feb7b7-cf6b-4154-b66f-fb09df8d20b7-0000000000000001-fc81f537-6abe-11eb-9ad3-e6ef196d01c3 GRPC response: {}
```

It took around 4 minutes to umount the targetPath after that the NodePublish is failing with below error

```log
I0209 10:14:31.025118       1 utils.go:132] ID: 56 Req-ID: 0001-0024-c3feb7b7-cf6b-4154-b66f-fb09df8d20b7-0000000000000001-fc81f537-6abe-11eb-9ad3-e6ef196d01c3 GRPC call: /csi.v1.Node/NodeUnpublishVolume
I0209 10:14:31.025255       1 utils.go:133] ID: 56 Req-ID: 0001-0024-c3feb7b7-cf6b-4154-b66f-fb09df8d20b7-0000000000000001-fc81f537-6abe-11eb-9ad3-e6ef196d01c3 GRPC request: {"target_path":"/var/lib/kubelet/pods/9d150e08-6b25-478d-96a6-03bfd96f907a/volumes/kubernetes.io~csi/pvc-2a3650cd-8454-40e8-ae4b-31a7f6034dec/mount","volume_id":"0001-0024-c3feb7b7-cf6b-4154-b66f-fb09df8d20b7-0000000000000001-fc81f537-6abe-11eb-9ad3-e6ef196d01c3"}
I0209 10:14:31.031176       1 cephcmds.go:53] ID: 56 Req-ID: 0001-0024-c3feb7b7-cf6b-4154-b66f-fb09df8d20b7-0000000000000001-fc81f537-6abe-11eb-9ad3-e6ef196d01c3 an error (exit status 32) occurred while running umount args: [/var/lib/kubelet/pods/9d150e08-6b25-478d-96a6-03bfd96f907a/volumes/kubernetes.io~csi/pvc-2a3650cd-8454-40e8-ae4b-31a7f6034dec/mount]
E0209 10:14:31.031215       1 utils.go:136] ID: 56 Req-ID: 0001-0024-c3feb7b7-cf6b-4154-b66f-fb09df8d20b7-0000000000000001-fc81f537-6abe-11eb-9ad3-e6ef196d01c3 GRPC error: rpc error: code = Internal desc = an error (exit status 32) occurred while running umount args: [/var/lib/kubelet/pods/9d150e08-6b25-478d-96a6-03bfd96f907a/volumes/kubernetes.io~csi/pvc-2a3650cd-8454-40e8-ae4b-31a7f6034dec/mount]
```
as the umount is already done cephcsi should return success not the Internal server error.

_Originally posted by @Madhu-1 in https://github.com/ceph/ceph-csi/issues/1811#issuecomment-775845207_

### PR DESCRIPTION
**Pull request by Rakshith-R**
This commit fixes bug which caused unmountVolume to fail when path was already unmounted.

Fixes: #1860 

### Future concerns ###
~Changes in the following line has direct impact on ability to catch _path not mounted error.~

Signed-off-by: Rakshith R <rar@redhat.com>

### CODE REVIEW

File: internal/cephfs/volumemounter.go [hunk 1]
```diff
@@ -258,7 +258,7 @@ func bindMount(ctx context.Context, from, to string, readOnly bool, mntOptions [
 
 func unmountVolume(ctx context.Context, mountPoint string) error {
 	if err := execCommandErr(ctx, "umount", mountPoint); err != nil {
```
Comment (Madhu-1) [inline internal/cephfs/volumemounter.go]: This becomes too generic and can cause issues. actual umount error will be captured in the stderr, `execCommandErr
` should also return the stderr or add stderr to the error message.

**Review by Madhu-1 — CHANGES_REQUESTED** [review]
please add the E2E test.

**Review by yati1998 — COMMENTED** [review]
Please change the commit message according to proper guidelines.

File: internal/cephfs/volumemounter.go [hunk 2]
```diff
@@ -258,7 +258,7 @@ func bindMount(ctx context.Context, from, to string, readOnly bool, mntOptions [
...
-		if strings.Contains(err.Error(), fmt.Sprintf("exit status 32: umount: %s: not mounted", mountPoint)) ||
+		if strings.Contains(err.Error(), fmt.Sprintf("an error (exit status 32) occurred while running umount args: [%s]", mountPoint)) ||
```
Comment (humblec) [inline internal/cephfs/volumemounter.go]: @Rakshith-R please check the error string in 2/3 ceph versions from current. Most of the time the assumed error strings has caused the issues or regression so the request.

Comment (Madhu-1) [reply internal/cephfs/volumemounter.go]: @humblec is this dependent on the ceph version?

Comment (nixpanic) [reply internal/cephfs/volumemounter.go]: no, it should not depend on the Ceph version. The error comes from the `umount` executable, not Ceph.

Comment (humblec) [reply internal/cephfs/volumemounter.go]: ah. .its unmount not mount. ignore

File: e2e/utils.go [hunk 3]
```diff
@@ -28,8 +28,10 @@ const (
 	defaultNs     = "default"
 	vaultSecretNs = "/secret/ceph-csi/"
 
-	rookTolBoxPodLabel = "app=rook-ceph-tools"
-	rbdmountOptions    = "mountOptions"
+	rookTolBoxPodLabel        = "app=rook-ceph-tools"
```
Comment (nixpanic) [inline e2e/utils.go]: You might want to send an other PR or add a commit that corrects the name of `ToolBox`. Not required, as you did not introduce the typo :)

File: e2e/cephfs_helper.go [hunk 4]
```diff
@@ -98,6 +98,23 @@ func createCephfsSecret(f *framework.Framework, secretName, userName, userKey st
 	return err
 }
 
+func unmountCephFSVolume(f *framework.Framework, app *v1.Pod, pvc *v1.PersistentVolumeClaim) error {
+	app, err := f.ClientSet.CoreV1().Pods(f.UniqueName).Get(context.TODO(), app.Name, metav1.GetOptions{})
```
Comment (nixpanic) [inline e2e/cephfs_helper.go]: It is not very clean to re-assign variables that were passed as an argument to a function. Using a new variable name is makes the code easier to understand.

Is the getting of the `app` Pod really needed here?

This works on our standard e2e because there is only a single node (minikube). It would be good to add a comment like `FIXME: run the unmount command on the node where the pod is running` or similar. It would give a hint on what is needed to  get addressed when we start running multi-node tests.

Comment (Rakshith-R) [reply e2e/cephfs_helper.go]: > It is not very clean to re-assign variables that were passed as an argument to a function. Using a new variable name is makes the code easier to understand.

Okay, app name and volume name is sufficient. I will change the function to use them instead.

> Is the getting of the `app` Pod really needed here?

Need `UID` of `app` pod to form the mount path to run unmount command.
`cmd := fmt.Sprintf("umount /var/lib/kubelet/pods/%s/volumes/kubernetes.io~csi/%s/mount", app.ObjectMeta.UID, pv.ObjectMeta.Name)`

> This works on our standard e2e because there is only a single node (minikube). It would be good to add a comment like `FIXME: run the unmount command on the node where the pod is running` or similar. It would give a hint on what is needed to get addressed when we start running multi-node tests.

I'll do that :+1:

File: e2e/cephfs_helper.go [hunk 5]
```diff
@@ -98,6 +98,23 @@ func createCephfsSecret(f *framework.Framework, secretName, userName, userKey st
...
+	if err != nil {
+		return err
+	}
+	pv, err := f.ClientSet.CoreV1().PersistentVolumes().Get(context.TODO(), pvc.Spec.VolumeName, metav1.GetOptions{})
+	if err != nil {
+		return err
+	}
+	cmd := fmt.Sprintf("umount /var/lib/kubelet/pods/%s/volumes/kubernetes.io~csi/%s/mount", app.ObjectMeta.UID, pv.ObjectMeta.Name)
```
Comment (Madhu-1) [inline e2e/cephfs_helper.go]: The E2E should be as below

* Get list of running cephfs plugin pods
* Run through all cephfsplugin pods and run `mount |grep path`  and check application is mounted in cephfs plugin pod
* If the mount is present than umount it.

File: internal/cephfs/volumemounter.go [hunk 6]
```diff
@@ -257,8 +257,9 @@ func bindMount(ctx context.Context, from, to string, readOnly bool, mntOptions [
 }
 
 func unmountVolume(ctx context.Context, mountPoint string) error {
-	if err := execCommandErr(ctx, "umount", mountPoint); err != nil {
-		if strings.Contains(err.Error(), fmt.Sprintf("exit status 32: umount: %s: not mounted", mountPoint)) ||
+	if _, stderr, err := util.ExecCommand(ctx, "umount", mountPoint); err != nil {
+		err = fmt.Errorf("%w stderr: %s", err, stderr)
+		if strings.Contains(err.Error(), fmt.Sprintf("an error (exit status 32) occurred while running umount args: [%s] stderr: umount: %s: not mounted.", mountPoint, mountPoint)) ||
```
Comment (Madhu-1) [inline internal/cephfs/volumemounter.go]: Just check for `umount: %s: not mounted`?

File: e2e/cephfs.go [hunk 7]
```diff
@@ -528,6 +528,23 @@ var _ = Describe("cephfs", func() {
 				}
 			})
 
+			By("Create PVC, bind it to an app, unmount volume and check app deletion", func() {
+				pvc, app, err := createPVCAndAppBinding(pvcPath, appPath, f, deployTimeout)
+				if err != nil {
+					e2elog.Failf("failed to create PVC and application with error %v", err)
```
Comment (yati1998) [inline e2e/cephfs.go:534]: Use wrapped static errors instead of dynamic. You can refer this PR: https://github.com/humblec/ceph-csi/commit/82b2ad28a6e3b578af701c32bd112e761e9ec602

File: e2e/pod.go [hunk 8]
```diff
@@ -121,6 +121,42 @@ func getCommandInPodOpts(f *framework.Framework, c, ns string, opt *metav1.ListO
 	}, nil
 }
 
+func execCommanddInDaemonsetPod(f *framework.Framework, c, daemonsetName, nodeName, containerName, ns string) (string, string, error) {
```
Comment (nixpanic) [inline e2e/pod.go]: typo: double 'd' in 'Commandd'

File: e2e/pod.go [hunk 9]
```diff
@@ -105,26 +105,30 @@ func waitForDeploymentComplete(name, ns string, c kubernetes.Interface, t int) e
...
 		CaptureStdout:      true,
 		CaptureStderr:      true,
 		PreserveWhitespace: true,
 	}, nil
 }
 
+func listPods(f *framework.Framework, ns string, opt *metav1.ListOptions) ([]v1.Pod, error) {
+	podList, err := f.PodClientNS(ns).List(context.TODO(), *opt)
+	if len(podList.Items) == 0 {
+		return podList.Items, errors.New("podlist is empty")
```
Comment (nixpanic) [inline e2e/pod.go]: it probably helps debugging if you can add some of the details (namespace, ListOptions) to the error message

File: e2e/pod.go [hunk 10]
```diff
@@ -18,6 +18,21 @@ import (
 	e2elog "k8s.io/kubernetes/test/e2e/framework/log"
 )
 
+func getDaemonSetLabelSelector(f *framework.Framework, ns, dsn string) (string, error) {
```
Comment (nixpanic) [inline e2e/pod.go]: it is strongly recommended to add comments for new functions, even when they are for e2e/internal usage

**Review by nixpanic — CHANGES_REQUESTED** [review]
need to fix the typo "Commandd', maybe address other nits

**Review by nixpanic — DISMISSED** [review]
This looks really clean now, thanks!

**Review by humblec — DISMISSED** [review]

**Review by Madhu-1 — DISMISSED** [review]

**Comment by Madhu-1** [comment]
@Rakshith-R DCO bot is failing

**Review by Madhu-1 — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]
