### PR TITLE
Fix regression when no image features are provided

### LINKED ISSUE #1937: Getting all the time rpc error: code = Internal desc = invalid feature
# Describe the bug #

Installed the Ceph-csi stuff completly new based on the Ceph Doku. The ceph Cluster is a fresh installed version based on the management from Proxmox-VE.

# Environment details #

- Image/version of Ceph CSI driver : canary
- Ceph cluster version : 15.2.9
- Kubernetes cluster version : 
Kernel version
5.4.0-70-generic
OS Image
Ubuntu 20.04.2 LTS
Container runtime version
containerd://1.3.7
kubelet version
v1.19.8-34+811e9feeade1d3
kube-proxy version
v1.19.8-34+811e9feeade1d3
Operating system
linux
Architecture
amd64

# Steps to reproduce #

Just install anything like stated here:
https://docs.ceph.com/en/latest/rbd/rbd-kubernetes/#configure-ceph-csi

csi-main
ourceVersion:"27458", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "kube-system/raw-block-pvc"
I0327 14:46:01.736851       1 controller.go:731] CreateVolumeRequest name:"pvc-135cf774-db66-4d34-9d29-654d6527bb16" capacity_range:<required_bytes:1073741824 > volume_capabilities:<block:<> access_mode:<mode:SINGLE_NODE_WRITER > > parameters:<key:"clusterID" value:"065d7a87-b64f-4d80-9d60-46a1598ff07d" > parameters:<key:"csi.storage.k8s.io/pv/name" value:"pvc-135cf774-db66-4d34-9d29-654d6527bb16" > parameters:<key:"csi.storage.k8s.io/pvc/name" value:"raw-block-pvc" > parameters:<key:"csi.storage.k8s.io/pvc/namespace" value:"kube-system" > parameters:<key:"pool" value:"kubernetes" > secrets:<key:"userID" value:"kubernetes" > secrets:<key:"userKey" value:"jjjjkj" > 
I0327 14:46:01.738099       1 connection.go:182] GRPC call: /csi.v1.Controller/CreateVolume
I0327 14:46:01.738130       1 connection.go:183] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","parameters":{"clusterID":"065d7a87-b64f-4d80-9d60-46a1598ff07d","csi.storage.k8s.io/pv/name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","csi.storage.k8s.io/pvc/name":"raw-block-pvc","csi.storage.k8s.io/pvc/namespace":"kube-system","pool":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
I0327 14:46:01.742915       1 connection.go:185] GRPC response: {}
I0327 14:46:01.743112       1 connection.go:186] GRPC error: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:01.743176       1 controller.go:752] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:01.743380       1 controller.go:1099] Final error received, removing PVC 135cf774-db66-4d34-9d29-654d6527bb16 from claims in progress
W0327 14:46:01.743434       1 controller.go:958] Retrying syncing claim "135cf774-db66-4d34-9d29-654d6527bb16", failure 0
I0327 14:46:01.743544       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"raw-block-pvc", UID:"135cf774-db66-4d34-9d29-654d6527bb16", APIVersion:"v1", ResourceVersion:"27458", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = InvalidArgument desc = invalid feature 
E0327 14:46:01.743578       1 controller.go:981] error syncing claim "135cf774-db66-4d34-9d29-654d6527bb16": failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:01.743681       1 controller.go:1332] provision "kube-system/raw-block-pvc" class "csi-rbd-sc": started
I0327 14:46:01.744167       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"raw-block-pvc", UID:"135cf774-db66-4d34-9d29-654d6527bb16", APIVersion:"v1", ResourceVersion:"27458", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "kube-system/raw-block-pvc"
I0327 14:46:01.753047       1 controller.go:731] CreateVolumeRequest name:"pvc-135cf774-db66-4d34-9d29-654d6527bb16" capacity_range:<required_bytes:1073741824 > volume_capabilities:<block:<> access_mode:<mode:SINGLE_NODE_WRITER > > parameters:<key:"clusterID" value:"065d7a87-b64f-4d80-9d60-46a1598ff07d" > parameters:<key:"csi.storage.k8s.io/pv/name" value:"pvc-135cf774-db66-4d34-9d29-654d6527bb16" > parameters:<key:"csi.storage.k8s.io/pvc/name" value:"raw-block-pvc" > parameters:<key:"csi.storage.k8s.io/pvc/namespace" value:"kube-system" > parameters:<key:"pool" value:"kubernetes" > secrets:<key:"userID" value:"kubernetes" > secrets:<key:"userKey" value:"hbbb" > 
I0327 14:46:01.753418       1 connection.go:182] GRPC call: /csi.v1.Controller/CreateVolume
I0327 14:46:01.753543       1 connection.go:183] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","parameters":{"clusterID":"065d7a87-b64f-4d80-9d60-46a1598ff07d","csi.storage.k8s.io/pv/name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","csi.storage.k8s.io/pvc/name":"raw-block-pvc","csi.storage.k8s.io/pvc/namespace":"kube-system","pool":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
I0327 14:46:01.757720       1 connection.go:185] GRPC response: {}
I0327 14:46:01.757860       1 connection.go:186] GRPC error: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:01.757940       1 controller.go:752] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:01.758088       1 controller.go:1099] Final error received, removing PVC 135cf774-db66-4d34-9d29-654d6527bb16 from claims in progress
W0327 14:46:01.758145       1 controller.go:958] Retrying syncing claim "135cf774-db66-4d34-9d29-654d6527bb16", failure 1
E0327 14:46:01.758245       1 controller.go:981] error syncing claim "135cf774-db66-4d34-9d29-654d6527bb16": failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:01.758316       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"raw-block-pvc", UID:"135cf774-db66-4d34-9d29-654d6527bb16", APIVersion:"v1", ResourceVersion:"27458", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:02.244206       1 controller.go:1332] provision "kube-system/raw-block-pvc" class "csi-rbd-sc": started
I0327 14:46:02.244777       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"raw-block-pvc", UID:"135cf774-db66-4d34-9d29-654d6527bb16", APIVersion:"v1", ResourceVersion:"27458", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "kube-system/raw-block-pvc"
I0327 14:46:02.253676       1 controller.go:731] CreateVolumeRequest name:"pvc-135cf774-db66-4d34-9d29-654d6527bb16" capacity_range:<required_bytes:1073741824 > volume_capabilities:<block:<> access_mode:<mode:SINGLE_NODE_WRITER > > parameters:<key:"clusterID" value:"065d7a87-b64f-4d80-9d60-46a1598ff07d" > parameters:<key:"csi.storage.k8s.io/pv/name" value:"pvc-135cf774-db66-4d34-9d29-654d6527bb16" > parameters:<key:"csi.storage.k8s.io/pvc/name" value:"raw-block-pvc" > parameters:<key:"csi.storage.k8s.io/pvc/namespace" value:"kube-system" > parameters:<key:"pool" value:"kubernetes" > secrets:<key:"userID" value:"kubernetes" > secrets:<key:"userKey" value:"" > 
I0327 14:46:02.253939       1 connection.go:182] GRPC call: /csi.v1.Controller/CreateVolume
I0327 14:46:02.253978       1 connection.go:183] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","parameters":{"clusterID":"065d7a87-b64f-4d80-9d60-46a1598ff07d","csi.storage.k8s.io/pv/name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","csi.storage.k8s.io/pvc/name":"raw-block-pvc","csi.storage.k8s.io/pvc/namespace":"kube-system","pool":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
I0327 14:46:02.256666       1 connection.go:185] GRPC response: {}
I0327 14:46:02.256778       1 connection.go:186] GRPC error: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:02.256841       1 controller.go:752] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:02.256934       1 controller.go:1099] Final error received, removing PVC 135cf774-db66-4d34-9d29-654d6527bb16 from claims in progress
W0327 14:46:02.256986       1 controller.go:958] Retrying syncing claim "135cf774-db66-4d34-9d29-654d6527bb16", failure 2
E0327 14:46:02.257034       1 controller.go:981] error syncing claim "135cf774-db66-4d34-9d29-654d6527bb16": failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:02.257100       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"raw-block-pvc", UID:"135cf774-db66-4d34-9d29-654d6527bb16", APIVersion:"v1", ResourceVersion:"27458", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:04.080642       1 leaderelection.go:273] successfully renewed lease kube-system/rbd-csi-ceph-com
I0327 14:46:04.257524       1 controller.go:1332] provision "kube-system/raw-block-pvc" class "csi-rbd-sc": started
I0327 14:46:04.258083       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"raw-block-pvc", UID:"135cf774-db66-4d34-9d29-654d6527bb16", APIVersion:"v1", ResourceVersion:"27458", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "kube-system/raw-block-pvc"
I0327 14:46:04.266789       1 controller.go:731] CreateVolumeRequest name:"pvc-135cf774-db66-4d34-9d29-654d6527bb16" capacity_range:<required_bytes:1073741824 > volume_capabilities:<block:<> access_mode:<mode:SINGLE_NODE_WRITER > > parameters:<key:"clusterID" value:"065d7a87-b64f-4d80-9d60-46a1598ff07d" > parameters:<key:"csi.storage.k8s.io/pv/name" value:"pvc-135cf774-db66-4d34-9d29-654d6527bb16" > parameters:<key:"csi.storage.k8s.io/pvc/name" value:"raw-block-pvc" > parameters:<key:"csi.storage.k8s.io/pvc/namespace" value:"kube-system" > parameters:<key:"pool" value:"kubernetes" > secrets:<key:"userID" value:"kubernetes" > secrets:<key:"userKey" value:"" > 
I0327 14:46:04.267108       1 connection.go:182] GRPC call: /csi.v1.Controller/CreateVolume
I0327 14:46:04.267183       1 connection.go:183] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","parameters":{"clusterID":"065d7a87-b64f-4d80-9d60-46a1598ff07d","csi.storage.k8s.io/pv/name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","csi.storage.k8s.io/pvc/name":"raw-block-pvc","csi.storage.k8s.io/pvc/namespace":"kube-system","pool":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
I0327 14:46:04.269893       1 connection.go:185] GRPC response: {}
I0327 14:46:04.269987       1 connection.go:186] GRPC error: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:04.270046       1 controller.go:752] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:04.270158       1 controller.go:1099] Final error received, removing PVC 135cf774-db66-4d34-9d29-654d6527bb16 from claims in progress
W0327 14:46:04.270192       1 controller.go:958] Retrying syncing claim "135cf774-db66-4d34-9d29-654d6527bb16", failure 3
E0327 14:46:04.270239       1 controller.go:981] error syncing claim "135cf774-db66-4d34-9d29-654d6527bb16": failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:04.270295       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"raw-block-pvc", UID:"135cf774-db66-4d34-9d29-654d6527bb16", APIVersion:"v1", ResourceVersion:"27458", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:08.270752       1 controller.go:1332] provision "kube-system/raw-block-pvc" class "csi-rbd-sc": started
I0327 14:46:08.271364       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"raw-block-pvc", UID:"135cf774-db66-4d34-9d29-654d6527bb16", APIVersion:"v1", ResourceVersion:"27458", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "kube-system/raw-block-pvc"
I0327 14:46:08.282387       1 controller.go:731] CreateVolumeRequest name:"pvc-135cf774-db66-4d34-9d29-654d6527bb16" capacity_range:<required_bytes:1073741824 > volume_capabilities:<block:<> access_mode:<mode:SINGLE_NODE_WRITER > > parameters:<key:"clusterID" value:"065d7a87-b64f-4d80-9d60-46a1598ff07d" > parameters:<key:"csi.storage.k8s.io/pv/name" value:"pvc-135cf774-db66-4d34-9d29-654d6527bb16" > parameters:<key:"csi.storage.k8s.io/pvc/name" value:"raw-block-pvc" > parameters:<key:"csi.storage.k8s.io/pvc/namespace" value:"kube-system" > parameters:<key:"pool" value:"kubernetes" > secrets:<key:"userID" value:"kubernetes" > secrets:<key:"userKey" value:"" > 
I0327 14:46:08.282616       1 connection.go:182] GRPC call: /csi.v1.Controller/CreateVolume
I0327 14:46:08.282644       1 connection.go:183] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","parameters":{"clusterID":"065d7a87-b64f-4d80-9d60-46a1598ff07d","csi.storage.k8s.io/pv/name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","csi.storage.k8s.io/pvc/name":"raw-block-pvc","csi.storage.k8s.io/pvc/namespace":"kube-system","pool":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
I0327 14:46:08.285820       1 connection.go:185] GRPC response: {}
I0327 14:46:08.285979       1 connection.go:186] GRPC error: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:08.286049       1 controller.go:752] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:08.286167       1 controller.go:1099] Final error received, removing PVC 135cf774-db66-4d34-9d29-654d6527bb16 from claims in progress
W0327 14:46:08.286224       1 controller.go:958] Retrying syncing claim "135cf774-db66-4d34-9d29-654d6527bb16", failure 4
E0327 14:46:08.286281       1 controller.go:981] error syncing claim "135cf774-db66-4d34-9d29-654d6527bb16": failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:08.286336       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"raw-block-pvc", UID:"135cf774-db66-4d34-9d29-654d6527bb16", APIVersion:"v1", ResourceVersion:"27458", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:09.135215       1 leaderelection.go:273] successfully renewed lease kube-system/rbd-csi-ceph-com

csi-provisioner:

pvc","csi.storage.k8s.io/pvc/namespace":"kube-system","pool":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
E0327 14:46:01.757179       1 rbd_util.go:918] ID: 34 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 failed to validate image features invalid feature 
E0327 14:46:01.757300       1 utils.go:136] ID: 34 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC error: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:02.255285       1 utils.go:132] ID: 35 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC call: /csi.v1.Controller/CreateVolume
I0327 14:46:02.255594       1 utils.go:133] ID: 35 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","parameters":{"clusterID":"065d7a87-b64f-4d80-9d60-46a1598ff07d","csi.storage.k8s.io/pv/name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","csi.storage.k8s.io/pvc/name":"raw-block-pvc","csi.storage.k8s.io/pvc/namespace":"kube-system","pool":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
E0327 14:46:02.256074       1 rbd_util.go:918] ID: 35 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 failed to validate image features invalid feature 
E0327 14:46:02.256195       1 utils.go:136] ID: 35 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC error: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:04.268457       1 utils.go:132] ID: 36 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC call: /csi.v1.Controller/CreateVolume
I0327 14:46:04.268765       1 utils.go:133] ID: 36 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","parameters":{"clusterID":"065d7a87-b64f-4d80-9d60-46a1598ff07d","csi.storage.k8s.io/pv/name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","csi.storage.k8s.io/pvc/name":"raw-block-pvc","csi.storage.k8s.io/pvc/namespace":"kube-system","pool":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
E0327 14:46:04.269244       1 rbd_util.go:918] ID: 36 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 failed to validate image features invalid feature 
E0327 14:46:04.269381       1 utils.go:136] ID: 36 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC error: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:08.283931       1 utils.go:132] ID: 37 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC call: /csi.v1.Controller/CreateVolume
I0327 14:46:08.284445       1 utils.go:133] ID: 37 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","parameters":{"clusterID":"065d7a87-b64f-4d80-9d60-46a1598ff07d","csi.storage.k8s.io/pv/name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","csi.storage.k8s.io/pvc/name":"raw-block-pvc","csi.storage.k8s.io/pvc/namespace":"kube-system","pool":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
E0327 14:46:08.285020       1 rbd_util.go:918] ID: 37 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 failed to validate image features invalid feature 
E0327 14:46:08.285191       1 utils.go:136] ID: 37 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC error: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:12.637580       1 utils.go:132] ID: 38 GRPC call: /csi.v1.Identity/Probe
I0327 14:46:12.637774       1 utils.go:133] ID: 38 GRPC request: {}
I0327 14:46:12.637867       1 utils.go:138] ID: 38 GRPC response: {}
I0327 14:46:16.298944       1 utils.go:132] ID: 39 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC call: /csi.v1.Controller/CreateVolume
I0327 14:46:16.299271       1 utils.go:133] ID: 39 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","parameters":{"clusterID":"065d7a87-b64f-4d80-9d60-46a1598ff07d","csi.storage.k8s.io/pv/name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","csi.storage.k8s.io/pvc/name":"raw-block-pvc","csi.storage.k8s.io/pvc/namespace":"kube-system","pool":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
E0327 14:46:16.299676       1 rbd_util.go:918] ID: 39 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 failed to validate image features invalid feature 
E0327 14:46:16.299781       1 utils.go:136] ID: 39 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC error: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:32.319078       1 utils.go:132] ID: 40 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC call: /csi.v1.Controller/CreateVolume
I0327 14:46:32.319416       1 utils.go:133] ID: 40 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","parameters":{"clusterID":"065d7a87-b64f-4d80-9d60-46a1598ff07d","csi.storage.k8s.io/pv/name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","csi.storage.k8s.io/pvc/name":"raw-block-pvc","csi.storage.k8s.io/pvc/namespace":"kube-system","pool":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
E0327 14:46:32.319845       1 rbd_util.go:918] ID: 40 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 failed to validate image features invalid feature 
E0327 14:46:32.319964       1 utils.go:136] ID: 40 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC error: rpc error: code = InvalidArgument desc = invalid feature

### LINKED ISSUE #2049: rpc error: code = Internal desc = invalid feature when mounting all of a sudden
# Describe the bug #

When trying to mount pvs, that used to mount, we now get errors

```
MountVolume.MountDevice failed for volume "gitlab-data" : rpc error: code = Internal desc = invalid feature
```

We have a storageClass

```
provisioner: rbd.csi.ceph.com
mountOptions:
  - discard
parameters:
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/provisioner-secret-name: ceph-cluster-secret
  userId: openshift
  userSecretName: ceph-cluster-secret
  csi.storage.k8s.io/node-stage-secret-name: ceph-cluster-secret
  adminId: admin
  adminSecretName: ceph-cluster-secret
  csi.storage.k8s.io/controller-expand-secret-name: ceph-cluster-secret
  clusterID: REDACTED
  imageFeatures: layering
  csi.storage.k8s.io/controller-expand-secret-namespace: default
  monitors: REDACTED
  pool: openshift
  adminSecretNamespace: kube-system
  csi.storage.k8s.io/node-stage-secret-namespace: default
volumeBindingMode: Immediate
metadata:
  name: ceph-cluster
  selfLink: /apis/storage.k8s.io/v1/storageclasses/ceph-cluster
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
kind: StorageClass
reclaimPolicy: Delete
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
```

Here's an example PVC
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
  selfLink: /api/v1/namespaces/gitlab/persistentvolumeclaims/gitlab-data
  resourceVersion: '3563066'
  name: gitlab-data
  uid: 5242de7d-e2cb-4291-ad6b-a3acca5454f6
  creationTimestamp: '2020-12-20T00:48:52Z'
  namespace: gitlab
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: gitlab-data
  storageClassName: ceph-cluster
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
```

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: gitlab-data
  selfLink: /api/v1/persistentvolumes/gitlab-data
  uid: 2fe3e0a5-5ad9-4325-ab82-040b297e452e
  resourceVersion: '3563053'
  creationTimestamp: '2020-12-20T23:02:15Z'
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 100Gi
  csi:
    driver: rbd.csi.ceph.com
    volumeHandle: gitlab-data
    fsType: ext4
    volumeAttributes:
      radosNamespace: ''
      userId: openshift
      imageName: gitlab-data
      userSecretName: ceph-cluster-secret
      staticVolume: 'true'
      adminId: admin
      journalPool: openshift
      clusterID: REDACTED
      monitors: REDACTED
      storage.kubernetes.io/csiProvisionerIdentity: 1608421144578-8081-rbd.csi.ceph.com
      pool: openshift
      adminSecretNamespace: kube-system
    nodeStageSecretRef:
      name: ceph-cluster-secret
      namespace: default
    controllerExpandSecretRef:
      name: ceph-cluster-secret
      namespace: default
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: gitlab
    name: gitlab-data
    uid: 5242de7d-e2cb-4291-ad6b-a3acca5454f6
    apiVersion: v1
    resourceVersion: '3561740'
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound
```

# Environment details #

- Image/version of Ceph CSI driver : `3.2.0`
- Helm chart version : `3.2.0`
- Kernel version : `5.9.11-200.fc33.x86_64`
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : `rbd-nbd`
- Kubernetes cluster version : `v1.20.0+bafe72f-1054`
- Ceph cluster version : `15.2.10`

# Steps to reproduce #

1. Set everything up months ago, and have everything working. PVCs mounting, new ones creating, no issues.
2. Start a pod that mounts one of the pvcs
3. Look at the events for that pod

# Actual results #

Now when trying to mount a pvc, you get `MountVolume.MountDevice failed for volume "gitlab-data" : rpc error: code = Internal desc = invalid feature`

# Expected behavior #

The PVC should have mounted properly and the pod starts

# Logs #

If the issue is in PVC mounting please attach complete logs of below containers.

```
I0504 02:44:48.879717    6774 utils.go:173] ID: 22394 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}},{"Type":{"Rpc":{"type":3}}}]}
I0504 02:44:48.895586    6774 utils.go:162] ID: 22395 Req-ID: gitlab-redis GRPC call: /csi.v1.Node/NodeStageVolume
I0504 02:44:48.895799    6774 utils.go:166] ID: 22395 Req-ID: gitlab-redis GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/gitlab-redis/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"adminId":"admin","adminSecretNamespace":"kube-system","clusterID":"3880c3a5-0ada-4c9a-8b44-2b0aece72a33","imageName":"gitlab-redis","journalPool":"openshift","monitors":"129.21.49.224:6789,129.21.49.52:6789,129.21.49.161:6789","pool":"openshift","radosNamespace":"","staticVolume":"true","storage.kubernetes.io/csiProvisionerIdentity":"1608421144578-8081-rbd.csi.ceph.com","userId":"openshift","userSecretName":"ceph-cluster-secret"},"volume_id":"gitlab-redis"}
E0504 02:44:48.896190    6774 rbd_util.go:972] ID: 22395 Req-ID: gitlab-redis failed to validate image features invalid feature
E0504 02:44:48.896255    6774 utils.go:171] ID: 22395 Req-ID: gitlab-redis GRPC error: rpc error: code = Internal desc = invalid feature
I0504 02:44:57.541757    6774 utils.go:162] ID: 22396 GRPC call: /csi.v1.Identity/Probe
I0504 02:44:57.541871    6774 utils.go:166] ID: 22396 GRPC request: {}
I0504 02:44:57.541910    6774 utils.go:173] ID: 22396 GRPC response: {}
I0504 02:45:08.451092    6774 utils.go:162] ID: 22397 GRPC call: /csi.v1.Node/NodeGetCapabilities
I0504 02:45:08.451183    6774 utils.go:166] ID: 22397 GRPC request: {}
I0504 02:45:08.451302    6774 utils.go:173] ID: 22397 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}},{"Type":{"Rpc":{"type":3}}}]}
I0504 02:45:08.489826    6774 utils.go:162] ID: 22398 Req-ID: gitlab-data GRPC call: /csi.v1.Node/NodeStageVolume
I0504 02:45:08.490045    6774 utils.go:166] ID: 22398 Req-ID: gitlab-data GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/gitlab-data/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"adminId":"admin","adminSecretNamespace":"kube-system","clusterID":"3880c3a5-0ada-4c9a-8b44-2b0aece72a33","imageName":"gitlab-data","journalPool":"openshift","monitors":"129.21.49.224:6789,129.21.49.52:6789,129.21.49.161:6789","pool":"openshift","radosNamespace":"","staticVolume":"true","storage.kubernetes.io/csiProvisionerIdentity":"1608421144578-8081-rbd.csi.ceph.com","userId":"openshift","userSecretName":"ceph-cluster-secret"},"volume_id":"gitlab-data"}
E0504 02:45:08.490399    6774 rbd_util.go:972] ID: 22398 Req-ID: gitlab-data failed to validate image features invalid feature
E0504 02:45:08.490475    6774 utils.go:171] ID: 22398 Req-ID: gitlab-data GRPC error: rpc error: code = Internal desc = invalid feature
I0504 02:45:08.551963    6774 utils.go:162] ID: 22399 GRPC call: /csi.v1.Node/NodeGetCapabilities
I0504 02:45:08.552110    6774 utils.go:166] ID: 22399 GRPC request: {}
I0504 02:45:08.552289    6774 utils.go:173] ID: 22399 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}},{"Type":{"Rpc":{"type":3}}}]}
I0504 02:45:08.577479    6774 utils.go:162] ID: 22400 Req-ID: gitlab-etc GRPC call: /csi.v1.Node/NodeStageVolume
I0504 02:45:08.577719    6774 utils.go:166] ID: 22400 Req-ID: gitlab-etc GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/gitlab-etc/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"adminId":"admin","adminSecretNamespace":"kube-system","clusterID":"3880c3a5-0ada-4c9a-8b44-2b0aece72a33","imageName":"gitlab-etc","journalPool":"openshift","monitors":"129.21.49.224:6789,129.21.49.52:6789,129.21.49.161:6789","pool":"openshift","radosNamespace":"","staticVolume":"true","storage.kubernetes.io/csiProvisionerIdentity":"1608421144578-8081-rbd.csi.ceph.com","userId":"openshift","userSecretName":"ceph-cluster-secret"},"volume_id":"gitlab-etc"}
E0504 02:45:08.578005    6774 rbd_util.go:972] ID: 22400 Req-ID: gitlab-etc failed to validate image features invalid feature
E0504 02:45:08.578077    6774 utils.go:171] ID: 22400 Req-ID: gitlab-etc GRPC error: rpc error: code = Internal desc = invalid feature
I0504 02:45:57.541580    6774 utils.go:162] ID: 22401 GRPC call: /csi.v1.Identity/Probe
I0504 02:45:57.541703    6774 utils.go:166] ID: 22401 GRPC request: {}
I0504 02:45:57.542000    6774 utils.go:173] ID: 22401 GRPC response: {}
I0504 02:46:12.588078    6774 utils.go:162] ID: 22402 GRPC call: /csi.v1.Node/NodeGetCapabilities
I0504 02:46:12.588210    6774 utils.go:166] ID: 22402 GRPC request: {}
I0504 02:46:12.588332    6774 utils.go:173] ID: 22402 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}},{"Type":{"Rpc":{"type":3}}}]}
I0504 02:46:12.646633    6774 utils.go:162] ID: 22403 Req-ID: gitlab-data GRPC call: /csi.v1.Node/NodeStageVolume
I0504 02:46:12.646799    6774 utils.go:166] ID: 22403 Req-ID: gitlab-data GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/gitlab-data/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"adminId":"admin","adminSecretNamespace":"kube-system","clusterID":"3880c3a5-0ada-4c9a-8b44-2b0aece72a33","imageName":"gitlab-data","journalPool":"openshift","monitors":"129.21.49.224:6789,129.21.49.52:6789,129.21.49.161:6789","pool":"openshift","radosNamespace":"","staticVolume":"true","storage.kubernetes.io/csiProvisionerIdentity":"1608421144578-8081-rbd.csi.ceph.com","userId":"openshift","userSecretName":"ceph-cluster-secret"},"volume_id":"gitlab-data"}
E0504 02:46:12.647170    6774 rbd_util.go:972] ID: 22403 Req-ID: gitlab-data failed to validate image features invalid feature
E0504 02:46:12.647247    6774 utils.go:171] ID: 22403 Req-ID: gitlab-data GRPC error: rpc error: code = Internal desc = invalid feature
I0504 02:46:12.696948    6774 utils.go:162] ID: 22404 GRPC call: /csi.v1.Node/NodeGetCapabilities
I0504 02:46:12.697044    6774 utils.go:166] ID: 22404 GRPC request: {}
I0504 02:46:12.697181    6774 utils.go:173] ID: 22404 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}},{"Type":{"Rpc":{"type":3}}}]}
I0504 02:46:12.711057    6774 utils.go:162] ID: 22405 Req-ID: gitlab-etc GRPC call: /csi.v1.Node/NodeStageVolume
I0504 02:46:12.711226    6774 utils.go:166] ID: 22405 Req-ID: gitlab-etc GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/gitlab-etc/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"adminId":"admin","adminSecretNamespace":"kube-system","clusterID":"3880c3a5-0ada-4c9a-8b44-2b0aece72a33","imageName":"gitlab-etc","journalPool":"openshift","monitors":"129.21.49.224:6789,129.21.49.52:6789,129.21.49.161:6789","pool":"openshift","radosNamespace":"","staticVolume":"true","storage.kubernetes.io/csiProvisionerIdentity":"1608421144578-8081-rbd.csi.ceph.com","userId":"openshift","userSecretName":"ceph-cluster-secret"},"volume_id":"gitlab-etc"}
E0504 02:46:12.711544    6774 rbd_util.go:972] ID: 22405 Req-ID: gitlab-etc failed to validate image features invalid feature
E0504 02:46:12.711623    6774 utils.go:171] ID: 22405 Req-ID: gitlab-etc GRPC error: rpc error: code = Internal desc = invalid feature
I0504 02:46:50.962287    6774 utils.go:162] ID: 22406 GRPC call: /csi.v1.Node/NodeGetCapabilities
I0504 02:46:50.962383    6774 utils.go:166] ID: 22406 GRPC request: {}
I0504 02:46:50.962468    6774 utils.go:173] ID: 22406 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}},{"Type":{"Rpc":{"type":3}}}]}
I0504 02:46:50.979662    6774 utils.go:162] ID: 22407 Req-ID: gitlab-redis GRPC call: /csi.v1.Node/NodeStageVolume
I0504 02:46:50.979872    6774 utils.go:166] ID: 22407 Req-ID: gitlab-redis GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/gitlab-redis/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"adminId":"admin","adminSecretNamespace":"kube-system","clusterID":"3880c3a5-0ada-4c9a-8b44-2b0aece72a33","imageName":"gitlab-redis","journalPool":"openshift","monitors":"129.21.49.224:6789,129.21.49.52:6789,129.21.49.161:6789","pool":"openshift","radosNamespace":"","staticVolume":"true","storage.kubernetes.io/csiProvisionerIdentity":"1608421144578-8081-rbd.csi.ceph.com","userId":"openshift","userSecretName":"ceph-cluster-secret"},"volume_id":"gitlab-redis"}
E0504 02:46:50.980270    6774 rbd_util.go:972] ID: 22407 Req-ID: gitlab-redis failed to validate image features invalid feature
E0504 02:46:50.980336    6774 utils.go:171] ID: 22407 Req-ID: gitlab-redis GRPC error: rpc error: code = Internal desc = invalid feature
I0504 02:46:57.541381    6774 utils.go:162] ID: 22408 GRPC call: /csi.v1.Identity/Probe
I0504 02:46:57.541467    6774 utils.go:166] ID: 22408 GRPC request: {}
I0504 02:46:57.541638    6774 utils.go:173] ID: 22408 GRPC response: {}
I0504 02:47:57.542353    6774 utils.go:162] ID: 22409 GRPC call: /csi.v1.Identity/Probe
I0504 02:47:57.542558    6774 utils.go:166] ID: 22409 GRPC request: {}
I0504 02:47:57.542633    6774 utils.go:173] ID: 22409 GRPC response: {}
I0504 02:48:14.752139    6774 utils.go:162] ID: 22410 GRPC call: /csi.v1.Node/NodeGetCapabilities
I0504 02:48:14.752334    6774 utils.go:166] ID: 22410 GRPC request: {}
I0504 02:48:14.752713    6774 utils.go:173] ID: 22410 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}},{"Type":{"Rpc":{"type":3}}}]}
I0504 02:48:14.752953    6774 utils.go:162] ID: 22411 GRPC call: /csi.v1.Node/NodeGetCapabilities
I0504 02:48:14.753119    6774 utils.go:166] ID: 22411 GRPC request: {}
I0504 02:48:14.753250    6774 utils.go:173] ID: 22411 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}},{"Type":{"Rpc":{"type":3}}}]}
I0504 02:48:14.767738    6774 utils.go:162] ID: 22412 Req-ID: gitlab-data GRPC call: /csi.v1.Node/NodeStageVolume
I0504 02:48:14.768191    6774 utils.go:166] ID: 22412 Req-ID: gitlab-data GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/gitlab-data/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"adminId":"admin","adminSecretNamespace":"kube-system","clusterID":"3880c3a5-0ada-4c9a-8b44-2b0aece72a33","imageName":"gitlab-data","journalPool":"openshift","monitors":"129.21.49.224:6789,129.21.49.52:6789,129.21.49.161:6789","pool":"openshift","radosNamespace":"","staticVolume":"true","storage.kubernetes.io/csiProvisionerIdentity":"1608421144578-8081-rbd.csi.ceph.com","userId":"openshift","userSecretName":"ceph-cluster-secret"},"volume_id":"gitlab-data"}
E0504 02:48:14.768792    6774 rbd_util.go:972] ID: 22412 Req-ID: gitlab-data failed to validate image features invalid feature
E0504 02:48:14.768887    6774 utils.go:171] ID: 22412 Req-ID: gitlab-data GRPC error: rpc error: code = Internal desc = invalid feature
I0504 02:48:14.769775    6774 utils.go:162] ID: 22413 Req-ID: gitlab-etc GRPC call: /csi.v1.Node/NodeStageVolume
I0504 02:48:14.770005    6774 utils.go:166] ID: 22413 Req-ID: gitlab-etc GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/gitlab-etc/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"adminId":"admin","adminSecretNamespace":"kube-system","clusterID":"3880c3a5-0ada-4c9a-8b44-2b0aece72a33","imageName":"gitlab-etc","journalPool":"openshift","monitors":"129.21.49.224:6789,129.21.49.52:6789,129.21.49.161:6789","pool":"openshift","radosNamespace":"","staticVolume":"true","storage.kubernetes.io/csiProvisionerIdentity":"1608421144578-8081-rbd.csi.ceph.com","userId":"openshift","userSecretName":"ceph-cluster-secret"},"volume_id":"gitlab-etc"}
E0504 02:48:14.770331    6774 rbd_util.go:972] ID: 22413 Req-ID: gitlab-etc failed to validate image features invalid feature
E0504 02:48:14.770418    6774 utils.go:171] ID: 22413 Req-ID: gitlab-etc GRPC error: rpc error: code = Internal desc = invalid feature
I0504 02:48:53.067223    6774 utils.go:162] ID: 22414 GRPC call: /csi.v1.Node/NodeGetCapabilities
I0504 02:48:53.067496    6774 utils.go:166] ID: 22414 GRPC request: {}
I0504 02:48:53.067752    6774 utils.go:173] ID: 22414 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}},{"Type":{"Rpc":{"type":3}}}]}
I0504 02:48:53.087379    6774 utils.go:162] ID: 22415 Req-ID: gitlab-redis GRPC call: /csi.v1.Node/NodeStageVolume
I0504 02:48:53.088144    6774 utils.go:166] ID: 22415 Req-ID: gitlab-redis GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/gitlab-redis/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"adminId":"admin","adminSecretNamespace":"kube-system","clusterID":"3880c3a5-0ada-4c9a-8b44-2b0aece72a33","imageName":"gitlab-redis","journalPool":"openshift","monitors":"129.21.49.224:6789,129.21.49.52:6789,129.21.49.161:6789","pool":"openshift","radosNamespace":"","staticVolume":"true","storage.kubernetes.io/csiProvisionerIdentity":"1608421144578-8081-rbd.csi.ceph.com","userId":"openshift","userSecretName":"ceph-cluster-secret"},"volume_id":"gitlab-redis"}
E0504 02:48:53.088937    6774 rbd_util.go:972] ID: 22415 Req-ID: gitlab-redis failed to validate image features invalid feature
E0504 02:48:53.089049    6774 utils.go:171] ID: 22415 Req-ID: gitlab-redis GRPC error: rpc error: code = Internal desc = invalid feature
I0504 02:48:57.543253    6774 utils.go:162] ID: 22416 GRPC call: /csi.v1.Identity/Probe
I0504 02:48:57.543366    6774 utils.go:166] ID: 22416 GRPC request: {}
I0504 02:48:57.543466    6774 utils.go:173] ID: 22416 GRPC response: {}
```

```
I0418 16:28:56.889345    5851 main.go:112] Version: v2.0.1
I0418 16:28:56.889463    5851 main.go:122] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0418 16:28:56.889803    5851 connection.go:151] Connecting to unix:///csi/csi.sock
W0418 16:29:06.889946    5851 connection.go:170] Still connecting to unix:///csi/csi.sock
W0418 16:29:16.889907    5851 connection.go:170] Still connecting to unix:///csi/csi.sock
W0418 16:29:26.890221    5851 connection.go:170] Still connecting to unix:///csi/csi.sock
W0418 16:29:36.890300    5851 connection.go:170] Still connecting to unix:///csi/csi.sock
W0418 16:29:46.889940    5851 connection.go:170] Still connecting to unix:///csi/csi.sock
W0418 16:29:56.889983    5851 connection.go:170] Still connecting to unix:///csi/csi.sock
W0418 16:30:06.889886    5851 connection.go:170] Still connecting to unix:///csi/csi.sock
W0418 16:30:16.890067    5851 connection.go:170] Still connecting to unix:///csi/csi.sock
W0418 16:30:26.889972    5851 connection.go:170] Still connecting to unix:///csi/csi.sock
W0418 16:30:36.890048    5851 connection.go:170] Still connecting to unix:///csi/csi.sock
I0418 16:30:43.448769    5851 main.go:129] Calling CSI driver to discover driver name
I0418 16:30:43.448833    5851 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
I0418 16:30:43.448854    5851 connection.go:181] GRPC request: {}
I0418 16:30:43.460494    5851 connection.go:183] GRPC response: {"name":"rbd.csi.ceph.com","vendor_version":"canary"}
I0418 16:30:43.460700    5851 connection.go:184] GRPC error: <nil>
I0418 16:30:43.460712    5851 main.go:139] CSI driver name: "rbd.csi.ceph.com"
I0418 16:30:43.460776    5851 node_register.go:55] Starting Registration Server at: /registration/rbd.csi.ceph.com-reg.sock
I0418 16:30:43.461254    5851 node_register.go:64] Registration Server started at: /registration/rbd.csi.ceph.com-reg.sock
I0418 16:30:43.461655    5851 node_register.go:86] Skipping healthz server because port set to: 0
I0418 16:30:43.630377    5851 main.go:79] Received GetInfo call: &InfoRequest{}
I0418 16:30:43.773324    5851 main.go:89] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
```

# Additional context #

This is running on our OKD4.7 cluster. The cluster used to allow these pvcs to mount without error, but now throws this error about failing to validate images and invalid features.

Here's the rbd info
```
rbd image 'gitlab-data':
	size 100 GiB in 25600 objects
	order 22 (4 MiB objects)
	snapshot_count: 0
	id: 2eceb238e1f29
	block_name_prefix: rbd_data.2eceb238e1f29
	format: 2
	features: layering
	op_features:
	flags:
	access_timestamp: Mon May  3 00:31:19 2021
```

### PR DESCRIPTION
**Pull request by mnaser**
# Describe what this PR does #
There is an issue that if the storage class was originally created with no image features (which worked fine), it would fail when upgrading the Ceph CSI.

The regression was introduced by this commit:

https://github.com/ceph/ceph-csi/commit/d8f7b38d3dac9718695ff6c33328f5f6cfce2c2f

Several users have filed issues about this, see listed in related issues below.

## Is there anything that requires special attention ##

This is a regression which really hurts when upgrading (and only noticed when remounting volumes).  It's incredibly hard to fix in production because PVs are read-only.  Users could potentially lose their data if they try and force a replace as the PV is recreated.

## Related issues ##

Fixes: #1937 
Fixes: #2049 

## Future concerns ##

None for now.

### CODE REVIEW

**Comment by mnaser** [comment]
I've added a failing test, I'm investigating the fix now, but it's 100% a problem with that test, seeing locally:

```
$ go test ./internal/rbd
--- FAIL: TestValidateImageFeatures (0.00s)
    rbd_util_test.go:134: 
                Error Trace:    rbd_util_test.go:134
                Error:          Expected nil, but got: &errors.errorString{s:"invalid feature "}
                Test:           TestValidateImageFeatures
FAIL
FAIL    github.com/ceph/ceph-csi/internal/rbd   0.048s
FAIL
```

**Comment by mnaser** [comment]
OK, so it seems like an empty string being split will result in at least one item:

```
package main

import (
	"fmt"
	"strings"
)

func main() {
	arr := strings.Split("", ",")
	for x, _ := range arr {
		fmt.Print(x)
	}
}
```

which results in:

```
0
Program exited.
```

**Comment by mnaser** [comment]
This is ready and good to go, I believe it should be a quite high priority fix as it's a regression.

File: internal/rbd/rbd_util.go [hunk 1]
```diff
@@ -993,6 +993,9 @@ func genVolFromVolumeOptions(ctx context.Context, volOptions, credentials map[st
 }
 
 func (rv *rbdVolume) validateImageFeatures(imageFeatures string) error {
+	if strings.TrimSpace(imageFeatures) == "" {
```
Comment (Madhu-1) [inline internal/rbd/rbd_util.go:1000]: @mnaser I have seen some issues opened failed to mount the PVC when the imageFeatures are not set in storageclass https://github.com/ceph/ceph-csi/issues/1217#issuecomment-655871773 https://github.com/ceph/ceph-csi/issues/1293#issuecomment-665752463 etc. IMO below changes to fix the backward compatibility issue and also to provide a proper error message to the user during CreateVolume if the imageFeature is not set.

* Return proper error message from `validateImageFeatures` function which will get returned to the user in CreateVolume
* In NodestageVolume to support backward compatibility we can discard if `validateImageFeatures` returns the above error message and continue for the next operation.

**Comment by nixpanic** [comment]
Thanks for the PR! Please note that we expect commit messages to have a prefix of the affected component. In this case, you can add `rbd: ` as a prefix. Please update the commit messages and force-push the updated commits to your fork+branch again.

More details about this can be found in the [development guide](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md).

File: internal/rbd/rbd_util.go (hunk 1 above)
Comment (humblec) [inline internal/rbd/rbd_util.go:1000]: @mnaser just above this , please feel free to add some source code comment about the scenario we came across. :+1:

Comment (Madhu-1) [reply internal/rbd/rbd_util.go:1000]: alternativity PR https://github.com/ceph/ceph-csi/pull/2139 to fix this completely

**Review by Madhu-1 — DISMISSED** [review]

File: internal/rbd/rbd_util.go (hunk 1 above)
Comment (Rakshith-R) [reply internal/rbd/rbd_util.go:1000]: > * Return proper error message from `validateImageFeatures` function which will get returned to the user in CreateVolume

This error message will be wrapped as following and maybe misleading 
https://github.com/ceph/ceph-csi/blob/7cbad9305f71b70040509ed854f1d65c7c624d4f/internal/rbd/rbd_util.go#L979-L982
> * In NodestageVolume to support backward compatibility we can discard if `validateImageFeatures` returns the above error message and continue for the next operation.

By discarding error, we would fail to enforce required `imageFeatures` option on static PVs(whose attributes can be edited). 

---
IMO, we need to validate and enforce required parameter like `imageFeatures` in https://github.com/ceph/ceph-csi/blob/7cbad9305f71b70040509ed854f1d65c7c624d4f/internal/rbd/controllerserver.go#L94 
by adding something like 
```go
	if _, ok := req.GetParameters()["imageFeatures"]; !ok {
		return nil, status.Error(codes.InvalidArgument, "missing required parameter imageFeatures")
	}
````
and in https://github.com/ceph/ceph-csi/blob/7cbad9305f71b70040509ed854f1d65c7c624d4f/internal/rbd/nodeserver.go#L115
Allow non-static volume to maintain backwards compatibility while enforcing the paramter for static pvs.
(newly provisioned non-static volume can be let go, since we enforce it during createrequest)
```go
	if _, ok := req.GetParameters()["imageFeatures"]; !ok && !staticVol {
		return nil, status.Error(codes.InvalidArgument, "missing required parameter imageFeatures")
	}
````
cc @nixpanic @humblec @Madhu-1 
Update: pr up here https://github.com/ceph/ceph-csi/pull/2139*

Comment (mnaser) [reply internal/rbd/rbd_util.go:1000]: I think this would still leave use cases like me that have PV's which I cannot edit with no image features that refuse to be mounted (but work just fine once they are mounted).

**Review by Rakshith-R — APPROVED** [review]

**Comment by mnaser** [comment]
Thanks for the reviews.  I've made the required modifications..

**Review by nixpanic — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Review by humblec — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by Rakshith-R** [comment]
@mnaser , did u have any reason for adding trimspace function `strings.TrimSpace(imageFeatures)`? 
Just spaces like `imageFeatures: "    "` config should also be treated as invalid. 
While upgrading, it should not exist and `map[string]string` should just return empty strings.

This would present an edge case wherein a user can pass just  `imageFeatures: "    "`  and will not trigger error with #2139 .
If there is no reason for having `TrimSpace`, I'll remove it. 
Thanks 
cc @nixpanic @humblec @Madhu-1

**Comment by remixtj** [comment]
Hello,

when will be this fix released? We did an upgrade of rook today and we weren't unable to use csi 3.3.1 because of this bug. We had to rollback to 3.2.2 to have data available again.

**Comment by Rakshith-R** [comment]
> Hello,
> 
> when will be this fix released? We did an upgrade of rook today and we weren't unable to use csi 3.3.1 because of this bug. We had to rollback to 3.2.2 to have data available again.

This fix is not available in v3.3.1 but is available in v3.4.0
https://github.com/ceph/ceph-csi/compare/v3.3.1...release-v3.3 
Should we do a `v3.3.2` release ?@Madhu-1 @nixpanic @humblec PTAL

**Comment by Madhu-1** [comment]
As fix is available in `3.4.0` You can use `3.4.0` in any version of Rook. and `3.4.0` is the default in `1.7.1` of Rook.
