### PR TITLE
rbd: skip comparing volumes in a group if new group is created

### LINKED ISSUE #5344: ceph rbd crashes when volumegroup with 0 volumes is created
# Describe the bug #
rbd reports a crash while executing the `CreateVolumeGroup` RPC when group is created with 0 volumes.

# Environment details #

- Image/version of Ceph CSI driver : canary
- Helm chart version :
- Kernel version :
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) :
- Kubernetes cluster version :
- Ceph cluster version : main

# Steps to reproduce #

1. Create a volumegroup with 0 volumes
2. Check the `rbd-plugin` container for crashes.

# Actual results #

`CreateVolumeGroup` RPC call crashes while creating the group.

Describe what happened

# Expected behavior #

No crash should happen

# Logs #

If the issue is in PVC creation, deletion, cloning please attach complete logs
of below containers.

- csi-provisioner and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

```
I0526 05:27:27.086964       1 utils.go:271] ID: 25 Req-ID: vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5 GRPC call: /volumegroup.Controller/CreateVolumeGroup
I0526 05:27:27.089855       1 utils.go:272] ID: 25 Req-ID: vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5 GRPC request: {"name":"vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5","parameters":{"clusterID":"rook-ceph","pool":"replicapool","schedulingInterval":"1m"},"secrets":"***stripped***"}
I0526 05:27:27.090655       1 volumegroup.go:136] ID: 25 Req-ID: vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5 all 0 Volumes for VolumeGroup "vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5" have been found
E0526 05:27:27.243963       1 omap.go:80] ID: 25 Req-ID: vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5 omap not found (pool="replicapool", namespace="", name="csi.groups.default"): rados: ret=-2, No such file or directory
I0526 05:27:27.244834       1 manager.go:299] ID: 25 Req-ID: vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5 the journal does not contain a reservation for a volume group with name "vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5" yet
I0526 05:27:27.274447       1 omap.go:159] ID: 25 Req-ID: vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5 set omap keys (pool="replicapool", namespace="", name="csi.groups.default"): map[csi.volume.group.vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5:1cdc1db7-9f1e-4aff-8879-8f2c4bad7732])
I0526 05:27:27.280148       1 omap.go:159] ID: 25 Req-ID: vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5 set omap keys (pool="replicapool", namespace="", name="csi.volume.group.1cdc1db7-9f1e-4aff-8879-8f2c4bad7732"): map[csi.creationtime:2025-05-26T05:27:27.274488569Z csi.groupname:csi-vol-group-1cdc1db7-9f1e-4aff-8879-8f2c4bad7732 csi.volname:vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5])
I0526 05:27:27.286076       1 omap.go:221] ID: 25 Req-ID: vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5 got omap values: (pool="replicapool", namespace="", name="csi.volume.group.1cdc1db7-9f1e-4aff-8879-8f2c4bad7732"): map[csi.creationtime:2025-05-26T05:27:27.274488569Z csi.groupname:csi-vol-group-1cdc1db7-9f1e-4aff-8879-8f2c4bad7732 csi.volname:vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5]
I0526 05:27:27.287309       1 util.go:194] ID: 25 Req-ID: vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5 object for volume group "0001-0009-rook-ceph-0000000000000001-1cdc1db7-9f1e-4aff-8879-8f2c4bad7732" has been initialized
I0526 05:27:27.291045       1 omap.go:221] ID: 25 Req-ID: vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5 got omap values: (pool="replicapool", namespace="", name="csi.volume.group.1cdc1db7-9f1e-4aff-8879-8f2c4bad7732"): map[csi.creationtime:2025-05-26T05:27:27.274488569Z csi.groupname:csi-vol-group-1cdc1db7-9f1e-4aff-8879-8f2c4bad7732 csi.volname:vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5]
I0526 05:27:27.292105       1 volume_group.go:111] ID: 25 Req-ID: vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5 GetVolumeGroup(0001-0009-rook-ceph-0000000000000001-1cdc1db7-9f1e-4aff-8879-8f2c4bad7732) returns {commonVolumeGroup:{id:0001-0009-rook-ceph-0000000000000001-1cdc1db7-9f1e-4aff-8879-8f2c4bad7732 requestName:vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5 name:csi-vol-group-1cdc1db7-9f1e-4aff-8879-8f2c4bad7732 creationTime:0xc0005803f0 clusterID:rook-ceph objectUUID:1cdc1db7-9f1e-4aff-8879-8f2c4bad7732 credentials:0xc00006c640 conn:<nil> ioctx:<nil> monitors:192.168.122.5:6789 pool:replicapool namespace: csiDriver:default journal:0xc00068a870} volumes:[] volumesToFree:[]}
I0526 05:27:27.292833       1 util.go:332] ID: 25 Req-ID: vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5 connection established for volume group "0001-0009-rook-ceph-0000000000000001-1cdc1db7-9f1e-4aff-8879-8f2c4bad7732"
I0526 05:27:27.293260       1 util.go:383] ID: 25 Req-ID: vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5 iocontext created for volume group "0001-0009-rook-ceph-0000000000000001-1cdc1db7-9f1e-4aff-8879-8f2c4bad7732" in pool "replicapool"
I0526 05:27:27.308265       1 volume_group.go:179] ID: 25 Req-ID: vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5 volume group "replicapool/csi-vol-group-1cdc1db7-9f1e-4aff-8879-8f2c4bad7732" has been created
I0526 05:27:27.308900       1 volumegroup.go:158] ID: 25 Req-ID: vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5 volume group "vgrcontent-2a90c204-c959-47e4-996f-1135bec8e5e5" has been created: replicapool/csi-vol-group-1cdc1db7-9f1e-4aff-8879-8f2c4bad7732
E0526 05:27:27.309524       1 utils.go:340] panic occurred: runtime error: index out of range [0] with length 0
goroutine 7 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:26 +0x5e
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:18 +0x13
github.com/ceph/ceph-csi/internal/csi-common.panicHandler.func1()
	/go/src/github.com/ceph/ceph-csi/internal/csi-common/utils.go:341 +0xca
panic({0x2534ca0?, 0xc00005aca8?})
	/usr/local/go/src/runtime/panic.go:785 +0x132
github.com/ceph/ceph-csi/internal/rbd.(*rbdManager).CompareVolumesInGroup(0xc00071ec80, {0x2b9f3b0, 0xc00070fa10}, {0xc0000652f0, 0x0, 0x0}, {0x2bb4790, 0xc0009084b0})
	/go/src/github.com/ceph/ceph-csi/internal/rbd/manager.go:694 +0x545
github.com/ceph/ceph-csi/internal/csi-addons/rbd.(*VolumeGroupServer).CreateVolumeGroup(0x4029bd0?, {0x2b9f3b0, 0xc00070fa10}, 0xc000700540)
	/go/src/github.com/ceph/ceph-csi/internal/csi-addons/rbd/volumegroup.go:182 +0xb38
github.com/csi-addons/spec/lib/go/volumegroup._Controller_CreateVolumeGroup_Handler.func1({0x2b9f3b0?, 0xc00070fa10?}, {0x25170e0?, 0xc000700540?})
	/go/src/github.com/ceph/ceph-csi/vendor/github.com/csi-addons/spec/lib/go/volumegroup/volumegroup_grpc.pb.go:162 +0xcb
github.com/ceph/ceph-csi/internal/csi-common.panicHandler({0x2b9f3b0?, 0xc00070fa10?}, {0x25170e0?, 0xc000700540?}, 0xc00090ca80?, 0x1e85bab?)
	/go/src/github.com/ceph/ceph-csi/internal/csi-common/utils.go:346 +0x71
github.com/ceph/ceph-csi/internal/csi-common.NewMiddlewareServerOption.ChainUnaryServer.func3.1({0x2b9f3b0?, 0xc00070fa10?}, {0x25170e0?, 0xc000700540?})
	/go/src/github.com/ceph/ceph-csi/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:48 +0x45
github.com/ceph/ceph-csi/internal/csi-common.logSlowGRPC(0x6fc23ac00, {0x2b9f3b0, 0xc00070fa10}, {0x25170e0, 0xc000700540}, 0xc00006c540, 0xc00071eb00)
	/go/src/github.com/ceph/ceph-csi/internal/csi-common/utils.go:325 +0x1db
github.com/ceph/ceph-csi/internal/csi-common.NewMiddlewareServerOption.func1({0x2b9f3b0?, 0xc00070fa10?}, {0x25170e0?, 0xc000700540?}, 0xc0005e1800?, 0xc000982f50?)
	/go/src/github.com/ceph/ceph-csi/internal/csi-common/utils.go:134 +0x45
github.com/ceph/ceph-csi/internal/csi-common.NewMiddlewareServerOption.ChainUnaryServer.func3.1({0x2b9f3b0?, 0xc00070fa10?}, {0x25170e0?, 0xc000700540?})
	/go/src/github.com/ceph/ceph-csi/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:48 +0x45
github.com/ceph/ceph-csi/internal/csi-common.logGRPC({0x2b9f3b0, 0xc00070fa10}, {0x25170e0, 0xc000700540}, 0x2199f80?, 0xc00071eb40)
	/go/src/github.com/ceph/ceph-csi/internal/csi-common/utils.go:274 +0x165
github.com/ceph/ceph-csi/internal/csi-common.NewMiddlewareServerOption.ChainUnaryServer.func3.1({0x2b9f3b0?, 0xc00070fa10?}, {0x25170e0?, 0xc000700540?})
	/go/src/github.com/ceph/ceph-csi/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:48 +0x45
github.com/ceph/ceph-csi/internal/csi-common.contextIDInjector({0x2b9f3b0, 0xc00070ef00}, {0x25170e0, 0xc000700540}, 0x0?, 0xc00071eb80)
	/go/src/github.com/ceph/ceph-csi/internal/csi-common/utils.go:262 +0x132
github.com/ceph/ceph-csi/internal/csi-common.NewMiddlewareServerOption.ChainUnaryServer.func3({0x2b9f3b0, 0xc00070ef00}, {0x25170e0, 0xc000700540}, 0xc00006c540, 0x80?)
	/go/src/github.com/ceph/ceph-csi/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:53 +0x123
github.com/csi-addons/spec/lib/go/volumegroup._Controller_CreateVolumeGroup_Handler({0x24af040, 0xc000146c30}, {0x2b9f3b0, 0xc00070ef00}, 0xc0000ec080, 0xc0007443c0)
	/go/src/github.com/ceph/ceph-csi/vendor/github.com/csi-addons/spec/lib/go/volumegroup/volumegroup_grpc.pb.go:164 +0x143
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00045ca00, {0x2b9f3b0, 0xc00070ee70}, 0xc0007004e0, 0xc000744750, 0x40469c0, 0x0)
	/go/src/github.com/ceph/ceph-csi/vendor/google.golang.org/grpc/server.go:1405 +0x103b
google.golang.org/grpc.(*Server).handleStream(0xc00045ca00, {0x2ba0050, 0xc000706000}, 0xc0007004e0)
	/go/src/github.com/ceph/ceph-csi/vendor/google.golang.org/grpc/server.go:1815 +0xbaa
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	/go/src/github.com/ceph/ceph-csi/vendor/google.golang.org/grpc/server.go:1035 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 70
	/go/src/github.com/ceph/ceph-csi/vendor/google.golang.org/grpc/server.go:1046 +0x125
```

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
While calling CreateVolumeGroup RPC, if a new group is being created we can skip comparing volumes in a group because it is redundant.

Fixes: #5344

### CODE REVIEW

File: internal/csi-addons/rbd/volumegroup.go [hunk 1]
```diff
@@ -180,20 +180,23 @@ func (vs *VolumeGroupServer) CreateVolumeGroup(
 		log.DebugLog(ctx, "existing volume group %q has been resolved: %+v", groupName, vg)
 	}
 
-	// TODO: check the number of volumes in the vg, it needs to be empty, or match len(volumes)
```
Comment (Rakshith-R) [inline internal/csi-addons/rbd/volumegroup.go:183]: This TODO seems to be removed by mistake ?

Comment (Nikhil-Ladha) [reply internal/csi-addons/rbd/volumegroup.go:183]: No, looking at the code this check was already implemented it seems, ref: https://github.com/ceph/ceph-csi/blob/devel/internal/rbd/manager.go#L562

File: internal/csi-addons/rbd/volumegroup.go [hunk 2]
```diff
@@ -180,20 +180,23 @@ func (vs *VolumeGroupServer) CreateVolumeGroup(
...
-			groupName,
-			err.Error())
-	} else if !matches {
-		return nil, status.Errorf(
-			codes.Internal,
-			"volume group %q does not match with requested volumes",
-			groupName)
+	// If vgHandle is empty, it means that a new group is created. Hence, we can
+	// skip comparing the volumes in a group.
+	if vgHandle == "" {
```
Comment (iPraveenParihar) [inline internal/csi-addons/rbd/volumegroup.go]: instead can we have this handled in  `CompareVolumesInGroup()` function?
return early if `len(vgVols) == 0` is true?

**Comment by Rakshith-R** [comment]
@Nikhil-Ladha 
Shouldn't the solution be to initialize the volumes list in VG to empty list when a VG is created ?

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha Shouldn't the solution be to initialize the volumes list in VG to empty list when a VG is created ?

It's not about initialising the list. If you check the trace mentioned in the lined issue, the error happened here: https://github.com/ceph/ceph-csi/blob/devel/internal/rbd/manager.go#L585 where we are checking using the 0th index directly (`[0]`)

**Comment by Rakshith-R** [comment]
> > @Nikhil-Ladha Shouldn't the solution be to initialize the volumes list in VG to empty list when a VG is created ?
> 
> It's not about initialising the list. If you check the trace mentioned in the lined issue, the error happened here: https://github.com/ceph/ceph-csi/blob/devel/internal/rbd/manager.go#L585 where we are checking using the 0th index directly (`[0]`)

Then, @iPraveenParihar approach would be preferred https://github.com/ceph/ceph-csi/pull/5345#discussion_r2115259455 
than an external check.

File: internal/csi-addons/rbd/volumegroup.go (hunk 2 above)
Comment (Madhu-1) [reply internal/csi-addons/rbd/volumegroup.go]: i dont think its a good idea to do it. The Compare should not check for vgHandle because it should be done by outside.  The CompareVolumesInGroup should return true or false based on the volumes in the list and the group not to return positive response by passing extra input that need to be checked outside.


can we move to to inside the else statement where the vgHandle is check above at line 180?

Comment (Nikhil-Ladha) [reply internal/csi-addons/rbd/volumegroup.go]: @iPraveenParihar We can't have a check there because the `CompareVolumesInGroup` expect a group to be empty only if the volumes list provided to it is also empty.
Rather, it can be `len(volumes) == 0`, that means there are no new volumes to compare in the group, and we can retrurn early.

Comment (Nikhil-Ladha) [reply internal/csi-addons/rbd/volumegroup.go]: > i dont think its a good idea to do it. The Compare should not check for vgHandle because it should be done by outside. The CompareVolumesInGroup should return true or false based on the volumes in the list and the group not to return positive response by passing extra input that need to be checked outside.

@Madhu-1, @iPraveenParihar was suggesting to add a check using the existing params and not passing a new param.

Comment (Madhu-1) [reply internal/csi-addons/rbd/volumegroup.go]: why not move this check https://github.com/ceph/ceph-csi/blob/a0074471ce155fd3cc699a12a6d66d949c9c6c3c/internal/csi-addons/rbd/volumegroup.go#L180 here? if we do it we dont need any additional checks and this will be called if the group already exists not a new group

Comment (Nikhil-Ladha) [reply internal/csi-addons/rbd/volumegroup.go]: We can do that, but having an additional check in the `ComapreVolumesInGroup` func would avoid such issues when called from other functions as well.

Comment (Madhu-1) [reply internal/csi-addons/rbd/volumegroup.go]: The defeats the purpose of the function as per the function name and explanation. we are returning positive response even if not the case.

Comment (Nikhil-Ladha) [reply internal/csi-addons/rbd/volumegroup.go]: Hmm, right. That's what my initial suggestion was 😅 
Moving it to the `else` block.

Comment (Nikhil-Ladha) [reply internal/csi-addons/rbd/volumegroup.go]: Done

**Review by Madhu-1 — APPROVED** [review]

**Review by Rakshith-R — COMMENTED** [review]
LGTM

**Review by iPraveenParihar — APPROVED** [review]

**Comment by iPraveenParihar** [comment]
@Mergifyio rebase

**Comment by iPraveenParihar** [comment]
@Mergifyio queue

**Comment by iPraveenParihar** [comment]
@Nikhil-Ladha, do we need to back port this to v3.13 & v3.14?

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha, do we need to back port this to v3.13 & v3.14?

Only `v3.14`
