### PR TITLE
util: more generic kernel version parsing

### LINKED ISSUE #2248: Kernel Subversion Parsing Failure
# Description #

A parsing issue in `internal/util/util.go` prevents proper detection of OS kernel support.

# Environment details #

- Image/version of Ceph CSI driver : `cephcsi/cephcsi:v3.3.1`
- Kernel version : 5.12.14xlinux-svr
- Mounter used for mounting PVC : krbd
- Kubernetes cluster version : 1.21.1
- Ceph cluster version : v16.2.4

# Steps to reproduce #

1. Deploy kernel with a version string without a separating dash between subversion and extra version components 
2. Deploy cephcsi/cephcsi:v3.3.1 (in whatever form suits best) to deploy RBDs via the krbd mounter
3. See version parsing error in cephcsi container log

# Expected behavior #

Parsing the numeric version should be possible without regard for any trailing garbage.

# Logs #

```
# kubectl logs -n rook-ceph csi-rbdplugin-rf8bp csi-rbdplugin
...
E0706 15:39:24.281024   53097 util.go:196] failed to parse sublevel from 5.12.14xlinux-svr: strconv.Atoi: parsing "14xlinux": invalid syntax
...
```

### PR DESCRIPTION
**Pull request by lyind**
Fixes: #2248 (Kernel Subversion Parsing Failure)

Kernel version parsing is enhanced in a backward compatible way to support a wider array of version strings.

An extensive test has been added to `internal/util/util_test.go`.

Versions like `5.12.14xlinux` are now correctly parsed.

### CODE REVIEW

**Comment by lyind** [comment]
Sorry for multiple edits to the comment/commit. I tried to match style/indent better and add more test strings.

File: internal/util/util.go [hunk 1]
```diff
@@ -158,6 +157,40 @@ type KernelVersion struct {
 	Backport     bool   // backports have a fixed version/patchlevel/sublevel
 }
 
+// Parses a kernel release version string into:
+//   version, patch version, sub version and extra version
+func ParseKernelRelease(release string) (int, int , int, int, error) {
```
Comment (Madhu-1) [inline internal/util/util.go]: this need not be exported anymore?

File: internal/util/util.go [hunk 2]
```diff
@@ -158,6 +157,40 @@ type KernelVersion struct {
...
+	version := 0
+	patchlevel := 0
+	sublevel := 0
+	extraversion := 0
+
+	extra := ""
+	n, err := fmt.Sscanf(release, "%d.%d%s", &version, &patchlevel, &extra)
+	if n < 2 && err != nil {
+		err = fmt.Errorf("failed to parse version and patchlevel from %s: %v", release, err)
```
Comment (Madhu-1) [inline internal/util/util.go]:
```suggestion
err = fmt.Errorf("failed to parse version and patchlevel from %s: %w", release, err)
```

Comment (Madhu-1) [reply internal/util/util.go]: use `%w` in fmt.Errorf for  error in other places also

**Review by Madhu-1 — COMMENTED** [review]
@lyind can you please add a test case to cover the kernel version format that you are trying to fix?

**Comment by nixpanic** [comment]
Thanks for the PR! Here are some notes to improve the proposed change so that we can include it:

1. the subject of the commit should be `util: ...`, we do not use `internal: ...`
2. the contents of the commit message should explain (no single bullet point) what problem is being addressed or enhancement is made
3. add additional unit testing so that this doesn't break in the future with updates (see [`TestCheckKernelSupport`](https://github.com/ceph/ceph-csi/blob/0837c05be06947b91c6604f4bbb3f4c92f132517/internal/util/util_test.go#L247))

You can run the unit tests with `make containerized-tests` and verify that the change you are making does not break existing parsing, and fixes it for the additional format.

File: internal/util/util.go (hunk 2 above)
Comment (lyind) [reply internal/util/util.go]: Done, thank you.

File: internal/util/util.go (hunk 1 above)
Comment (lyind) [reply internal/util/util.go]: Public for testing.

**Comment by lyind** [comment]
> Thanks for the PR! Here are some notes to improve the proposed change so that we can include it:
> 
>     1. the subject of the commit should be `util: ...`, we do not use `internal: ...`
> 
>     2. the contents of the commit message should explain (no single bullet point) what problem is being addressed or enhancement is made
> 
>     3. add additional unit testing so that this doesn't break in the future with updates (see [`TestCheckKernelSupport`](https://github.com/ceph/ceph-csi/blob/0837c05be06947b91c6604f4bbb3f4c92f132517/internal/util/util_test.go#L247))
> 
> 
> You can run the unit tests with `make containerized-tests` and verify that the change you are making does not break existing parsing, and fixes it for the additional format.

Thank you for the review:

1. Done.
2. Please check the updated, more detailed commit message.
3. Unit test `TestParseKernelRelease` added to `internal/util/util_test.go`, please review.

I ran the tests and all passed.

**Comment by lyind** [comment]
> @lyind can you please add a test case to cover the kernel version format that you are trying to fix?

I added the test `TestParseKernelRelease`to `internal/util/util_test.go`.

File: internal/util/util_test.go [hunk 3]
```diff
@@ -244,6 +244,36 @@ func TestMountOptionsAdd(t *testing.T) {
 		})
 	}
 }
+
+func TestParseKernelRelease(t *testing.T) {
+	t.Parallel()
+
+	badReleases := []string{ "x", "5", "5.", "5.4.", "5.x-2-oops", "4.1.x-7-oh", "5.12.x" }
+	for _, release := range badReleases {
+		_, _, _, _, err := ParseKernelRelease(release)
```
Comment (Madhu-1) [inline internal/util/util_test.go]: as both files are in the same packages this need not be exported?

Comment (lyind) [reply internal/util/util_test.go]: The visibility of `parseKernelRelease` has been adjusted. Thank you.

File: internal/util/util_test.go [hunk 4]
```diff
@@ -244,6 +244,36 @@ func TestMountOptionsAdd(t *testing.T) {
...
 }
+
+func TestParseKernelRelease(t *testing.T) {
+	t.Parallel()
+
+	badReleases := []string{ "x", "5", "5.", "5.4.", "5.x-2-oops", "4.1.x-7-oh", "5.12.x" }
+	for _, release := range badReleases {
+		_, _, _, _, err := parseKernelRelease(release)
+		if err == nil {
+			t.Errorf("release \"%s\" must not be parsed successfully", release)
```
Comment (nixpanic) [inline internal/util/util_test.go]: Instead of `\"%s\"` you can use `%q` for creating quoted strings.

**Review by nixpanic — COMMENTED** [review]
I'm very interested what Linux distributions formats its kernel version like this. It would be nice to have that mentioned as a comment in the test case, or commit message.

Thanks for all the follow ups and improvements! CI runs have been approved now, lets see how things go :crossed_fingers:

File: internal/util/util_test.go (hunk 4 above)
Comment (lyind) [reply internal/util/util_test.go]: Done.

**Comment by lyind** [comment]
>Regarding the version string:

```
If you see anything at all after the dash, you are running a *distribution kernel*. Please use the support channels offered by your distribution vendor to obtain kernel support." -- https://www.kernel.org/category/releases.html

Thus some people tag their (vanilla, unpatched but modified config) kernels with, for example, `5.1interesting` to separate them from patched distribution kernels but still have some name to differentiate different use cases.

The linux kernel config does not enforce a specific separator or format after the `Kernel.Major.Minor` triple and all tools have worked fine with these versions so far.
```

Thanks for sharing above documentation, its also good to document in source code I feel :)

**Review by nixpanic — DISMISSED** [review]
Thanks, looks good to me.

File: internal/util/util.go [hunk 5]
```diff
@@ -158,6 +157,41 @@ type KernelVersion struct {
 	Backport     bool   // backports have a fixed version/patchlevel/sublevel
 }
 
+// Parses a kernel release version string into:
+//   version, patch version, sub version and extra version
```
Comment (humblec) [inline internal/util/util.go]: @nit:  may be remove first space in above comment.

**Comment by humblec** [comment]
@lyind Thanks for the contribution! :+1:  mostly looks good , just minor comments from my end!

File: internal/util/util.go (hunk 5 above)
Comment (lyind) [reply internal/util/util.go]: Done.

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Review by Madhu-1 — DISMISSED** [review]

**Review by humblec — DISMISSED** [review]

File: internal/util/util.go [hunk 6]
```diff
@@ -158,6 +157,41 @@ type KernelVersion struct {
 	Backport     bool   // backports have a fixed version/patchlevel/sublevel
 }
 
+// Parses a kernel release version string into:
+// version, patch version, sub version and extra version
```
Comment (nixpanic) [inline internal/util/util.go]: golang-ci complains about:
```
internal/util/util.go:161:1: Top level comment should end in a period (godot)
// version, patch version, sub version and extra version
^
```

File: internal/util/util.go [hunk 7]
```diff
@@ -158,6 +157,41 @@ type KernelVersion struct {
...
+	}
+
+	sublevel := 0
+	extraversion := 0
+	err = nil
+	if n > minVersions {
+		n, err = fmt.Sscanf(extra, ".%d%s", &sublevel, &extra)
+		if err != nil && n == 0 && len(extra) > 0 && extra[0] != '-' && extra[0] == '.' {
+			return 0, 0, 0, 0, fmt.Errorf("failed to parse subversion from %s: %w", release, err)
+		} else {
```
Comment (nixpanic) [inline internal/util/util.go]: and also:
```
internal/util/util.go:180:10: `if` block ends with a `return` statement, so drop this `else` and outdent its block (golint)
		} else {
		       ^
```

The `else` clause/indention is just not needed as the `if` returns already.

**Review by nixpanic — CHANGES_REQUESTED** [review]

File: internal/util/util.go [hunk 8]
```diff
@@ -158,6 +157,41 @@ type KernelVersion struct {
 	Backport     bool   // backports have a fixed version/patchlevel/sublevel
 }
 
+// Parses a kernel release version string into:
+// version, patch version, sub version and extra version
+func parseKernelRelease(release string) (int, int, int, int, error) {
```
Comment (Rakshith-R) [inline internal/util/util.go]:
```suggestion
// parseKernelRelease parses a kernel release version string into:
// version, patch version, sub version and extra version.
func parseKernelRelease(release string) (int, int, int, int, error) {
```
just a minor change, golang func doc begins with function name 
Thanks! :slightly_smiling_face:

File: internal/util/util.go (hunk 6 above)
Comment (lyind) [reply internal/util/util.go]: Thank you, change applied.

File: internal/util/util.go (hunk 7 above)
Comment (lyind) [reply internal/util/util.go]: Removed the unnecessary `else` and cleaned it up.

**Comment by lyind** [comment]
In general, do you prefer force-pushes or multiple iterative commits (and later squash) for this project?

**Comment by nixpanic** [comment]
> In general, do you prefer force-pushes or multiple iterative commits (and later squash) for this project?

Force pushes has the preference. A commit per functional change. Have a look at the [commit history ](https://github.com/ceph/ceph-csi/commits/devel) to get the idea how PRs often get split into multiple commits. GitHub does not help with reviewing changes between updates of PRs, and that makes me sad. But squashing commits later on, makes more work for contributors as we want to keep a clear history of the changes. (We do not use merge-commits either.)

**Review by nixpanic — APPROVED** [review]

**Review by Rakshith-R — APPROVED** [review]

**Review by humblec — APPROVED** [review]

**Comment by Rakshith-R** [comment]
> /retest ci/centos/upgrade-tests-rbd

[logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/upgrade-tests-rbd/detail/upgrade-tests-rbd/2093/pipeline)
`
    Error from server: error when creating "STDIN": etcdserver: request timed out
`
