### PR TITLE
rbd: remove topologyConstrainedPools parameter

### LINKED ISSUE #4497: Don't add topology details in the pv volumeAttributes
# Describe the bug #

currently provisioning with topologypools, we also add the details of topology in the volumeAttributes, so the proposal is to remove those details as it is not required

an example:
```
~ % oc get pv pvc-d1a26969-a15c-4e60-8f76-847d1fdd6041 -o=jsonpath='{.spec.csi.volumeAttributes}' | jq
{
 "clusterID": "openshift-storage",
 "imageFeatures": "layering,deep-flatten,exclusive-lock,object-map,fast-diff",
 "imageFormat": "2",
 "imageName": "csi-vol-937ee9e9-2f99-11ed-b2d0-0a580a83001a",
 "journalPool": "ocs-storagecluster-cephblockpool",
 "pool": "ocs-storagecluster-cephblockpool-us-east-1a",
 "storage.kubernetes.io/csiProvisionerIdentity": "1662652453217-8081-openshift-storage.rbd.csi.ceph.com",
 "topologyConstrainedPools": "[\n {\n \"poolName\": \"ocs-storagecluster-cephblockpool-us-east-1a\",\n \"domainSegments\": [\n {\n \"domainLabel\": \"zone\",\n \"value\": \"us-east-1a\"\n }\n ]\n },\n {\n \"poolName\": \"ocs-storagecluster-cephblockpool-us-east-1b\",\n \"domainSegments\": [\n {\n \"domainLabel\": \"zone\",\n \"value\": \"us-east-1b\"\n }\n ]\n },\n {\n \"poolName\": \"ocs-storagecluster-cephblockpool-us-east-1c\",\n \"domainSegments\": [\n {\n \"domainLabel\": \"zone\",\n \"value\": \"us-east-1c\"\n }\n ]\n }\n]"
}
```

# Environment details #

- Image/version of Ceph CSI driver :
- Helm chart version :
- Kernel version :
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) :
- Kubernetes cluster version :
- Ceph cluster version :

# Steps to reproduce #

1. Setup details: provision PVC with topologyconstraintpool pools(RBD storageclass)

# Actual results #

 Describe what happened

# Expected behavior #

#A clear and concise description of what you expected to happen.

# Logs #

If the issue is in PVC creation, deletion, cloning please attach complete logs
of below containers.

- csi-provisioner and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC resize please attach complete logs of below containers.

- csi-resizer and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in snapshot creation and deletion please attach complete logs
of below containers.

- csi-snapshotter and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC mounting please attach complete logs of below containers.

- csi-rbdplugin/csi-cephfsplugin and driver-registrar container logs from
  plugin pod from the node where the mount is failing.

- if required attach dmesg logs.

**Note:-** If its a rbd issue please provide only rbd related logs, if its a
cephFS issue please provide cephFS logs.

# Additional context #

For example:

Any existing bug report which describe about the similar issue/behavior

### PR DESCRIPTION
**Pull request by iPraveenParihar**
# Describe what this PR does #

This commit removes the `topologyConstrainedPools` parameter from PV volumeAttributes as it is not required.

## Related issues ##

Fixes: #4497 

## Future concerns ##

List items that are not part of the PR and do not impact it's
functionality, but are work items that can be taken up subsequently.

**Checklist:**

* [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#commit-messages).
* [x] Reviewed the developer guide on [Submitting a Pull Request](https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#development-workflow)
* [x] [Pending release notes](https://github.com/ceph/ceph-csi/blob/devel/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next major release.
* [x] Documentation has been updated, if necessary.
* [x] Unit tests have been added, if necessary.
* [x] Integration tests have been added, if necessary.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

* `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)

</details>

### CODE REVIEW

**Comment by iPraveenParihar** [comment]
verified that `topologyConstrainedPools` has been removed. 

```shell
[pm@dhcp53-176 examples]$ k get pv pvc-5aaf7aef-fda5-4a57-af7c-abbb737d77bb -o jsonpath='{.spec.csi.volumeAttributes}' | jq
{
  "clusterID": "rook-ceph",
  "encryptionKMSID": "azure-kms",
  "encryptionType": "block",
  "imageFeatures": "layering",
  "imageName": "csi-vol-1292393c-b86a-4ff7-abb7-52750879d83a",
  "journalPool": "replicapool",
  "pool": "rp",
  "storage.kubernetes.io/csiProvisionerIdentity": "1710418563048-5228-rook-ceph.rbd.csi.ceph.com"
}
```

File: internal/rbd/controllerserver.go [hunk 1]
```diff
@@ -252,6 +252,9 @@ func buildCreateVolumeResponse(req *csi.CreateVolumeRequest, rbdVol *rbdVolume)
 		}
 	}
 
+	// remove topologyConstrainedPools param as it is not required
```
Comment (nixpanic) [inline internal/rbd/controllerserver.go]: It feels cleaner to do this at the place where other keys to `volumeContext` are added or removed. Maybe directly below `k8s.RemoveCSIPrefixedParameters()` ?

Comment (iPraveenParihar) [reply internal/rbd/controllerserver.go]: yea, that will be good.
How about introducing a function called `RemoveVolumeContextParameters`? This function could serve the specific purpose of removing parameters from the volume context."

Comment (nixpanic) [reply internal/rbd/controllerserver.go]: Sure, or make that a `volumeContext := rbdVol.getVolumeContext(req.GetParameters())` function.

File: internal/rbd/controllerserver.go [hunk 2]
```diff
@@ -225,8 +225,10 @@ func (cs *ControllerServer) parseVolCreateRequest(
 }
 
 func buildCreateVolumeResponse(req *csi.CreateVolumeRequest, rbdVol *rbdVolume) *csi.CreateVolumeResponse {
+	volumeContext := rbdVol.getVolumeContext(req.GetParameters())
+	
 	// remove kubernetes csi prefixed parameters.
-	volumeContext := k8s.RemoveCSIPrefixedParameters(req.GetParameters())
+	volumeContext = k8s.RemoveCSIPrefixedParameters(req.GetParameters())
```
Comment (nixpanic) [inline internal/rbd/controllerserver.go]: Move `k8s.RemoveCSIPrefixedParameters()` into your new `rbdVol.getVolumeContext()` function

File: internal/rbd/rbd_util.go [hunk 3]
```diff
@@ -2155,3 +2156,24 @@ func (rv *rbdVolume) unsetAllMetadata(keys []string) error {
 
 	return nil
 }
+
+// getVolumeContext filters out parameters that are not required in the volume context.
+func (rv *rbdVolume) getVolumeContext(parameters map[string]string) map[string]string {
```
Comment (Madhu-1) [inline internal/rbd/rbd_util.go]: we dont need to make this as a method, moving this to outside util is good and we can pass the notRequiredParams so that we can reuse this same function for cephfs as well.

Comment (iPraveenParihar) [reply internal/rbd/rbd_util.go]: @Madhu-1 
will move this to `internal/util/util.go`  and rename as `RemoveParameters(params, notRequiredParams)` ?

Comment (Madhu-1) [reply internal/rbd/rbd_util.go]: Yes that also helps

File: internal/util/topology.go [hunk 4]
```diff
@@ -30,6 +30,9 @@ import (
 const (
 	keySeparator   rune   = '/'
 	labelSeparator string = ","
+
+	// topologyPoolsParam is the parameter name used to pass topology constrained pools.
+	TopologyPoolsParam = "topologyConstrainedPools"
```
Comment (nixpanic) [inline internal/util/topology.go]: this is not use outside of the package, so you can call it `topologyPoolsParam` as in the comment

File: internal/util/util.go [hunk 5]
```diff
@@ -390,3 +391,34 @@ func CallStack() string {
 
 	return string(stack)
 }
+
+// CheckSliceContains checks the slice for string.
+func CheckSliceContains(options []string, opt string) bool {
```
Comment (nixpanic) [inline internal/util/util.go]: `k8s.io/utils/strings/slices` is already used elsewhere, can you replace `CheckSliceContains()` by `slices.Contains()`?

Comment (nixpanic) [reply internal/util/util.go]: Wait, no! There is https://pkg.go.dev/slices in recent Golang versions :partying_face: , use that instead.

Comment (iPraveenParihar) [reply internal/util/util.go]: done😃

**Review by nixpanic — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
@mergifyio queue

**Comment by nixpanic** [comment]
> /retest ci/centos/mini-e2e/k8s-1.29

spurious failure, the [logs](https://jenkins-ceph-csi.apps.ocp.cloud.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.29/detail/mini-e2e_k8s-1.29/165/pipeline) show that an image was not cleaned up (yet?):
```
[FAILED] backend images not matching kubernetes resource count,image count 1 kubernetes resource count 0
```

**Comment by nixpanic** [comment]
@mergifyio requeue

**Comment by Madhu-1** [comment]
> > /retest ci/centos/mini-e2e/k8s-1.29
> 
> spurious failure, the [logs](https://jenkins-ceph-csi.apps.ocp.cloud.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.29/detail/mini-e2e_k8s-1.29/165/pipeline) show that an image was not cleaned up (yet?):
> 
> ```
> [FAILED] backend images not matching kubernetes resource count,image count 1 kubernetes resource count 0
> ```

i think we need to update the validation function to print `rbd info` and `rbd status` of each images to get more clarity what happened. it looks like the image is opened by someone but not closed? not sure who

**Comment by nixpanic** [comment]
@mergifyio queue
